### PR TITLE
CSI Hostpath Driver & VolumeSnapshots addons

### LINKED ISSUE #8343: feature-gates: add support for VolumeSnapshotDataSource
Minikube does not seem to support volume snapshots even with the appropriate feature gate activated.

This makes it very hard to test functionality based on it (e.g.: VolumeSnapshot based backup in Stash or Velero)

**Steps to reproduce the issue:** 

1. Create new Minikube instance

~~~
minikube start \
    --feature-gates="VolumeSnapshotDataSource=true" \
    --driver="kvm2"
~~~

Startup log:

~~~
😄  minikube v1.11.0 on Ubuntu 20.04
✨  Using the kvm2 driver based on user configuration
💾  Downloading driver docker-machine-driver-kvm2:
    > docker-machine-driver-kvm2.sha256: 65 B / 65 B [-------] 100.00% ? p/s 0s
    > docker-machine-driver-kvm2: 13.88 MiB / 13.88 MiB  100.00% 2.92 MiB p/s 5
💿  Downloading VM boot image ...
    > minikube-v1.11.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.11.0.iso: 174.99 MiB / 174.99 MiB  100.00% 1.14 MiB p/s 2m34s
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4: 526.01 MiB
🔥  Creating kvm2 VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

❗  /usr/local/bin/kubectl is version 1.15.2, which may be incompatible with Kubernetes 1.18.3.
💡  You can also use 'minikube kubectl -- get pods' to invoke a matching version
~~~

2.  Check if minikube is ready

~~~
kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
minikube   Ready    master   13m   v1.18.3
~~~

3. Query VolumeSnapshots

~~~
kubectl get volumesnapshot
~~~

**Full output of failed command:** 

~~~
error: the server doesn't have a resource type "volumesnapshot"
~~~

The full log with --alsologtostderr:
~~~
❯ minikube kubectl get volumesnapshot --alsologtostderr
I0601 12:48:20.192244 2462981 mustload.go:64] Loading cluster: minikube
I0601 12:48:20.194420 2462981 main.go:110] libmachine: Found binary path at /home/sola/.minikube/bin/docker-machine-driver-kvm2
I0601 12:48:20.194555 2462981 main.go:110] libmachine: Launching plugin server for driver kvm2
I0601 12:48:20.265075 2462981 main.go:110] libmachine: Plugin server listening at address 127.0.0.1:40307
I0601 12:48:20.266402 2462981 main.go:110] libmachine: () Calling .GetVersion
I0601 12:48:20.268004 2462981 main.go:110] libmachine: Using API Version  1
I0601 12:48:20.268103 2462981 main.go:110] libmachine: () Calling .SetConfigRaw
I0601 12:48:20.269193 2462981 main.go:110] libmachine: () Calling .GetMachineName
I0601 12:48:20.269705 2462981 main.go:110] libmachine: (minikube) Calling .GetState
I0601 12:48:20.274816 2462981 host.go:65] Checking if "minikube" exists ...
I0601 12:48:20.276546 2462981 main.go:110] libmachine: Found binary path at /home/sola/.minikube/bin/docker-machine-driver-kvm2
I0601 12:48:20.276864 2462981 main.go:110] libmachine: Launching plugin server for driver kvm2
I0601 12:48:20.341136 2462981 main.go:110] libmachine: Plugin server listening at address 127.0.0.1:33015
I0601 12:48:20.342434 2462981 main.go:110] libmachine: () Calling .GetVersion
I0601 12:48:20.344648 2462981 main.go:110] libmachine: Using API Version  1
I0601 12:48:20.344730 2462981 main.go:110] libmachine: () Calling .SetConfigRaw
I0601 12:48:20.345901 2462981 main.go:110] libmachine: () Calling .GetMachineName
I0601 12:48:20.346651 2462981 main.go:110] libmachine: (minikube) Calling .DriverName
I0601 12:48:20.347331 2462981 api_server.go:145] Checking apiserver status ...
I0601 12:48:20.347542 2462981 ssh_runner.go:148] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0601 12:48:20.347618 2462981 main.go:110] libmachine: (minikube) Calling .GetSSHHostname
I0601 12:48:20.360787 2462981 main.go:110] libmachine: (minikube) Calling .GetSSHPort
I0601 12:48:20.361357 2462981 main.go:110] libmachine: (minikube) Calling .GetSSHKeyPath
I0601 12:48:20.361757 2462981 main.go:110] libmachine: (minikube) Calling .GetSSHUsername
I0601 12:48:20.362167 2462981 sshutil.go:44] new ssh client: &{IP:192.168.39.85 Port:22 SSHKeyPath:/home/sola/.minikube/machines/minikube/id_rsa Username:docker}
I0601 12:48:20.634288 2462981 ssh_runner.go:148] Run: sudo egrep ^[0-9]+:freezer: /proc/3218/cgroup
I0601 12:48:20.658027 2462981 api_server.go:161] apiserver freezer: "2:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod53d7a7ff031a824e2ec4f5c5864c09b2.slice/docker-3c1e9218222569135d4767776afe8fc0374bef0519a342156a623aecc2f2dfa6.scope"
I0601 12:48:20.658332 2462981 ssh_runner.go:148] Run: sudo cat /sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod53d7a7ff031a824e2ec4f5c5864c09b2.slice/docker-3c1e9218222569135d4767776afe8fc0374bef0519a342156a623aecc2f2dfa6.scope/freezer.state
I0601 12:48:20.687608 2462981 api_server.go:183] freezer state: "THAWED"
I0601 12:48:20.687702 2462981 api_server.go:193] Checking apiserver healthz at https://192.168.39.85:8443/healthz ...
I0601 12:48:20.717078 2462981 api_server.go:213] https://192.168.39.85:8443/healthz returned 200:
ok
I0601 12:48:20.717267 2462981 binary.go:56] Not caching binary, using https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubectl.sha256
I0601 12:48:20.717306 2462981 kubectl.go:51] Running  [get volumesnapshot]
error: the server doesn't have a resource type "volumesnapshot"

~~~

**Full output of `minikube start` command used, if not already included:**
~~~
included above
~~~

**Optional: Full output of `minikube logs` command:**
~~~
~~~

</details>

### LINKED ISSUE #8815: Add CSI Hostpath driver as addon to minikube
I am currently working on enabling Volume Snapshots in minikube: #8343. Enabling the snapshots is however useless without a CSI based storage provider, which the user would have to configure manually. Adding the CSI hostpath driver as an addon would not only make the volume snapshots ready for use, but provide a complete CSI based storage solution to minikube.

This change would bring all the required yaml files from the driver to minikube. These files are dependent on kubernetes version, thus an upgrade of kubernetes in minikube could break it. However with a proper integration test this should be detected immediately and the yaml files upgraded accordingly.

If approved, I will rework my PR (#8461) and once done it would close both this issue as well as #8343.

kind/feature

### PR DESCRIPTION
**Pull request by 11janci**
Fixes #8343 
Fixes #8815 

Adds the csi-hostpath-driver and volumesnapshots addons to minikube. Splitting it into two separate addons gives the users the flexibility to configure the CSI driver of their choice (should they prefer a different driver than CSI Hostpath), without having to set up volume snapshots by themselves.

The change is split into three logical commits - it might be easier to review it as such:

1. volumesnapshots addon
2. csi-hostpath-driver addon
3. documentation and integration test

### CODE REVIEW

**Comment by 11janci** [comment]
@priyawadhwa @all thank you for your comments, the PR is now ready for review. Pls see the updated description

File: test/integration/addons_test.go [hunk 1]
```diff
@@ -398,3 +399,108 @@ func validateOlmAddon(ctx context.Context, t *testing.T, profile string) {
 		t.Errorf("failed checking operator installed: %v", err.Error())
 	}
 }
+
+func validateCsiDriverAndSnapshots(ctx context.Context, t *testing.T, profile string) {
```
Comment (priyawadhwa) [inline test/integration/addons_test.go:403]: nit: This should be validateCSIDriverAndSnapshots to maintain case

File: site/content/en/docs/tutorials/volume_snapshots_and_csi.md [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+linkTitle: "CSI Driver and Volume Snapshots"
+weight: 1
+date: 2020-08-06
+description: >
+  CSI Driver and Volume Snapshots
+---
+
+## Overview
+
+This tutorial explains how to set up the CSI Hostpath Driver in Minikube and create volume snapshots.
```
Comment (priyawadhwa) [inline site/content/en/docs/tutorials/volume_snapshots_and_csi.md:12]: nit: Minikube should be lower case throughout this doc

File: site/content/en/docs/tutorials/volume_snapshots_and_csi.md [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+
+## Prerequisites
+
+- Minikube 1.12.3 with Kubernetes 1.18.x or higher
```
Comment (priyawadhwa) [inline site/content/en/docs/tutorials/volume_snapshots_and_csi.md:16]: I would just say latest version of minikube here, since 1.12.3 has already been released

File: test/integration/helpers_test.go [hunk 4]
```diff
@@ -372,6 +373,56 @@ func PodWait(ctx context.Context, t *testing.T, profile string, ns string, selec
 	return names, fmt.Errorf("%s: %v", fmt.Sprintf("%s within %s", selector, timeout), err)
 }
 
+//// PvcWait waits for persistent volume claim to reach bound state
+func PvcWait(ctx context.Context, t *testing.T, profile string, ns string, name string, timeout time.Duration) error {
```
Comment (priyawadhwa) [inline test/integration/helpers_test.go:377]: nit: PVCWait

File: test/integration/helpers_test.go [hunk 5]
```diff
@@ -372,6 +373,56 @@ func PodWait(ctx context.Context, t *testing.T, profile string, ns string, selec
 	return names, fmt.Errorf("%s: %v", fmt.Sprintf("%s within %s", selector, timeout), err)
 }
 
+//// PvcWait waits for persistent volume claim to reach bound state
```
Comment (priyawadhwa) [inline test/integration/helpers_test.go:376]: nit: //// on this comment

File: pkg/minikube/assets/addons.go [hunk 6]
```diff
@@ -440,6 +440,106 @@ var Addons = map[string]*Addon{
...
+			"rbac-volume-snapshot-controller.yaml",
+			"0640",
+			false),
+		MustBinAsset(
+			"deploy/addons/volumesnapshots/volume-snapshot-controller-deployment.yaml",
+			vmpath.GuestAddonsDir,
+			"volume-snapshot-controller-deployment.yaml",
+			"0640",
+			false),
+	}, true, "volumesnapshots"),
```
Comment (priyawadhwa) [inline pkg/minikube/assets/addons.go:474]: Why did you choose to enable this addon by default? Typically, I prefer to keep the number of default addons to a minimum so that a standard cluster doesn't have extra CPU overhead, but if a lot of users will be needing this addon then it could make sense.

**Comment by 11janci** [comment]
@priyawadhwa thanks for all the comments! I will fix the small issues right away.

> Why did you choose to enable this addon by default? Typically, I prefer to keep the number of default addons to a minimum so that a standard cluster doesn't have extra CPU overhead, but if a lot of users will be needing this addon then it could make sense.

Basically the only reason was that it is enabled by default in standard k8s as well, so I thought I'll mirror that. I'll be happy to disable it if you'd prefer that.

And lastly, I see bunch of tests failed but they should be all unrelated. The new test passed.

**Comment by priyawadhwa** [comment]
Hey @11janci yah, let's disable by default then!

Also, if both of those addons need to be enabled for them to work, I'd add a warning in as a validation. Something like:

```
<this addon> requires <that addon> to be enabled as well, please run:
    minikube addons enable <addon name>
```

**Comment by 11janci** [comment]
@priyawadhwa all done & ready for review 🙂

**Comment by sharifelgamal** [comment]
Thanks for this contribution!
