### PR TITLE
Fix TestKubernetesUpgrade

### LINKED ISSUE #11376: TestKubernetesUpgrade
```
=== RUN   TestKubernetesUpgrade
=== PAUSE TestKubernetesUpgrade
=== CONT  TestKubernetesUpgrade
=== CONT  TestKubernetesUpgrade
version_upgrade_test.go:227: (dbg) Run:  out/minikube-linux-amd64 start -p kubernetes-upgrade-20210511174846-6531 --memory=2200 --kubernetes-version=v1.14.0 --alsologtostderr -v=1 --driver=docker  --container-runtime=docker
=== CONT  TestKubernetesUpgrade
version_upgrade_test.go:227: (dbg) Done: out/minikube-linux-amd64 start -p kubernetes-upgrade-20210511174846-6531 --memory=2200 --kubernetes-version=v1.14.0 --alsologtostderr -v=1 --driver=docker  --container-runtime=docker: (48.974713837s)
version_upgrade_test.go:232: (dbg) Run:  out/minikube-linux-amd64 stop -p kubernetes-upgrade-20210511174846-6531
version_upgrade_test.go:232: (dbg) Done: out/minikube-linux-amd64 stop -p kubernetes-upgrade-20210511174846-6531: (2.530657261s)
version_upgrade_test.go:237: (dbg) Run:  out/minikube-linux-amd64 -p kubernetes-upgrade-20210511174846-6531 status --format={{.Host}}
version_upgrade_test.go:237: (dbg) Non-zero exit: out/minikube-linux-amd64 -p kubernetes-upgrade-20210511174846-6531 status --format={{.Host}}: exit status 7 (130.889587ms)
-- stdout --
	Stopped
-- /stdout --
version_upgrade_test.go:239: status error: exit status 7 (may be ok)
version_upgrade_test.go:248: (dbg) Run:  out/minikube-linux-amd64 start -p kubernetes-upgrade-20210511174846-6531 --memory=2200 --kubernetes-version=v1.22.0-alpha.1 --alsologtostderr -v=1 --driver=docker  --container-runtime=docker
version_upgrade_test.go:248: (dbg) Done: out/minikube-linux-amd64 start -p kubernetes-upgrade-20210511174846-6531 --memory=2200 --kubernetes-version=v1.22.0-alpha.1 --alsologtostderr -v=1 --driver=docker  --container-runtime=docker: (20.435382445s)
version_upgrade_test.go:253: (dbg) Run:  kubectl --context kubernetes-upgrade-20210511174846-6531 version --output=json
version_upgrade_test.go:269: expected server version v1.14.0 is not the same with latest version v1.22.0-alpha.1
panic.go:613: *** TestKubernetesUpgrade FAILED at 2021-05-11 17:49:58.273591764 +0000 UTC m=+1761.344865436
```
https://storage.googleapis.com/minikube-builds/logs/11364/acadaa6/Docker_Linux.html#fail_TestKubernetesUpgrade

### PR DESCRIPTION
**Pull request by dinever**
Hi,

This PR fixes #11376. The issue seems to be 50637dd1498504c1f15aa911319cd148c963633e accidentally removed these lines:

```go
	if cmd.Flags().Changed(kubernetesVersion) {
		cc.KubernetesConfig.KubernetesVersion = getKubernetesVersion(existing)
	}
```

https://github.com/kubernetes/minikube/commit/50637dd1498504c1f15aa911319cd148c963633e#diff-0e864ab4025634664724909a47c34fbcae246ad52307eaaaa58153f0b256a8b4L636-L638

Testing result after the fix:

<details>

```
go build  -tags "" -ldflags="-X k8s.io/minikube/pkg/version.version=v1.20.0 -X k8s.io/minikube/pkg/version.isoVersion=v1.20.0 -X k8s.io/minikube/pkg/version.gitCommitID="d156e5cbed1675d44126b89bb176b3b399e3d2b7" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v5" -o out/minikube k8s.io/minikube/cmd/minikube
go test -ldflags="-X k8s.io/minikube/pkg/version.version=v1.20.0 -X k8s.io/minikube/pkg/version.isoVersion=v1.20.0 -X k8s.io/minikube/pkg/version.gitCommitID="d156e5cbed1675d44126b89bb176b3b399e3d2b7" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v5" -v -test.timeout=90m ./test/integration --tags="integration " -minikube-start-args=--driver=docker -test.run TestKubernetesUpgrade 2>&1 | tee "./out/testout_d156e5cbe.txt"
Found 16 cores, limiting parallelism with --test.parallel=9
=== RUN   TestKubernetesUpgrade
=== PAUSE TestKubernetesUpgrade
=== CONT  TestKubernetesUpgrade
    version_upgrade_test.go:227: (dbg) Run:  out/minikube start -p kubernetes-upgrade-20210512215149-95553 --memory=2200 --kubernetes-version=v1.14.0 --alsologtostderr -v=1 --driver=docker
    version_upgrade_test.go:227: (dbg) Done: out/minikube start -p kubernetes-upgrade-20210512215149-95553 --memory=2200 --kubernetes-version=v1.14.0 --alsologtostderr -v=1 --driver=docker: (1m44.14501526s)
    version_upgrade_test.go:232: (dbg) Run:  out/minikube stop -p kubernetes-upgrade-20210512215149-95553
    version_upgrade_test.go:232: (dbg) Done: out/minikube stop -p kubernetes-upgrade-20210512215149-95553: (19.438593985s)
    version_upgrade_test.go:237: (dbg) Run:  out/minikube -p kubernetes-upgrade-20210512215149-95553 status --format={{.Host}}
    version_upgrade_test.go:237: (dbg) Non-zero exit: out/minikube -p kubernetes-upgrade-20210512215149-95553 status --format={{.Host}}: exit status 7 (224.761294ms)

        -- stdout --
        	Stopped

        -- /stdout --
    version_upgrade_test.go:239: status error: exit status 7 (may be ok)
    version_upgrade_test.go:248: (dbg) Run:  out/minikube start -p kubernetes-upgrade-20210512215149-95553 --memory=2200 --kubernetes-version=v1.22.0-alpha.1 --alsologtostderr -v=1 --driver=docker
    version_upgrade_test.go:248: (dbg) Done: out/minikube start -p kubernetes-upgrade-20210512215149-95553 --memory=2200 --kubernetes-version=v1.22.0-alpha.1 --alsologtostderr -v=1 --driver=docker: (1m41.768097038s)
    version_upgrade_test.go:253: (dbg) Run:  kubectl --context kubernetes-upgrade-20210512215149-95553 version --output=json
    version_upgrade_test.go:272: Attempting to downgrade Kubernetes (should fail)
    version_upgrade_test.go:274: (dbg) Run:  out/minikube start -p kubernetes-upgrade-20210512215149-95553 --memory=2200 --kubernetes-version=v1.14.0 --driver=docker
    version_upgrade_test.go:274: (dbg) Non-zero exit: out/minikube start -p kubernetes-upgrade-20210512215149-95553 --memory=2200 --kubernetes-version=v1.14.0 --driver=docker: exit status 106 (210.804351ms)

        -- stdout --
        	* [kubernetes-upgrade-20210512215149-95553] minikube v1.20.0 on Darwin 10.15.7
        	  - KUBECONFIG=/Users/pding200/.kube/config-linear-dev



        -- /stdout --
        ** stderr **
        	X Exiting due to K8S_DOWNGRADE_UNSUPPORTED: Unable to safely downgrade existing Kubernetes v1.22.0-alpha.1 cluster to v1.14.0
        	* Suggestion:

        	    1) Recreate the cluster with Kubernetes 1.14.0, by running:

        	    minikube delete -p kubernetes-upgrade-20210512215149-95553
        	    minikube start -p kubernetes-upgrade-20210512215149-95553 --kubernetes-version=v1.14.0

        	    2) Create a second cluster with Kubernetes 1.14.0, by running:

        	    minikube start -p kubernetes-upgrade-20210512215149-955532 --kubernetes-version=v1.14.0

        	    3) Use the existing cluster at version Kubernetes 1.22.0-alpha.1, by running:

        	    minikube start -p kubernetes-upgrade-20210512215149-95553 --kubernetes-version=v1.22.0-alpha.1


        ** /stderr **
    version_upgrade_test.go:278: Attempting restart after unsuccessful downgrade
    version_upgrade_test.go:280: (dbg) Run:  out/minikube start -p kubernetes-upgrade-20210512215149-95553 --memory=2200 --kubernetes-version=v1.22.0-alpha.1 --alsologtostderr -v=1 --driver=docker
    version_upgrade_test.go:280: (dbg) Done: out/minikube start -p kubernetes-upgrade-20210512215149-95553 --memory=2200 --kubernetes-version=v1.22.0-alpha.1 --alsologtostderr -v=1 --driver=docker: (1m27.421891854s)
    helpers_test.go:171: Cleaning up "kubernetes-upgrade-20210512215149-95553" profile ...
    helpers_test.go:174: (dbg) Run:  out/minikube delete -p kubernetes-upgrade-20210512215149-95553
    helpers_test.go:174: (dbg) Done: out/minikube delete -p kubernetes-upgrade-20210512215149-95553: (16.78051616s)
--- PASS: TestKubernetesUpgrade (330.12s)
PASS
Tests completed in 5m30.122456543s (result code 0)
ok  	k8s.io/minikube/test/integration	332.075s
```
</details>

Thanks!

### CODE REVIEW

File: cmd/minikube/cmd/start_flags.go [hunk 1]
```diff
@@ -571,6 +571,10 @@ func updateExistingConfigFromFlags(cmd *cobra.Command, existing *config.ClusterC
 	updateBoolFromFlag(cmd, &cc.KubernetesConfig.ShouldLoadCachedImages, cacheImages)
 	updateIntFromFlag(cmd, &cc.KubernetesConfig.NodePort, apiServerPort)
 
+	if cmd.Flags().Changed(kubernetesVersion) {
```
Comment (medyagh) [inline cmd/minikube/cmd/start_flags.go:574]: Nice catch ! Is there a chance that we missed more changed flags ?

Comment (dinever) [reply cmd/minikube/cmd/start_flags.go:574]: Thanks! There could be. Let me do a thorough check.

Comment (dinever) [reply cmd/minikube/cmd/start_flags.go:575]: I did find `apiserver-names` being removed as well: https://github.com/kubernetes/minikube/commit/50637dd1498504c1f15aa911319cd148c963633e#diff-0e864ab4025634664724909a47c34fbcae246ad52307eaaaa58153f0b256a8b4L644-L646
So I added it in 7b98243ea31c214de4f7639249b7d65991aaf7f3.
Ideally I think we should cover this piece of logic in the unit test. Might need some refactoring. Will look into it and probably open a follow-up PR.

Thanks!

Comment (medyagh) [reply cmd/minikube/cmd/start_flags.go:575]: @dinever yes  please a refactor to make this simplified is much needed !

I really like your contributions ! would you be interested to join our office hours sometimes ? if it works with your timezone?
https://minikube.sigs.k8s.io/community/

**Review by medyagh — APPROVED** [review]

**Comment by medyagh** [comment]
Thank you very much for fixing this test @dinever good catch !

File: cmd/minikube/cmd/start_flags.go (hunk 1 above)
Comment (dinever) [reply cmd/minikube/cmd/start_flags.go:575]: Thanks @medyagh! Yep I'd love to join the office hours. I've added it to my calendar. Thanks!
