### PR TITLE
hyperv Delete: call StopHost before removing VM

### LINKED ISSUE #6804: delete: The process cannot access the file because it is being used by another process
**The exact command to reproduce the issue**:
```
minikube delete
```
**The full output of the command that failed**:<details>
```
! Unable to get the status of the minikube cluster.
* Removing C:\Users\Csongor Halmai\.minikube\machines\minikube ...
*
X Unable to remove machine directory: %v: remove C:\Users\Csongor Halmai\.minikube\machines\minikube\disk.vhd: The process cannot access the file because it is being used by another process.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```
</details>

**The output of the `minikube logs` command**:<details>

```
*
X api load: filestore "minikube": open C:\Users\Csongor Halmai\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```
</details>

**The operating system version**:

Microsoft Windows [Version 10.0.18362.592]

I hoped that creating a config.json file can solve the problem. I created one with 0 bytes which was simply deleted by  `minikube delete`. Then I created one with the content `{}` but it caused `minikube delete` to die with `panic: runtime error: invalid memory address or nil pointer dereference`. Then I gave up.

### PR DESCRIPTION
**Pull request by tstromberg**
Fixes #6804 - a bug I ran into this morning while running "minikube start/minikube delete" in an infinite loop.

Just in case, it also tries driver deletion twice, since it gets messy if we later delete the machine profile but the VM deletion never happened.

### CODE REVIEW

File: pkg/minikube/machine/delete.go [hunk 1]
```diff
@@ -75,18 +75,26 @@ func DeleteHost(api libmachine.API, machineName string) error {
...
 		}
-		out.T(out.DeletingHost, "Successfully powered off Hyper-V. minikube driver -- {{.driver}}", out.V{"driver": host.Driver.DriverName()})
+		// Hack: give the Hyper-V VM more time to stop before deletion
+		time.Sleep(1 * time.Second)
 	}
 
 	out.T(out.DeletingHost, `Deleting "{{.profile_name}}" in {{.driver_name}} ...`, out.V{"profile_name": machineName, "driver_name": host.DriverName})
 	if err := host.Driver.Remove(); err != nil {
-		return errors.Wrap(err, "host remove")
+		glog.Warningf("remove failed, will retry: %v", err)
```
Comment (medyagh) [inline pkg/minikube/machine/delete.go]: nit: how about using retry.Expo ( and set the max number of retry to 2 or 3)

Comment (tstromberg) [reply pkg/minikube/machine/delete.go]: I considered it, but feel like it may provide an awkward experience to retry more than once. Will reconsider based on user reports.
