### PR TITLE
Persist custom addon image/registry settings.

### LINKED ISSUE #10877: custom addon images get ignored on minikube restart
**Note this environment is entirely air-gapped.
minikube start --driver=docker --base-image="<local_IP>:5000/gcr.io/k8s-minikube/kicbase:v0.0.18" --insecure-registry="<local_IP>:5000" --image-repository="<local_IP>:5000" --alsologtostderr  2>&1 >> [minikube_clean_startup_logs.log](https://github.com/kubernetes/minikube/files/6172761/minikube_clean_startup_logs.log)

Note this capability added with [PR-10111](https://github.com/kubernetes/minikube/pull/10111)
**Steps to reproduce the issue:** 

1.  Start minikube for offline environment (above)
2.  Enable ingress addones (with --image flag) 
[minikbe_ingress_addon_enabled.log](https://github.com/kubernetes/minikube/files/6172766/minikbe_ingress_addon_enabled.log)

3. Stop minikube 
4. Start Minikube (with or without flags, same result)  [minikube_bad_startup_logs.log](https://github.com/kubernetes/minikube/files/6172770/minikube_bad_startup_logs.log)

5. Ingress container fails to start (wrong image)
[Minikube_ingress_failed.txt](https://github.com/kubernetes/minikube/files/6172796/Minikube_ingress_failed.txt)

**Full output of failed command:** 
 Alsologtostderr is already included. 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
Workaround: (disabling and re-adding ingress fixes it)
1. minikube addons disable ingress
2. minikube addons enable ingress --images= 

</details>

### PR DESCRIPTION
**Pull request by andriyDev**
fixes #10877.

Before:
```
$ minikube start -p addon
😄  [addon] minikube v1.20.0 on Debian rodete
✨  Automatically selected the docker driver. Other choices: kvm2, ssh
👍  Starting control plane node addon in cluster addon
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.6 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "addon" cluster and "default" namespace by default
$ minikube -p addon addons enable dashboard --images="Dashboard=k8s.gcr.io/echoserver:1.4"
    ▪ Using image k8s.gcr.io/echoserver:1.4
    ▪ Using image kubernetesui/metrics-scraper:v1.0.4
💡  Some dashboard features require the metrics-server addon. To enable all features please run:

	minikube -p addon addons enable metrics-server	


🌟  The 'dashboard' addon is enabled
$ minikube stop -p addon
✋  Stopping node "addon"  ...
🛑  Powering off "addon" via SSH ...
🛑  1 nodes stopped.
$ minikube start -p addon
😄  [addon] minikube v1.20.0 on Debian rodete
✨  Using the docker driver based on existing profile
👍  Starting control plane node addon in cluster addon
🚜  Pulling base image ...
🔄  Restarting existing docker container for "addon" ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.6 ...
🔎  Verifying Kubernetes components...
    ▪ Using image kubernetesui/dashboard:v2.1.0
    ▪ Using image kubernetesui/metrics-scraper:v1.0.4
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass, dashboard
🏄  Done! kubectl is now configured to use "addon" cluster and "default" namespace by default
```
After:
```
$ minikube start -p addon
😄  [addon] minikube v1.20.0 on Debian rodete
✨  Automatically selected the docker driver. Other choices: kvm2, ssh
👍  Starting control plane node addon in cluster addon
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.6 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "addon" cluster and "default" namespace by default
$ minikube -p addon addons enable dashboard --images="Dashboard=k8s.gcr.io/echoserver:1.4"
    ▪ Using image k8s.gcr.io/echoserver:1.4
    ▪ Using image kubernetesui/metrics-scraper:v1.0.4
💡  Some dashboard features require the metrics-server addon. To enable all features please run:

	minikube -p addon addons enable metrics-server	


🌟  The 'dashboard' addon is enabled
$ minikube stop -p addon
✋  Stopping node "addon"  ...
🛑  Powering off "addon" via SSH ...
🛑  1 nodes stopped.
$ minikube start -p addon
😄  [addon] minikube v1.20.0 on Debian rodete
✨  Using the docker driver based on existing profile
👍  Starting control plane node addon in cluster addon
🚜  Pulling base image ...
🔄  Restarting existing docker container for "addon" ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.6 ...
🔎  Verifying Kubernetes components...
    ▪ Using image k8s.gcr.io/echoserver:1.4
    ▪ Using image kubernetesui/metrics-scraper:v1.0.4
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass, dashboard
🏄  Done! kubectl is now configured to use "addon" cluster and "default" namespace by default
```
Note: Difference occurs under "Verifying Kubernetes components" on the second start. This PR also handles the case of enabling the addon with custom images prior to starting.

### CODE REVIEW

**Comment by andriyDev** [comment]
Forgot to rebase onto master first!

File: test/integration/addons_test.go [hunk 1]
```diff
@@ -711,3 +712,58 @@ func validateGCPAuthAddon(ctx context.Context, t *testing.T, profile string) {
 		t.Errorf("failed disabling gcp-auth addon. arg %q.s %v", rr.Command(), err)
 	}
 }
+
+func TestAddonsPersistAfterRestart(t *testing.T) {
```
Comment (medyagh) [inline test/integration/addons_test.go:716]: how about instead of adding a new Start Stop test
add this to our existing Test Start Stop as a test case

```

				t.Run("serial", func(t *testing.T) {
					serialTests := []struct {
						name      string
						validator validateStartStopFunc
					}{
						{"FirstStart", validateFirstStart},
						{"DeployApp", validateDeploying},
						{"Stop", validateStop},
						{"EnableAddonAfterStop", validateEnableAddonAfterStop},
						{"SecondStart", validateSecondStart},
						{"UserAppExistsAfterStop", validateAppExistsAfterStop},
						{"AddonExistsAfterStop", validateAddonAfterStop},
						{"VerifyKubernetesImages", validateKubernetesImages},
						{"Pause", validatePauseAfterStart},
```

add to look like this

```
```

				t.Run("serial", func(t *testing.T) {
					serialTests := []struct {
						name      string
						validator validateStartStopFunc
					}{
						{"FirstStart", validateFirstStart},
						{"DeployApp", validateDeploying},
						{"Stop", validateStop},
						// Enable an addon with a different image 
						{"EnableAddonAfterStop", validateEnableAddonAfterStop},
						{"SecondStart", validateSecondStart},
						{"UserAppExistsAfterStop", validateAppExistsAfterStop},
						{"AddonExistsAfterStop", validateAddonAfterStop},
						{"VerifyKubernetesImages", validateKubernetesImages},
						{"Pause", validatePauseAfterStart},
```
```

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/assets/addons.go [hunk 2]
```diff
@@ -659,8 +659,110 @@ var Addons = map[string]*Addon{
 	}),
 }
 
+// parseMapString creates a map based on `str` which is encoded as <key1>=<value1>,<key2>=<value2>,...
+func parseMapString(str string) map[string]string {
```
Comment (medyagh) [inline pkg/minikube/assets/addons.go:663]: add unit test here

Comment (andriyDev) [reply pkg/minikube/assets/addons.go:664]: Done.

File: test/integration/addons_test.go (hunk 1 above)
Comment (andriyDev) [reply test/integration/addons_test.go]: Done.

File: test/integration/start_stop_delete_test.go [hunk 3]
```diff
@@ -190,7 +216,7 @@ func validateEnableAddonAfterStop(ctx context.Context, t *testing.T, profile str
 	}
 
 	// Enable an addon to assert it comes up afterwards
-	rr, err := Run(t, exec.CommandContext(ctx, Target(), "addons", "enable", "dashboard", "-p", profile))
+	rr, err := Run(t, exec.CommandContext(ctx, Target(), "addons", "enable", "dashboard", "-p", profile, "--images=MetricsScraper=k8s.gcr.io/echoserver:1.4"))
```
Comment (medyagh) [inline test/integration/start_stop_delete_test.go:219]: why do we change the image in both Addons metric-server in validateEnableAddonWhileActive and also change existing dasbhoard to custom image too ? if no good reason lets keep existing test like it was before.

File: pkg/minikube/config/types.go [hunk 4]
```diff
@@ -74,6 +74,8 @@ type ClusterConfig struct {
 	KubernetesConfig        KubernetesConfig
 	Nodes                   []Node
 	Addons                  map[string]bool
+	CustomAddonImages       map[string]string
+	CustomAddonRegistries   map[string]string
```
Comment (medyagh) [inline pkg/minikube/config/types.go:78]: knit: add a few comments maybe examples here

File: test/integration/start_stop_delete_test.go (hunk 3 above)
Comment (andriyDev) [reply test/integration/start_stop_delete_test.go:219]: The dashboard addon now tests 2 things when minikube is stopped - that the Dashboard deployment properly starts (existing behavior), and that the MetricsScraper tries to load the custom image - notice that we only change the image for MetricsScraper and not for Dashboard. The distinction between this and the metric-server is that the metric-server is being enabled WHILE minikube is on. This caused a bug in my original implementation of this so I'd like to protect us from that in the future. Also I used different addons to ensure their settings don't collide in some strange way.

File: pkg/minikube/config/types.go (hunk 4 above)
Comment (andriyDev) [reply pkg/minikube/config/types.go]: Done.
