### PR TITLE
convert dockerNetworkInspect to a struct

### LINKED ISSUE #9690: convert dockerNetworkInspect to a struct
currently we use comma to get the info we need

https://github.com/medyagh/minikube/blob/a84cbed217c45c34e13bce14e1c144bcde7ee168/pkg/drivers/kic/oci/network_create.go#L139
```
	cmd := exec.Command(Docker, "network", "inspect", name, "--format", `{{(index .IPAM.Config 0).Subnet}},{{(index .IPAM.Config 0).Gateway}},{{(index .Options "com.docker.network.driver.mtu")}}`)

```

one better approach is using something like this
```
docker network inspect minikube --format='{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{(index .IPAM.Config 0).Subnet}}","Gateway": "{{(index .IPAM.Config 0).Gateway}}",MTU: "{{(index .Options "com.docker.network.driver.mtu")}}",{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }} {{if $first}} {{$first = false}}{{else}},{{end}}"{{$v.IPv4Address}}",{{end}}]}'
```

that will output a json
```
{"Name": "minikube","Driver": "bridge","Subnet": "192.168.49.0/24","Gateway": "192.168.49.1",MTU: "1500", "ContainerIPs": [  "192.168.49.3/24", ,"192.168.49.4/24", ,"192.168.49.2/24",]}
```

but the problem is making sure the dateway and subnet get parsed into netinfo struct

so we get more information as a struct, the challenges are making sure it doesn't throw an exception in wide variety of platforms and exceptional cases. when we do json unmarshal

### PR DESCRIPTION
**Pull request by valaparthvi**
fixes #9690

**minikube start after the changes**
```
➜  minikube git:(issue9690) ✗ ./out/minikube start
I1118 10:57:25.679592    6343 translate.go:89] Failed to load translation file for en: Asset translations/en.json not found
😄  minikube v1.15.0 on Fedora 32
🆕  Kubernetes 1.19.4 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.19.4
✨  Using the kvm2 driver based on existing profile
💾  Downloading driver docker-machine-driver-kvm2:
    > docker-machine-driver-kvm2.sha256: 65 B / 65 B [-------] 100.00% ? p/s 0s
    > docker-machine-driver-kvm2: 13.56 MiB / 13.56 MiB  100.00% 180.70 KiB p/s
💿  Downloading VM boot image ...
    > minikube-v1.15.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.15.0.iso: 181.00 MiB / 181.00 MiB  100.00% 1.92 MiB p/s 1m34s
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing kvm2 VM for "minikube" ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.12 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass, dashboard

❗  /usr/bin/kubectl is version 1.10.0+b3b92b2, which may have incompatibilites with Kubernetes 1.18.3.
    ▪ Want kubectl v1.18.3? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "" namespace by default
```

### CODE REVIEW

**Review by medyagh — COMMENTED** [review]
thank you for this PR do you mind putting in the PR Descriptipn the After this PR. minikube start output ?

**Review by medyagh — COMMENTED** [review]
Please check the Docker Windows Test failure

```
020-11-15T11:13:15.3983628Z         ** stderr ** 
2020-11-15T11:13:15.3984110Z         	! Local proxy ignored: not passing HTTP_PROXY=localhost:43067 to docker env.
2020-11-15T11:13:15.4020343Z         	    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 8.00 MiB /    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 16.00 MiB     > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 16.00 MiB     > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 16.00 MiB     > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 20.64 MiB     > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 48.00 MiB     > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 66.67 MiB     > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 95.45 MiB     > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 112.00 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 130.83 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 136.00 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 136.00 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 136.00 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 136.00 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 140.72 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 167.53 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 168.00 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 168.00 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 168.00 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 168.00 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 168.00 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 176.06 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 200.77 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 223.39 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 251.72 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 274.83 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 300.73 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 333.58 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 360.95 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 392.23 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 425.77 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 456.16 MiB    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 486.35 MiB! Local proxy ignored: not passing HTTP_PROXY=localhost:43067 to docker env.
2020-11-15T11:13:15.4273968Z         	! You appear to be using a proxy, but your NO_PROXY environment does not include the minikube IP (192.168.49.188).
2020-11-15T11:13:15.4282358Z         	E1115 11:13:15.361152    2502 start.go:99] Unable to get host IP: network inspect: error parsing network inspect output: "{\"Name\": \"functional-20201115111211-2491\",\"Driver\": \"bridge\",\"Subnet\": \"192.168.49.0/24\",\"Gateway\": \"192.168.49.1\",\"MTU\": 1500, \"ContainerIPs\": [  \"192.168.49.188/24\",]}\n"
2020-11-15T11:13:15.4284497Z         	X Exiting due to GUEST_START: Failed to setup kubeconfig: network inspect: error parsing network inspect output: "{\"Name\": \"functional-20201115111211-2491\",\"Driver\": \"bridge\",\"Subnet\": \"192.168.49.0/24\",\"Gateway\": \"192.168.49.1\",\"MTU\": 1500, \"ContainerIPs\": [  \"192.168.49.188/24\",]}\n"
2020-11-15T11:13:15.4285484Z         	* 
2020-11-15T11:13:15.4285863Z         	* If the above advice does not help, please let us know: 
2020-11-15T11:13:15.4286883Z         	  - https://github.com/kubernetes/minikube/issues/new/choose
2020-11-15T11:13:15.4287380Z         
2020-11-15T11:13:15.4287632Z         ** /stderr **
```

**Comment by valaparthvi** [comment]
@medyagh Looks like we're good to go. Although I am not completely happy with the format string
```
{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{(index .Options "com.docker.network.driver.mtu")}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}
```

I do not understand the purpose of defining `first` variable but it does help in solving the problem we were facing earlier regarding json unmarshall. Also, the error did not occur because of `\n` but because of a trailing comma in the `ContainerIPs` array.

I have tried a few different ways to fix this error but none of them seem elegant enough with regards to the current code.

File: pkg/drivers/kic/oci/network_create.go [hunk 1]
```diff
@@ -134,11 +134,21 @@ type netInfo struct {
 	gateway net.IP
 	mtu     int
 }
+type networkInspect struct {
```
Comment (medyagh) [inline pkg/drivers/kic/oci/network_create.go:137]: could add a comment that this struct is only used for unmarshal the docker output and later it will be translated to netinfo

**Review by medyagh — APPROVED** [review]
thank you @valaparthvi for this PR
