### PR TITLE
Fix translations not looking for correct file.

### LINKED ISSUE #11697: Translations not working
Using LC_ALL the translations are not properly utilized and English is used as a fallback.

### PR DESCRIPTION
**Pull request by andriyDev**
fixes #11697.

Before:
```
$ minikube start
😄  minikube v1.21.0 on Debian rodete
✨  Automatically selected the docker driver. Other choices: kvm2, ssh
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
$ LC_ALL=fr minikube start
😄  minikube v1.21.0 on Debian rodete
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🤷  docker "minikube" container is missing, will recreate.
```
After:
```
$ minikube start
😄  minikube v1.21.0 on Debian rodete
✨  Automatically selected the docker driver. Other choices: kvm2, ssh
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
$ LC_ALL=fr minikube start
😄  minikube v1.21.0 sur Debian rodete
✨  Utilisation du pilote docker basé sur le profil existant
👍  Démarrage du noeud de plan de contrôle minikube dans le cluster minikube
🚜  Pulling base image ...
🤷  docker "minikube" container est manquant, il va être recréé.
```
Note I terminated minikube early so thats why there are error messages in the second half.

### CODE REVIEW

**Review by sharifelgamal — APPROVED** [review]

File: test/integration/functional_test.go [hunk 1]
```diff
@@ -897,6 +898,31 @@ func validateDryRun(ctx context.Context, t *testing.T, profile string) {
 	}
 }
 
+func validateInternationalLanguage(ctx context.Context, t *testing.T, profile string) {
```
Comment (medyagh) [inline test/integration/functional_test.go:901]: add comment here so it shows up in the docs

Comment (andriyDev) [reply test/integration/functional_test.go:902]: Done.
