### PR TITLE
Refresh known issues map

### LINKED ISSUE #9165: Add actionable error message if user does not have permission to write config.json
As seen in this log:

```
I0817 14:49:10.446876    6686 exit.go:58] WithError(error provisioning host)=Failed to save config: writefile failed for /Users/conradwt/.minikube/profiles/gcloud-local-dev/config.json: open /Users/conradwt/.minikube/profiles/gcloud-local-dev/config.json: permission denied called from:
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x100000000000000)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
k8s.io/minikube/pkg/minikube/exit.WithError(0x27c2b14, 0x17, 0x2ada260, 0xc0003d2840)
	/app/pkg/minikube/exit/exit.go:58 +0x34
k8s.io/minikube/cmd/minikube/cmd.runStart(0x38ead00, 0xc0008fd5e0, 0x0, 0xa)
	/app/cmd/minikube/cmd/start.go:172 +0xe12
github.com/spf13/cobra.(*Command).execute(0x38ead00, 0xc0008fd4a0, 0xa, 0xa, 0x38ead00, 0xc0008fd4a0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x38e9d40, 0x0, 0x1, 0xc000537fc0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/app/cmd/minikube/cmd/root.go:106 +0x72c
main.main()
	/app/cmd/minikube/main.go:71 +0x11f
W0817 14:49:10.447311    6686 out.go:252] error provisioning host: Failed to save config: writefile failed for /Users/conradwt/.minikube/profiles/gcloud-local-dev/config.json: open /Users/conradwt/.minikube/profiles/gcloud-local-dev/config.json: permission denied
```

### PR DESCRIPTION
**Pull request by tstromberg**
Reveals two new types of failures from logs:

*    Failed to start ContainerManager - #8797 #7923 #8673
*   failed to start daemon - #7992 #7933 #7626 #6795

Adds known issue data for:

*    HOST_PIDS_CGROUP #6411
*   HOST_HOME_PERMISSION: Fixes #9165
*    PR_DOCKER_MOUNTS_EOF #8832 (both Windows & Mac flavors for correct documentation link)
*    PR_POWERSHELL_CONSTRAINED #7347
*    PR_HYPERV_MODULE_NOT_INSTALLED #9040
*    GUEST_NOT_FOUND #9130
*    GUEST_CONFIG_CORRUPT: #9175

### CODE REVIEW

File: pkg/minikube/reason/known_issues.go [hunk 1]
```diff
@@ -865,7 +955,7 @@ var runtimeIssues = []match{
 		Kind: Kind{
 			ID:       "RT_DOCKER_RESTART",
 			ExitCode: ExRuntimeError,
-			Advice:   "Remove the incompatible --docker-opt flag if one was provided",
+			Advice:   "Remove the invalid --docker-opt or --inecure-registry flag if one was provided",
```
Comment (sharifelgamal) [inline pkg/minikube/reason/known_issues.go:958]: --insecure-registry

Comment (tstromberg) [reply pkg/minikube/reason/known_issues.go]: Thanks!

**Review by sharifelgamal — APPROVED** [review]
