### PR TITLE
fix unable to set memory in config

### LINKED ISSUE #9769: `minikube config set memory` with given unit results in error
**Steps to reproduce the issue:** 

1. Try to configure the memory with a given unit:
```
minikube config set memory 8g
```

**Full output of failed command:** 

```
❯ minikube version
minikube version: v1.15.1
commit: 23f40a012abb52eff365ff99a709501a61ac5876
❯ minikube config set memory 8g --alsologtostderr
I1124 13:08:06.532895   91753 out.go:185] Setting OutFile to fd 1 ...
I1124 13:08:06.534342   91753 out.go:237] isatty.IsTerminal(1) = true
I1124 13:08:06.534423   91753 out.go:198] Setting ErrFile to fd 2...
I1124 13:08:06.534434   91753 out.go:237] isatty.IsTerminal(2) = true
I1124 13:08:06.535094   91753 root.go:279] Updating PATH: /Users/hag/.minikube/bin
I1124 13:08:06.547629   91753 out.go:110]

W1124 13:08:06.548405   91753 out.go:146] ❌  Exiting due to MK_CONFIG_SET: run validations for "memory" with value of "8g": [memory:strconv.Atoi: parsing "8g": invalid syntax]
❌  Exiting due to MK_CONFIG_SET: run validations for "memory" with value of "8g": [memory:strconv.Atoi: parsing "8g": invalid syntax]
W1124 13:08:06.549032   91753 out.go:146]

W1124 13:08:06.549059   91753 out.go:146] 😿  If the above advice does not help, please let us know:
😿  If the above advice does not help, please let us know:
W1124 13:08:06.549096   91753 out.go:146] 👉  https://github.com/kubernetes/minikube/issues/new/choose
👉  https://github.com/kubernetes/minikube/issues/new/choose
I1124 13:08:06.570154   91753 out.go:110] 
```

**Full output of `minikube start` command used, if not already included:**

not applicable here

---

IMHO the unit should be respected, see https://github.com/kubernetes/minikube/blob/64bfa1596d18560ee2a85cbba74d3638714f8562/cmd/minikube/cmd/start_flags.go#L129

### PR DESCRIPTION
**Pull request by tharun208**
Signed-off-by: Tharun <rajendrantharun@live.com>

This PR fixes the `config set memory` command which has invalid `Validation` and `Set` function which not allowed to set a valid memory value. 

Fixes #9769

### CODE REVIEW

**Review by priyawadhwa — APPROVED** [review]
Thank you for fixing this!

**Comment by priyawadhwa** [comment]
@tharun208 before merge, could you provide the output of the following with your change to ensure it works:

```
minikube config set memory 3g
minikube start
```

**Comment by tharun208** [comment]
> @tharun208 before merge, could you provide the output of the following with your change to ensure it works:
> 
> ```
> minikube config set memory 3g
> minikube start
> ```

Screen Shot 2020-12-01 at 1 56 24 PM

File: cmd/minikube/cmd/config/set_test.go [hunk 1]
```diff
@@ -38,6 +38,10 @@ func TestSetNotAllowed(t *testing.T) {
 	if err == nil || err.Error() != "run validations for \"driver\" with value of \"123456\": [driver \"123456\" is not supported]" {
 		t.Fatalf("Set did not return error for unallowed value: %+v", err)
 	}
+	err = Set("memory", "10a")
+	if err == nil || err.Error() != "run validations for \"memory\" with value of \"10a\": [invalid disk size: invalid size: '10a']" {
+		t.Fatalf("Set did not return error for unallowed value: %+v", err)
+	}
 }
```
Comment (hcguersoy) [inline cmd/minikube/cmd/config/set_test.go:46]: IMHO the positive case should be tested too. Or may I've missed it in the code.

**Review by medyagh — APPROVED** [review]
thanks for this PR 
@tharun208
