### PR TITLE
Detect status before enable/disable addon

### LINKED ISSUE #4417: Usability: check addon status before disable.
Usability issue. While disable an addon, should message to user the addon is not enabled, but not a disabled failed crash message as below:
 
**The exact command to reproduce the issue**:
minikube addons disable heapster

**The full output of the command that failed**:
 ✘ > ~/Documents/GitHub/minikube_fengli > > master > minikube addons disable heapster
✅  heapster was successfully disabled
 ~/Documents/GitHub/minikube_fengli > > master > minikube addons disable heapster

💣  disable failed: [disabling addon deploy/addons/heapster/influx-grafana-rc.yaml.tmpl: Process exited with status 1]
😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:

 ✘ > ~/Documents/GitHub/minikube_fengli > > master > minikube logs |tail
2019/06/03 13:28:04 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:28:34 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:29:04 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:29:34 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:30:04 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:30:34 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:31:04 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:31:34 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.

==> storage-provisioner <==

**The operating system version**:
MAC OS

### PR DESCRIPTION
**Pull request by fenglixa**
- Fix #4417

- UT Result PASS:
image

- Build & Test PASS:
image

### CODE REVIEW

**Comment by RA489** [comment]
@minikube-bot ok-to-test

**Comment by medyagh** [comment]
@minikube-bot ok-to-test

File: cmd/minikube/cmd/config/util.go [hunk 1]
```diff
@@ -138,7 +139,17 @@ func EnableOrDisableAddon(name string, val string) error {
 
 func enableOrDisableAddonInternal(addon *assets.Addon, cmd bootstrapper.CommandRunner, data interface{}, enable bool) error {
 	var err error
+	// check addon status before enable/disable
+	ok, err := addon.IsEnabled()
```
Comment (hpandeycodeit) [inline cmd/minikube/cmd/config/util.go]: Can you change this variable name to be little more informative?

File: cmd/minikube/cmd/config/util.go [hunk 2]
```diff
@@ -138,7 +139,17 @@ func EnableOrDisableAddon(name string, val string) error {
...
+	if err != nil {
+		exit.WithError("Failed to get the addon status ", err)
+	}
+
 	if enable {
+		if ok {
```
Comment (hpandeycodeit) [inline cmd/minikube/cmd/config/util.go]: I think this logic can be moved to the respective command files.

File: cmd/minikube/cmd/config/util.go [hunk 3]
```diff
@@ -155,6 +166,10 @@ func enableOrDisableAddonInternal(addon *assets.Addon, cmd bootstrapper.CommandR
 			}
 		}
 	} else {
+		if !ok {
+			console.ErrStyle(console.Conflict, "addon %s is already disabled.", addon.GetAddon())
```
Comment (hpandeycodeit) [inline cmd/minikube/cmd/config/util.go]: same for this too.

File: cmd/minikube/cmd/config/util.go (hunk 1 above)
Comment (fenglixa) [reply cmd/minikube/cmd/config/util.go]: Address done. Thanks

File: cmd/minikube/cmd/config/util.go (hunk 2 above)
Comment (fenglixa) [reply cmd/minikube/cmd/config/util.go]: Address done. Thanks

File: cmd/minikube/cmd/config/util.go (hunk 3 above)
Comment (fenglixa) [reply cmd/minikube/cmd/config/util.go]: Address done. Thanks
Append my new UT result:
image

**Comment by fenglixa** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
Thanks for contribution, could you pleas add unit testint ? Maybe have a mock enabled addon and try to enable it

**Comment by fenglixa** [comment]
> Thanks for contribution, could you pleas add unit testint ? Maybe have a mock enabled addon and try to enable it

Thanks @medyagh  Did you mean following? I think I appended it already. : )

```
 > ~/Documents/GitHub/minikube >> minikube addons list |grep enable
- addon-manager: enabled
- dashboard: enabled
- default-storageclass: enabled
- storage-provisioner: enabled
 ~/Documents/GitHub/minikube>> minikube addons enable dashboard
💥  addon dashboard was already enabled. 
```

**Comment by medyagh** [comment]
> > > Thanks for contribution, could you pleas add unit testint ? Maybe have a mock enabled addon and try to enable it
> > 
> > 
> > Thanks @medyagh Did you mean following? I think I appended it already. : )
> > ```
> >  > ~/Documents/GitHub/minikube >> minikube addons list |grep enable
> > - addon-manager: enabled
> > - dashboard: enabled
> > - default-storageclass: enabled
> > - storage-provisioner: enabled
> >  ~/Documents/GitHub/minikube>> minikube addons enable dashboard
> > 💥  addon dashboard was already enabled. 
> > ```
> 
> I meant like for example for this logic in your code
> 
> ```
> 	if addonStatus && enable {
> 		console.ErrStyle(console.Conflict, "addon %s was already enabled.", addon.GetAddon())
> 		os.Exit(exit.Unavailable)
> 	} else if !addonStatus && !enable {
> 		console.ErrStyle(console.Conflict, "addon %s was already disabled.", addon.GetAddon())
> 		os.Exit(exit.Unavailable)
> 	}
> ```
> 
> you could put it in a func and then add a TestFunc for it.
> that you could do unit testing for that func, here are some example unit tests in minikube. https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/config/util_test.go#L69
> 
> you could have a unit test that tries to disable an already disabled addon, and expects it to get err

for example you could have a func called

`func isAddonAlreadySet(addon *assets.Addon, enable bool) bool`
and then you can move the logic of  `addonStatus, err := addon.IsEnabled()`  inside that func

**Comment by sharifelgamal** [comment]
@minikube-bot OK to test

**Comment by fenglixa** [comment]
@medyagh Thanks for your comments. I added unit test cases for the new added func. Please help check & review.
@sharifelgamal I addressed the issue in the result of integration test, please help check again. Thanks.
(the reason is get dashboard url will enable dashboard always, which will be failed as it was already enabled)

BR
-Francis

File: cmd/minikube/cmd/config/util.go [hunk 4]
```diff
@@ -138,6 +139,21 @@ func EnableOrDisableAddon(name string, val string) error {
...
+	if addonStatus && enable {
+		console.ErrStyle(console.Conflict, "addon %s was already enabled.", addon.GetAddon())
+		os.Exit(exit.Unavailable)
+	} else if !addonStatus && !enable {
+		console.ErrStyle(console.Conflict, "addon %s was already disabled.", addon.GetAddon())
+		os.Exit(exit.Unavailable)
+	}
+
 	if enable {
 		for _, addon := range addon.Assets {
```
[the remark this answers is not in the document]
Comment (fenglixa) [reply cmd/minikube/cmd/config/util.go]: removed. Thanks

**Comment by fenglixa** [comment]
```
09:34:38 | >   - error: failed to create listener: failed to listen on 0.0.0.0:8443: listen tcp 0.0.0.0:8443: bind: address already in use
--- FAIL: TestVersionUpgrade (127.96s)
```
should be case issue related to #4418

**Comment by fenglixa** [comment]
@minikube-bot OK to test

File: cmd/minikube/cmd/config/util.go [hunk 5]
```diff
@@ -137,20 +137,28 @@ func EnableOrDisableAddon(name string, val string) error {
...
 
 	if err != nil {
-		exit.WithError("Failed to get the addon status ", err)
+		return errors.Wrap(err, "get the addon status")
 	}
 
 	if addonStatus && enable {
-		console.ErrStyle(console.Conflict, "addon %s was already enabled.", addon.GetAddon())
-		os.Exit(exit.Unavailable)
+		return fmt.Errorf("addon %s was already enabled", addon.GetAddon())
```
Comment (medyagh) [inline cmd/minikube/cmd/config/util.go]: for more consistency, lets use errors.Wrap in stead of `fmt.Errorf`

File: cmd/minikube/cmd/config/util_test.go [hunk 6]
```diff
@@ -79,3 +80,15 @@ func TestSetBool(t *testing.T) {
...
 }
+
+func TestIsAddonAlreadySet(t *testing.T) {
+	names := []string{"ingress", "heapster"}
+	for _, name := range names {
+		addon := assets.Addons[name]
+		addonStatus, _ := addon.IsEnabled()
+		err := isAddonAlreadySet(addon, addonStatus)
+		if err == nil {
+			t.Fatalf("did not return error for the addon was already set")
```
Comment (medyagh) [inline cmd/minikube/cmd/config/util_test.go]: Thanks for adding the unit tests, two things to impriove this unit test
1- first lets change the t.Fatalf to t.Error
2- lets make the message in the following format:
```
t.Errorf("Expected to get error , got nil", )
```

File: pkg/minikube/assets/addons.go [hunk 7]
```diff
@@ -47,6 +47,11 @@ func NewAddon(assets []*BinAsset, enabled bool, addonName string) *Addon {
 	return a
 }
 
+// GetAddon get the addon name
+func (a *Addon) GetAddon() string {
```
Comment (medyagh) [inline pkg/minikube/assets/addons.go]: lets change this to Name()
since this does not return the addon but returns a string.

File: cmd/minikube/cmd/config/util.go [hunk 8]
```diff
@@ -136,8 +137,31 @@ func EnableOrDisableAddon(name string, val string) error {
...
+
+	return nil
+}
+
 func enableOrDisableAddonInternal(addon *assets.Addon, cmd bootstrapper.CommandRunner, data interface{}, enable bool) error {
 	var err error
+	// check addon status before enabling/disabling it
+	if err := isAddonAlreadySet(addon, enable); err != nil {
+		console.ErrStyle(console.Conflict, "%v", err)
+		os.Exit(exit.Unavailable)
```
Comment (medyagh) [inline cmd/minikube/cmd/config/util.go]: lets exit with 0, because we don't want to fail automated minikubes tests used CI, if their addon was already set, this will make their script to fail.

I rather we just warn the user but not exit with error. lets exit with code 0

Comment (fenglixa) [reply cmd/minikube/cmd/config/util.go]: Done. Thanks Medya

File: pkg/minikube/assets/addons.go (hunk 7 above)
Comment (fenglixa) [reply pkg/minikube/assets/addons.go]: Done. Thanks Medya

File: cmd/minikube/cmd/config/util_test.go (hunk 6 above)
Comment (fenglixa) [reply cmd/minikube/cmd/config/util_test.go]: Done. Thanks

File: cmd/minikube/cmd/config/util.go (hunk 5 above)
Comment (fenglixa) [reply cmd/minikube/cmd/config/util.go]: Thanks Medya, should not errors.Wrap for this case

**Comment by fenglixa** [comment]
Test failed is not related to my modification.

/retest

File: pkg/minikube/assets/addons.go (hunk 7 above)
Comment (medyagh) [reply pkg/minikube/assets/addons.go]: in go style usually there is no need to say Get, and also since the func on an addon, there is no need to say Addon in the name either, so I suggest changing it to just Name()

File: pkg/minikube/assets/addons.go [hunk 9]
```diff
@@ -47,6 +47,11 @@ func NewAddon(assets []*BinAsset, enabled bool, addonName string) *Addon {
 	return a
 }
 
+// GetAddonName get the addon name
+func (a *Addon) GetAddonName() string {
```
Comment (medyagh) [inline pkg/minikube/assets/addons.go]: Thanks for all the changes, please change this to Name(). I think after this change it will be good to go !

Comment (fenglixa) [reply pkg/minikube/assets/addons.go]: Done. Thanks

File: pkg/minikube/assets/addons.go (hunk 7 above)
Comment (fenglixa) [reply pkg/minikube/assets/addons.go]: Thanks Medya, I changed it to Name().

**Comment by RA489** [comment]
@fenglixa can you please squash the commit to one

**Comment by fenglixa** [comment]
@RA489  squashed done. Thanks

**Comment by RA489** [comment]
fenglixa Thanks!

**Comment by fenglixa** [comment]
Seems it can not take effect when I provide /retest command. Could someone help trigger retest of integration? Thanks

**Comment by fenglixa** [comment]
Thanks @RA489.  but seems it is also not take effect.

**Comment by sharifelgamal** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
@minikube-bot okay to test

**Comment by fenglixa** [comment]
@minikube-bot okay to test

**Comment by medyagh** [comment]
@minikube-bot okay to test.

**Comment by medyagh** [comment]
@minikube-bot okay to test

**Comment by medyagh** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
@fenglixa Thank you so much for patiently making all the required changes and sorry for the unrelated failing tests. Thank you for the contribution
