### PR TITLE
Regenerate docker certs on startup.

### LINKED ISSUE #208: How to re-generate SSL certs?
Hi, thanks for sharing this :)
I've recently moved from docker-machine+localkube to minikube and it is working like a charm!

After running `minikube stop` and then `minikube start`, I see minikubeVM's IP is changed from 192.168.100.101 to 192.168.100.100 and running `eval $(minikube docker-env) && docker ...` or `eval $(minikube docker-env) && docker-compose ...` fails complaining a mismatching hostname in the cert.
Recreating minikubeVM with `minikube delete` and then `minikube start` fixes this.

I believe that `docker-machine` provides `docker-machine regenerate-certs` to handle this case without recreating VMs. I don't know if it is in scope of minikube but anyway I'm reporting this issue for further discussion.

Full log follows:

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 58, in main
  File "compose/cli/main.py", line 109, in perform_command
  File "compose/cli/main.py", line 734, in up
  File "compose/project.py", line 373, in up
  File "compose/project.py", line 471, in find_orphan_containers
  File "compose/project.py", line 466, in _find
  File "compose/project.py", line 448, in _labeled_containers
  File "site-packages/docker/api/container.py", line 70, in containers
  File "site-packages/docker/utils/decorators.py", line 47, in inner
  File "site-packages/docker/client.py", line 120, in _get
  File "site-packages/requests/sessions.py", line 477, in get
  File "site-packages/requests/sessions.py", line 465, in request
  File "site-packages/requests/sessions.py", line 573, in send
  File "site-packages/requests/adapters.py", line 370, in send
  File "site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
  File "site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
  File "site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
  File "site-packages/requests/packages/urllib3/connection.py", line 253, in connect
  File "site-packages/backports/ssl_match_hostname/__init__.py", line 147, in match_hostname
backports.ssl_match_hostname.CertificateError: hostname '192.168.99.100' doesn't match either of 'localhost', '192.168.99.101'
docker-compose returned -1
```

```
$ minikube docker-env
export DOCKER_TLS_VERIFY=1
export DOCKER_HOST=tcp://192.168.99.100:2376
export DOCKER_CERT_PATH=/Users/mumoshu/.minikube/certs
# Run this command to configure your shell:
# eval $(minikube docker-env)
```

### PR DESCRIPTION
**Pull request by dlorenc**
A few other cleanups:

Move host_mock to it's own file
Define a new provision_mock type for testing provisioners

Fixes #208.

### CODE REVIEW

File: pkg/minikube/cluster/cluster_test.go [hunk 1]
```diff
@@ -195,6 +183,10 @@ func TestStartHost(t *testing.T) {
 	if s, _ := h.Driver.GetState(); s != state.Running {
 		t.Fatalf("Machine not started.")
 	}
+
+	if md.Provisioner.Provisioned {
```
Comment (luxas) [inline pkg/minikube/cluster/cluster_test.go]: Why not? Maybe add a comment why you didn't expect a provision.

Comment (dlorenc) [inline pkg/minikube/cluster/cluster_test.go]: Added a comment to clarify. Thanks for the review.

**Comment by luxas** [comment]
LGTM
