### PR TITLE
Fix profile list when there are multi node clusters 

### LINKED ISSUE #9772: profile list for multi node shows error wrongfully
as noted by @sharifelgamal the missing part of this PR is left https://github.com/kubernetes/minikube/pull/9702#issuecomment-731445695
```

|----------|-----------|---------|--------------|------|---------|---------|-------|
| Profile  | VM Driver | Runtime |      IP      | Port | Version | Status  | Nodes |
|----------|-----------|---------|--------------|------|---------|---------|-------|
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.19.4 | Running |     1 |
| p2       | docker    | docker  | 192.168.59.2 | 8443 | v1.19.4 | Running |     2 |
|----------|-----------|---------|--------------|------|---------|---------|-------|
❗  Found 1 invalid profile(s) ! 
	 p2-m02
💡  You can delete them using the following command(s): 
	 $ minikube delete -p p2-m02 
```

### PR DESCRIPTION
**Pull request by daehyeok**
Fix problem which ListProfiles return sub-nodes in Mult-Node clusters as
a part of inValidPs.

fixes #9772
 
before
```
❯ minikube profile list
|----------|-----------|---------|--------------|------|---------|---------|-------|
| Profile  | VM Driver | Runtime |      IP      | Port | Version | Status  | Nodes |
|----------|-----------|---------|--------------|------|---------|---------|-------|
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.20.0 | Running |     2 |
|----------|-----------|---------|--------------|------|---------|---------|-------|
❗  Found 1 invalid profile(s) !
	 minikube-m02
💡  You can delete them using the following command(s):
	 $ minikube delete -p minikube-m02
```
after
```
❯ minikube profile list
|----------|-----------|---------|--------------|------|---------|---------|-------|
| Profile  | VM Driver | Runtime |      IP      | Port | Version | Status  | Nodes |
|----------|-----------|---------|--------------|------|---------|---------|-------|
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.20.0 | Running |     2 |
|----------|-----------|---------|--------------|------|---------|---------|-------|
❗  Found 0 invalid profile(s) !
💡  You can delete them using the following command(s):
```

### CODE REVIEW

File: pkg/minikube/config/profile.go [hunk 1]
```diff
@@ -242,6 +250,27 @@ func removeDupes(profiles []string) []string {
 	return result
 }
 
+// TODO: MachineName is copied from driver to avoid dependency cycle. Remove it or move to other module
+// MachineName returns the name of the machine, as seen by the hypervisor given the cluster and node names
+func MachineName(cc *ClusterConfig, n *Node) string {
```
Comment (medyagh) [inline pkg/minikube/config/profile.go:255]: lets move this a package that everyone can use, and we could refactor all other existances of this function

File: pkg/minikube/config/profile.go [hunk 2]
```diff
@@ -206,8 +207,9 @@ func ListProfiles(miniHome ...string) (validPs []*Profile, inValidPs []*Profile,
 	if err == nil {
 		pDirs = append(pDirs, cs...)
```
Comment (medyagh) [inline pkg/minikube/config/profile.go:208]: the source of the problem is this ListOwnedContainers, that returns "all continuers" including multi node ones
for example it returns

```
[ "minikube",  "minikube-m02"]
```

we could add a check here, to append only if it is not a node conaterin

```
	// try to get profiles list based on all containers created by docker driver
	cs, err := oci.ListOwnedContainers(oci.Docker)
	if err == nil {
                   // add logic here to check if it is primary container or worker node container
		pDirs = append(pDirs, cs...)
	}
```

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/config/profile.go (hunk 2 above)
Comment (medyagh) [reply pkg/minikube/config/profile.go:208]: additionaly we can make the oci.ListOwnedContainers(oci.Docker) to have an option to only return the Master Containers

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/config/profile.go (hunk 1 above)
Comment (daehyeok) [reply pkg/minikube/config/profile.go:255]: Which package is good for new home of this func?

File: pkg/minikube/config/profile.go (hunk 2 above)
Comment (daehyeok) [reply pkg/minikube/config/profile.go:208]: I agree fix `ListOwnedContainers` is the best way.
Could you let me know how can i filter nodes?

Comment (medyagh) [reply pkg/minikube/config/profile.go:208]: unfornatunately in multi node implementaiotn we didnt use the labels https://githu
b.com/medyagh/minikube/blob/9e5beb4e37298d296694cd7339740e336c62a653/pkg/drivers/kic/oci/types.go#L39

so we can't filter the nodes by master there ... ( we could do that for future releases though)
but one simple thing we can do is filter out any -m01 -m02 (digits) from the returned list
so it only returns minikube and not minikbe-m02

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/config/profile.go (hunk 2 above)
Comment (daehyeok) [reply pkg/minikube/config/profile.go:208]: hmm I'm worrying about user make profile with -m02 postfix..
```
minikube start -p test-profile-m02
```

File: pkg/minikube/config/profile.go (hunk 1 above)
Comment (medyagh) [reply pkg/minikube/config/profile.go:255]: does it allow to put it in 'drivers"  package ?

Comment (medyagh) [reply pkg/minikube/config/profile.go:255]: or can we put it in the `machine` package?
so we could call it something like this

```
machine.NameFromConfig(cc *ClusterConfig, n *Node)
```

**Review by medyagh — CHANGES_REQUESTED** [review]

**Comment by tstromberg** [comment]
Any update here? I wonder if @medyagh 's suggestion will also result in a circular dependency.

File: pkg/minikube/config/profile.go (hunk 1 above)
Comment (medyagh) [reply pkg/minikube/config/profile.go:255]: how about we refactor the MachineName func to not depend on clusterConfig or Node ?

so we pass everything we want from it ?

machine.Name(name string,  int nodes, controlPlane bool, ...)

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/config/profile.go (hunk 1 above)
Comment (daehyeok) [reply pkg/minikube/config/profile.go:255]: Function required following arguments,
Cluster name, Node name, number of node in cluster, is controlPlane or not
`machine.Name(clusterName, nodeName string, int nodes, controlPlane bool)`. 
Is it okay?

Comment (medyagh) [reply pkg/minikube/config/profile.go:255]: sure that sounds like a good comprimise

File: pkg/minikube/config/profile.go (hunk 2 above)
Comment (daehyeok) [reply pkg/minikube/config/profile.go:208]: Filter out any -m0x node will have a potential false-negative result with profile.
Do we have any other way??

**Review by medyagh — CHANGES_REQUESTED** [review]
thanks for this PR 
it looks good just one thing I request to add integation test for it.

we have a TestMultiNode https://github.com/medyagh/minikube/blob/89a8cdc794098f9ba0550fbb5eeb19bc3dd8774d/test/integration/multinode_test.go#L29
lets add a Profile List to that test
and ensure the Profile List Exits Normally
only check for exit code 0
```
		}{
			{"FreshStart2Nodes", validateMultiNodeStart},
			{"AddNode", validateAddNodeToMultiNode},
			{"StopNode", validateStopRunningNode},
			{"StartAfterStop", validateStartNodeAfterStop},
			{"DeleteNode", validateDeleteNodeFromMultiNode},
			{"StopMultiNode", validateStopMultiNodeCluster},
			{"RestartMultiNode", validateRestartMultiNodeCluster},
```

lets add profile list after "FreshStart2Nodes",

**Comment by daehyeok** [comment]
Test added case to integration test.

**Comment by sharifelgamal** [comment]
Can we be sure that we don't show the "Found 0 invalid profiles" when there are no invalid profiles? When everything is ok, it should just show the table.

**Comment by daehyeok** [comment]
> Can we be sure that we don't show the "Found 0 invalid profiles" when there are no invalid profiles? When everything is ok, it should just show the table.

How about JSON output? Should we remove empty list too ( "invalid":[] )?
```
❯ minikube profile list -o json
{"invalid":[],"valid":[{"Name":"minikube","Status":"Stopped","Config":{"Name":"minikube","KeepContext":false,"EmbedCerts":false,"MinikubeISO":"","KicBaseImage":"gcr.io/k8s-minikube/kicbase:v0.0.16-snapshot1@sha256:dff16232547bb3ac3f2a9e09a42246a96ecf8f40d9a1c5bcf5a37953690954b6","Memory":3890,"CPUs":2,"DiskSize":20000,"VMDriver":"","Driver":"docker","HyperkitVpnKitSock":"","HyperkitVSockPorts":[],"DockerEnv":null,"ContainerVolumeMounts":null,"InsecureRegistry":null,"RegistryMirror":null,"HostOnlyCIDR":"192.168.99.1/24","HypervVirtualSwitch":"","HypervUseExternalSwitch":false,"HypervExternalAdapter":"","KVMNetwork":"default","KVMQemuURI":"qemu:///system","KVMGPU":false,"KVMHidden":false,"DockerOpt":null,"DisableDriverMounts":false,"NFSShare":[],"NFSSharesRoot":"/nfsshares","UUID":"","NoVTXCheck":false,"DNSProxy":false,"HostDNSResolver":true,"HostOnlyNicType":"virtio","NatNicType":"virtio","SSHIPAddress":"","SSHUser":"","SSHKey":"","SSHPort":0,"KubernetesConfig":{"KubernetesVersion":"v1.20.0","ClusterName":"minikube","Namespace":"default","APIServerName":"minikubeCA","APIServerNames":null,"APIServerIPs":null,"DNSDomain":"cluster.local","ContainerRuntime":"docker","CRISocket":"","NetworkPlugin":"","FeatureGates":"","ServiceCIDR":"10.96.0.0/12","ImageRepository":"","LoadBalancerStartIP":"","LoadBalancerEndIP":"","CustomIngressCert":"","ExtraOptions":null,"ShouldLoadCachedImages":true,"EnableDefaultCNI":false,"CNI":"","NodeIP":"","NodePort":8443,"NodeName":""},"Nodes":[{"Name":"","IP":"192.168.49.2","Port":8443,"KubernetesVersion":"v1.20.0","ControlPlane":true,"Worker":true}],"Addons":{"default-storageclass":true,"storage-provisioner":true},"VerifyComponents":{"apiserver":true,"system_pods":true},"StartHostTimeout":360000000000,"ScheduledStop":null,"ExposedPorts":[],"Network":"","MultiNodeRequested":false}}]}%                                     
```

**Comment by daehyeok** [comment]
> Can we be sure that we don't show the "Found 0 invalid profiles" when there are no invalid profiles? When everything is ok, it should just show the table.

Oops my bad.  I confused master brach also print warn. Please ignore my previous comment.

fixed it.
```
❯ minikube profile list
|----------|-----------|---------|--------------|------|---------|---------|-------|
| Profile  | VM Driver | Runtime |      IP      | Port | Version | Status  | Nodes |
|----------|-----------|---------|--------------|------|---------|---------|-------|
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.20.0 | Stopped |     1 |
|----------|-----------|---------|--------------|------|---------|---------|-------|
```

**Review by medyagh — APPROVED** [review]
