### PR TITLE
--kubernetes-version add support for checking github k8s versions and exit nicely on error

### LINKED ISSUE #16607: make error look nicer when user enters a too new that doesnt exist
### What Happened?

for example if you do 
minikube start --kuberentes-version=1.26.99

minikube should first look up the kuberentes version in our supported versions in constants packages
if it is not there then it should heads up to the users we will try to fetch it from internet, and if it failed it should fail nicely

### PR DESCRIPTION
**Pull request by JudahNour**
fixes  #16607
## Before: 
```
$ mk start --kubernetes-version=v1.28.0-alpha.5
😄  minikube v1.30.1 on Debian rodete (amd64)
❗  Specified Kubernetes version 1.28.0-alpha.5 is newer than the newest supported version: v1.27.3. Use `minikube config defaults kubernetes-version` for details.
✨  Automatically selected the docker driver
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=8000MB) ...
❗  The image 'registry.k8s.io/kube-scheduler:v1.28.0-alpha.5' was not found; unable to add it to cache.
❗  The image 'registry.k8s.io/kube-apiserver:v1.28.0-alpha.5' was not found; unable to add it to cache.
❗  The image 'registry.k8s.io/kube-controller-manager:v1.28.0-alpha.5' was not found; unable to add it to cache.
❗  The image 'registry.k8s.io/kube-proxy:v1.28.0-alpha.5' was not found; unable to add it to cache.
🐳  Preparing Kubernetes v1.28.0-alpha.5 on Docker 24.0.2 ...
❌  Unable to load cached images: loading cached images: stat /usr/local/google/home/judahn/.minikube/cache/images/amd64/registry.k8s.io/kube-apiserver_v1.28.0-alpha.5: no such file or directory

❌  Exiting due to K8S_INSTALL_FAILED: Failed to update cluster: updating control plane: downloading binaries: downloading kubectl: download failed: https://dl.k8s.io/release/v1.28.0-alpha.5/bin/linux/amd64/kubectl?checksum=file:https://dl.k8s.io/release/v1.28.0-alpha.5/bin/linux/amd64/kubectl.sha256: getter: &{Ctx:context.Background Src:https://dl.k8s.io/release/v1.28.0-alpha.5/bin/linux/amd64/kubectl?checksum=file:https://dl.k8s.io/release/v1.28.0-alpha.5/bin/linux/amd64/kubectl.sha256 Dst:/usr/local/google/home/judahn/.minikube/cache/linux/amd64/v1.28.0-alpha.5/kubectl.download Pwd: Mode:2 Umask:---------- Detectors:[0x3f01040 0x3f01040 0x3f01040 0x3f01040 0x3f01040 0x3f01040 0x3f01040] Decompressors:map[bz2:0xc000238490 gz:0xc000238498 tar:0xc000238440 tar.bz2:0xc000238450 tar.gz:0xc000238460 tar.xz:0xc000238470 tar.zst:0xc000238480 tbz2:0xc000238450 tgz:0xc000238460 txz:0xc000238470 tzst:0xc000238480 xz:0xc0002384a0 zip:0xc0002384b0 zst:0xc0002384a8] Getters:map[file:0xc001552bd0 http:0xc00070b590 https:0xc00070b5e0] Dir:false ProgressListener:0x3ec1760 Insecure:false DisableSymlinks:false Options:[0x1c0d8e0]}: invalid checksum: Error downloading checksum file: bad response code: 404

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

```
## After: 
```
$ mk start --kubernetes-version=v1.28.0-alpha.5
😄  minikube v1.30.1 on Debian rodete (amd64)
❗  Specified Kubernetes version 1.28.0-alpha.5 is newer than the newest supported version: v1.27.3. Use `minikube config defaults kubernetes-version` for details.
❗  Specified Kubernetes version 1.28.0-alpha.5 not found in Kubernetes version list. Searching the internet...
❗  Kubernetes version not found in Github version list. You can force a Kubernetes version via the --force flag

❌  Exiting due to K8S_NEW_UNSUPPORTED: Kubernetes 1.28.0-alpha.5 is not supported by this release of minikube
```

## Before: 
```
$ mk start --kubernetes-version=v1.28.0-alpha.4
😄  minikube v1.30.1 on Debian rodete (amd64)
❗  Specified Kubernetes version 1.28.0-alpha.4 is newer than the newest supported version: v1.27.3. Use `minikube config defaults kubernetes-version` for details.
✨  Automatically selected the docker driver
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=8000MB) ...
🐳  Preparing Kubernetes v1.28.0-alpha.4 on Docker 24.0.2 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```
## After: 
```
$ mk start --kubernetes-version=v1.28.0-alpha.4
😄  minikube v1.30.1 on Debian rodete (amd64)
❗  Specified Kubernetes version 1.28.0-alpha.4 is newer than the newest supported version: v1.27.3. Use `minikube config defaults kubernetes-version` for details.
❗  Specified Kubernetes version 1.28.0-alpha.4 not found in Kubernetes version list. Searching the internet...
✅  Kubernetes version 1.28.0-alpha.4 found in Github version list
✨  Automatically selected the docker driver
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=8000MB) ...
🐳  Preparing Kubernetes v1.28.0-alpha.4 on Docker 24.0.2 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

### CODE REVIEW

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: cmd/minikube/cmd/config/kubernetes_version.go [hunk 1]
```diff
@@ -34,3 +38,29 @@ func supportedKubernetesVersions() (releases []string) {
...
+	var releases []string
+	for {
+		rls, resp, err := ghc.Repositories.ListReleases(context.Background(), "kubernetes", "kubernetes", opts)
+		if err != nil {
+			return nil, err
+		}
+		for _, rl := range rls {
+			tag := rl.GetTagName()
+			if semver.IsValid(tag) {
+				releases = append(releases, tag)
```
[the remark this answers is not in the document]
Comment (spowelljr) [reply cmd/minikube/cmd/config/kubernetes_version.go:56]: Actually, this could be made super efficient by simply calling `GetReleaseByTag`

https://pkg.go.dev/github.com/google/go-github/v53/github#RepositoriesService.GetReleaseByTag

https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-a-release-by-tag-name

File: cmd/minikube/cmd/config/kubernetes_version.go [hunk 2]
```diff
@@ -34,3 +38,21 @@ func supportedKubernetesVersions() (releases []string) {
...
+	release, resp, err := ghc.Repositories.GetReleaseByTag(context.Background(), "kubernetes", "kubernetes", ver)
+	if err != nil {
+		if resp != nil && resp.StatusCode == http.StatusNotFound {
+			return false, nil
+		}
+		return false, err
+	}
+	if release.GetTagName() == ver {
+		return true, nil
+	}
```
Comment (spowelljr) [inline cmd/minikube/cmd/config/kubernetes_version.go:55]:
```suggestion
```

This should be redundant now that you're searching for the exact tag.

File: cmd/minikube/cmd/start.go [hunk 3]
```diff
@@ -1771,6 +1771,21 @@ func validateKubernetesVersion(old *config.ClusterConfig) {
...
+		if contains(constants.ValidKubernetesVersions, kubernetesVer) {
+			out.Styled(style.Check, "Kubernetes version {{.specified}} found in version list", out.V{"specified": nvs})
+		} else {
+			out.WarningT("Specified Kubernetes version {{.specified}} not found in Kubernetes version list. Searching the internet...", out.V{"specified": nvs})
+			found, err := cmdcfg.IsInGithubKubernetesVersions(kubernetesVer)
+			if err != nil && !viper.GetBool(force) {
+				exit.Error(reason.KubernetesNotConnect, "error fetching Kubernetes version list from Github", err)
+			}
+			if found {
+				out.Styled(style.Check, "Kubernetes version {{.specified}} found in Github version list", out.V{"specified": nvs})
```
Comment (spowelljr) [inline cmd/minikube/cmd/start.go:1783]:
```suggestion
				out.Styled(style.Check, "Kubernetes version {{.specified}} found in GitHub version list", out.V{"specified": nvs})
```

File: cmd/minikube/cmd/start.go [hunk 4]
```diff
@@ -1771,6 +1771,21 @@ func validateKubernetesVersion(old *config.ClusterConfig) {
...
+			} else if !viper.GetBool(force) {
+				out.WarningT("Kubernetes version not found in Github version list. You can force a Kubernetes version via the --force flag")
```
Comment (spowelljr) [inline cmd/minikube/cmd/start.go:1785]:
```suggestion
				out.WarningT("Kubernetes version not found in GitHub version list. You can force a Kubernetes version via the --force flag")
```

File: pkg/minikube/reason/reason.go [hunk 5]
```diff
@@ -466,6 +466,8 @@ var (
 	KubernetesTooOld = Kind{ID: "K8S_OLD_UNSUPPORTED", ExitCode: ExControlPlaneUnsupported}
 	// a too new Kubernetes version was specified for minikube to use
 	KubernetesTooNew = Kind{ID: "K8S_NEW_UNSUPPORTED", ExitCode: ExControlPlaneUnsupported}
+	// error fetching github kubernetes version list
```
Comment (spowelljr) [inline pkg/minikube/reason/reason.go:469]:
```suggestion
	// error fetching GitHub Kubernetes version list
```

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: cmd/minikube/cmd/start.go [hunk 6]
```diff
@@ -1771,6 +1771,21 @@ func validateKubernetesVersion(old *config.ClusterConfig) {
 	}
 	if nvs.GT(newestVersion) {
 		out.WarningT("Specified Kubernetes version {{.specified}} is newer than the newest supported version: {{.newest}}. Use `minikube config defaults kubernetes-version` for details.", out.V{"specified": nvs, "newest": constants.NewestKubernetesVersion})
+		if contains(constants.ValidKubernetesVersions, kubernetesVer) {
```
Comment (spowelljr) [inline cmd/minikube/cmd/start.go:1774]: If the user specifies `--force` we should probably skip all this as the point of all these checks are to potentially exit, but if the user uses `--force` we aren't going to exit here anyway. Then we're not wasting time doing internet checks if the user explicitly doesn't care.

**Review by spowelljr — CHANGES_REQUESTED** [review]

**Comment by medyagh** [comment]
```
$ mk start --kubernetes-version=v1.28.0-alpha.4
😄  minikube v1.30.1 on Debian rodete (amd64)
❗  Specified Kubernetes version 1.28.0-alpha.4 is newer than the newest supported version: v1.27.3. Use `minikube config defaults kubernetes-version` for details.
❗  Specified Kubernetes version 1.28.0-alpha.4 not found in Kubernetes version list. Searching the internet...
```

second one should not be Warnining Icon it is searching...

File: cmd/minikube/cmd/start.go (hunk 6 above)
Comment (JudahNour) [reply cmd/minikube/cmd/start.go:1774]: Noted. Medya said to still do all the checks

File: cmd/minikube/cmd/config/kubernetes_version.go [hunk 7]
```diff
@@ -17,6 +17,10 @@ limitations under the License.
 package config
 
 import (
+	"context"
+	"net/http"
+
+	"github.com/google/go-github/v53/github"
```
Comment (spowelljr) [inline cmd/minikube/cmd/config/kubernetes_version.go:23]: Could you add this filename to the following list so the automation updates the package version

https://github.com/kubernetes/minikube/blob/10785b3e71ae24a76a62c4e678ff232828cee534/hack/update/go_github_version/update_go_github_version.go#L63-L69

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: cmd/minikube/cmd/config/kubernetes_version.go [hunk 8]
```diff
@@ -34,3 +38,17 @@ func supportedKubernetesVersions() (releases []string) {
 	}
 	return releases
 }
+
+// IsInGithubKubernetesVersions checks whether ver is in the Github list of k8s versions
+func IsInGithubKubernetesVersions(ver string) (bool, error) {
```
Comment (spowelljr) [inline cmd/minikube/cmd/config/kubernetes_version.go:43]:
```suggestion
// IsInGitHubKubernetesVersions checks whether ver is in the GitHub list of K8s versions
func IsInGitHubKubernetesVersions(ver string) (bool, error) {
```

File: cmd/minikube/cmd/start.go [hunk 9]
```diff
@@ -1771,6 +1771,22 @@ func validateKubernetesVersion(old *config.ClusterConfig) {
...
+			out.Styled(style.Check, "Kubernetes version {{.specified}} found in version list", out.V{"specified": nvs})
+		} else {
+			out.WarningT("Specified Kubernetes version {{.specified}} not found in Kubernetes version list", out.V{"specified": nvs})
+			out.Styled(style.Verifying, "Searching the internet for Kubernetes version...")
+			found, err := cmdcfg.IsInGithubKubernetesVersions(kubernetesVer)
```
Comment (spowelljr) [inline cmd/minikube/cmd/start.go:1779]:
```suggestion
			found, err := cmdcfg.IsInGitHubKubernetesVersions(kubernetesVer)
```

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: cmd/minikube/cmd/config/kubernetes_version.go (hunk 8 above)
Comment (JudahNour) [reply cmd/minikube/cmd/config/kubernetes_version.go:43]: Done. I noticed though that there are some constants in pkg/minikube/notify/constants.go with Github instead of GitHub (like GithubMinikubeReleasesURL) are these just typos?

Comment (spowelljr) [reply cmd/minikube/cmd/config/kubernetes_version.go:43]: Yeah, they should be `GitHub`

**Review by spowelljr — APPROVED** [review]

**Comment by spowelljr** [comment]
Something went wrong with your rebase, there's a bunch of file changes here now

**Comment by JudahNour** [comment]
> Something went wrong with your rebase, there's a bunch of file changes here now

I believe this is fixed but I'm trying to fix an issue that I think rebasing again just caused

File: pkg/minikube/reason/reason.go [hunk 10]
```diff
@@ -475,6 +475,8 @@ var (
 	KubernetesTooOld = Kind{ID: "K8S_OLD_UNSUPPORTED", ExitCode: ExControlPlaneUnsupported}
 	// a too new Kubernetes version was specified for minikube to use
 	KubernetesTooNew = Kind{ID: "K8S_NEW_UNSUPPORTED", ExitCode: ExControlPlaneUnsupported}
+	// error fetching GitHub Kubernetes version list
+	KubernetesNotConnect = Kind{ID: "K8S_FAIL_CONNECT"}
```
Comment (spowelljr) [inline pkg/minikube/reason/reason.go:479]: This should have an exit code associated with it

**Review by spowelljr — CHANGES_REQUESTED** [review]

**Review by spowelljr — APPROVED** [review]
