### PR TITLE
Fix --extra-config when starting an existing cluster

### LINKED ISSUE #8242: --extra-config does not take effect on an existing cluster
For example, if you specify `-extra-config kubelet.kube-api-qps=5 --extra-config controller-manager.kube-api-qps=5`, and run `sudo ps -afe | grep controller`, you'll see that the new arguments do not appear.

### PR DESCRIPTION
**Pull request by dekkers**
Fixes #8242

Creating a minikube cluster with `minikube start` no arguments results in null value for ExtraOptions in `.minikube/profiles/minikube/config.json`:

```
        "ExtraOptions": null,
```

If we then stop and start minikube a second time with `minikube start --extra-config=apiserver.enable-admission-plugins=NamespaceAutoProvision` the ExtraOptions in the config file stays the same and in the cluster the apiserver config also doesn't change:

```
$ ps auxwf | grep -v grep | grep -o -- '--enable-admission[^ ]*'
--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
```

Doing the same thing with my patch the ExtraOptions in the profile will change to:

```
                "ExtraOptions": [
                        {
                                "Component": "apiserver",
                                "Key": "enable-admission-plugins",
                                "Value": "NamespaceAutoProvision"
                        }
                ],
```

And if we look in the cluster we see the config has been applied this time:

```
$ ps auxwf | grep -v grep | grep -o -- '--enable-admission[^ ]*'
--enable-admission-plugins=NamespaceAutoProvision
```

### CODE REVIEW

**Review by medyagh — COMMENTED** [review]
do you mind putting the PR description before and after this PR and check if the extra-config actually goes through on an existing cluster?

File: cmd/minikube/cmd/start_flags.go [hunk 1]
```diff
@@ -611,6 +611,10 @@ func updateExistingConfigFromFlags(cmd *cobra.Command, existing *config.ClusterC
 		cc.KubernetesConfig.ImageRepository = viper.GetString(imageRepository)
 	}
 
+	if cmd.Flags().Changed("extra-config") {
+		cc.KubernetesConfig.ExtraOptions = config.ExtraOptions;
```
Comment (tstromberg) [inline cmd/minikube/cmd/start_flags.go:615]: Thank you! Please remove the trailing semi-colon so that this passes the lint check.

An integration test would be nice too to prevent future breakage, but I'd be willing to leave it to a follow-up PR.

Comment (dekkers) [reply cmd/minikube/cmd/start_flags.go]: I've fixed the lint error. I've added an integration test and verified that the test fails without the change.

**Review by priyawadhwa — APPROVED** [review]
LGTM, let's run the tests and make sure they pass

**Comment by sharifelgamal** [comment]
Thanks for your contribution!
