### PR TITLE
extra-config for kube-proxy

### LINKED ISSUE #6689: --extra-config not available for kube-proxy
I’m trying to pass some extra-config to kubeproxy with `--extra-config` but i get the following error:

**The exact command to reproduce the issue**:
```sh
$ minikube start --cpus=2 --memory=6144 --kubernetes-version=1.16.3 --network-plugin=cni  --container-runtime=containerd --addons=metrics-server --extra-config="kubelet.allowed-unsafe-sysctls=net.*" --extra-config="proxy.ipvs-scheduler=rr" --extra-config="proxy.proxy-mode=ipvs"
```
**The full output of the command that failed**:<details>

```sh
Failed to update cluster: generating kubeadm cfg: generating extra component config for kubeadm: unknown component map["apiserver":"apiServer" "controller-manager":"controllerManager" "kubeadm":"kubeadm" "kubelet":"" "scheduler":"scheduler"]. valid components are: map[apiserver:apiServer controller-manager:controllerManager kubeadm:kubeadm kubelet: scheduler:scheduler]
```

</details>

**The output of the `minikube logs` command**:<details>
```
==> container status <==
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID

==> containerd <==
-- Logs begin at Wed 2020-02-19 19:13:40 UTC, end at Wed 2020-02-19 19:14:25 UTC. --
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.362183594Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.362615343Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.362922583Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364077053Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364174765Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364253796Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364275284Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364292084Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364304941Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364318489Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364333474Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364346947Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364360269Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364373781Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364467122Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364490981Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364506359Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364519726Z" level=info msg="loading plugin "io.containerd.grpc.v1.cri"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364761867Z" level=info msg="Start cri plugin with config {PluginConfig:{ContainerdConfig:{Snapshotter:overlayfs DefaultRuntime:{Type:io.containerd.runtime.v1.linux Engine: Root: Options:<nil>} UntrustedWorkloadRuntime:{Type: Engine: Root: Options:<nil>} Runtimes:map[] NoPivot:true} CniConfig:{NetworkPluginBinDir:/opt/cni/bin NetworkPluginConfDir:/etc/cni/net.d NetworkPluginConfTemplate:} Registry:{Mirrors:map[docker.io:{Endpoints:[https://registry-1.docker.io]}] Auths:map[]} StreamServerAddress: StreamServerPort:10010 EnableSelinux:false SandboxImage:k8s.gcr.io/pause:3.1 StatsCollectPeriod:10 SystemdCgroup:false EnableTLSStreaming:false X509KeyPairStreaming:{TLSCertFile: TLSKeyFile:} MaxContainerLogLineSize:16384 DisableProcMount:false} ContainerdRootDir:/mnt/vda1/var/lib/containerd ContainerdEndpoint:/run/containerd/containerd.sock RootDir:/mnt/vda1/var/lib/containerd/io.containerd.grpc.v1.cri StateDir:/run/containerd/io.containerd.grpc.v1.cri}"
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.364951487Z" level=info msg="Connect containerd service"
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.365349741Z" level=info msg="Get image filesystem path "/mnt/vda1/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs""
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.365565623Z" level=error msg="Failed to load cni during init, please check CRI plugin status before setting up network for pods" error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.366943769Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.367868476Z" level=info msg=serving... address="/run/containerd/containerd.sock"
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.367959351Z" level=info msg="containerd successfully booted in 0.196852s"
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.378816167Z" level=info msg="Start subscribing containerd event"
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.378910737Z" level=info msg="Start recovering state"
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.379098133Z" level=info msg="Start event monitor"
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.379116462Z" level=info msg="Start snapshots syncer"
Feb 19 19:13:46 minikube containerd[1903]: time="2020-02-19T19:13:46.379124550Z" level=info msg="Start streaming server"
Feb 19 19:13:49 minikube containerd[1903]: time="2020-02-19T19:13:49.247352810Z" level=info msg="ImageCreate event &ImageCreate{Name:docker.io/kubernetesui/metrics-scraper:v1.0.2,Labels:map[string]string{},}"
Feb 19 19:13:49 minikube containerd[1903]: time="2020-02-19T19:13:49.251638707Z" level=info msg="ImageCreate event &ImageCreate{Name:sha256:3b08661dc379d9f80155be9d658f71578988640357ebae1aab287d6954c723d1,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:49 minikube containerd[1903]: time="2020-02-19T19:13:49.252183930Z" level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/kubernetesui/metrics-scraper:v1.0.2,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:50 minikube containerd[1903]: time="2020-02-19T19:13:50.416365775Z" level=info msg="ImageCreate event &ImageCreate{Name:docker.io/kubernetesui/dashboard:v2.0.0-beta8,Labels:map[string]string{},}"
Feb 19 19:13:50 minikube containerd[1903]: time="2020-02-19T19:13:50.419842352Z" level=info msg="ImageCreate event &ImageCreate{Name:sha256:eb51a359752560a66f314602e87155b75f428fb838bf951079ff1f9621958c0c,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:50 minikube containerd[1903]: time="2020-02-19T19:13:50.421145144Z" level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/kubernetesui/dashboard:v2.0.0-beta8,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:52 minikube containerd[1903]: time="2020-02-19T19:13:52.959866641Z" level=info msg="ImageCreate event &ImageCreate{Name:gcr.io/k8s-minikube/storage-provisioner:v1.8.1,Labels:map[string]string{},}"
Feb 19 19:13:52 minikube containerd[1903]: time="2020-02-19T19:13:52.964238288Z" level=info msg="ImageCreate event &ImageCreate{Name:sha256:4689081edb103a9e8174bf23a255bfbe0b2d9ed82edc907abab6989d1c60f02c,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:52 minikube containerd[1903]: time="2020-02-19T19:13:52.964779897Z" level=info msg="ImageUpdate event &ImageUpdate{Name:gcr.io/k8s-minikube/storage-provisioner:v1.8.1,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:54 minikube containerd[1903]: time="2020-02-19T19:13:54.426357208Z" level=info msg="ImageCreate event &ImageCreate{Name:k8s.gcr.io/kube-proxy:v1.16.3,Labels:map[string]string{},}"
Feb 19 19:13:54 minikube containerd[1903]: time="2020-02-19T19:13:54.429735730Z" level=info msg="ImageCreate event &ImageCreate{Name:sha256:9b65a0f78b091719e2c0bfbc341b5dad88ba7a1a941d8ea04e3e6499c6462a09,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:54 minikube containerd[1903]: time="2020-02-19T19:13:54.430152683Z" level=info msg="ImageUpdate event &ImageUpdate{Name:k8s.gcr.io/kube-proxy:v1.16.3,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:56 minikube containerd[1903]: time="2020-02-19T19:13:56.291405896Z" level=info msg="ImageCreate event &ImageCreate{Name:k8s.gcr.io/pause:3.1,Labels:map[string]string{},}"
Feb 19 19:13:56 minikube containerd[1903]: time="2020-02-19T19:13:56.295085156Z" level=info msg="ImageCreate event &ImageCreate{Name:sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:56 minikube containerd[1903]: time="2020-02-19T19:13:56.295345527Z" level=info msg="ImageUpdate event &ImageUpdate{Name:k8s.gcr.io/pause:3.1,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:56 minikube containerd[1903]: time="2020-02-19T19:13:56.773881143Z" level=info msg="ImageCreate event &ImageCreate{Name:k8s.gcr.io/kube-scheduler:v1.16.3,Labels:map[string]string{},}"
Feb 19 19:13:56 minikube containerd[1903]: time="2020-02-19T19:13:56.777413777Z" level=info msg="ImageCreate event &ImageCreate{Name:sha256:98fecf43a54fdcdd27e2e946a610e417f4f8a2bc1a1f7315fcc4107cc9e87cc3,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:56 minikube containerd[1903]: time="2020-02-19T19:13:56.777827531Z" level=info msg="ImageUpdate event &ImageUpdate{Name:k8s.gcr.io/kube-scheduler:v1.16.3,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:57 minikube containerd[1903]: time="2020-02-19T19:13:57.694946605Z" level=info msg="ImageCreate event &ImageCreate{Name:k8s.gcr.io/coredns:1.6.2,Labels:map[string]string{},}"
Feb 19 19:13:57 minikube containerd[1903]: time="2020-02-19T19:13:57.698570821Z" level=info msg="ImageCreate event &ImageCreate{Name:sha256:bf261d157914477ee1a5969d28ec687f3fbfc9fb5a664b22df78e57023b0e03b,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:57 minikube containerd[1903]: time="2020-02-19T19:13:57.699759606Z" level=info msg="ImageUpdate event &ImageUpdate{Name:k8s.gcr.io/coredns:1.6.2,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:59 minikube containerd[1903]: time="2020-02-19T19:13:59.124181221Z" level=info msg="ImageCreate event &ImageCreate{Name:k8s.gcr.io/kube-controller-manager:v1.16.3,Labels:map[string]string{},}"
Feb 19 19:13:59 minikube containerd[1903]: time="2020-02-19T19:13:59.127941614Z" level=info msg="ImageCreate event &ImageCreate{Name:sha256:bb16442bcd949ab044a0efa29143425c27b2c70dccf97403df78cf0007e85064,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:13:59 minikube containerd[1903]: time="2020-02-19T19:13:59.128522200Z" level=info msg="ImageUpdate event &ImageUpdate{Name:k8s.gcr.io/kube-controller-manager:v1.16.3,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:14:01 minikube containerd[1903]: time="2020-02-19T19:14:01.408497734Z" level=info msg="ImageCreate event &ImageCreate{Name:k8s.gcr.io/kube-apiserver:v1.16.3,Labels:map[string]string{},}"
Feb 19 19:14:01 minikube containerd[1903]: time="2020-02-19T19:14:01.411338652Z" level=info msg="ImageCreate event &ImageCreate{Name:sha256:df60c7526a3dc927817657e25398765a36c957709208e34e622dabe26e4ee382,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:14:01 minikube containerd[1903]: time="2020-02-19T19:14:01.411636596Z" level=info msg="ImageUpdate event &ImageUpdate{Name:k8s.gcr.io/kube-apiserver:v1.16.3,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:14:04 minikube containerd[1903]: time="2020-02-19T19:14:04.604395632Z" level=info msg="ImageCreate event &ImageCreate{Name:k8s.gcr.io/etcd:3.3.15-0,Labels:map[string]string{},}"
Feb 19 19:14:04 minikube containerd[1903]: time="2020-02-19T19:14:04.606869378Z" level=info msg="ImageCreate event &ImageCreate{Name:sha256:b2756210eeabf84f3221da9959e9483f3919dc2aaab4cd45e7cd072fcbde27ed,Labels:map[string]string{io.cri-containerd.image: managed,},}"
Feb 19 19:14:04 minikube containerd[1903]: time="2020-02-19T19:14:04.607563156Z" level=info msg="ImageUpdate event &ImageUpdate{Name:k8s.gcr.io/etcd:3.3.15-0,Labels:map[string]string{io.cri-containerd.image: managed,},}"

==> dmesg <==
[Feb19 19:13] ERROR: earlyprintk= earlyser already used
[  +0.000000] You have booted with nomodeset. This means your GPU drivers are DISABLED
[  +0.000000] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
[  +0.000001] Unless you actually understand what nomodeset does, you should reboot without enabling it
[  +0.128400] ACPI BIOS Warning (bug): Incorrect checksum in table [DSDT] - 0xC0, should be 0x1D (20180810/tbprint-177)
[  +3.887269] ACPI Error: Could not enable RealTimeClock event (20180810/evxfevnt-184)
[  +0.000002] ACPI Warning: Could not enable fixed event - RealTimeClock (4) (20180810/evxface-620)
[  +0.007653] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[  +2.831496] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
[  +0.008279] systemd-fstab-generator[1096]: Ignoring "noauto" for root device
[  +0.001517] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[  +0.000002] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  +0.984645] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
[  +0.604040] vboxguest: loading out-of-tree module taints kernel.
[  +0.003184] vboxguest: PCI device not found, probably running on physical hardware.

==> kernel <==
 19:14:25 up 0 min,  0 users,  load average: 0.37, 0.12, 0.04
Linux minikube 4.19.88 #1 SMP Tue Feb 4 22:25:03 PST 2020 x86_64 GNU/Linux
PRETTY_NAME="Buildroot 2019.02.8"

==> kubelet <==
-- Logs begin at Wed 2020-02-19 19:13:40 UTC, end at Wed 2020-02-19 19:14:25 UTC. --
-- No entries --
```

</details>

**The operating system version**:

macOS v10.14.6

### PR DESCRIPTION
**Pull request by ulm0**
Fixes #6689

### CODE REVIEW

**Comment by medyagh** [comment]
@ulm0 please make sure to run "make test" locally to make sure to pass the tests

**Comment by tstromberg** [comment]
Because this updates the kubeadm config file, the testdata will need to be updated as well. The testdata is located at pkg/minikube/bootstrapper/bsutil/testdata

Please run `make test` to see the list of files to update

**Comment by priyawadhwa** [comment]
Hey @ulm0 are you still working on this? It looks like there are some unit tests that need to be fixed.

**Comment by tstromberg** [comment]
Can this PR be updated? I would really like to see it land in v1.10.

**Comment by ulm0** [comment]
@priyawadhwa yes, i'm working on this! so sorry, it's been a busy few weeks lately.

**Comment by ulm0** [comment]
Added

```go
func createKubeProxyOptions(extraOptions config.ExtraOptionSlice) map[string]string {
	kubeProxyOptions := extraOptions.AsMap().Get(Kubeproxy)
	return kubeProxyOptions
}
```

```go
func GenerateKubeadmYAML(cc config.ClusterConfig, n config.Node, r cruntime.Manager) ([]byte, error) {
...
	opts := struct {
		...
		KubeProxyOptions    map[string]string
	}{
		...
		KubeProxyOptions:    createKubeProxyOptions(k8s.ExtraOptions),
	}
...
}
```

```go
var V1Beta2 = template.Must(template.New("configTmpl-v1beta2").Funcs(template.FuncMap{
	"printMapInOrder": printMapInOrder,
}).Parse(`apiVersion: kubeadm.k8s.io/v1beta2
...
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
clusterCIDR: "{{.PodSubnet }}"
metricsBindAddress: {{.AdvertiseAddress}}:10249
{{- range $i, $val := printMapInOrder .KubeProxyOptions ": " }}
{{$val}}
{{- end}}
`))
```

Drawbacks:
1. Options from `--extra-config` get double quoted 

e.g:

```yaml
...
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
enableProfiling: "true"
```

2. No way to pass objects to config file (such as ipvs configuration and so on)

e.g:

```yaml
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
    excludeCIDRs: null
    minSyncPeriod: 0s
    scheduler: ""
    strictARP: false
    syncPeriod: 0s
    tcpFinTimeout: 0s
    tcpTimeout: 0s
    udpTimeout: 0s
```

- Should we have a list of allowed configs for kube-proxy as in kubeadm params?

Any idea as to how to address the mentioned issues or any other opinion about this PR, please let me know.

**Comment by medyagh** [comment]
@ulm0 sorry for the delay in the review.

**Comment by medyagh** [comment]
@ulm0 do you mind putting in the PR description the After this PR output of an example of using this new extra option feature?

File: cmd/minikube/cmd/start.go [hunk 1]
```diff
@@ -177,7 +177,7 @@ func initKubernetesFlags() {
 	startCmd.Flags().Var(&node.ExtraOptions, "extra-config",
 		`A set of key=value pairs that describe configuration that may be passed to different components.
 		The key should be '.' separated, and the first part before the dot is the component to apply the configuration to.
-		Valid components are: kubelet, kubeadm, apiserver, controller-manager, etcd, proxy, scheduler
+		Valid components are: kubelet, kubeadm, apiserver, controller-manager, etcd, kube-proxy, scheduler
```
Comment (medyagh) [inline cmd/minikube/cmd/start.go]: optional: 
how about putting these valid options in a list, somwhere in the packge and call it here?
so it is always up to date ? and also when we validate the options, we can use the same

Comment (ulm0) [reply cmd/minikube/cmd/start.go]: @medyagh good idea, and been thinking of using something similar to kubeadm options for kubeproxy options also

```go
var KubeadmExtraArgsWhitelist = map[int][]string{
	KubeadmCmdParam: {
		"ignore-preflight-errors",
		"dry-run",
		"kubeconfig",
		"kubeconfig-dir",
		"node-name",
		"cri-socket",
		"experimental-upload-certs",
		"certificate-key",
		"rootfs",
		"skip-phases",
	},
	KubeadmConfigParam: {
		"pod-network-cidr",
	},
}
```

so it can be restricted in order to avoid failure when launching minikube, possible valid values for kubeproxy are as follows

```yaml
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: ""
bindAddressHardFail: false
clientConnection:
    acceptContentTypes: ""
    burst: 0
    contentType: ""
    kubeconfig: ""
    qps: 0
clusterCIDR: ""
configSyncPeriod: 0s
conntrack:
    maxPerCore: null
    min: null
    tcpCloseWaitTimeout: null
    tcpEstablishedTimeout: null
detectLocalMode: ""
enableProfiling: false
healthzBindAddress: ""
hostnameOverride: ""
iptables:
    masqueradeAll: false
    masqueradeBit: null
    minSyncPeriod: 0s
    syncPeriod: 0s
ipvs:
    excludeCIDRs: null
    minSyncPeriod: 0s
    scheduler: ""
    strictARP: false
    syncPeriod: 0s
    tcpFinTimeout: 0s
    tcpTimeout: 0s
    udpTimeout: 0s
metricsBindAddress: ""
mode: ""
nodePortAddresses: null
oomScoreAdj: null
portRange: ""
showHiddenMetricsForVersion: ""
udpIdleTimeout: 0s
winkernel:
    enableDSR: false
    networkName: ""
    sourceVip: ""
```

but package only manages `key: value` for `KubeProxyConfiguration` since `extraOptions.AsMap().Get` only returns `map[string]string`, so as i mentioned a list with valid options for kube-proxy can be added

- bindAddress
- bindAddressHardFail
- configSyncPeriod
- detectLocalMode
- enableProfiling
- healthzBindAddress
- hostnameOverride
- mode
- nodePortAddresses
- oomScoreAdj
- portRange
- showHiddenMetricsForVersion
- udpIdleTimeout

Comment (medyagh) [reply cmd/minikube/cmd/start.go]: that sounds like a good idea for a recator. how about create an issue from your comment and make a follow up refactor PR so I see it in action what u mean ?

**Comment by medyagh** [comment]
@ulm0  could u plz pull upstream master, so we run the tests one more time and then we can merge?

File: cmd/minikube/cmd/start.go (hunk 1 above)
Comment (ulm0) [reply cmd/minikube/cmd/start.go]: @medyagh kk will do so!

**Comment by ulm0** [comment]
@medyagh just updated and pushed

File: pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta1.go [hunk 2]
```diff
@@ -82,5 +82,9 @@ evictionHard:
 ---
 apiVersion: kubeproxy.config.k8s.io/v1alpha1
 kind: KubeProxyConfiguration
+clusterCIDR: "{{.PodSubnet }}"
```
Comment (tstromberg) [inline pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta1.go:85]: When .PodSubnet is empty, I think this line should be removed. To do so,  I think this should be:

{{ if ne .PodSubnet "" }}clusterCIDR: "{{.PodSubnet }}"{{ end }}

File: pkg/minikube/bootstrapper/bsutil/testdata/v1.15/dns.yaml [hunk 3]
```diff
@@ -50,4 +50,5 @@ evictionHard:
 ---
 apiVersion: kubeproxy.config.k8s.io/v1alpha1
 kind: KubeProxyConfiguration
+clusterCIDR: ""
```
Comment (tstromberg) [inline pkg/minikube/bootstrapper/bsutil/testdata/v1.15/dns.yaml:53]: Having clusterCIDR set to an empty string feels wrong here. See previous comment.

File: pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta1.go (hunk 2 above)
Comment (ulm0) [reply pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta1.go:85]: I've based this config block on the existing ones, since clusterCIDR and podSubnet share  the same value

e.g: https://github.com/kubernetes/minikube/blob/master/pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta1.go#L71
```go
...
networking:
  dnsDomain: {{if .DNSDomain}}{{.DNSDomain}}{{else}}cluster.local{{end}}
  podSubnet: "{{.PodSubnet }}"
  serviceSubnet: {{.ServiceCIDR}}
...
```

File: pkg/minikube/bootstrapper/bsutil/testdata/v1.15/dns.yaml (hunk 3 above)
Comment (ulm0) [reply pkg/minikube/bootstrapper/bsutil/testdata/v1.15/dns.yaml:53]: I've based this config block on the existing ones, since clusterCIDR and podSubnet share  the same value

e.g: https://github.com/kubernetes/minikube/blob/master/pkg/minikube/bootstrapper/bsutil/testdata/v1.15/dns.yaml#L37
```yaml
...
networking:
  dnsDomain: 1.1.1.1
  podSubnet: ""
  serviceSubnet: 10.96.0.0/12
...
```

Comment (tstromberg) [reply pkg/minikube/bootstrapper/bsutil/testdata/v1.15/dns.yaml:53]: OK, that seems reasonable. I do think podSubnet is probably doing it wrong as well though.

Comment (ulm0) [reply pkg/minikube/bootstrapper/bsutil/testdata/v1.15/dns.yaml:53]: Got you, i'm doing a refactor PR in the coming days to address these issues
