### PR TITLE
mount: unmount on sigint/sigterm, add --options and --mode, improve UI

### LINKED ISSUE #3853: Hitting Ctrl-C on `minikube mount` fails to unmount volume
```
% /usr/local/bin/minikube mount /tmp/700:/tmp/700
📁  Mounting /tmp/700 into /tmp/700 on the minikube VM
📌  This daemon process needs to stay alive for the mount to be accessible ...
ufs starting
```

If you hit Ctrl-C now, the VM still thinks the volume is mapped:

```
$ mount | grep 700 | grep /tmp/700
192.168.39.1 on /tmp/700 type 9p (rw,relatime,sync,dirsync,dfltuid=1001,dfltgid=1001,access=any,msize=65536,trans=tcp,noextend,port=43403)
$ stat /tmp/700
stat: cannot stat '/tmp/700': Input/output error
```

This means that subsequent changes to the mount point, such as uid/gid, might result in confusion within the host VM.

### PR DESCRIPTION
**Pull request by tstromberg**
A refactoring of the mount command to make it suck less, inspired by @jlaswell on Slack:

- If Ctrl-C or SIGTERM is received, unmount the target volume
- Add `--options` flag to allow arbitrary mount options to be passed
- Add `--mode` flag to set the file mode of the target mount
- Improve mount UI presentation and help strings

Example command:

`minikube mount --mode 0777 --9p-version 9p2000 --uid 72 --gid 82 --options cache
=fscache,nodevmap --msize=8192 /tmp/700:/tmp/700`

Example output:

```
📁  Mounting host path /tmp/700 into VM as /tmp/700 ...
💾  Mount options:
    ▪ Type:     9p
    ▪ UID:      72
    ▪ GID:      82
    ▪ Version:  9p2000
    ▪ MSize:    8192
    ▪ Mode:     777 (-rwxrwxrwx)
    ▪ Options:  map[cache:fscache nodevmap:]
🚀  Userspace file server: ufs starting
✅  Successfully mounted /tmp/700 to /tmp/700

📌  NOTE: This process must stay alive for the mount to be accessible ...
^C🔥  Unmounting /tmp/700 ...
💣  Exiting due to interrupt signal
```

Closes #3853

### CODE REVIEW

File: cmd/minikube/cmd/mount.go [hunk 1]
```diff
@@ -104,22 +109,67 @@ var mountCmd = &cobra.Command{
...
 		}
-		console.OutStyle("mounting", "Mounting %s into %s on the minikube VM", hostPath, vmPath)
-		console.OutStyle("notice", "This daemon process needs to stay alive for the mount to be accessible ...")
 		port, err := cmdUtil.GetPort()
 		if err != nil {
 			exit.WithError("Error finding port for mount", err)
 		}
+
+		cfg := &cluster.MountConfig{
+			Type:    "9p",
```
Comment (tejal29) [inline cmd/minikube/cmd/mount.go]: use constant?
