### PR TITLE
Initial implementation of 'console' package for stylized & localized console output 😂

### LINKED ISSUE #3569: minikube output should include version/platform/arch
This is very useful for bug reports.

### PR DESCRIPTION
**Pull request by tstromberg**
Introduces new console package, and replaces most calls to fmt.Print* with the appropriate calls to console.Out* (stdout) or console.Err* (stderr).

Example usage:

```
console.OutLn("Starting up!")
console.OutStyle("status-change", "Configuring things")
```

These messages are plumbed through to the message.Printer API, which provides a mechanism for future localization. Full support for styles is currently only enabled for TERM's which mention "color", and only then if it's writing to a TTY. This whitelist does not currently include the Windows console, as that will require further testing. 

It is possible to manually turn styles off and on by setting MINIKUBE_IN_COLOR=[01] in your environment.

This resolves #3569 and paves the way for the following roadmap items:

- Localized output to 5+ written languages
- Pre-flight error checks for common connectivity and configuration errors

My apologies for touching so many files in a single PR. This was due to heavy testing to make sure that the error messages plumbed to the user were proper enough for an initial implementation.

### CODE REVIEW

File: pkg/minikube/cluster/cluster.go [hunk 1]
```diff
@@ -80,7 +80,10 @@ func StartHost(api libmachine.API, config cfg.MachineConfig) (*host.Host, error)
 	}
 
 	if h.Driver.DriverName() != config.VMDriver {
-		fmt.Printf("Skipping %s driver, existing host has %s driver.\n", config.VMDriver, h.Driver.DriverName())
+		console.Warning("Ignoring --vm-driver=%s, as the %q host was created using the %s driver.",
```
Comment (balopat) [inline pkg/minikube/cluster/cluster.go]: :heart_eyes:

File: pkg/minikube/console/style.go [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+	"ready":      {Prefix: "🏄"},
+	"restarting": {Prefix: "🔄"},
+	"stopping":   {Prefix: "✋"},
+	"stopped":    {Prefix: "🛑"},
+	"warning":    {Prefix: "⚠️"},
+	"waiting":    {Prefix: "⌛"},
+	"usage":      {Prefix: "💡"},
+	"launch":     {Prefix: "🚀"},
+	"thumbs-up":  {Prefix: "👍"},
+	"option":     {Prefix: "   ▪ "},
```
Comment (balopat) [inline pkg/minikube/console/style.go]: This one has an extra space at the end - is that intentional? 
```suggestion
	"option":     {Prefix: "   ▪"},
```

File: pkg/minikube/bootstrapper/command_runner.go [hunk 3]
```diff
@@ -34,7 +34,7 @@ type CommandRunner interface {
 	//
 	//          var b bytes.Buffer
 	//          CombinedOutput(cmd, &b)
-	//          fmt.Println(b.Bytes())
+	//          console.Fatal(b.Bytes())
```
Comment (balopat) [inline pkg/minikube/bootstrapper/command_runner.go]: accidental or intentional replace?

File: cmd/minikube/main.go [hunk 4]
```diff
@@ -31,12 +32,17 @@ const minikubeEnableProfile = "MINIKUBE_ENABLE_PROFILING"
...
 		defer profile.Start(profile.TraceProfile).Stop()
 	}
 	if os.Getenv(constants.IsMinikubeChildProcess) == "" {
 		machine.StartDriver()
 	}
+	console.SetOutFile(os.Stdout)
+	console.SetErrFile(os.Stderr)
+	err := console.SetPreferredLanguage(os.Getenv("LANG"))
+	if err != nil {
+		glog.Warningf("unable to detect language: %v", err)
```
Comment (balopat) [inline cmd/minikube/main.go]: can the user do anything about this? what does it mean? are we falling back to default English?

File: cmd/minikube/cmd/update-context.go [hunk 5]
```diff
@@ -55,9 +55,9 @@ var updateContextCmd = &cobra.Command{
 			cmdUtil.MaybeReportErrorAndExit(err)
 		}
 		if ok {
-			fmt.Println("Reconfigured kubeconfig IP, now pointing at " + ip.String())
+			console.Fatal("Reconfigured kubeconfig IP, now pointing at %s", ip)
```
Comment (balopat) [inline cmd/minikube/cmd/update-context.go]: is this really Fatal?

File: cmd/minikube/cmd/ssh.go [hunk 6]
```diff
@@ -36,22 +34,22 @@ var sshCmd = &cobra.Command{
...
 		host, err := cluster.CheckIfHostExistsAndLoad(api, config.GetMachineName())
 		if err != nil {
-			fmt.Fprintf(os.Stderr, "Error getting host: %v\n", err)
+			console.Fatal("Error getting host: %v", err)
 			os.Exit(1)
 		}
 		if host.Driver.DriverName() == "none" {
-			fmt.Println(`'none' driver does not support 'minikube ssh' command`)
+			console.Fatal(`'none' driver does not support 'minikube ssh' command`)
 			os.Exit(0)
```
Comment (balopat) [inline cmd/minikube/cmd/ssh.go]: do we want to update this exit code as well to 1?

File: pkg/minikube/console/console.go [hunk 7]
```diff
@@ -0,0 +1,203 @@
...
+	glog.Infof("Setting ErrFile to fd %d...", w.Fd())
+	errFile = w
+	useColor = wantsColor(w.Fd())
+}
+
+// wantsColor determines if the user might want colorized output.
+func wantsColor(fd uintptr) bool {
+	glog.Infof("%s=%q\n", OverrideEnv, os.Getenv(OverrideEnv))
+	switch os.Getenv(OverrideEnv) {
+	case "0":
```
Comment (balopat) [inline pkg/minikube/console/console.go]: I would consider using "true/false" or "on/off" or "yes/no" over "0/1"

File: pkg/minikube/console/console.go [hunk 8]
```diff
@@ -0,0 +1,203 @@
...
+	// errFile is where Err* functions send output to. Set using SetErrFile()
+	errFile fdWriter
+	// preferredLanguage is the default language messages will be output in
+	preferredLanguage = language.AmericanEnglish
+	// our default language
+	defaultLanguage = language.AmericanEnglish
+	// useColor is whether or not color output should be used, updated by Set*Writer.
+	useColor = false
+	// OverrideEnv is the environment variable used to override color/emoji usage
+	OverrideEnv = "MINIKUBE_IN_COLOR"
```
Comment (balopat) [inline pkg/minikube/console/console.go]: this should be a const rather

File: pkg/minikube/console/console.go [hunk 9]
```diff
@@ -0,0 +1,203 @@
...
+
+var (
+	// outFile is where Out* functions send output to. Set using SetOutFile()
+	outFile fdWriter
+	// errFile is where Err* functions send output to. Set using SetErrFile()
+	errFile fdWriter
+	// preferredLanguage is the default language messages will be output in
+	preferredLanguage = language.AmericanEnglish
+	// our default language
+	defaultLanguage = language.AmericanEnglish
```
Comment (balopat) [inline pkg/minikube/console/console.go]: this should be a const rather

File: pkg/minikube/console/console.go [hunk 10]
```diff
@@ -0,0 +1,203 @@
...
+
+// SetPreferredLanguageTag configures which language future messages should use.
+func SetPreferredLanguageTag(l language.Tag) {
+	glog.Infof("Setting Language to %s ...", l)
+	preferredLanguage = l
+}
+
+// SetPreferredLanguage configures which language future messages should use, based on a LANG string.
+func SetPreferredLanguage(s string) error {
+	if s == "" || s == "C" {
```
Comment (balopat) [inline pkg/minikube/console/console.go]: why is "C" default?

File: pkg/minikube/console/console.go [hunk 11]
```diff
@@ -0,0 +1,203 @@
...
+		SetPreferredLanguageTag(defaultLanguage)
+		return nil
+	}
+	// Ignore encoding preferences: we always output utf8. Handles "de_DE.utf8"
```
Comment (balopat) [inline pkg/minikube/console/console.go]: do we want to warn about when we discard encoding preferences?

**Comment by afbjorklund** [comment]
I think you meant "In front of our users 😀" - thanks for making it optional, though
Can we translate this using normal gettext objects later, or how does this work ?

File: pkg/minikube/console/console.go (hunk 7 above)
Comment (afbjorklund) [reply pkg/minikube/console/console.go]: Normally you set the env var to enable, and leave it unset to disable.

In Go this means "" and "1", unless you want to bother with LookupEnv ?

File: cmd/minikube/main.go (hunk 4 above)
Comment (afbjorklund) [reply cmd/minikube/main.go]: Small nitpick here is that LANG is the locale (while LANGUAGE is the language)

    LANG=sv_SE.UTF-8
    LANGUAGE=sv

File: pkg/minikube/console/console.go (hunk 10 above)
Comment (afbjorklund) [reply pkg/minikube/console/console.go]: It's normally what you get, when you don't have any language support installed (including "en")

File: pkg/minikube/console/console.go (hunk 7 above)
Comment (afbjorklund) [reply pkg/minikube/console/console.go]: Since the idea here is to enable the user to opt _out_ of this, and enable it by default...
Maybe we should change the variable name altogether ? like MINIKUBE_NOEMOJIS

Or keep the current approach, and use a string (not "bool") - and let "" mean auto-determine.
Just have to add some more case statements, to cover the above alternative spellings.

File: pkg/minikube/console/style.go (hunk 2 above)
Comment (tstromberg) [reply pkg/minikube/console/style.go]: Thanks for pointing this out. I've switched it so that styles now define their own trailing whitespace, as this one is slightly different.

File: pkg/minikube/bootstrapper/command_runner.go (hunk 3 above)
Comment (tstromberg) [reply pkg/minikube/bootstrapper/command_runner.go]: Accidental. Thanks!

File: cmd/minikube/main.go (hunk 4 above)
Comment (tstromberg) [reply cmd/minikube/main.go]: LANG settings are incredibly complicated: LANG, LANGUAGE, and LC_* all control specific locale settings. LANG is the fallback.

To reduce complexity, I've removed the call to SetPreferredLanguage here. I'll re-introduce it once we have a way of loading alternative languages.

File: cmd/minikube/cmd/update-context.go (hunk 5 above)
Comment (tstromberg) [reply cmd/minikube/cmd/update-context.go]: Fixed.

File: pkg/minikube/console/console.go (hunk 7 above)
Comment (tstromberg) [reply pkg/minikube/console/console.go]: I've switched this code to use strconv.ParseBool to allow true/false as well as 0/1. NOTE: Other parts of minikube use the ladder.

I've added some comments as well, to clarify the behavior. I want users to also be able to force color on, if our automatic sniffing isn't appropriate for their environment.

File: pkg/minikube/console/console.go (hunk 8 above)
Comment (tstromberg) [reply pkg/minikube/console/console.go]: I intentionally left this as a var, in case someone else wants to abuse this library for their own nefarious uses.

File: pkg/minikube/console/console.go (hunk 9 above)
Comment (tstromberg) [reply pkg/minikube/console/console.go]: I agree, but consts in Go are limited to a few built-in data types, and language.Tag isn't one of them: 
https://golang.org/ref/spec#Constants

File: pkg/minikube/console/console.go (hunk 10 above)
Comment (tstromberg) [reply pkg/minikube/console/console.go]: Added a comment describing what C is about. It's hard to find an authoritative declaration of where the value originated, but it's well used and defined in POSIX: http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap07.html#tag_07_02

File: pkg/minikube/console/console.go (hunk 11 above)
Comment (tstromberg) [reply pkg/minikube/console/console.go]: Clarified comment.

**Comment by tstromberg** [comment]
> Can we translate minikube using normal gettext objects later, or how does this work ?

No need to sling objects around. You can today register a translation from anywhere via:

err := message.SetString(language.Swedish, "Installing Kubernetes version %s ...",  "Installerar  Kubernetes version %s ...")

Any future outputs that match the string will be translated appropriately. The intent though is to store a translation maps in a data file (JSON? YAML? Go?) that minikube can reference. Any string which does not have a translation value will default to the closest language -- or english.

https://phraseapp.com/blog/posts/internationalization-i18n-go/ has more info on this approach.

**Comment by balopat** [comment]
LGTM, thank you!

File: pkg/minikube/cluster/cluster.go [hunk 12]
```diff
@@ -80,7 +80,10 @@ func StartHost(api libmachine.API, config cfg.MachineConfig) (*host.Host, error)
...
+			config.VMDriver, cfg.GetMachineName(), h.Driver.DriverName())
+		console.Warning("To change drivers, create a new host using `minikube start -p <name>` or run `minikube delete -p %s`",
```
Comment (balopat) [inline pkg/minikube/cluster/cluster.go]: missing a `%s`

error message: 

``
⚠️  Ignoring --vm-driver=virtualbox, as the "minikube" host was created using the hyperkit driver.
⚠️  To change drivers, create a new host using `minikube start -p <name>` or run `minikube delete -p hyperkit`%!!(MISSING)!(MISSING)(EXTRA string=minikube)
``

Comment (tstromberg) [reply pkg/minikube/cluster/cluster.go]: Good find. New text reads:

```
⚠️  Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the hyperkit driver.
⚠️  To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
⚠️  Alternatively, you may delete the existing VM using `minikube delete -p minikube`
```

**Comment by balopat** [comment]
🎆 🍾
