### PR TITLE
fix "cache add" command error when not specifying :latest tag 

### LINKED ISSUE #10047: `cache add` should use "latest" automatically
**Steps to reproduce the issue:** 

1. `docker pull nginx && minikube cache add nginx`
2. start a cluster: `minikube start -v=5 --alsologtostderr`. The log contains:
```
W1224 16:51:31.103434 2627189 cache_images.go:220] Failed to load cached images for profile minikube. make sure the profile is running. loading cached images: Docker load /var/lib/minikube/images/nginx: loadimage docker.: docker load -i /var/lib/minikube/images/nginx: Process exited with status 1
stdout:

stderr:
invalid tag "nginx"
```
3. inside container/vm, the image has no tag

image

The image is `nginx:latest`:
image

`minikube cache add nginx:latest` works well.

<details>

add a added image:

```
❯ minikube-v1.16.0 cache add nginx -v=6 --alsologtostderr
I1224 17:29:24.348248 2642710 out.go:221] Setting OutFile to fd 1 ...
I1224 17:29:24.348410 2642710 out.go:273] isatty.IsTerminal(1) = true
I1224 17:29:24.348424 2642710 out.go:234] Setting ErrFile to fd 2...
I1224 17:29:24.348436 2642710 out.go:273] isatty.IsTerminal(2) = true
I1224 17:29:24.348559 2642710 root.go:280] Updating PATH: /home/lingsamuel/.minikube/bin
I1224 17:29:24.349436 2642710 cache.go:92] acquiring lock: {Name:mk82677e6f27a2953727b594fc9cf67eb434c366 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I1224 17:29:24.349640 2642710 cache.go:100] /home/lingsamuel/.minikube/cache/images/nginx exists
I1224 17:29:24.349671 2642710 cache.go:81] cache image "nginx" -> "/home/lingsamuel/.minikube/cache/images/nginx" took 488.312µs
I1224 17:29:24.349688 2642710 cache.go:66] save to tar file nginx -> /home/lingsamuel/.minikube/cache/images/nginx succeeded
I1224 17:29:24.349705 2642710 cache.go:73] Successfully saved all images to host disk.
I1224 17:29:24.350606 2642710 cli_runner.go:111] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io --format {{.Names}}
I1224 17:29:24.450138 2642710 main.go:119] libmachine: Found binary path at /home/lingsamuel/.minikube/bin/docker-machine-driver-kvm2
I1224 17:29:24.450666 2642710 main.go:119] libmachine: Launching plugin server for driver kvm2
I1224 17:29:24.528288 2642710 main.go:119] libmachine: Plugin server listening at address 127.0.0.1:34521
I1224 17:29:24.529918 2642710 main.go:119] libmachine: () Calling .GetVersion
I1224 17:29:24.530773 2642710 main.go:119] libmachine: Using API Version  1
I1224 17:29:24.530789 2642710 main.go:119] libmachine: () Calling .SetConfigRaw
I1224 17:29:24.531094 2642710 main.go:119] libmachine: () Calling .GetMachineName
I1224 17:29:24.531212 2642710 main.go:119] libmachine: (minikube) Calling .GetState
I1224 17:29:24.538232 2642710 main.go:119] libmachine: Found binary path at /home/lingsamuel/.minikube/bin/docker-machine-driver-kvm2
I1224 17:29:24.538269 2642710 main.go:119] libmachine: Launching plugin server for driver kvm2
I1224 17:29:24.552997 2642710 main.go:119] libmachine: Plugin server listening at address 127.0.0.1:34779
I1224 17:29:24.553297 2642710 main.go:119] libmachine: () Calling .GetVersion
I1224 17:29:24.553684 2642710 main.go:119] libmachine: Using API Version  1
I1224 17:29:24.553699 2642710 main.go:119] libmachine: () Calling .SetConfigRaw
I1224 17:29:24.553954 2642710 main.go:119] libmachine: () Calling .GetMachineName
I1224 17:29:24.554071 2642710 main.go:119] libmachine: (minikube) Calling .DriverName
I1224 17:29:24.554205 2642710 ssh_runner.go:149] Run: systemctl --version
I1224 17:29:24.554225 2642710 main.go:119] libmachine: (minikube) Calling .GetSSHHostname
I1224 17:29:24.561278 2642710 main.go:119] libmachine: (minikube) Calling .GetSSHPort
I1224 17:29:24.561451 2642710 main.go:119] libmachine: (minikube) Calling .GetSSHKeyPath
I1224 17:29:24.561578 2642710 main.go:119] libmachine: (minikube) Calling .GetSSHUsername
I1224 17:29:24.561687 2642710 sshutil.go:48] new ssh client: &{IP:192.168.39.218 Port:22 SSHKeyPath:/home/lingsamuel/.minikube/machines/minikube/id_rsa Username:docker}
I1224 17:29:24.661536 2642710 ssh_runner.go:149] Run: docker images --format {{.Repository}}:{{.Tag}}
I1224 17:29:24.694245 2642710 docker.go:382] Got preloaded images: -- stdout --
<none>:<none>
kubernetesui/dashboard:v2.1.0
gcr.io/k8s-minikube/storage-provisioner:v4
<none>:<none>
k8s.gcr.io/kube-proxy:v1.19.3
k8s.gcr.io/kube-apiserver:v1.19.3
k8s.gcr.io/kube-scheduler:v1.19.3
k8s.gcr.io/kube-controller-manager:v1.19.3
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/coredns:1.7.0
calico/node:v3.14.1
calico/pod2daemon-flexvol:v3.14.1
calico/cni:v3.14.1
calico/kube-controllers:v3.14.1
kubernetesui/metrics-scraper:v1.0.4
k8s.gcr.io/pause:3.2
kindest/kindnetd:0.5.4

-- /stdout --
I1224 17:29:24.694282 2642710 docker.go:388] nginx wasn't preloaded
I1224 17:29:24.694292 2642710 cache_images.go:77] LoadImages start: [nginx]
I1224 17:29:24.698133 2642710 ssh_runner.go:149] Run: docker image inspect --format {{.Id}} nginx
I1224 17:29:24.722822 2642710 cache_images.go:105] "nginx" needs transfer: "nginx" does not exist at hash "sha256:ae2feff98a0cc5095d97c6c283dcd33090770c76d63877caa99aefbbe4343bdd" in container runtime
I1224 17:29:24.722859 2642710 cache_images.go:241] Loading image from cache: /home/lingsamuel/.minikube/cache/images/nginx
I1224 17:29:24.722881 2642710 vm_assets.go:96] NewFileAsset: /home/lingsamuel/.minikube/cache/images/nginx -> /var/lib/minikube/images/nginx
I1224 17:29:24.722940 2642710 ssh_runner.go:149] Run: stat -c "%s %y" /var/lib/minikube/images/nginx
I1224 17:29:24.726434 2642710 ssh_runner.go:304] copy: skipping /var/lib/minikube/images/nginx (exists)
I1224 17:29:24.726467 2642710 docker.go:152] Loading image: /var/lib/minikube/images/nginx
I1224 17:29:24.726519 2642710 ssh_runner.go:149] Run: docker load -i /var/lib/minikube/images/nginx
I1224 17:29:24.905646 2642710 cache_images.go:81] LoadImages completed in 211.33552ms
W1224 17:29:24.905666 2642710 cache_images.go:220] Failed to load cached images for profile minikube. make sure the profile is running. loading cached images: Docker load /var/lib/minikube/images/nginx: loadimage docker.: docker load -i /var/lib/minikube/images/nginx: Process exited with status 1
stdout:

stderr:
invalid tag "nginx"
I1224 17:29:24.905778 2642710 cache_images.go:227] succeeded pushing to: minikube
I1224 17:29:24.905789 2642710 cache_images.go:228] failed pushing to: minikube
I1224 17:29:24.905802 2642710 main.go:119] libmachine: Making call to close driver server
I1224 17:29:24.905811 2642710 main.go:119] libmachine: (minikube) Calling .Close
I1224 17:29:24.905956 2642710 main.go:119] libmachine: Successfully made call to close driver server
I1224 17:29:24.905973 2642710 main.go:119] libmachine: Making call to close connection to plugin binary
I1224 17:29:24.905991 2642710 main.go:119] libmachine: Making call to close driver server
I1224 17:29:24.906003 2642710 main.go:119] libmachine: (minikube) Calling .Close
I1224 17:29:24.907173 2642710 main.go:119] libmachine: Successfully made call to close driver server
I1224 17:29:24.907187 2642710 main.go:119] libmachine: (minikube) DBG | Closing plugin on server side
I1224 17:29:24.907192 2642710 main.go:119] libmachine: Making call to close connection to plugin binary
```

add a new image:

```
❯ minikube-v1.16.0 cache add alpine -v=6 --alsologtostderr
I1224 17:33:37.070007 2643421 out.go:221] Setting OutFile to fd 1 ...
I1224 17:33:37.070500 2643421 out.go:273] isatty.IsTerminal(1) = true
I1224 17:33:37.070514 2643421 out.go:234] Setting ErrFile to fd 2...
I1224 17:33:37.070525 2643421 out.go:273] isatty.IsTerminal(2) = true
I1224 17:33:37.070649 2643421 root.go:280] Updating PATH: /home/lingsamuel/.minikube/bin
I1224 17:33:37.071515 2643421 cache.go:92] acquiring lock: {Name:mk664644f42df37d00f80d63b7b6d74ef514befb Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I1224 17:33:37.071689 2643421 image.go:168] retrieving image: alpine
I1224 17:33:37.329578 2643421 image.go:171] found index.docker.io/library/alpine:latest locally: &{Image:0xc0006eaa40}
I1224 17:33:37.329620 2643421 cache.go:134] opening:  /home/lingsamuel/.minikube/cache/images/alpine
I1224 17:33:37.864131 2643421 cache.go:129] /home/lingsamuel/.minikube/cache/images/alpine exists
I1224 17:33:37.864174 2643421 cache.go:81] cache image "alpine" -> "/home/lingsamuel/.minikube/cache/images/alpine" took 792.94142ms
I1224 17:33:37.864187 2643421 cache.go:66] save to tar file alpine -> /home/lingsamuel/.minikube/cache/images/alpine succeeded
I1224 17:33:37.864201 2643421 cache.go:73] Successfully saved all images to host disk.
I1224 17:33:37.864855 2643421 cli_runner.go:111] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io --format {{.Names}}
I1224 17:33:37.907700 2643421 main.go:119] libmachine: Found binary path at /home/lingsamuel/.minikube/bin/docker-machine-driver-kvm2
I1224 17:33:37.907733 2643421 main.go:119] libmachine: Launching plugin server for driver kvm2
I1224 17:33:37.984861 2643421 main.go:119] libmachine: Plugin server listening at address 127.0.0.1:41663
I1224 17:33:37.986174 2643421 main.go:119] libmachine: () Calling .GetVersion
I1224 17:33:37.987200 2643421 main.go:119] libmachine: Using API Version  1
I1224 17:33:37.987223 2643421 main.go:119] libmachine: () Calling .SetConfigRaw
I1224 17:33:37.987721 2643421 main.go:119] libmachine: () Calling .GetMachineName
I1224 17:33:37.987874 2643421 main.go:119] libmachine: (minikube) Calling .GetState
I1224 17:33:38.005619 2643421 main.go:119] libmachine: Found binary path at /home/lingsamuel/.minikube/bin/docker-machine-driver-kvm2
I1224 17:33:38.005670 2643421 main.go:119] libmachine: Launching plugin server for driver kvm2
I1224 17:33:38.021084 2643421 main.go:119] libmachine: Plugin server listening at address 127.0.0.1:43905
I1224 17:33:38.021445 2643421 main.go:119] libmachine: () Calling .GetVersion
I1224 17:33:38.021816 2643421 main.go:119] libmachine: Using API Version  1
I1224 17:33:38.021835 2643421 main.go:119] libmachine: () Calling .SetConfigRaw
I1224 17:33:38.022106 2643421 main.go:119] libmachine: () Calling .GetMachineName
I1224 17:33:38.022222 2643421 main.go:119] libmachine: (minikube) Calling .DriverName
I1224 17:33:38.022380 2643421 ssh_runner.go:149] Run: systemctl --version
I1224 17:33:38.022401 2643421 main.go:119] libmachine: (minikube) Calling .GetSSHHostname
I1224 17:33:38.030740 2643421 main.go:119] libmachine: (minikube) Calling .GetSSHPort
I1224 17:33:38.030848 2643421 main.go:119] libmachine: (minikube) Calling .GetSSHKeyPath
I1224 17:33:38.030997 2643421 main.go:119] libmachine: (minikube) Calling .GetSSHUsername
I1224 17:33:38.031091 2643421 sshutil.go:48] new ssh client: &{IP:192.168.39.218 Port:22 SSHKeyPath:/home/lingsamuel/.minikube/machines/minikube/id_rsa Username:docker}
I1224 17:33:38.129951 2643421 ssh_runner.go:149] Run: docker images --format {{.Repository}}:{{.Tag}}
I1224 17:33:38.158973 2643421 docker.go:382] Got preloaded images: -- stdout --
<none>:<none>
kubernetesui/dashboard:v2.1.0
gcr.io/k8s-minikube/storage-provisioner:v4
<none>:<none>
k8s.gcr.io/kube-proxy:v1.19.3
k8s.gcr.io/kube-scheduler:v1.19.3
k8s.gcr.io/kube-controller-manager:v1.19.3
k8s.gcr.io/kube-apiserver:v1.19.3
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/coredns:1.7.0
calico/node:v3.14.1
calico/pod2daemon-flexvol:v3.14.1
calico/cni:v3.14.1
calico/kube-controllers:v3.14.1
kubernetesui/metrics-scraper:v1.0.4
k8s.gcr.io/pause:3.2
kindest/kindnetd:0.5.4

-- /stdout --
I1224 17:33:38.159010 2643421 docker.go:388] alpine wasn't preloaded
I1224 17:33:38.159021 2643421 cache_images.go:77] LoadImages start: [alpine]
I1224 17:33:38.161243 2643421 ssh_runner.go:149] Run: docker image inspect --format {{.Id}} alpine
I1224 17:33:38.190851 2643421 cache_images.go:105] "alpine" needs transfer: "alpine" does not exist at hash "sha256:b7b28af77ffec6054d13378df4fdf02725830086c7444d9c278af25312aa39b9" in container runtime
I1224 17:33:38.190881 2643421 cache_images.go:241] Loading image from cache: /home/lingsamuel/.minikube/cache/images/alpine
I1224 17:33:38.190911 2643421 vm_assets.go:96] NewFileAsset: /home/lingsamuel/.minikube/cache/images/alpine -> /var/lib/minikube/images/alpine
I1224 17:33:38.191017 2643421 ssh_runner.go:149] Run: stat -c "%s %y" /var/lib/minikube/images/alpine
I1224 17:33:38.194809 2643421 ssh_runner.go:300] existence check for /var/lib/minikube/images/alpine: stat -c "%s %y" /var/lib/minikube/images/alpine: Process exited with status 1
stdout:

stderr:
stat: cannot stat '/var/lib/minikube/images/alpine': No such file or directory
I1224 17:33:38.194850 2643421 ssh_runner.go:310] scp /home/lingsamuel/.minikube/cache/images/alpine --> /var/lib/minikube/images/alpine (3031552 bytes)
I1224 17:33:38.246827 2643421 docker.go:152] Loading image: /var/lib/minikube/images/alpine
I1224 17:33:38.246903 2643421 ssh_runner.go:149] Run: docker load -i /var/lib/minikube/images/alpine
I1224 17:33:38.607391 2643421 cache_images.go:81] LoadImages completed in 448.34555ms
W1224 17:33:38.607420 2643421 cache_images.go:220] Failed to load cached images for profile minikube. make sure the profile is running. loading cached images: Docker load /var/lib/minikube/images/alpine: loadimage docker.: docker load -i /var/lib/minikube/images/alpine: Process exited with status 1
stdout:

stderr:
invalid tag "alpine"
I1224 17:33:38.607579 2643421 cache_images.go:227] succeeded pushing to: minikube
I1224 17:33:38.607590 2643421 cache_images.go:228] failed pushing to: minikube
I1224 17:33:38.607613 2643421 main.go:119] libmachine: Making call to close driver server
I1224 17:33:38.607627 2643421 main.go:119] libmachine: (minikube) Calling .Close
I1224 17:33:38.607871 2643421 main.go:119] libmachine: Successfully made call to close driver server
I1224 17:33:38.609952 2643421 main.go:119] libmachine: Making call to close connection to plugin binary
I1224 17:33:38.609972 2643421 main.go:119] libmachine: Making call to close driver server
I1224 17:33:38.609984 2643421 main.go:119] libmachine: (minikube) Calling .Close
I1224 17:33:38.607878 2643421 main.go:119] libmachine: (minikube) DBG | Closing plugin on server side
I1224 17:33:38.610197 2643421 main.go:119] libmachine: Successfully made call to close driver server
I1224 17:33:38.610227 2643421 main.go:119] libmachine: Making call to close connection to plugin binary
```

add with latest tag:

```
❯ minikube-v1.16.0 cache add alpine:latest -v=6 --alsologtostderr
I1224 17:35:14.264371 2643750 out.go:221] Setting OutFile to fd 1 ...
I1224 17:35:14.264740 2643750 out.go:273] isatty.IsTerminal(1) = true
I1224 17:35:14.264756 2643750 out.go:234] Setting ErrFile to fd 2...
I1224 17:35:14.264766 2643750 out.go:273] isatty.IsTerminal(2) = true
I1224 17:35:14.264870 2643750 root.go:280] Updating PATH: /home/lingsamuel/.minikube/bin
I1224 17:35:14.265677 2643750 cache.go:92] acquiring lock: {Name:mk426787395d015f8d0beb964b13d2eb6e3a386a Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I1224 17:35:14.265942 2643750 image.go:168] retrieving image: alpine:latest
I1224 17:35:14.366267 2643750 image.go:171] found index.docker.io/library/alpine:latest locally: &{Image:0xc000590b00}
I1224 17:35:14.366303 2643750 cache.go:134] opening:  /home/lingsamuel/.minikube/cache/images/alpine_latest
I1224 17:35:14.976216 2643750 cache.go:129] /home/lingsamuel/.minikube/cache/images/alpine_latest exists
I1224 17:35:14.976257 2643750 cache.go:81] cache image "alpine:latest" -> "/home/lingsamuel/.minikube/cache/images/alpine_latest" took 711.001683ms
I1224 17:35:14.976273 2643750 cache.go:66] save to tar file alpine:latest -> /home/lingsamuel/.minikube/cache/images/alpine_latest succeeded
I1224 17:35:14.976286 2643750 cache.go:73] Successfully saved all images to host disk.
I1224 17:35:14.976972 2643750 cli_runner.go:111] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io --format {{.Names}}
I1224 17:35:15.124875 2643750 main.go:119] libmachine: Found binary path at /home/lingsamuel/.minikube/bin/docker-machine-driver-kvm2
I1224 17:35:15.125317 2643750 main.go:119] libmachine: Launching plugin server for driver kvm2
I1224 17:35:15.141526 2643750 main.go:119] libmachine: Plugin server listening at address 127.0.0.1:46461
I1224 17:35:15.141900 2643750 main.go:119] libmachine: () Calling .GetVersion
I1224 17:35:15.142523 2643750 main.go:119] libmachine: Using API Version  1
I1224 17:35:15.142544 2643750 main.go:119] libmachine: () Calling .SetConfigRaw
I1224 17:35:15.142779 2643750 main.go:119] libmachine: () Calling .GetMachineName
I1224 17:35:15.142894 2643750 main.go:119] libmachine: (minikube) Calling .GetState
I1224 17:35:15.147363 2643750 main.go:119] libmachine: Found binary path at /home/lingsamuel/.minikube/bin/docker-machine-driver-kvm2
I1224 17:35:15.147401 2643750 main.go:119] libmachine: Launching plugin server for driver kvm2
I1224 17:35:15.163537 2643750 main.go:119] libmachine: Plugin server listening at address 127.0.0.1:35627
I1224 17:35:15.163865 2643750 main.go:119] libmachine: () Calling .GetVersion
I1224 17:35:15.164176 2643750 main.go:119] libmachine: Using API Version  1
I1224 17:35:15.164193 2643750 main.go:119] libmachine: () Calling .SetConfigRaw
I1224 17:35:15.164413 2643750 main.go:119] libmachine: () Calling .GetMachineName
I1224 17:35:15.164520 2643750 main.go:119] libmachine: (minikube) Calling .DriverName
I1224 17:35:15.164682 2643750 ssh_runner.go:149] Run: systemctl --version
I1224 17:35:15.164703 2643750 main.go:119] libmachine: (minikube) Calling .GetSSHHostname
I1224 17:35:15.170838 2643750 main.go:119] libmachine: (minikube) Calling .GetSSHPort
I1224 17:35:15.170969 2643750 main.go:119] libmachine: (minikube) Calling .GetSSHKeyPath
I1224 17:35:15.171104 2643750 main.go:119] libmachine: (minikube) Calling .GetSSHUsername
I1224 17:35:15.171188 2643750 sshutil.go:48] new ssh client: &{IP:192.168.39.218 Port:22 SSHKeyPath:/home/lingsamuel/.minikube/machines/minikube/id_rsa Username:docker}
I1224 17:35:15.261052 2643750 ssh_runner.go:149] Run: docker images --format {{.Repository}}:{{.Tag}}
I1224 17:35:15.288474 2643750 docker.go:382] Got preloaded images: -- stdout --
<none>:<none>
kubernetesui/dashboard:v2.1.0
gcr.io/k8s-minikube/storage-provisioner:v4
<none>:<none>
k8s.gcr.io/kube-proxy:v1.19.3
k8s.gcr.io/kube-scheduler:v1.19.3
k8s.gcr.io/kube-apiserver:v1.19.3
k8s.gcr.io/kube-controller-manager:v1.19.3
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/coredns:1.7.0
calico/node:v3.14.1
calico/pod2daemon-flexvol:v3.14.1
calico/cni:v3.14.1
calico/kube-controllers:v3.14.1
kubernetesui/metrics-scraper:v1.0.4
k8s.gcr.io/pause:3.2
kindest/kindnetd:0.5.4
<none>:<none>

-- /stdout --
I1224 17:35:15.288506 2643750 docker.go:388] alpine:latest wasn't preloaded
I1224 17:35:15.288521 2643750 cache_images.go:77] LoadImages start: [alpine:latest]
I1224 17:35:15.290061 2643750 ssh_runner.go:149] Run: docker image inspect --format {{.Id}} alpine:latest
I1224 17:35:15.314430 2643750 cache_images.go:105] "alpine:latest" needs transfer: "alpine:latest" does not exist at hash "sha256:b7b28af77ffec6054d13378df4fdf02725830086c7444d9c278af25312aa39b9" in container runtime
I1224 17:35:15.314456 2643750 cache_images.go:241] Loading image from cache: /home/lingsamuel/.minikube/cache/images/alpine_latest
I1224 17:35:15.314474 2643750 vm_assets.go:96] NewFileAsset: /home/lingsamuel/.minikube/cache/images/alpine_latest -> /var/lib/minikube/images/alpine_latest
I1224 17:35:15.314555 2643750 ssh_runner.go:149] Run: stat -c "%s %y" /var/lib/minikube/images/alpine_latest
I1224 17:35:15.317861 2643750 ssh_runner.go:300] existence check for /var/lib/minikube/images/alpine_latest: stat -c "%s %y" /var/lib/minikube/images/alpine_latest: Process exited with status 1
stdout:

stderr:
stat: cannot stat '/var/lib/minikube/images/alpine_latest': No such file or directory
I1224 17:35:15.317893 2643750 ssh_runner.go:310] scp /home/lingsamuel/.minikube/cache/images/alpine_latest --> /var/lib/minikube/images/alpine_latest (3031552 bytes)
I1224 17:35:15.372131 2643750 docker.go:152] Loading image: /var/lib/minikube/images/alpine_latest
I1224 17:35:15.372173 2643750 ssh_runner.go:149] Run: docker load -i /var/lib/minikube/images/alpine_latest
I1224 17:35:15.456962 2643750 cache_images.go:263] Transferred and loaded /home/lingsamuel/.minikube/cache/images/alpine_latest from cache
I1224 17:35:15.456990 2643750 cache_images.go:112] Successfully loaded all cached images
I1224 17:35:15.457009 2643750 cache_images.go:81] LoadImages completed in 168.467428ms
I1224 17:35:15.457022 2643750 cache_images.go:227] succeeded pushing to: minikube
I1224 17:35:15.457027 2643750 cache_images.go:228] failed pushing to: 
I1224 17:35:15.457041 2643750 main.go:119] libmachine: Making call to close driver server
I1224 17:35:15.457059 2643750 main.go:119] libmachine: (minikube) Calling .Close
I1224 17:35:15.457282 2643750 main.go:119] libmachine: Successfully made call to close driver server
I1224 17:35:15.457298 2643750 main.go:119] libmachine: Making call to close connection to plugin binary
I1224 17:35:15.457308 2643750 main.go:119] libmachine: Making call to close driver server
I1224 17:35:15.457318 2643750 main.go:119] libmachine: (minikube) Calling .Close
I1224 17:35:15.457487 2643750 main.go:119] libmachine: Successfully made call to close driver server
I1224 17:35:15.457544 2643750 main.go:119] libmachine: Making call to close connection to plugin binary
```

</details>

image

### PR DESCRIPTION
**Pull request by lingsamuel**
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>

Fixes #10047, code from https://github.com/google/go-containerregistry/blob/6544cb07415a0b92dcc4079fdb13c4540f651e11/pkg/name/tag.go#L74-L84

/kind bug

### CODE REVIEW

File: pkg/util/utils.go [hunk 1]
```diff
@@ -109,3 +110,22 @@ func MaybeChownDirRecursiveToMinikubeUser(dir string) error {
...
 	return semver.Make(version[1:])
 }
+
+// NormalizeImageName automatically tag latest to image
+// Example:
+//  nginx -> nginx:latest
+//  localhost:5000/nginx -> localhost:5000/nginx:latest
+//  localhost:5000/nginx:latest -> localhost:5000/nginx:latest
+//  docker.io/dotnet/core/sdk -> docker.io/dotnet/core/sdk:latest
+func NormalizeImageName(image string) string {
```
Comment (medyagh) [inline pkg/util/utils.go:120]: no need to have this in util package. I think `image` package is best place for it.
and it could be a private func in that package.

it could be called normalizeTagName

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/util/utils.go (hunk 1 above)
Comment (lingsamuel) [reply pkg/util/utils.go]: done

**Review by medyagh — APPROVED** [review]
