### PR TITLE
Don't error if we can't retrieve logs from a pod during `minikube logs`

### LINKED ISSUE #12128: Fix `TestStoppedBinaryUpgrade/MinikubeLogs` on Windows
Error:
```
	E0803 02:31:20.916307   36052 logs.go:190] command /bin/bash -c "docker logs --tail 60 61de1a38e325" failed with error: /bin/bash -c "docker logs --tail 60 61de1a38e325": Process exited with status 1
	stdout:
	
	stderr:
	Error: No such container: 61de1a38e325
	 output: "\n** stderr ** \nError: No such container: 61de1a38e325\n\n** /stderr **"
	E0803 02:31:21.493415   36052 logs.go:190] command /bin/bash -c "docker logs --tail 60 ab55cb883c3d" failed with error: /bin/bash -c "docker logs --tail 60 ab55cb883c3d": Process exited with status 1
	stdout:
	
	stderr:
	Error: No such container: ab55cb883c3d
	 output: "\n** stderr ** \nError: No such container: ab55cb883c3d\n\n** /stderr **"
	E0803 02:31:21.981363   36052 logs.go:190] command /bin/bash -c "docker logs --tail 60 3e8d25ce3a8a" failed with error: /bin/bash -c "docker logs --tail 60 3e8d25ce3a8a": Process exited with status 1
	stdout:
	
	stderr:
	Error: No such container: 3e8d25ce3a8a
	 output: "\n** stderr ** \nError: No such container: 3e8d25ce3a8a\n\n** /stderr **"
	! unable to fetch logs for: kube-apiserver [61de1a38e325], kube-controller-manager [ab55cb883c3d], kube-scheduler [3e8d25ce3a8a]
```
https://storage.googleapis.com/minikube-builds/logs/master/19799/Docker_Windows.html#fail_TestStoppedBinaryUpgrade%2fMinikubeLogs

### PR DESCRIPTION
**Pull request by spowelljr**
Fixes #12128

**Problem:**
If we can't retrieve logs from a pod when running the `minikube logs` command fail, a non-zero exit code is returned.

This doesn't make sense for a few reasons:
1. `minikube logs` is a debugging command, as long as it accurately attempts to retrieve logs shouldn't return an error
2. If we fail to get the last start or audit logs we don't return an error, this change would follow convention

**Solution:**
Stop returning a non-zero exit code if we can't retrieve logs from a pod.

### CODE REVIEW

**Comment by spowelljr** [comment]
Test is still failing

File: test/integration/version_upgrade_test.go [hunk 1]
```diff
@@ -197,19 +197,19 @@ func TestStoppedBinaryUpgrade(t *testing.T) {
 		t.Errorf("failed to stop cluster: %s: %v", rr.Command(), err)
 	}
 
-	args = append([]string{"start", "-p", profile, "--memory=2200", "--alsologtostderr", "-v=1"}, StartArgs()...)
-	rr, err = Run(t, exec.CommandContext(ctx, Target(), args...))
-	if err != nil {
-		t.Fatalf("upgrade from %s to HEAD failed: %s: %v", desiredLegacyVersion, rr.Command(), err)
-	}
-
 	t.Run("MinikubeLogs", func(t *testing.T) {
```
Comment (andriyDev) [inline test/integration/version_upgrade_test.go:200]: Control plane node must be running for minikube logs. All other environments get upset about moving the start.

File: cmd/minikube/cmd/logs.go [hunk 2]
```diff
@@ -97,13 +96,7 @@ var logsCmd = &cobra.Command{
...
 			return
 		}
-		err = logs.Output(cr, bs, *co.Config, co.CP.Runner, numberOfLines, logOutput)
-		if err != nil {
-			out.Ln("")
-			// Avoid exit.Error, since it outputs the issue URL
-			out.WarningT("{{.error}}", out.V{"error": err})
-			os.Exit(reason.ExSvcError)
-		}
+		logs.Output(cr, bs, *co.Config, co.CP.Runner, numberOfLines, logOutput)
```
Comment (medyagh) [inline cmd/minikube/cmd/logs.go:99]: it is not a good idea to ignore error,

how about we check for error and if it is becaue we cant get logs because it is not running then just tell the out.Warning("cant get logs for ...") without exiting

**Review by medyagh — CHANGES_REQUESTED** [review]

File: cmd/minikube/cmd/logs.go (hunk 2 above)
Comment (spowelljr) [reply cmd/minikube/cmd/logs.go]: Added it back

**Review by sharifelgamal — APPROVED** [review]
