### PR TITLE
Fix native-ssh flag for the ssh command

### LINKED ISSUE #6852: Not possible to use external ssh client
For some reason, `minikube ssh` is not respecting the `--native-ssh` parameter.

```
Options:
      --native-ssh=true: Use native Golang SSH client (default true). Set to 'false' to use the command line 'ssh'
command when accessing the docker machine. Useful for the machine drivers when they will not start with 'Waiting for
SSH'.
```

But when running `minikube ssh --native-ssh=false`, it still uses the native client.

libmachine: Using SSH client type: native

Seems like something is wrong with the parsing of parameters, with viper/cobra ?

```go
                if viper.GetBool(nativeSSH) {
                        ssh.SetDefaultClient(ssh.Native)
                } else {
                        ssh.SetDefaultClient(ssh.External)
                }

```

### PR DESCRIPTION
**Pull request by afbjorklund**
Closes #6852

### CODE REVIEW

File: cmd/minikube/cmd/ssh.go [hunk 1]
```diff
@@ -69,5 +73,5 @@ var sshCmd = &cobra.Command{
 }
 
 func init() {
-	sshCmd.Flags().Bool(nativeSSH, true, "Use native Golang SSH client (default true). Set to 'false' to use the command line 'ssh' command when accessing the docker machine. Useful for the machine drivers when they will not start with 'Waiting for SSH'.")
+	sshCmd.Flags().BoolVar(&nativeSSHClient, nativeSSH, true, "Use native Golang SSH client (default true). Set to 'false' to use the command line 'ssh' command when accessing the docker machine. Useful for the machine drivers when they will not start with 'Waiting for SSH'.")
```
Comment (medyagh) [inline cmd/minikube/cmd/ssh.go]: I am curious if we have other "bool" flags like this that could be fixed the same way ? (if not I am okay with merging this PR)

Comment (starbassma) [reply cmd/minikube/cmd/ssh.go]: No, this the only one.
Regards
