### PR TITLE
docker: Choose the appropriate bridge interface when multiple exist

### LINKED ISSUE #8131: Docker: Failed to setup kubeconfig: inspect IP bridge network
srahmed@hp:~$ minikube start
😄  minikube v1.10.1 on Ubuntu 20.04
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.2 ...
E0513 19:32:35.665322   20138 start.go:95] Unable to get host IP: inspect IP bridge network "de7f841a3590\n13c6d9205f9b".: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" de7f841a3590
13c6d9205f9b: exit status 1
stdout:

stderr:
Error: No such object: de7f841a3590
13c6d9205f9b

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "de7f841a3590\n13c6d9205f9b".: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" de7f841a3590
13c6d9205f9b: exit status 1
stdout:

stderr:
Error: No such object: de7f841a3590
13c6d9205f9b

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

### PR DESCRIPTION
**Pull request by kadern0**
Signed-off-by: Pablo Caderno <kaderno@gmail.com>

### CODE REVIEW

**Comment by kadern0** [comment]
That's interesting. When I run this test locally, it passes:
```
make integration -e TEST_ARGS="-test.run TestOffline/group/crio --cleanup=false"
go test -ldflags="-X k8s.io/minikube/pkg/version.version=v1.12.3 -X k8s.io/minikube/pkg/version.isoVersion=v1.12.2 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -X k8s.io/minikube/pkg/version.gitCommitID="d98d5a716735c040783b6d82464536fa56dda390" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v2" -v -test.timeout=90m ./test/integration --tags="integration container_image_ostree_stub containers_image_openpgp go_getter_nos3 go_getter_nogcs" -test.run TestOffline/group/crio --cleanup=false
Found 8 cores, limiting parallelism with --test.parallel=4
=== RUN   TestOffline
=== RUN   TestOffline/group
=== RUN   TestOffline/group/crio
=== PAUSE TestOffline/group/crio
=== CONT  TestOffline/group/crio
    TestOffline/group/crio: aab_offline_test.go:55: (dbg) Run:  out/minikube start -p offline-crio-20200825100746-7889 --alsologtostderr -v=1 --memory=2000 --wait=true --container-runtime crio 
    TestOffline/group/crio: aab_offline_test.go:55: (dbg) Done: out/minikube start -p offline-crio-20200825100746-7889 --alsologtostderr -v=1 --memory=2000 --wait=true --container-runtime crio : (1m14.126769298s)
    TestOffline/group/crio: helpers_test.go:176: skipping cleanup of offline-crio-20200825100746-7889 (--cleanup=false)
--- PASS: TestOffline (74.13s)
    --- PASS: TestOffline/group (0.00s)
        --- PASS: TestOffline/group/crio (74.13s)
PASS
Tests completed in 1m14.129398246s (result code 0)
ok  	k8s.io/minikube/test/integration	74.195s
```


Although, I can see in this test that there was some issue with the network before reaching the new code part:
```
	W0822 17:46:24.990195    7322 kic.go:85] unable to create docker network; node ip may not be stable: error creating network: docker network create --driver=bridge --subnet=192.168.39.0/24 --gateway 192.168.39.1 offline-crio-20200822174622-5598: exit status 1

	stdout:

	

	stderr:

	Error response from daemon: Pool overlaps with other one on this address space
```

Can you trigger another test to rule out any external issue that could have impacted the test?

**Comment by medyagh** [comment]
I think this PR will be obsolete by this https://github.com/kubernetes/minikube/pull/9094

**Comment by kadern0** [comment]
@medyagh I've just tested it and it does start without any issue.

File: pkg/drivers/kic/oci/network.go [hunk 1]
```diff
@@ -70,8 +81,25 @@ func dockerGatewayIP(profile string) (net.IP, error) {
 	if err != nil {
 		return nil, errors.Wrapf(err, "get network bridge")
 	}
+	networksOutput := strings.TrimSpace(rr.Stdout.String())
+	networksSlice := strings.Fields(networksOutput)
+	// Look for the minikube container within each docker network
+	for _, net := range networksSlice {
+		// get all containers in the network
+		rs, err := runCmd(exec.Command(Docker, "network", "inspect", net, "-f", "'{{range $k, $v := .Containers}}{{$v.Name}} {{end}}'"))
```
Comment (tstromberg) [inline pkg/drivers/kic/oci/network.go:89]: Remove the inner single-quotes from the template. Otherwise, on UNIX, it adds single apostrophes to the first and last network name.

File: pkg/drivers/kic/oci/network.go [hunk 2]
```diff
@@ -70,8 +81,25 @@ func dockerGatewayIP(profile string) (net.IP, error) {
...
+		if err != nil {
+			return nil, errors.Wrapf(err, "get containers in network")
+		}
+		containersSlice := strings.Fields(rs.Stdout.String())
```
Comment (tstromberg) [inline pkg/drivers/kic/oci/network.go:93]: Call strings.TrimSpace on rr.Stdout.String(): otherwise it will leave the final newline in.

Comment (kadern0) [reply pkg/drivers/kic/oci/network.go:93]: The newLine character is already trimmed by the strings.Fields() function.

Comment (tstromberg) [reply pkg/drivers/kic/oci/network.go:93]: I assumed it was too, and in fact, I tried do duplicate this on Go Playground, and it behaves as you mention. I suspcet my confusion stems from my earlier debugging attempt which the quoting fixed:

```
12.984928  519897 network.go:68] container "'minikube" does not match profile "minikube"
12.984954  519897 network.go:68] container "'" does not match profile "minikube"
13.027496  519897 network.go:68] container "''" does not match profile "minikube"
```

**Comment by tstromberg** [comment]
I can confirm that this fixes my issue. Thank you!
