### PR TITLE
Use `sudo -n` if `--interactive=false`

### LINKED ISSUE #19518: --interactive=false is ignored
### What Happened?

Actual behavior:

When starting minikube with --interactive=false, minikube run sudo command without -n, triggering sudo password prompts.

Expected behavior:

If interaction is disabled use `sudo -n` and fail immediately if sudo without a password is not configured for the command.

Example run:

```
% minikube start --driver qemu --memory 2g --container-runtime containerd --interactive=false --alsologtostderr -v=4
...
| I0827 02:16:48.390075   16853 out.go:177] 🔑  Your firewall is blocking bootpd which is required for socket_vmnet. The following commands will be executed to unblock bootpd:

    $ sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/libexec/bootpd 
    $ sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblock /usr/libexec/bootpd 



🔑  Your firewall is blocking bootpd which is required for socket_vmnet. The following commands will be executed to unblock bootpd:

    $ sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/libexec/bootpd 
    $ sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblock /usr/libexec/bootpd 


I0827 02:16:48.395109   16853 firewall.go:73] testing: [sudo -n /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/libexec/bootpd]
I0827 02:16:48.414543   16853 firewall.go:75] [sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/libexec/bootpd] may require a password: exit status 1
W0827 02:16:48.414588   16853 firewall.go:77] [sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/libexec/bootpd] requires a password, and --interactive=false
I0827 02:16:48.414592   16853 firewall.go:80] running: [sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/libexec/bootpd]
Password:
```

### Attach the log file

[log.txt](https://github.com/user-attachments/files/16754668/log.txt)

### Operating System

macOS (Default)

### Driver

QEMU

### PR DESCRIPTION
**Pull request by spowelljr**
Fixes #19518

Uses `sudo -n` if `--interactive=false`

Also changed the wording from `Your firewall is blocking bootpd which is required for socket_vmnet.` to `Your firewall is blocking bootpd which is required for this configuration.` since vfkit also uses this logic.

### CODE REVIEW

File: pkg/minikube/firewall/firewall.go [hunk 1]
```diff
@@ -75,6 +76,7 @@ func UnblockBootpd() error {
 			klog.Infof("%v may require a password: %v", c.Args, err)
 			if !viper.GetBool("interactive") {
 				klog.Warningf("%s requires a password, and --interactive=false", c.Args)
+				c.Args = slices.Insert(c.Args, 1, "-n")
```
Comment (medyagh) [inline pkg/minikube/firewall/firewall.go:79]: thanks for limitting it only for "interactive" to avoid  Unintended Privilege Escalation like if the user has recently used sudo for a different purpose. This could pose a security risk if the script is compromised or contains errors.
but it makes sense for not interactive

**Review by medyagh — APPROVED** [review]
