### PR TITLE
gvisor: Use chroot instead of LD_LIBRARY_PATH

### LINKED ISSUE #5724: TestGvisorAddon:  "waiting to start: ContainerCreating"
TestGvisorAddon flakes:
```
gvisor :  Error from server (BadRequest): container "nginx" in pod "nginx-gvisor" is waiting to start: ContainerCreating
```

as seen here: https://storage.googleapis.com/minikube-builds/logs/5721/KVM_Linux.txt

<details>
<pre>
--- FAIL: TestGvisorAddon (1057.17s)
    helpers.go:349: MaybeSlowParallel: Sleeping 15s to avoid start race ...
    gvisor_addon_test.go:42: (dbg) Run:  out/minikube-linux-amd64 start -p gvisor-20191024T171027.666717625-13805 --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock --wait=false --vm-driver=kvm2 
    gvisor_addon_test.go:42: (dbg) Done: out/minikube-linux-amd64 start -p gvisor-20191024T171027.666717625-13805 --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock --wait=false --vm-driver=kvm2 : (2m47.430527396s)
    gvisor_addon_test.go:48: (dbg) Run:  out/minikube-linux-amd64 -p gvisor-20191024T171027.666717625-13805 cache add gcr.io/k8s-minikube/gvisor-addon:latest
    gvisor_addon_test.go:48: (dbg) Done: out/minikube-linux-amd64 -p gvisor-20191024T171027.666717625-13805 cache add gcr.io/k8s-minikube/gvisor-addon:latest: (1m33.613067312s)
    gvisor_addon_test.go:54: (dbg) Run:  out/minikube-linux-amd64 -p gvisor-20191024T171027.666717625-13805 addons enable gvisor
    gvisor_addon_test.go:67: (dbg) waiting for pods with labels "kubernetes.io/minikube-addons=gvisor" in namespace "kube-system" ...
    helpers.go:244: "gvisor" [f658f75b-119a-4cd2-911d-4d8b414601f0] Pending
    helpers.go:244: "gvisor" [f658f75b-119a-4cd2-911d-4d8b414601f0] Pending / Ready:ContainersNotReady (containers with unready status: [gvisor]) / ContainersReady:ContainersNotReady (containers with unready status: [gvisor])
    helpers.go:244: "gvisor" [f658f75b-119a-4cd2-911d-4d8b414601f0] Running
    helpers.go:244: "gvisor" [f658f75b-119a-4cd2-911d-4d8b414601f0] Running / Ready:ContainersNotReady (containers with unready status: [gvisor]) / ContainersReady:ContainersNotReady (containers with unready status: [gvisor])
    helpers.go:244: "gvisor" [f658f75b-119a-4cd2-911d-4d8b414601f0] Running
    gvisor_addon_test.go:67: (dbg) pods kubernetes.io/minikube-addons=gvisor up and healthy within 14.165278096s
    gvisor_addon_test.go:72: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 replace --force -f testdata/nginx-untrusted.yaml
    gvisor_addon_test.go:72: (dbg) Done: kubectl --context gvisor-20191024T171027.666717625-13805 replace --force -f testdata/nginx-untrusted.yaml: (4.463675608s)
    gvisor_addon_test.go:77: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 replace --force -f testdata/nginx-gvisor.yaml
    gvisor_addon_test.go:82: (dbg) waiting for pods with labels "run=nginx,untrusted=true" in namespace "default" ...
    helpers.go:244: "nginx-untrusted" [08391835-b41d-4564-9a46-6cc4f8294759] Pending / Ready:ContainersNotReady (containers with unready status: [nginx]) / ContainersReady:ContainersNotReady (containers with unready status: [nginx])
    gvisor_addon_test.go:82: pod "run=nginx,untrusted=true" failed to start: timed out waiting for the condition
    helpers.go:289: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 get po -A --show-labels
    helpers.go:295: (dbg) kubectl --context gvisor-20191024T171027.666717625-13805 get po -A --show-labels:
        NAMESPACE     NAME                               READY   STATUS              RESTARTS   AGE     LABELS
        default       nginx-gvisor                       0/1     ContainerCreating   0          2m1s    run=nginx,runtime=gvisor
        default       nginx-untrusted                    0/1     ContainerCreating   0          2m1s    run=nginx,untrusted=true
        kube-system   coredns-5644d7b6d9-296sq           1/1     Running             0          4m1s    k8s-app=kube-dns,pod-template-hash=5644d7b6d9
        kube-system   coredns-5644d7b6d9-blmlb           1/1     Running             0          4m1s    k8s-app=kube-dns,pod-template-hash=5644d7b6d9
        kube-system   etcd-minikube                      1/1     Running             0          3m7s    component=etcd,tier=control-plane
        kube-system   gvisor                             0/1     CrashLoopBackOff    4          2m18s   addonmanager.kubernetes.io/mode=Reconcile,kubernetes.io/minikube-addons=gvisor
        kube-system   kube-addon-manager-minikube        1/1     Running             0          2m59s   component=kube-addon-manager,kubernetes.io/minikube-addons=addon-manager,version=v9.0.2
        kube-system   kube-apiserver-minikube            1/1     Running             0          3m31s   component=kube-apiserver,tier=control-plane
        kube-system   kube-controller-manager-minikube   1/1     Running             0          3m10s   component=kube-controller-manager,tier=control-plane
        kube-system   kube-proxy-zj44q                   1/1     Running             0          4m1s    controller-revision-hash=5447bbc5f8,k8s-app=kube-proxy,pod-template-generation=1
        kube-system   kube-scheduler-minikube            1/1     Running             0          3m11s   component=kube-scheduler,tier=control-plane
        kube-system   storage-provisioner                1/1     Running             0          3m49s   addonmanager.kubernetes.io/mode=Reconcile,integration-test=storage-provisioner
    helpers.go:298: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 describe po nginx-untrusted -n default
    helpers.go:302: (dbg) kubectl --context gvisor-20191024T171027.666717625-13805 describe po nginx-untrusted -n default:
        Name:         nginx-untrusted
        Namespace:    default
        Priority:     0
        Node:         minikube/192.168.39.47
        Start Time:   Thu, 24 Oct 2019 17:15:08 +0000
        Labels:       run=nginx
                      untrusted=true
        Annotations:  io.kubernetes.cri.untrusted-workload: true
        Status:       Pending
        IP:           
        IPs:          <none>
        Containers:
          nginx:
            Container ID:   
            Image:          nginx
            Image ID:       
            Port:           <none>
            Host Port:      <none>
            State:          Waiting
              Reason:       ContainerCreating
            Ready:          False
            Restart Count:  0
            Environment:    <none>
            Mounts:
              /var/run/secrets/kubernetes.io/serviceaccount from default-token-q2v2q (ro)
        Conditions:
          Type              Status
          Initialized       True 
          Ready             False 
          ContainersReady   False 
          PodScheduled      True 
        Volumes:
          default-token-q2v2q:
            Type:        Secret (a volume populated by a Secret)
            SecretName:  default-token-q2v2q
            Optional:    false
        QoS Class:       BestEffort
        Node-Selectors:  <none>
        Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                         node.kubernetes.io/unreachable:NoExecute for 300s
        Events:
          Type     Reason                  Age                 From               Message
          ----     ------                  ----                ----               -------
          Normal   Scheduled               <unknown>           default-scheduler  Successfully assigned default/nginx-untrusted to minikube
          Warning  FailedCreatePodSandBox  12s (x8 over 119s)  kubelet, minikube  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
    helpers.go:305: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 logs nginx-untrusted -n default
    helpers.go:305: (dbg) Non-zero exit: kubectl --context gvisor-20191024T171027.666717625-13805 logs nginx-untrusted -n default: exit status 1 (1.404701928s)
         
        ** stderr ** 
        Error from server (BadRequest): container "nginx" in pod "nginx-untrusted" is waiting to start: ContainerCreating
         
        ** /stderr **
    helpers.go:307: kubectl --context gvisor-20191024T171027.666717625-13805 logs nginx-untrusted -n default: exit status 1
    gvisor_addon_test.go:83: nginx: run=nginx,untrusted=true within 2m0s: timed out waiting for the condition
    gvisor_addon_test.go:85: (dbg) waiting for pods with labels "run=nginx,runtime=gvisor" in namespace "default" ...
    helpers.go:244: "nginx-gvisor" [86aaab2d-bbd7-4b19-b842-e2add2c62776] Pending / Ready:ContainersNotReady (containers with unready status: [nginx]) / ContainersReady:ContainersNotReady (containers with unready status: [nginx])
    gvisor_addon_test.go:85: pod "run=nginx,runtime=gvisor" failed to start: timed out waiting for the condition
    helpers.go:289: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 get po -A --show-labels
    helpers.go:295: (dbg) kubectl --context gvisor-20191024T171027.666717625-13805 get po -A --show-labels:
        NAMESPACE     NAME                               READY   STATUS              RESTARTS   AGE     LABELS
        default       nginx-gvisor                       0/1     ContainerCreating   0          4m3s    run=nginx,runtime=gvisor
        default       nginx-untrusted                    0/1     ContainerCreating   0          4m3s    run=nginx,untrusted=true
        kube-system   coredns-5644d7b6d9-296sq           1/1     Running             0          6m3s    k8s-app=kube-dns,pod-template-hash=5644d7b6d9
        kube-system   coredns-5644d7b6d9-blmlb           1/1     Running             0          6m3s    k8s-app=kube-dns,pod-template-hash=5644d7b6d9
        kube-system   etcd-minikube                      1/1     Running             0          5m9s    component=etcd,tier=control-plane
        kube-system   gvisor                             0/1     CrashLoopBackOff    5          4m20s   addonmanager.kubernetes.io/mode=Reconcile,kubernetes.io/minikube-addons=gvisor
        kube-system   kube-addon-manager-minikube        1/1     Running             0          5m1s    component=kube-addon-manager,kubernetes.io/minikube-addons=addon-manager,version=v9.0.2
        kube-system   kube-apiserver-minikube            1/1     Running             0          5m33s   component=kube-apiserver,tier=control-plane
        kube-system   kube-controller-manager-minikube   1/1     Running             0          5m12s   component=kube-controller-manager,tier=control-plane
        kube-system   kube-proxy-zj44q                   1/1     Running             0          6m3s    controller-revision-hash=5447bbc5f8,k8s-app=kube-proxy,pod-template-generation=1
        kube-system   kube-scheduler-minikube            1/1     Running             0          5m13s   component=kube-scheduler,tier=control-plane
        kube-system   storage-provisioner                1/1     Running             0          5m51s   addonmanager.kubernetes.io/mode=Reconcile,integration-test=storage-provisioner
    helpers.go:298: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 describe po nginx-gvisor -n default
    helpers.go:302: (dbg) kubectl --context gvisor-20191024T171027.666717625-13805 describe po nginx-gvisor -n default:
        Name:         nginx-gvisor
        Namespace:    default
        Priority:     0
        Node:         minikube/192.168.39.47
        Start Time:   Thu, 24 Oct 2019 17:15:08 +0000
        Labels:       run=nginx
                      runtime=gvisor
        Annotations:  <none>
        Status:       Pending
        IP:           
        IPs:          <none>
        Containers:
          nginx:
            Container ID:   
            Image:          nginx
            Image ID:       
            Port:           <none>
            Host Port:      <none>
            State:          Waiting
              Reason:       ContainerCreating
            Ready:          False
            Restart Count:  0
            Environment:    <none>
            Mounts:
              /var/run/secrets/kubernetes.io/serviceaccount from default-token-q2v2q (ro)
        Conditions:
          Type              Status
          Initialized       True 
          Ready             False 
          ContainersReady   False 
          PodScheduled      True 
        Volumes:
          default-token-q2v2q:
            Type:        Secret (a volume populated by a Secret)
            SecretName:  default-token-q2v2q
            Optional:    false
        QoS Class:       BestEffort
        Node-Selectors:  <none>
        Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                         node.kubernetes.io/unreachable:NoExecute for 300s
        Events:
          Type     Reason                  Age                 From               Message
          ----     ------                  ----                ----               -------
          Normal   Scheduled               <unknown>           default-scheduler  Successfully assigned default/nginx-gvisor to minikube
          Warning  FailedCreatePodSandBox  3s (x17 over 4m2s)  kubelet, minikube  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
    helpers.go:305: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 logs nginx-gvisor -n default
    helpers.go:305: (dbg) Non-zero exit: kubectl --context gvisor-20191024T171027.666717625-13805 logs nginx-gvisor -n default: exit status 1 (431.510367ms)
         
        ** stderr ** 
        Error from server (BadRequest): container "nginx" in pod "nginx-gvisor" is waiting to start: ContainerCreating
         
        ** /stderr **
    helpers.go:307: kubectl --context gvisor-20191024T171027.666717625-13805 logs nginx-gvisor -n default: exit status 1
    gvisor_addon_test.go:86: nginx: run=nginx,runtime=gvisor within 2m0s: timed out waiting for the condition
    gvisor_addon_test.go:90: (dbg) Run:  out/minikube-linux-amd64 stop -p gvisor-20191024T171027.666717625-13805
    gvisor_addon_test.go:90: (dbg) Done: out/minikube-linux-amd64 stop -p gvisor-20191024T171027.666717625-13805: (1m39.913894745s)
    gvisor_addon_test.go:95: (dbg) Run:  out/minikube-linux-amd64 start -p gvisor-20191024T171027.666717625-13805 --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock --wait=false --vm-driver=kvm2 
    gvisor_addon_test.go:95: (dbg) Done: out/minikube-linux-amd64 start -p gvisor-20191024T171027.666717625-13805 --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock --wait=false --vm-driver=kvm2 : (2m46.323270373s)
    gvisor_addon_test.go:99: (dbg) waiting for pods with labels "kubernetes.io/minikube-addons=gvisor" in namespace "kube-system" ...
    helpers.go:244: "gvisor" [f658f75b-119a-4cd2-911d-4d8b414601f0] Running
    gvisor_addon_test.go:99: (dbg) pods kubernetes.io/minikube-addons=gvisor up and healthy within 5.167347418s
    gvisor_addon_test.go:102: (dbg) waiting for pods with labels "run=nginx,untrusted=true" in namespace "default" ...
    helpers.go:244: "nginx-untrusted" [08391835-b41d-4564-9a46-6cc4f8294759] Pending / Ready:ContainersNotReady (containers with unready status: [nginx]) / ContainersReady:ContainersNotReady (containers with unready status: [nginx])
    gvisor_addon_test.go:102: pod "run=nginx,untrusted=true" failed to start: timed out waiting for the condition
    helpers.go:289: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 get po -A --show-labels
    helpers.go:289: (dbg) Done: kubectl --context gvisor-20191024T171027.666717625-13805 get po -A --show-labels: (1.280007753s)
    helpers.go:295: (dbg) kubectl --context gvisor-20191024T171027.666717625-13805 get po -A --show-labels:
        NAMESPACE              NAME                                         READY   STATUS              RESTARTS   AGE     LABELS
        default                nginx-gvisor                                 0/1     ContainerCreating   0          10m     run=nginx,runtime=gvisor
        default                nginx-untrusted                              0/1     ContainerCreating   0          10m     run=nginx,untrusted=true
        kube-system            coredns-5644d7b6d9-296sq                     1/1     Running             1          12m     k8s-app=kube-dns,pod-template-hash=5644d7b6d9
        kube-system            coredns-5644d7b6d9-blmlb                     1/1     Running             1          12m     k8s-app=kube-dns,pod-template-hash=5644d7b6d9
        kube-system            etcd-minikube                                1/1     Running             1          11m     component=etcd,tier=control-plane
        kube-system            gvisor                                       0/1     Error               9          10m     addonmanager.kubernetes.io/mode=Reconcile,kubernetes.io/minikube-addons=gvisor
        kube-system            kube-addon-manager-minikube                  1/1     Running             1          11m     component=kube-addon-manager,kubernetes.io/minikube-addons=addon-manager,version=v9.0.2
        kube-system            kube-apiserver-minikube                      1/1     Running             1          12m     component=kube-apiserver,tier=control-plane
        kube-system            kube-controller-manager-minikube             1/1     Running             0          2m32s   component=kube-controller-manager,tier=control-plane
        kube-system            kube-proxy-zj44q                             1/1     Running             1          12m     controller-revision-hash=5447bbc5f8,k8s-app=kube-proxy,pod-template-generation=1
        kube-system            kube-scheduler-minikube                      1/1     Running             1          11m     component=kube-scheduler,tier=control-plane
        kube-system            storage-provisioner                          1/1     Running             1          12m     addonmanager.kubernetes.io/mode=Reconcile,integration-test=storage-provisioner
        kubernetes-dashboard   dashboard-metrics-scraper-76585494d8-nc7wk   1/1     Running             0          2m7s    k8s-app=dashboard-metrics-scraper,pod-template-hash=76585494d8
        kubernetes-dashboard   kubernetes-dashboard-57f4cb4545-bqjcr        1/1     Running             0          2m7s    k8s-app=kubernetes-dashboard,pod-template-hash=57f4cb4545
    helpers.go:298: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 describe po nginx-untrusted -n default
    helpers.go:302: (dbg) kubectl --context gvisor-20191024T171027.666717625-13805 describe po nginx-untrusted -n default:
        Name:         nginx-untrusted
        Namespace:    default
        Priority:     0
        Node:         minikube/192.168.39.47
        Start Time:   Thu, 24 Oct 2019 17:15:08 +0000
        Labels:       run=nginx
                      untrusted=true
        Annotations:  io.kubernetes.cri.untrusted-workload: true
        Status:       Pending
        IP:           
        IPs:          <none>
        Containers:
          nginx:
            Container ID:   
            Image:          nginx
            Image ID:       
            Port:           <none>
            Host Port:      <none>
            State:          Waiting
              Reason:       ContainerCreating
            Ready:          False
            Restart Count:  0
            Environment:    <none>
            Mounts:
              /var/run/secrets/kubernetes.io/serviceaccount from default-token-q2v2q (ro)
        Conditions:
          Type              Status
          Initialized       True 
          Ready             False 
          ContainersReady   False 
          PodScheduled      True 
        Volumes:
          default-token-q2v2q:
            Type:        Secret (a volume populated by a Secret)
            SecretName:  default-token-q2v2q
            Optional:    false
        QoS Class:       BestEffort
        Node-Selectors:  <none>
        Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                         node.kubernetes.io/unreachable:NoExecute for 300s
        Events:
          Type     Reason                  Age                   From               Message
          ----     ------                  ----                  ----               -------
          Normal   Scheduled               <unknown>             default-scheduler  Successfully assigned default/nginx-untrusted to minikube
          Warning  FailedCreatePodSandBox  6m38s (x17 over 10m)  kubelet, minikube  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
          Warning  FailedCreatePodSandBox  4s (x10 over 2m29s)   kubelet, minikube  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
    helpers.go:305: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 logs nginx-untrusted -n default
    helpers.go:305: (dbg) Non-zero exit: kubectl --context gvisor-20191024T171027.666717625-13805 logs nginx-untrusted -n default: exit status 1 (553.237231ms)
         
        ** stderr ** 
        Error from server (BadRequest): container "nginx" in pod "nginx-untrusted" is waiting to start: ContainerCreating
         
        ** /stderr **
    helpers.go:307: kubectl --context gvisor-20191024T171027.666717625-13805 logs nginx-untrusted -n default: exit status 1
    gvisor_addon_test.go:103: nginx: run=nginx,untrusted=true within 2m0s: timed out waiting for the condition
    gvisor_addon_test.go:105: (dbg) waiting for pods with labels "run=nginx,runtime=gvisor" in namespace "default" ...
    helpers.go:244: "nginx-gvisor" [86aaab2d-bbd7-4b19-b842-e2add2c62776] Pending / Ready:ContainersNotReady (containers with unready status: [nginx]) / ContainersReady:ContainersNotReady (containers with unready status: [nginx])
    gvisor_addon_test.go:105: pod "run=nginx,runtime=gvisor" failed to start: timed out waiting for the condition
    helpers.go:289: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 get po -A --show-labels
    helpers.go:295: (dbg) kubectl --context gvisor-20191024T171027.666717625-13805 get po -A --show-labels:
        NAMESPACE              NAME                                         READY   STATUS              RESTARTS   AGE     LABELS
        default                nginx-gvisor                                 0/1     ContainerCreating   0          12m     run=nginx,runtime=gvisor
        default                nginx-untrusted                              0/1     ContainerCreating   0          12m     run=nginx,untrusted=true
        kube-system            coredns-5644d7b6d9-296sq                     1/1     Running             1          14m     k8s-app=kube-dns,pod-template-hash=5644d7b6d9
        kube-system            coredns-5644d7b6d9-blmlb                     1/1     Running             1          14m     k8s-app=kube-dns,pod-template-hash=5644d7b6d9
        kube-system            etcd-minikube                                1/1     Running             1          13m     component=etcd,tier=control-plane
        kube-system            gvisor                                       0/1     CrashLoopBackOff    10         12m     addonmanager.kubernetes.io/mode=Reconcile,kubernetes.io/minikube-addons=gvisor
        kube-system            kube-addon-manager-minikube                  1/1     Running             1          13m     component=kube-addon-manager,kubernetes.io/minikube-addons=addon-manager,version=v9.0.2
        kube-system            kube-apiserver-minikube                      1/1     Running             1          14m     component=kube-apiserver,tier=control-plane
        kube-system            kube-controller-manager-minikube             1/1     Running             0          4m33s   component=kube-controller-manager,tier=control-plane
        kube-system            kube-proxy-zj44q                             1/1     Running             1          14m     controller-revision-hash=5447bbc5f8,k8s-app=kube-proxy,pod-template-generation=1
        kube-system            kube-scheduler-minikube                      1/1     Running             1          13m     component=kube-scheduler,tier=control-plane
        kube-system            storage-provisioner                          1/1     Running             1          14m     addonmanager.kubernetes.io/mode=Reconcile,integration-test=storage-provisioner
        kubernetes-dashboard   dashboard-metrics-scraper-76585494d8-nc7wk   1/1     Running             0          4m8s    k8s-app=dashboard-metrics-scraper,pod-template-hash=76585494d8
        kubernetes-dashboard   kubernetes-dashboard-57f4cb4545-bqjcr        1/1     Running             0          4m8s    k8s-app=kubernetes-dashboard,pod-template-hash=57f4cb4545
    helpers.go:298: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 describe po nginx-gvisor -n default
    helpers.go:302: (dbg) kubectl --context gvisor-20191024T171027.666717625-13805 describe po nginx-gvisor -n default:
        Name:         nginx-gvisor
        Namespace:    default
        Priority:     0
        Node:         minikube/192.168.39.47
        Start Time:   Thu, 24 Oct 2019 17:15:08 +0000
        Labels:       run=nginx
                      runtime=gvisor
        Annotations:  <none>
        Status:       Pending
        IP:           
        IPs:          <none>
        Containers:
          nginx:
            Container ID:   
            Image:          nginx
            Image ID:       
            Port:           <none>
            Host Port:      <none>
            State:          Waiting
              Reason:       ContainerCreating
            Ready:          False
            Restart Count:  0
            Environment:    <none>
            Mounts:
              /var/run/secrets/kubernetes.io/serviceaccount from default-token-q2v2q (ro)
        Conditions:
          Type              Status
          Initialized       True 
          Ready             False 
          ContainersReady   False 
          PodScheduled      True 
        Volumes:
          default-token-q2v2q:
            Type:        Secret (a volume populated by a Secret)
            SecretName:  default-token-q2v2q
            Optional:    false
        QoS Class:       BestEffort
        Node-Selectors:  <none>
        Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                         node.kubernetes.io/unreachable:NoExecute for 300s
        Events:
          Type     Reason                  Age                   From               Message
          ----     ------                  ----                  ----               -------
          Normal   Scheduled               <unknown>             default-scheduler  Successfully assigned default/nginx-gvisor to minikube
          Warning  FailedCreatePodSandBox  8m38s (x17 over 12m)  kubelet, minikube  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
          Warning  FailedCreatePodSandBox  8s (x18 over 4m30s)   kubelet, minikube  Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
    helpers.go:305: (dbg) Run:  kubectl --context gvisor-20191024T171027.666717625-13805 logs nginx-gvisor -n default
    helpers.go:305: (dbg) Non-zero exit: kubectl --context gvisor-20191024T171027.666717625-13805 logs nginx-gvisor -n default: exit status 1 (196.278527ms)
         
        ** stderr ** 
        Error from server (BadRequest): container "nginx" in pod "nginx-gvisor" is waiting to start: ContainerCreating
         
        ** /stderr **
    helpers.go:307: kubectl --context gvisor-20191024T171027.666717625-13805 logs nginx-gvisor -n default: exit status 1
    gvisor_addon_test.go:106: nginx: run=nginx,runtime=gvisor within 2m0s: timed out waiting for the condition
    gvisor_addon_test.go:61: (dbg) Run:  out/minikube-linux-amd64 -p gvisor-20191024T171027.666717625-13805 addons disable gvisor
    gvisor_addon_test.go:38: TestGvisorAddon failed, collecting logs ...
    gvisor_addon_test.go:38: (dbg) Run:  out/minikube-linux-amd64 -p gvisor-20191024T171027.666717625-13805 logs -n 100
    gvisor_addon_test.go:38: (dbg) Done: out/minikube-linux-amd64 -p gvisor-20191024T171027.666717625-13805 logs -n 100: (1.288797841s)
    gvisor_addon_test.go:38: TestGvisorAddon logs: * ==> container status <==
        * CONTAINER           IMAGE               CREATED             STATE               NAME                        ATTEMPT             POD ID
        * d589c6324d246       fc1c144086460       39 seconds ago      Exited              gvisor                      10                  6b7c83ef287c2
        * 0ae8843e6569b       709901356c115       3 minutes ago       Running             dashboard-metrics-scraper   0                   0fbbf589dcb4f
        * 6f29aa17b1b37       6802d83967b99       4 minutes ago       Running             kubernetes-dashboard        0                   17bc36d201cd7
        * 66cdd2a08d034       bf261d1579144       4 minutes ago       Running             coredns                     1                   0644cdafc41fb
        * d1b57a27ce84c       bf261d1579144       4 minutes ago       Running             coredns                     1                   a77bb18ea3590
        * 26d455cf8c634       0d2430db3cd0a       4 minutes ago       Running             kube-proxy                  1                   67b3b5dd616ab
        * 948a4aaaf0b2d       4689081edb103       4 minutes ago       Running             storage-provisioner         1                   bddc65c3b547b
        * f363c55fe8b96       b2756210eeabf       5 minutes ago       Running             etcd                        1                   fed5304c20ba0
        * a2e2f17c22133       f15aad0426f5c       5 minutes ago       Running             kube-apiserver              1                   3ab2a97243b6e
        * 6219bd10f32ff       ba306669806e6       5 minutes ago       Running             kube-controller-manager     0                   20f41bcbd7231
        * 894336a5c9af0       e15192a921829       5 minutes ago       Running             kube-scheduler              1                   2316d9bc33581
        * 6967159c815d8       bd12a212f9dcb       5 minutes ago       Running             kube-addon-manager          1                   4204ca4955e20
        * 3fa0bbeaba8bc       4689081edb103       14 minutes ago      Exited              storage-provisioner         0                   f811466c7d6b6
        * 114b09b88692c       bf261d1579144       14 minutes ago      Exited              coredns                     0                   92dd1c32b9dd0
        * f1be047731736       bf261d1579144       14 minutes ago      Exited              coredns                     0                   f2936d187275c
        * 86d5549649f61       0d2430db3cd0a       14 minutes ago      Exited              kube-proxy                  0                   d18e3e9bf2b01
        * 9433fab6f9b0e       bd12a212f9dcb       15 minutes ago      Exited              kube-addon-manager          0                   80da0fd757374
        * 51c6e39162ad1       b2756210eeabf       15 minutes ago      Exited              etcd                        0                   85776d14ea332
        * 7a51037303e49       e15192a921829       15 minutes ago      Exited              kube-scheduler              0                   5dab0cb3d19e9
        * 8a929359f2334       f15aad0426f5c       15 minutes ago      Exited              kube-apiserver              0                   76eeac5d343b5
        * 
        * ==> containerd <==
        * -- Logs begin at Thu 2019-10-24 17:21:52 UTC, end at Thu 2019-10-24 17:27:48 UTC. --
        * Oct 24 17:24:03 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:03.724751384Z" level=info msg="shim containerd-shim started" address="/containerd-shim/k8s.io/6e9cefa51eee32bcb9afa9c3c689a96a00886f778a43bd71bd4b285977778daa/shim.sock" debug=false pid=4952
        * Oct 24 17:24:04 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:04.550529292Z" level=info msg="StartContainer for "6e9cefa51eee32bcb9afa9c3c689a96a00886f778a43bd71bd4b285977778daa" returns successfully"
        * Oct 24 17:24:07 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:07.325008006Z" level=info msg="Finish piping stderr of container "6e9cefa51eee32bcb9afa9c3c689a96a00886f778a43bd71bd4b285977778daa""
        * Oct 24 17:24:07 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:07.325708366Z" level=info msg="Finish piping stdout of container "6e9cefa51eee32bcb9afa9c3c689a96a00886f778a43bd71bd4b285977778daa""
        * Oct 24 17:24:07 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:07.388411815Z" level=info msg="TaskExit event &TaskExit{ContainerID:6e9cefa51eee32bcb9afa9c3c689a96a00886f778a43bd71bd4b285977778daa,ID:6e9cefa51eee32bcb9afa9c3c689a96a00886f778a43bd71bd4b285977778daa,Pid:4971,ExitStatus:1,ExitedAt:2019-10-24 17:24:07.385611833 +0000 UTC,}"
        * Oct 24 17:24:07 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:07.870372145Z" level=info msg="shim reaped" id=6e9cefa51eee32bcb9afa9c3c689a96a00886f778a43bd71bd4b285977778daa
        * Oct 24 17:24:08 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:08.810602030Z" level=info msg="RemoveContainer for "14a6cdfc32e0e28c554ebd73baf89bf7bb8725f33ec2dffea7b327f30359bb71""
        * Oct 24 17:24:09 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:09.047646540Z" level=info msg="RemoveContainer for "14a6cdfc32e0e28c554ebd73baf89bf7bb8725f33ec2dffea7b327f30359bb71" returns successfully"
        * Oct 24 17:24:13 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:13.252033522Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:24:15 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:15.268842510Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:24:15 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:15.770581763Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:24:17 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:17.496001272Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:24:27 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:27.447729369Z" level=info msg="StopPodSandbox for "ca842fc8b2d7ef63c49985b4067510de5c6dfba182cb832915addd2cce8dc158""
        * Oct 24 17:24:27 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:27.506756945Z" level=info msg="TearDown network for sandbox "ca842fc8b2d7ef63c49985b4067510de5c6dfba182cb832915addd2cce8dc158" successfully"
        * Oct 24 17:24:27 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:27.507027409Z" level=info msg="StopPodSandbox for "ca842fc8b2d7ef63c49985b4067510de5c6dfba182cb832915addd2cce8dc158" returns successfully"
        * Oct 24 17:24:27 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:27.508421402Z" level=info msg="RemovePodSandbox for "ca842fc8b2d7ef63c49985b4067510de5c6dfba182cb832915addd2cce8dc158""
        * Oct 24 17:24:27 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:27.640157301Z" level=info msg="RemovePodSandbox "ca842fc8b2d7ef63c49985b4067510de5c6dfba182cb832915addd2cce8dc158" returns successfully"
        * Oct 24 17:24:29 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:29.279890456Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:24:30 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:30.932485684Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:24:31 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:31.268406280Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:24:34 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:34.063371053Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:24:35 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:35.283555129Z" level=info msg="CreateContainer within sandbox "6b7c83ef287c2c52e798af785d10ecd0676128a50f19cb9a4876537b36ca6a28" for container &ContainerMetadata{Name:gvisor,Attempt:8,}"
        * Oct 24 17:24:35 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:35.729673560Z" level=info msg="CreateContainer within sandbox "6b7c83ef287c2c52e798af785d10ecd0676128a50f19cb9a4876537b36ca6a28" for &ContainerMetadata{Name:gvisor,Attempt:8,} returns container id "224dd31d380fd2e173b0afff0219f2a273a8e185989a4e89c2a26c1833dbabb7""
        * Oct 24 17:24:35 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:35.735001267Z" level=info msg="StartContainer for "224dd31d380fd2e173b0afff0219f2a273a8e185989a4e89c2a26c1833dbabb7""
        * Oct 24 17:24:35 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:35.738885687Z" level=info msg="shim containerd-shim started" address="/containerd-shim/k8s.io/224dd31d380fd2e173b0afff0219f2a273a8e185989a4e89c2a26c1833dbabb7/shim.sock" debug=false pid=5544
        * Oct 24 17:24:36 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:36.579773651Z" level=info msg="StartContainer for "224dd31d380fd2e173b0afff0219f2a273a8e185989a4e89c2a26c1833dbabb7" returns successfully"
        * Oct 24 17:24:42 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:42.868615616Z" level=info msg="Finish piping stdout of container "224dd31d380fd2e173b0afff0219f2a273a8e185989a4e89c2a26c1833dbabb7""
        * Oct 24 17:24:42 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:42.869653837Z" level=info msg="Finish piping stderr of container "224dd31d380fd2e173b0afff0219f2a273a8e185989a4e89c2a26c1833dbabb7""
        * Oct 24 17:24:43 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:43.012694238Z" level=info msg="TaskExit event &TaskExit{ContainerID:224dd31d380fd2e173b0afff0219f2a273a8e185989a4e89c2a26c1833dbabb7,ID:224dd31d380fd2e173b0afff0219f2a273a8e185989a4e89c2a26c1833dbabb7,Pid:5574,ExitStatus:1,ExitedAt:2019-10-24 17:24:43.009873438 +0000 UTC,}"
        * Oct 24 17:24:43 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:43.794706902Z" level=info msg="shim reaped" id=224dd31d380fd2e173b0afff0219f2a273a8e185989a4e89c2a26c1833dbabb7
        * Oct 24 17:24:44 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:44.256516247Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:24:44 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:44.594939356Z" level=info msg="RemoveContainer for "6e9cefa51eee32bcb9afa9c3c689a96a00886f778a43bd71bd4b285977778daa""
        * Oct 24 17:24:44 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:44.776897130Z" level=info msg="RemoveContainer for "6e9cefa51eee32bcb9afa9c3c689a96a00886f778a43bd71bd4b285977778daa" returns successfully"
        * Oct 24 17:24:46 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:46.608689484Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:24:48 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:48.266748883Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:24:50 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:24:50.313552411Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:25:02 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:02.312917222Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:25:03 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:03.108017196Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:25:06 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:06.271030274Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:25:06 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:06.788038859Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:25:20 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:20.254640257Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:25:21 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:21.447866646Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:25:23 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:23.358533185Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:25:24 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:24.192019286Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:25:27 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:27.399862881Z" level=info msg="CreateContainer within sandbox "6b7c83ef287c2c52e798af785d10ecd0676128a50f19cb9a4876537b36ca6a28" for container &ContainerMetadata{Name:gvisor,Attempt:9,}"
        * Oct 24 17:25:27 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:27.850968298Z" level=info msg="CreateContainer within sandbox "6b7c83ef287c2c52e798af785d10ecd0676128a50f19cb9a4876537b36ca6a28" for &ContainerMetadata{Name:gvisor,Attempt:9,} returns container id "6b9165ddb6ad96f62b84ec9cd84041367acc37cd6b4c9c4df7cad77c72ecb618""
        * Oct 24 17:25:27 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:27.863464402Z" level=info msg="StartContainer for "6b9165ddb6ad96f62b84ec9cd84041367acc37cd6b4c9c4df7cad77c72ecb618""
        * Oct 24 17:25:27 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:27.880932320Z" level=info msg="shim containerd-shim started" address="/containerd-shim/k8s.io/6b9165ddb6ad96f62b84ec9cd84041367acc37cd6b4c9c4df7cad77c72ecb618/shim.sock" debug=false pid=6335
        * Oct 24 17:25:28 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:28.777066802Z" level=info msg="StartContainer for "6b9165ddb6ad96f62b84ec9cd84041367acc37cd6b4c9c4df7cad77c72ecb618" returns successfully"
        * Oct 24 17:25:34 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:34.297766093Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:25:34 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:34.617905108Z" level=info msg="Finish piping stdout of container "6b9165ddb6ad96f62b84ec9cd84041367acc37cd6b4c9c4df7cad77c72ecb618""
        * Oct 24 17:25:34 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:34.647456264Z" level=info msg="Finish piping stderr of container "6b9165ddb6ad96f62b84ec9cd84041367acc37cd6b4c9c4df7cad77c72ecb618""
        * Oct 24 17:25:35 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:35.187177936Z" level=info msg="TaskExit event &TaskExit{ContainerID:6b9165ddb6ad96f62b84ec9cd84041367acc37cd6b4c9c4df7cad77c72ecb618,ID:6b9165ddb6ad96f62b84ec9cd84041367acc37cd6b4c9c4df7cad77c72ecb618,Pid:6353,ExitStatus:1,ExitedAt:2019-10-24 17:25:35.171167729 +0000 UTC,}"
        * Oct 24 17:25:35 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:35.926483014Z" level=info msg="shim reaped" id=6b9165ddb6ad96f62b84ec9cd84041367acc37cd6b4c9c4df7cad77c72ecb618
        * Oct 24 17:25:36 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:36.305037434Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:25:36 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:36.864978632Z" level=info msg="RemoveContainer for "224dd31d380fd2e173b0afff0219f2a273a8e185989a4e89c2a26c1833dbabb7""
        * Oct 24 17:25:36 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:36.984598645Z" level=info msg="RemoveContainer for "224dd31d380fd2e173b0afff0219f2a273a8e185989a4e89c2a26c1833dbabb7" returns successfully"
        * Oct 24 17:25:39 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:39.357536098Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:25:41 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:41.289893862Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:25:47 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:47.281589082Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:25:49 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:49.848747735Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:25:55 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:55.271141658Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:25:57 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:25:57.932467707Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:26:04 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:04.254594838Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:26:06 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:06.389554153Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:26:11 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:11.254944438Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:26:13 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:13.546524816Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:26:21 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:21.271428929Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:26:23 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:23.748783211Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:26:29 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:29.252226624Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:26:31 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:31.339540603Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:26:35 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:35.264845968Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:26:37 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:37.557944730Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:26:44 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:44.256039747Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:26:46 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:46.516541196Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:26:48 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:48.253391363Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:26:50 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:26:50.856195319Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:27:00 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:00.251696273Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:27:02 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:02.201597520Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:27:04 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:04.252131682Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:27:05 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:05.754529687Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:27:08 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:08.278945001Z" level=info msg="CreateContainer within sandbox "6b7c83ef287c2c52e798af785d10ecd0676128a50f19cb9a4876537b36ca6a28" for container &ContainerMetadata{Name:gvisor,Attempt:10,}"
        * Oct 24 17:27:08 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:08.793509223Z" level=info msg="CreateContainer within sandbox "6b7c83ef287c2c52e798af785d10ecd0676128a50f19cb9a4876537b36ca6a28" for &ContainerMetadata{Name:gvisor,Attempt:10,} returns container id "d589c6324d246a702e0e4d1c374ee36b3c50372164e0ab411594aa93cf64cae9""
        * Oct 24 17:27:08 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:08.798452665Z" level=info msg="StartContainer for "d589c6324d246a702e0e4d1c374ee36b3c50372164e0ab411594aa93cf64cae9""
        * Oct 24 17:27:08 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:08.827572561Z" level=info msg="shim containerd-shim started" address="/containerd-shim/k8s.io/d589c6324d246a702e0e4d1c374ee36b3c50372164e0ab411594aa93cf64cae9/shim.sock" debug=false pid=7951
        * Oct 24 17:27:09 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:09.483030485Z" level=info msg="StartContainer for "d589c6324d246a702e0e4d1c374ee36b3c50372164e0ab411594aa93cf64cae9" returns successfully"
        * Oct 24 17:27:13 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:13.851615048Z" level=info msg="Finish piping stderr of container "d589c6324d246a702e0e4d1c374ee36b3c50372164e0ab411594aa93cf64cae9""
        * Oct 24 17:27:13 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:13.853628656Z" level=info msg="Finish piping stdout of container "d589c6324d246a702e0e4d1c374ee36b3c50372164e0ab411594aa93cf64cae9""
        * Oct 24 17:27:13 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:13.894734383Z" level=info msg="TaskExit event &TaskExit{ContainerID:d589c6324d246a702e0e4d1c374ee36b3c50372164e0ab411594aa93cf64cae9,ID:d589c6324d246a702e0e4d1c374ee36b3c50372164e0ab411594aa93cf64cae9,Pid:7977,ExitStatus:1,ExitedAt:2019-10-24 17:27:13.891695685 +0000 UTC,}"
        * Oct 24 17:27:14 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:14.104611885Z" level=info msg="shim reaped" id=d589c6324d246a702e0e4d1c374ee36b3c50372164e0ab411594aa93cf64cae9
        * Oct 24 17:27:15 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:15.139914736Z" level=info msg="RemoveContainer for "6b9165ddb6ad96f62b84ec9cd84041367acc37cd6b4c9c4df7cad77c72ecb618""
        * Oct 24 17:27:15 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:15.261123531Z" level=info msg="RemoveContainer for "6b9165ddb6ad96f62b84ec9cd84041367acc37cd6b4c9c4df7cad77c72ecb618" returns successfully"
        * Oct 24 17:27:15 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:15.291740079Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:27:17 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:17.525664541Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:27:19 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:19.255712684Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:27:21 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:21.404486876Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * Oct 24 17:27:32 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:32.252483805Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,}"
        * Oct 24 17:27:33 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:33.608006246Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-untrusted,Uid:08391835-b41d-4564-9a46-6cc4f8294759,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "untrusted" is configured"
        * Oct 24 17:27:37 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:37.251242325Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,}"
        * Oct 24 17:27:39 gvisor-20191024T171027.666717625-13805 containerd[2031]: time="2019-10-24T17:27:39.161525412Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:nginx-gvisor,Uid:86aaab2d-bbd7-4b19-b842-e2add2c62776,Namespace:default,Attempt:0,} failed, error" error="failed to get sandbox runtime: no runtime for "runsc" is configured"
        * 
        * ==> coredns [66cdd2a08d03427240d26729806adcfb99c2e71de36c9fe70dbce2a7d2ee48d0] <==
        * E1024 17:23:27.793432       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793432       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793432       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/toolsE1024/cache/refl e1cto7r:.23go::94: F2ailed 7.793432t     o lis  t1 refle c*tvo1.Namesr.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *pvace: 1G.eNt httampess:p/a/c1e0.96.0.1:4:4 3G/apet httpsi:///10.96.0.v11:443//anpamespiac/evs1?limi/namest=50p0a&crees?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * sourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793814       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793814       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793814       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793814       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.795667       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.795667       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.795667       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.795667       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.797542       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.799718       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.797542       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.797542       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.797542       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.799718       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.799718       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.799718       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.805976       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.805976       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.805976       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.805976       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.798785       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.798785       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.798785       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.798785       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.802994       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.802994       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.802994       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.802994       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.807173       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.807173       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.807173       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.807173       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * 2019-10-24T17:23:29.913Z [INFO] plugin/ready: Still waiting on: "kubernetes"
        * E1024 17:23:30.802716       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.804961       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.810623       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10E.1024 17:23:30.89027166 . 0     1. 1r:e4f4l3e/capi/v1t/osre.rvicgeos?li:m126] pkgi/tm=o5d0/0k&8resosu.rceVersioino=/0c:l iednita-lgo@v 1tcp 101.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.802716       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.802716       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: conn.e9c6.0.1t: conn:443:e connectc: tion cronefunsectioen refusedd
        * 
        * E1024 17:23:30.804961       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.804961       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.804961       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.810623       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.810623       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.810623       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * .:53
        * 2019-10-24T17:23:32.081Z [INFO] plugin/reload: Running configuration MD5 = f64cb9b977c7dfca58c4fab108535a76
        * 2019-10-24T17:23:32.081Z [INFO] CoreDNS-1.6.2
        * 2019-10-24T17:23:32.081Z [INFO] linux/amd64, go1.12.8, 795a3eb
        * CoreDNS-1.6.2
        * linux/amd64, go1.12.8, 795a3eb
        * 
        * ==> coredns [d1b57a27ce84c5a970f878a96aac312cfce0795c96896ebe586c4b141b0a83c1] <==
        * E1024 17:23:27.792074       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.792074       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443E10/api/v1/24 17:23e:2n7.d792poi074       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * nts?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.792074       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793182       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793182       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793182       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793220       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793220       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793220       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793182       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:27.793220       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.801404       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.801404       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.801404       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.801404       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.803456       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.803456       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.803456       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.803456       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.805871       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.804737       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.808756       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10E.196.0.0241 :443: co17:2n3:28.nect:80587 conn1e      c 1 treflion refecustor.go:e1d
        * 26] pkg/mEod1024 17:23/:29.8k088s.8io2/clie2    nt   1 -go@v11.0.r0+iefncomplectatiobler/t.go:o126] opkg/mlod/sk8s.io/c/lcaichent-ge/o@v11.r0.0+ieflecnctorompatib.le/tools/cacheg/refo:94: Falielced totor.g lo:94:is Failt *ved to1.Na limesstpac *ve1.Name:space:  GetG httpet httsps:/://10./1096.0.1.:4943/api/v1/namespaces?limit=500&resourceVersion6=0.0.: 1dial: t443/apicp /10.9v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.805871       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:28.805871       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Fa6iled t.0.1o lis:4t4 *v1.3Nam: conespnaeccet:: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.804737       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.804737       1  rceonfnelectoctrion.go refuse:d
        * 126] pkg/mod/k8s.E1024 1i7:23o/:3c0l.80i64ent91   -g   o@v 11.1 r0eflec.0+intor.gcoo:m126] ppkatibgle/t/mools/od/kcach8s.io/cliee/reflnt-goec@tor.gov11:94: .0.Failed0+ tincompoati blelist *v1.E/ndpotintos: Getols/cac httphe/res:fle/ct/10or..go:9496.0:.1:443 F/ailedapi/v 1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.804737       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.808756       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.808756       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failedt to lo lisistt  *v1*v1.E.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection rndpoeints: Get httpfused
        * s://10.96.E1024 17:23:29.808756       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:40.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.811537       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.812547       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+4i3/apinco/v1/smpatiervicble/teools/cachs?le/refilmiector.tg=500&o:94:r esoFailedur to liceVerst *vsio1n.=Name0: dspaialc tcep 1:0. Get96 https://10.9.6.0.10.:1443/a:443:p icon/v1/nnecamespt:ac conesnec?litiomn ireft=5us0ed
        * 0&resourceVE1024ersi on=10: di7:23al tcp 1:0.96.209..1:443:8 conn0ect: conne882c2 tion       r1 efusreedf
        * lector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.808822       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:29.808822       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * 2019-10-24T17:23:30.602Z [INFO] plugin/ready: Still waiting on: "kubernetes"
        * E1024 17:23:30.806491       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.806491       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.806491       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.96.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.811537       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.811537       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.811537       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.96.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.812547       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.812547       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * E1024 17:23:30.812547       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.0+incompatible/tools/cache/reflector.go:94: Failed to list *v1.Namespace: Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: connection refused
        * .:53
        * 2019-10-24T17:23:32.074Z [INFO] plugin/reload: Running configuration MD5 = f64cb9b977c7dfca58c4fab108535a76
        * 2019-10-24T17:23:32.075Z [INFO] CoreDNS-1.6.2
        * 2019-10-24T17:23:32.075Z [INFO] linux/amd64, go1.12.8, 795a3eb
        * CoreDNS-1.6.2
        * linux/amd64, go1.12.8, 795a3eb
        * 
        * ==> dmesg <==
        * [Oct24 17:20] You have booted with nomodeset. This means your GPU drivers are DISABLED
        * [  +0.000001] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
        * [  +0.000000] Unless you actually understand what nomodeset does, you should reboot without enabling it
        * [  +0.170605] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
        * [Oct24 17:21] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
        * [  +0.000156] Unstable clock detected, switching default tracing clock to "global"
        *               If you want to keep using the local clock, then add:
        *                 "trace_clock=local"
        *               on the kernel command line
        * [ +12.236359] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
        * [  +0.137146] systemd-fstab-generator[1134]: Ignoring "noauto" for root device
        * [  +0.025579] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
        * [  +0.000005] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
        * [Oct24 17:22] vboxguest: loading out-of-tree module taints kernel.
        * [  +0.053065] vboxguest: PCI device not found, probably running on physical hardware.
        * [  +2.107715] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
        * [  +2.413066] systemd-fstab-generator[1943]: Ignoring "noauto" for root device
        * [ +14.409120] systemd-fstab-generator[2105]: Ignoring "noauto" for root device
        * [ +23.790365] hrtimer: interrupt took 21410587 ns
        * [Oct24 17:23] kauditd_printk_skb: 20 callbacks suppressed
        * [ +15.120865] kauditd_printk_skb: 89 callbacks suppressed
        * [  +8.745326] kauditd_printk_skb: 83 callbacks suppressed
        * [  +6.231981] kauditd_printk_skb: 44 callbacks suppressed
        * [  +5.473039] kauditd_printk_skb: 44 callbacks suppressed
        * [Oct24 17:24] kauditd_printk_skb: 26 callbacks suppressed
        * [  +5.182093] NFSD: Unable to end grace period: -110
        * [  +6.977854] kauditd_printk_skb: 14 callbacks suppressed
        * [ +12.013593] kauditd_printk_skb: 44 callbacks suppressed
        * [  +5.269761] kauditd_printk_skb: 2 callbacks suppressed
        * [ +13.708451] kauditd_printk_skb: 41 callbacks suppressed
        * [  +5.774666] kauditd_printk_skb: 20 callbacks suppressed
        * [  +5.994078] kauditd_printk_skb: 14 callbacks suppressed
        * [Oct24 17:25] kauditd_printk_skb: 44 callbacks suppressed
        * [  +6.032116] kauditd_printk_skb: 44 callbacks suppressed
        * [ +14.619968] kauditd_printk_skb: 20 callbacks suppressed
        * [  +6.576477] kauditd_printk_skb: 14 callbacks suppressed
        * [  +7.809380] kauditd_printk_skb: 17 callbacks suppressed
        * [Oct24 17:26] kauditd_printk_skb: 23 callbacks suppressed
        * [  +6.925612] kauditd_printk_skb: 17 callbacks suppressed
        * [ +10.068804] kauditd_printk_skb: 17 callbacks suppressed
        * [  +5.358654] kauditd_printk_skb: 17 callbacks suppressed
        * [  +8.674250] kauditd_printk_skb: 26 callbacks suppressed
        * [  +8.943775] kauditd_printk_skb: 17 callbacks suppressed
        * [  +5.950897] kauditd_printk_skb: 20 callbacks suppressed
        * [  +7.210771] kauditd_printk_skb: 14 callbacks suppressed
        * [Oct24 17:27] kauditd_printk_skb: 23 callbacks suppressed
        * [ +11.053219] kauditd_printk_skb: 17 callbacks suppressed
        * [  +5.779949] kauditd_printk_skb: 20 callbacks suppressed
        * [  +5.658682] kauditd_printk_skb: 14 callbacks suppressed
        * [ +12.191313] kauditd_printk_skb: 20 callbacks suppressed
        * 
        * ==> kernel <==
        *  17:27:48 up 6 min,  0 users,  load average: 3.70, 4.04, 1.96
        * Linux gvisor-20191024T171027.666717625-13805 4.19.76 #1 SMP Mon Oct 21 11:09:09 PDT 2019 x86_64 GNU/Linux
        * PRETTY_NAME="Buildroot 2019.02.6"
        * 
        * ==> kube-addon-manager [6967159c815d818dfc4405d2b793e1517a7d45d4e9e2341af790470d30f08c7a] <==
        * error: no objects passed to apply
        * error: no objects passed to apply
        * error: no objects passed to apply
        * error: no objects passed to apply
        * role.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * serviceaccount/kubernetes-dashboard unchanged
        * secret/kubernetes-dashboard-certs unchanged
        * secret/kubernetes-dashboard-csrf unchanged
        * secret/kubernetes-dashboard-key-holder unchanged
        * service/kubernetes-dashboard unchanged
        * service/dashboard-metrics-scraper unchanged
        * runtimeclass.node.k8s.io/gvisor unchanged
        * serviceaccount/storage-provisioner unchanged
        * INFO: == Kubernetes addon reconcile completed at 2019-10-24T17:27:26+00:00 ==
        * INFO: Leader election disabled.
        * INFO: == Kubernetes addon ensure completed at 2019-10-24T17:27:27+00:00 ==
        * INFO: == Reconciling with deprecated label ==
        * INFO: == Reconciling with addon-manager label ==
        * clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * clusterrolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * configmap/kubernetes-dashboard-settings unchanged
        * deployment.apps/dashboard-metrics-scraper unchanged
        * deployment.apps/kubernetes-dashboard unchanged
        * namespace/kubernetes-dashboard unchanged
        * role.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * serviceaccount/kubernetes-dashboard unchanged
        * secret/kubernetes-dashboard-certs unchanged
        * secret/kubernetes-dashboard-csrf unchanged
        * secret/kubernetes-dashboard-key-holder unchanged
        * service/kubernetes-dashboard unchanged
        * service/dashboard-metrics-scraper unchanged
        * runtimeclass.node.k8s.io/gvisor unchanged
        * serviceaccount/storage-provisioner unchanged
        * INFO: == Kubernetes addon reconcile completed at 2019-10-24T17:27:32+00:00 ==
        * INFO: Leader election disabled.
        * INFO: == Kubernetes addon ensure completed at 2019-10-24T17:27:33+00:00 ==
        * INFO: == Reconciling with deprecated label ==
        * INFO: == Reconciling with addon-manager label ==
        * clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * clusterrolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * configmap/kubernetes-dashboard-settings unchanged
        * deployment.apps/dashboard-metrics-scraper unchanged
        * deployment.apps/kubernetes-dashboard unchanged
        * namespace/kubernetes-dashboard unchanged
        * role.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * serviceaccount/kubernetes-dashboard unchanged
        * secret/kubernetes-dashboard-certs unchanged
        * secret/kubernetes-dashboard-csrf unchanged
        * secret/kubernetes-dashboard-key-holder unchanged
        * service/kubernetes-dashboard unchanged
        * service/dashboard-metrics-scraper unchanged
        * runtimeclass.node.k8s.io/gvisor unchanged
        * serviceaccount/storage-provisioner unchanged
        * INFO: == Kubernetes addon reconcile completed at 2019-10-24T17:27:38+00:00 ==
        * INFO: Leader election disabled.
        * INFO: == Kubernetes addon ensure completed at 2019-10-24T17:27:38+00:00 ==
        * INFO: == Reconciling with deprecated label ==
        * INFO: == Reconciling with addon-manager label ==
        * clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * clusterrolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * configmap/kubernetes-dashboard-settings unchanged
        * deployment.apps/dashboard-metrics-scraper unchanged
        * deployment.apps/kubernetes-dashboard unchanged
        * namespace/kubernetes-dashboard unchanged
        * role.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * serviceaccount/kubernetes-dashboard unchanged
        * secret/kubernetes-dashboard-certs unchanged
        * secret/kubernetes-dashboard-csrf unchanged
        * secret/kubernetes-dashboard-key-holder unchanged
        * service/kubernetes-dashboard unchanged
        * service/dashboard-metrics-scraper unchanged
        * runtimeclass.node.k8s.io/gvisor unchanged
        * serviceaccount/storage-provisioner unchanged
        * INFO: == Kubernetes addon reconcile completed at 2019-10-24T17:27:43+00:00 ==
        * INFO: Leader election disabled.
        * INFO: == Kubernetes addon ensure completed at 2019-10-24T17:27:43+00:00 ==
        * INFO: == Reconciling with deprecated label ==
        * INFO: == Reconciling with addon-manager label ==
        * clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * clusterrolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * configmap/kubernetes-dashboard-settings unchanged
        * deployment.apps/dashboard-metrics-scraper unchanged
        * deployment.apps/kubernetes-dashboard unchanged
        * namespace/kubernetes-dashboard unchanged
        * role.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
        * serviceaccount/kubernetes-dashboard unchanged
        * secret/kubernetes-dashboard-certs unchanged
        * secret/kubernetes-dashboard-csrf unchanged
        * secret/kubernetes-dashboard-key-holder unchanged
        * service/kubernetes-dashboard unchanged
        * service/dashboard-metrics-scraper unchanged
        * runtimeclass.node.k8s.io/gvisor unchanged
        * serviceaccount/storage-provisioner unchanged
        * INFO: == Kubernetes addon reconcile completed at 2019-10-24T17:27:48+00:00 ==
        * INFO: Leader election disabled.
        * 
        * ==> kube-apiserver [a2e2f17c221339ef16bc57162a0c812bb149bd27dafd3d2730a33235665a81b9] <==
        * I1024 17:23:24.376177       1 trace.go:116] Trace[1748408014]: "Create" url:/api/v1/namespaces/kube-system/events (started: 2019-10-24 17:23:23.814245989 +0000 UTC m=+40.843840758) (total time: 561.73922ms):
        * Trace[1748408014]: [561.674764ms] [559.320992ms] Object stored in database
        * I1024 17:23:24.411555       1 trace.go:116] Trace[1857835224]: "GuaranteedUpdate etcd3" type:*core.Pod (started: 2019-10-24 17:23:23.905895011 +0000 UTC m=+40.935489299) (total time: 505.611355ms):
        * Trace[1857835224]: [505.611355ms] [505.128024ms] END
        * I1024 17:23:24.413063       1 trace.go:116] Trace[2143386211]: "Patch" url:/api/v1/namespaces/kube-system/pods/gvisor (started: 2019-10-24 17:23:23.905500993 +0000 UTC m=+40.935094914) (total time: 507.532931ms):
        * Trace[2143386211]: [506.213973ms] [503.716042ms] Object stored in database
        * I1024 17:23:27.039007       1 trace.go:116] Trace[517117982]: "Get" url:/api/v1/namespaces/kube-system/endpoints/kube-scheduler (started: 2019-10-24 17:23:24.948854816 +0000 UTC m=+41.978448551) (total time: 2.090030923s):
        * Trace[517117982]: [2.089954342s] [2.08977882s] About to write a response
        * I1024 17:23:27.162410       1 trace.go:116] Trace[1001292021]: "Create" url:/api/v1/namespaces/kube-system/events (started: 2019-10-24 17:23:25.010975333 +0000 UTC m=+42.040568856) (total time: 2.151364096s):
        * Trace[1001292021]: [2.15118877s] [2.150732236s] Object stored in database
        * I1024 17:23:27.164212       1 trace.go:116] Trace[1542991101]: "Get" url:/api/v1/namespaces/default (started: 2019-10-24 17:23:25.927364601 +0000 UTC m=+42.956958094) (total time: 1.236754982s):
        * Trace[1542991101]: [1.236612137s] [1.236572994s] About to write a response
        * I1024 17:23:27.167747       1 trace.go:116] Trace[1275499533]: "Get" url:/api/v1/namespaces/kube-system/endpoints/kube-controller-manager (started: 2019-10-24 17:23:26.623338279 +0000 UTC m=+43.652931767) (total time: 544.380206ms):
        * Trace[1275499533]: [544.32428ms] [544.2436ms] About to write a response
        * I1024 17:23:27.177157       1 trace.go:116] Trace[1968191759]: "GuaranteedUpdate etcd3" type:*coordination.Lease (started: 2019-10-24 17:23:26.31621146 +0000 UTC m=+43.345805841) (total time: 860.91099ms):
        * Trace[1968191759]: [860.774644ms] [859.89033ms] Transaction committed
        * I1024 17:23:27.177409       1 trace.go:116] Trace[1527099487]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/minikube (started: 2019-10-24 17:23:26.315733383 +0000 UTC m=+43.345327367) (total time: 861.640698ms):
        * Trace[1527099487]: [861.45272ms] [861.102624ms] Object stored in database
        * I1024 17:23:31.500616       1 controller.go:606] quota admission added evaluator for: endpoints
        * I1024 17:23:33.431070       1 trace.go:116] Trace[1322170132]: "GuaranteedUpdate etcd3" type:*core.ServiceAccount (started: 2019-10-24 17:23:32.824686753 +0000 UTC m=+49.854281920) (total time: 606.212198ms):
        * Trace[1322170132]: [606.162227ms] [604.35569ms] Transaction committed
        * I1024 17:23:33.431448       1 trace.go:116] Trace[2095801634]: "Update" url:/api/v1/namespaces/kubernetes-dashboard/serviceaccounts/kubernetes-dashboard (started: 2019-10-24 17:23:32.824165944 +0000 UTC m=+49.853760043) (total time: 607.183424ms):
        * Trace[2095801634]: [606.972ms] [606.672946ms] Object stored in database
        * I1024 17:23:33.431920       1 trace.go:116] Trace[46292493]: "List etcd3" key:/services/specs/kube-system,resourceVersion:,limit:0,continue: (started: 2019-10-24 17:23:32.753153051 +0000 UTC m=+49.782746859) (total time: 678.745187ms):
        * Trace[46292493]: [678.745187ms] [678.745187ms] END
        * I1024 17:23:33.432026       1 trace.go:116] Trace[1130976023]: "List" url:/api/v1/namespaces/kube-system/services (started: 2019-10-24 17:23:32.752646678 +0000 UTC m=+49.782240320) (total time: 679.365066ms):
        * Trace[1130976023]: [679.285783ms] [678.891121ms] Listing from storage done
        * I1024 17:23:33.436177       1 trace.go:116] Trace[890466768]: "Get" url:/api/v1/namespaces/kube-system/serviceaccounts/certificate-controller (started: 2019-10-24 17:23:32.7979311 +0000 UTC m=+49.827524795) (total time: 638.226638ms):
        * Trace[890466768]: [638.196421ms] [637.978042ms] About to write a response
        * I1024 17:23:33.470979       1 trace.go:116] Trace[1371477572]: "GuaranteedUpdate etcd3" type:*core.Event (started: 2019-10-24 17:23:32.926072635 +0000 UTC m=+49.955666744) (total time: 544.863547ms):
        * Trace[1371477572]: [510.741764ms] [510.741764ms] initial value restored
        * I1024 17:23:33.471246       1 trace.go:116] Trace[1289641802]: "Patch" url:/api/v1/namespaces/default/events/nginx-gvisor.15d0a519455aa305 (started: 2019-10-24 17:23:32.924171235 +0000 UTC m=+49.953765119) (total time: 547.049511ms):
        * Trace[1289641802]: [512.65602ms] [510.902919ms] About to apply patch
        * I1024 17:23:36.646782       1 trace.go:116] Trace[1046736013]: "GuaranteedUpdate etcd3" type:*v1.Endpoints (started: 2019-10-24 17:23:36.106214564 +0000 UTC m=+53.135808789) (total time: 540.438409ms):
        * Trace[1046736013]: [524.959709ms] [504.526228ms] Transaction prepared
        * I1024 17:23:37.482738       1 controller.go:606] quota admission added evaluator for: replicasets.apps
        * I1024 17:23:38.186059       1 trace.go:116] Trace[727614143]: "Create" url:/api/v1/namespaces/kubernetes-dashboard/pods (started: 2019-10-24 17:23:37.66008202 +0000 UTC m=+54.689676230) (total time: 525.789608ms):
        * Trace[727614143]: [450.962754ms] [450.532143ms] About to store object in database
        * I1024 17:23:38.273030       1 trace.go:116] Trace[1542907634]: "List etcd3" key:/limitranges/kubernetes-dashboard,resourceVersion:,limit:0,continue: (started: 2019-10-24 17:23:37.708614608 +0000 UTC m=+54.738208318) (total time: 564.359878ms):
        * Trace[1542907634]: [564.359878ms] [564.359878ms] END
        * I1024 17:23:38.274490       1 trace.go:116] Trace[30577034]: "List" url:/api/v1/namespaces/kubernetes-dashboard/limitranges (started: 2019-10-24 17:23:37.708536606 +0000 UTC m=+54.738130361) (total time: 565.91782ms):
        * Trace[30577034]: [565.713318ms] [565.648491ms] Listing from storage done
        * I1024 17:23:38.365058       1 trace.go:116] Trace[445406093]: "Get" url:/apis/apps/v1/namespaces/kube-system/deployments/coredns (started: 2019-10-24 17:23:37.851709425 +0000 UTC m=+54.881303121) (total time: 512.814732ms):
        * Trace[445406093]: [509.529199ms] [509.378083ms] About to write a response
        * I1024 17:23:38.520114       1 controller.go:606] quota admission added evaluator for: events.events.k8s.io
        * I1024 17:23:38.615462       1 trace.go:116] Trace[644224801]: "Create" url:/api/v1/namespaces/kubernetes-dashboard/pods (started: 2019-10-24 17:23:37.704756519 +0000 UTC m=+54.734350673) (total time: 910.629229ms):
        * Trace[644224801]: [571.486644ms] [571.317039ms] About to store object in database
        * Trace[644224801]: [910.324542ms] [338.837898ms] Object stored in database
        * I1024 17:23:46.726673       1 trace.go:116] Trace[796803976]: "List etcd3" key:/pods/default,resourceVersion:,limit:0,continue: (started: 2019-10-24 17:23:46.140811657 +0000 UTC m=+63.170405786) (total time: 585.392649ms):
        * Trace[796803976]: [585.392649ms] [585.392649ms] END
        * I1024 17:23:46.728705       1 trace.go:116] Trace[1370868117]: "List" url:/api/v1/namespaces/default/pods (started: 2019-10-24 17:23:46.139011857 +0000 UTC m=+63.168605551) (total time: 589.647147ms):
        * Trace[1370868117]: [587.711132ms] [586.746692ms] Listing from storage done
        * I1024 17:23:46.753576       1 trace.go:116] Trace[1493004207]: "Get" url:/api/v1/namespaces/default/endpoints/kubernetes (started: 2019-10-24 17:23:46.176561397 +0000 UTC m=+63.206154877) (total time: 576.966047ms):
        * Trace[1493004207]: [576.599526ms] [576.431801ms] About to write a response
        * I1024 17:23:52.038928       1 trace.go:116] Trace[780699436]: "Get" url:/api/v1/namespaces/kube-system/endpoints/kube-scheduler (started: 2019-10-24 17:23:51.067097573 +0000 UTC m=+68.096691241) (total time: 971.111854ms):
        * Trace[780699436]: [970.957759ms] [970.846801ms] About to write a response
        * I1024 17:23:52.043977       1 trace.go:116] Trace[1688256467]: "List etcd3" key:/daemonsets/kube-system,resourceVersion:,limit:0,continue: (started: 2019-10-24 17:23:51.034548826 +0000 UTC m=+68.064142543) (total time: 1.00937997s):
        * Trace[1688256467]: [1.00937997s] [1.00937997s] END
        * I1024 17:23:52.044467       1 trace.go:116] Trace[1929523829]: "List" url:/apis/apps/v1/namespaces/kube-system/daemonsets (started: 2019-10-24 17:23:51.034212169 +0000 UTC m=+68.063805847) (total time: 1.010218429s):
        * Trace[1929523829]: [1.009784654s] [1.009461975s] Listing from storage done
        * I1024 17:23:52.051741       1 trace.go:116] Trace[688577554]: "List etcd3" key:/pods/default,resourceVersion:,limit:0,continue: (started: 2019-10-24 17:23:51.1382305 +0000 UTC m=+68.167824100) (total time: 913.47527ms):
        * Trace[688577554]: [913.47527ms] [913.47527ms] END
        * I1024 17:23:52.060120       1 trace.go:116] Trace[314802083]: "List" url:/api/v1/namespaces/default/pods (started: 2019-10-24 17:23:51.137995408 +0000 UTC m=+68.167588889) (total time: 922.092216ms):
        * Trace[314802083]: [915.001887ms] [914.84728ms] Listing from storage done
        * I1024 17:24:37.710496       1 trace.go:116] Trace[1291721369]: "List etcd3" key:/pods/default,resourceVersion:,limit:0,continue: (started: 2019-10-24 17:24:37.137706701 +0000 UTC m=+114.167300379) (total time: 572.155233ms):
        * Trace[1291721369]: [572.155233ms] [572.155233ms] END
        * I1024 17:24:37.717087       1 trace.go:116] Trace[467566002]: "List" url:/api/v1/namespaces/default/pods (started: 2019-10-24 17:24:37.137477014 +0000 UTC m=+114.167070501) (total time: 579.486419ms):
        * Trace[467566002]: [573.507481ms] [573.333857ms] Listing from storage done
        * I1024 17:24:37.724445       1 trace.go:116] Trace[215961780]: "List etcd3" key:/jobs,resourceVersion:,limit:500,continue: (started: 2019-10-24 17:24:37.11190035 +0000 UTC m=+114.141494070) (total time: 612.314102ms):
        * Trace[215961780]: [612.314102ms] [612.314102ms] END
        * I1024 17:24:37.725637       1 trace.go:116] Trace[951265823]: "List" url:/apis/batch/v1/jobs (started: 2019-10-24 17:24:37.111627433 +0000 UTC m=+114.141221027) (total time: 613.971536ms):
        * Trace[951265823]: [613.441712ms] [613.18871ms] Listing from storage done
        * I1024 17:24:37.752227       1 trace.go:116] Trace[2018880177]: "GuaranteedUpdate etcd3" type:*core.Endpoints (started: 2019-10-24 17:24:37.108501313 +0000 UTC m=+114.138095857) (total time: 643.562715ms):
        * Trace[2018880177]: [643.526182ms] [642.779587ms] Transaction committed
        * I1024 17:24:37.753543       1 trace.go:116] Trace[1476421760]: "Update" url:/api/v1/namespaces/kube-system/endpoints/kube-controller-manager (started: 2019-10-24 17:24:37.107880672 +0000 UTC m=+114.137474737) (total time: 645.589046ms):
        * Trace[1476421760]: [645.290365ms] [645.108176ms] Object stored in database
        * I1024 17:24:38.254460       1 trace.go:116] Trace[797046426]: "Create" url:/apis/storage.k8s.io/v1/storageclasses (started: 2019-10-24 17:24:37.186465774 +0000 UTC m=+114.216060136) (total time: 1.067661574s):
        * Trace[797046426]: [1.067661574s] [1.066883445s] END
        * I1024 17:24:43.088960       1 trace.go:116] Trace[918099140]: "Get" url:/api/v1/namespaces/kube-system/endpoints/kube-scheduler (started: 2019-10-24 17:24:42.528910834 +0000 UTC m=+119.558504505) (total time: 559.823303ms):
        * Trace[918099140]: [559.61464ms] [559.473384ms] About to write a response
        * I1024 17:24:43.093128       1 trace.go:116] Trace[411417179]: "List etcd3" key:/ingress/kubernetes-dashboard,resourceVersion:,limit:0,continue: (started: 2019-10-24 17:24:42.304881319 +0000 UTC m=+119.334474961) (total time: 788.170141ms):
        * Trace[411417179]: [788.170141ms] [788.170141ms] END
        * I1024 17:24:43.093609       1 trace.go:116] Trace[874386423]: "List" url:/apis/extensions/v1beta1/namespaces/kubernetes-dashboard/ingresses (started: 2019-10-24 17:24:42.304644776 +0000 UTC m=+119.334238483) (total time: 788.934988ms):
        * Trace[874386423]: [788.523466ms] [788.299134ms] Listing from storage done
        * I1024 17:25:03.426016       1 trace.go:116] Trace[2138322400]: "List etcd3" key:/pods/default,resourceVersion:,limit:0,continue: (started: 2019-10-24 17:25:00.801194534 +0000 UTC m=+137.830788188) (total time: 2.62371896s):
        * Trace[2138322400]: [2.62371896s] [2.62371896s] END
        * I1024 17:25:03.460413       1 trace.go:116] Trace[668487619]: "List" url:/api/v1/namespaces/default/pods (started: 2019-10-24 17:25:00.796719518 +0000 UTC m=+137.826313670) (total time: 2.663021474s):
        * Trace[668487619]: [2.629461807s] [2.625001735s] Listing from storage done
        * I1024 17:25:03.670479       1 trace.go:116] Trace[678491751]: "Get" url:/api/v1/namespaces/kube-system/endpoints/kube-controller-manager (started: 2019-10-24 17:25:02.211473698 +0000 UTC m=+139.241067908) (total time: 1.458931171s):
        * Trace[678491751]: [1.458405547s] [1.45238305s] About to write a response
        * I1024 17:25:03.671519       1 trace.go:116] Trace[2920242]: "Get" url:/api/v1/namespaces/kube-system/endpoints/kube-scheduler (started: 2019-10-24 17:25:02.211489218 +0000 UTC m=+139.241083571) (total time: 1.45998263s):
        * Trace[2920242]: [1.459901334s] [1.446441962s] About to write a response
        * I1024 17:25:06.993798       1 trace.go:116] Trace[841262235]: "Get" url:/api/v1/namespaces/default/endpoints/kubernetes (started: 2019-10-24 17:25:06.30466148 +0000 UTC m=+143.334255075) (total time: 689.014956ms):
        * Trace[841262235]: [688.903683ms] [688.838882ms] About to write a response
        * I1024 17:27:36.944448       1 trace.go:116] Trace[1760562445]: "List" url:/api/v1/namespaces/default/pods (started: 2019-10-24 17:27:36.200981634 +0000 UTC m=+293.230575123) (total time: 743.045404ms):
        * Trace[1760562445]: [743.040549ms] [737.842706ms] Writing http response done count:1
        * I1024 17:27:37.200669       1 trace.go:116] Trace[874191694]: "List etcd3" key:/cronjobs/kubernetes-dashboard,resourceVersion:,limit:0,continue: (started: 2019-10-24 17:27:36.625619075 +0000 UTC m=+293.655212606) (total time: 574.906551ms):
        * Trace[874191694]: [574.906551ms] [574.906551ms] END
        * I1024 17:27:37.201084       1 trace.go:116] Trace[835771838]: "List" url:/apis/batch/v1beta1/namespaces/kubernetes-dashboard/cronjobs (started: 2019-10-24 17:27:36.62545632 +0000 UTC m=+293.655049808) (total time: 575.575481ms):
        * Trace[835771838]: [575.351066ms] [575.199647ms] Listing from storage done
        * 
        * ==> kube-controller-manager [6219bd10f32ff45c1986691dc8019fedf5933a831c77330e30ceec949f7b96cc] <==
        * I1024 17:23:34.861840       1 controllermanager.go:534] Started "daemonset"
        * I1024 17:23:34.867733       1 daemon_controller.go:267] Starting daemon sets controller
        * I1024 17:23:34.867799       1 shared_informer.go:197] Waiting for caches to sync for daemon sets
        * I1024 17:23:35.001702       1 controllermanager.go:534] Started "disruption"
        * I1024 17:23:35.002872       1 disruption.go:333] Starting disruption controller
        * I1024 17:23:35.054971       1 shared_informer.go:197] Waiting for caches to sync for disruption
        * I1024 17:23:35.162797       1 replica_set.go:182] Starting replicaset controller
        * I1024 17:23:35.162851       1 shared_informer.go:197] Waiting for caches to sync for ReplicaSet
        * I1024 17:23:35.162919       1 controllermanager.go:534] Started "replicaset"
        * I1024 17:23:35.200905       1 node_lifecycle_controller.go:77] Sending events to api server
        * E1024 17:23:35.201036       1 core.go:201] failed to start cloud node lifecycle controller: no cloud provider provided
        * W1024 17:23:35.201066       1 controllermanager.go:526] Skipping "cloud-node-lifecycle"
        * I1024 17:23:35.343690       1 controllermanager.go:534] Started "namespace"
        * I1024 17:23:35.350588       1 namespace_controller.go:186] Starting namespace controller
        * I1024 17:23:35.350723       1 shared_informer.go:197] Waiting for caches to sync for namespace
        * I1024 17:23:35.443840       1 controllermanager.go:534] Started "statefulset"
        * W1024 17:23:35.443948       1 controllermanager.go:526] Skipping "nodeipam"
        * I1024 17:23:35.444218       1 stateful_set.go:145] Starting stateful set controller
        * I1024 17:23:35.445691       1 shared_informer.go:197] Waiting for caches to sync for stateful set
        * I1024 17:23:35.522170       1 controllermanager.go:534] Started "pv-protection"
        * I1024 17:23:35.524846       1 pv_protection_controller.go:81] Starting PV protection controller
        * I1024 17:23:35.524886       1 shared_informer.go:197] Waiting for caches to sync for PV protection
        * I1024 17:23:35.640890       1 controllermanager.go:534] Started "replicationcontroller"
        * I1024 17:23:35.641090       1 replica_set.go:182] Starting replicationcontroller controller
        * I1024 17:23:35.641108       1 shared_informer.go:197] Waiting for caches to sync for ReplicationController
        * I1024 17:23:35.841393       1 horizontal.go:156] Starting HPA controller
        * I1024 17:23:35.841663       1 shared_informer.go:197] Waiting for caches to sync for HPA
        * I1024 17:23:35.841753       1 controllermanager.go:534] Started "horizontalpodautoscaling"
        * I1024 17:23:36.049428       1 controllermanager.go:534] Started "ttl"
        * I1024 17:23:36.049829       1 ttl_controller.go:116] Starting TTL controller
        * I1024 17:23:36.050443       1 shared_informer.go:197] Waiting for caches to sync for TTL
        * I1024 17:23:36.092228       1 controllermanager.go:534] Started "bootstrapsigner"
        * I1024 17:23:36.095919       1 shared_informer.go:197] Waiting for caches to sync for bootstrap_signer
        * I1024 17:23:36.449004       1 controllermanager.go:534] Started "attachdetach"
        * I1024 17:23:36.449702       1 attach_detach_controller.go:334] Starting attach detach controller
        * I1024 17:23:36.450849       1 shared_informer.go:197] Waiting for caches to sync for attach detach
        * W1024 17:23:36.451648       1 controllermanager.go:526] Skipping "ttl-after-finished"
        * I1024 17:23:36.603148       1 cronjob_controller.go:96] Starting CronJob Manager
        * I1024 17:23:36.608886       1 controllermanager.go:534] Started "cronjob"
        * I1024 17:23:36.726539       1 controllermanager.go:534] Started "csrsigning"
        * I1024 17:23:36.727628       1 certificate_controller.go:113] Starting certificate controller
        * I1024 17:23:36.727859       1 shared_informer.go:197] Waiting for caches to sync for certificate
        * I1024 17:23:36.790925       1 node_lifecycle_controller.go:294] Sending events to api server.
        * I1024 17:23:36.792681       1 node_lifecycle_controller.go:327] Controller is using taint based evictions.
        * I1024 17:23:36.793379       1 taint_manager.go:162] Sending events to api server.
        * I1024 17:23:36.793722       1 node_lifecycle_controller.go:421] Controller will reconcile labels.
        * I1024 17:23:36.793884       1 node_lifecycle_controller.go:434] Controller will taint node by condition.
        * I1024 17:23:36.793933       1 controllermanager.go:534] Started "nodelifecycle"
        * I1024 17:23:36.794130       1 core.go:211] Will not configure cloud provider routes for allocate-node-cidrs: false, configure-cloud-routes: true.
        * W1024 17:23:36.795497       1 controllermanager.go:526] Skipping "route"
        * I1024 17:23:36.795746       1 node_lifecycle_controller.go:458] Starting node controller
        * I1024 17:23:36.796019       1 shared_informer.go:197] Waiting for caches to sync for taint
        * I1024 17:23:36.831428       1 controllermanager.go:534] Started "clusterrole-aggregation"
        * I1024 17:23:36.831894       1 clusterroleaggregation_controller.go:148] Starting ClusterRoleAggregator
        * I1024 17:23:36.831939       1 shared_informer.go:197] Waiting for caches to sync for ClusterRoleAggregator
        * I1024 17:23:36.897186       1 controllermanager.go:534] Started "pvc-protection"
        * W1024 17:23:36.900783       1 controllermanager.go:526] Skipping "root-ca-cert-publisher"
        * I1024 17:23:36.901606       1 shared_informer.go:197] Waiting for caches to sync for resource quota
        * I1024 17:23:36.901701       1 pvc_protection_controller.go:100] Starting PVC protection controller
        * I1024 17:23:36.901731       1 shared_informer.go:197] Waiting for caches to sync for PVC protection
        * I1024 17:23:36.976681       1 shared_informer.go:197] Waiting for caches to sync for garbage collector
        * I1024 17:23:37.113485       1 shared_informer.go:204] Caches are synced for PV protection 
        * W1024 17:23:37.127547       1 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="minikube" does not exist
        * I1024 17:23:37.168214       1 shared_informer.go:204] Caches are synced for TTL 
        * I1024 17:23:37.168924       1 shared_informer.go:204] Caches are synced for expand 
        * I1024 17:23:37.169212       1 shared_informer.go:204] Caches are synced for bootstrap_signer 
        * I1024 17:23:37.270832       1 shared_informer.go:204] Caches are synced for namespace 
        * I1024 17:23:37.271524       1 shared_informer.go:204] Caches are synced for service account 
        * I1024 17:23:37.282132       1 shared_informer.go:204] Caches are synced for certificate 
        * I1024 17:23:37.282387       1 shared_informer.go:204] Caches are synced for certificate 
        * I1024 17:23:37.282410       1 shared_informer.go:204] Caches are synced for ClusterRoleAggregator 
        * I1024 17:23:37.342922       1 shared_informer.go:204] Caches are synced for job 
        * I1024 17:23:37.349663       1 shared_informer.go:204] Caches are synced for endpoint 
        * I1024 17:23:37.351086       1 shared_informer.go:204] Caches are synced for ReplicationController 
        * I1024 17:23:37.363505       1 shared_informer.go:204] Caches are synced for attach detach 
        * I1024 17:23:37.368250       1 shared_informer.go:204] Caches are synced for HPA 
        * I1024 17:23:37.368431       1 shared_informer.go:204] Caches are synced for persistent volume 
        * I1024 17:23:37.370597       1 shared_informer.go:204] Caches are synced for ReplicaSet 
        * I1024 17:23:37.405181       1 shared_informer.go:204] Caches are synced for daemon sets 
        * I1024 17:23:37.414186       1 shared_informer.go:204] Caches are synced for PVC protection 
        * I1024 17:23:37.417914       1 shared_informer.go:204] Caches are synced for GC 
        * I1024 17:23:37.419915       1 shared_informer.go:204] Caches are synced for deployment 
        * I1024 17:23:37.515515       1 shared_informer.go:204] Caches are synced for taint 
        * I1024 17:23:37.516879       1 node_lifecycle_controller.go:1208] Initializing eviction metric for zone: 
        * W1024 17:23:37.518837       1 node_lifecycle_controller.go:903] Missing timestamp for Node minikube. Assuming now as a timestamp.
        * I1024 17:23:37.519746       1 node_lifecycle_controller.go:1108] Controller detected that zone  is now in state Normal.
        * I1024 17:23:37.525930       1 taint_manager.go:186] Starting NoExecuteTaintManager
        * I1024 17:23:37.527987       1 event.go:255] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"minikube", UID:"445a1093-36ae-4006-9758-d6fdb0757756", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node minikube event: Registered Node minikube in Controller
        * I1024 17:23:37.554940       1 shared_informer.go:204] Caches are synced for stateful set 
        * I1024 17:23:37.556546       1 shared_informer.go:204] Caches are synced for disruption 
        * I1024 17:23:37.556711       1 disruption.go:341] Sending events to api server.
        * I1024 17:23:37.579935       1 shared_informer.go:204] Caches are synced for garbage collector 
        * I1024 17:23:37.598438       1 shared_informer.go:204] Caches are synced for garbage collector 
        * I1024 17:23:37.598706       1 garbagecollector.go:139] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
        * I1024 17:23:37.612702       1 shared_informer.go:204] Caches are synced for resource quota 
        * I1024 17:23:37.621427       1 shared_informer.go:204] Caches are synced for resource quota 
        * I1024 17:23:37.641497       1 event.go:255] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"kubernetes-dashboard", Name:"dashboard-metrics-scraper", UID:"368175f8-922d-473b-a3e7-ad8375ca6315", APIVersion:"apps/v1", ResourceVersion:"1010", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set dashboard-metrics-scraper-76585494d8 to 1
        * I1024 17:23:37.937471       1 event.go:255] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"kubernetes-dashboard", Name:"kubernetes-dashboard", UID:"f976d6ca-4a2a-40e1-911b-2ac8fbde1846", APIVersion:"apps/v1", ResourceVersion:"1013", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set kubernetes-dashboard-57f4cb4545 to 1
        * I1024 17:23:38.192771       1 event.go:255] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kubernetes-dashboard", Name:"dashboard-metrics-scraper-76585494d8", UID:"edfaf3e8-2fdf-4a57-84e6-9257a0e067ae", APIVersion:"apps/v1", ResourceVersion:"1034", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: dashboard-metrics-scraper-76585494d8-nc7wk
        * I1024 17:23:38.629898       1 event.go:255] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kubernetes-dashboard", Name:"kubernetes-dashboard-57f4cb4545", UID:"e183817b-e91f-4272-868b-7eeafa1e9697", APIVersion:"apps/v1", ResourceVersion:"1037", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: kubernetes-dashboard-57f4cb4545-bqjcr
        * 
        * ==> kube-proxy [26d455cf8c634238dc452962db737b9ff82d4d799a44e12f6ccd67bd5ea0687e] <==
        * W1024 17:23:28.879849       1 server_others.go:329] Flag proxy-mode="" unknown, assuming iptables proxy
        * I1024 17:23:29.737812       1 node.go:135] Successfully retrieved node IP: 192.168.39.47
        * I1024 17:23:29.737990       1 server_others.go:149] Using iptables Proxier.
        * W1024 17:23:29.780213       1 proxier.go:287] clusterCIDR not specified, unable to distinguish between internal and external traffic
        * I1024 17:23:29.781934       1 server.go:529] Version: v1.16.1
        * I1024 17:23:29.815323       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
        * I1024 17:23:29.815453       1 conntrack.go:52] Setting nf_conntrack_max to 131072
        * I1024 17:23:29.815946       1 conntrack.go:83] Setting conntrack hashsize to 32768
        * I1024 17:23:29.825802       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
        * I1024 17:23:29.826024       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
        * I1024 17:23:29.826596       1 config.go:313] Starting service config controller
        * I1024 17:23:29.839134       1 shared_informer.go:197] Waiting for caches to sync for service config
        * I1024 17:23:29.840237       1 config.go:131] Starting endpoints config controller
        * I1024 17:23:29.840386       1 shared_informer.go:197] Waiting for caches to sync for endpoints config
        * I1024 17:23:29.939771       1 shared_informer.go:204] Caches are synced for service config 
        * I1024 17:23:29.942890       1 shared_informer.go:204] Caches are synced for endpoints config 
        * 
        * ==> kube-scheduler [894336a5c9af051d3e22e86cc9962e62656fb1d13e14c95ad744aa58e3d800e6] <==
        * I1024 17:22:49.563531       1 serving.go:319] Generated self-signed cert in-memory
        * W1024 17:22:51.166871       1 authentication.go:199] Error looking up in-cluster authentication configuration: Get https://localhost:8443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 127.0.0.1:8443: connect: connection refused
        * W1024 17:22:51.167013       1 authentication.go:200] Continuing without authentication configuration. This may treat all requests as anonymous.
        * W1024 17:22:51.167028       1 authentication.go:201] To require authentication configuration lookup to succeed, set --authentication-tolerate-lookup-failure=false
        * I1024 17:22:51.434509       1 server.go:143] Version: v1.16.1
        * I1024 17:22:51.436084       1 defaults.go:91] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
        * W1024 17:22:51.480896       1 authorization.go:47] Authorization is disabled
        * W1024 17:22:51.482135       1 authentication.go:79] Authentication is disabled
        * I1024 17:22:51.483091       1 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
        * I1024 17:22:51.526822       1 secure_serving.go:123] Serving securely on 127.0.0.1:10259
        * E1024 17:22:52.194849       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Node: Get https://localhost:8443/api/v1/nodes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:52.195211       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Service: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:52.196070       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: Get https://localhost:8443/apis/storage.k8s.io/v1beta1/csinodes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:52.198788       1 reflector.go:123] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:236: Failed to list *v1.Pod: Get https://localhost:8443/api/v1/pods?fieldSelector=status.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:52.200694       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StatefulSet: Get https://localhost:8443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:52.200855       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolume: Get https://localhost:8443/api/v1/persistentvolumes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:52.208438       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicaSet: Get https://localhost:8443/apis/apps/v1/replicasets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:52.208583       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicationController: Get https://localhost:8443/api/v1/replicationcontrollers?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:52.208883       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolumeClaim: Get https://localhost:8443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:52.209204       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StorageClass: Get https://localhost:8443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:52.312968       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.PodDisruptionBudget: Get https://localhost:8443/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:53.204480       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Node: Get https://localhost:8443/api/v1/nodes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:53.207139       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Service: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:53.209720       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: Get https://localhost:8443/apis/storage.k8s.io/v1beta1/csinodes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:53.210242       1 reflector.go:123] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:236: Failed to list *v1.Pod: Get https://localhost:8443/api/v1/pods?fieldSelector=status.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:53.213847       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StatefulSet: Get https://localhost:8443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:53.215861       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicaSet: Get https://localhost:8443/apis/apps/v1/replicasets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:53.217187       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicationController: Get https://localhost:8443/api/v1/replicationcontrollers?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:53.221512       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolume: Get https://localhost:8443/api/v1/persistentvolumes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:53.222750       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolumeClaim: Get https://localhost:8443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:53.223089       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StorageClass: Get https://localhost:8443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:53.324226       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.PodDisruptionBudget: Get https://localhost:8443/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:54.232102       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StatefulSet: Get https://localhost:8443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:54.234246       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicaSet: Get https://localhost:8443/apis/apps/v1/replicasets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:54.235122       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: Get https://localhost:8443/apis/storage.k8s.io/v1beta1/csinodes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:54.237674       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolumeClaim: Get https://localhost:8443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:54.239644       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicationController: Get https://localhost:8443/api/v1/replicationcontrollers?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:54.240238       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Service: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:54.240725       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StorageClass: Get https://localhost:8443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:54.248116       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Node: Get https://localhost:8443/api/v1/nodes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:54.248481       1 reflector.go:123] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:236: Failed to list *v1.Pod: Get https://localhost:8443/api/v1/pods?fieldSelector=status.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:54.248880       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolume: Get https://localhost:8443/api/v1/persistentvolumes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:54.328018       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.PodDisruptionBudget: Get https://localhost:8443/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:55.242518       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StatefulSet: Get https://localhost:8443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:55.245736       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicaSet: Get https://localhost:8443/apis/apps/v1/replicasets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:55.269169       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: Get https://localhost:8443/apis/storage.k8s.io/v1beta1/csinodes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:55.275202       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Service: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:55.279130       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicationController: Get https://localhost:8443/api/v1/replicationcontrollers?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:55.284606       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Node: Get https://localhost:8443/api/v1/nodes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:55.288570       1 reflector.go:123] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:236: Failed to list *v1.Pod: Get https://localhost:8443/api/v1/pods?fieldSelector=status.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:55.289887       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolumeClaim: Get https://localhost:8443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:55.293558       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolume: Get https://localhost:8443/api/v1/persistentvolumes?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:55.293606       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StorageClass: Get https://localhost:8443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * E1024 17:22:55.352561       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.PodDisruptionBudget: Get https://localhost:8443/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
        * I1024 17:23:06.290596       1 trace.go:116] Trace[1679428610]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (started: 2019-10-24 17:22:56.253818694 +0000 UTC m=+14.404374271) (total time: 10.018925902s):
        * Trace[1679428610]: [10.018925902s] [10.018925902s] END
        * I1024 17:23:06.293306       1 trace.go:116] Trace[331263775]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (started: 2019-10-24 17:22:56.246853687 +0000 UTC m=+14.397409194) (total time: 10.036694454s):
        * Trace[331263775]: [10.036694454s] [10.036694454s] END
        * E1024 17:23:06.293587       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StatefulSet: Get https://localhost:8443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
        * E1024 17:23:06.291174       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicaSet: Get https://localhost:8443/apis/apps/v1/replicasets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
        * I1024 17:23:06.343029       1 trace.go:116] Trace[78916921]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (started: 2019-10-24 17:22:56.322552492 +0000 UTC m=+14.473107590) (total time: 10.020311263s):
        * Trace[78916921]: [10.020311263s] [10.020311263s] END
        * E1024 17:23:06.343139       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicationController: Get https://localhost:8443/api/v1/replicationcontrollers?limit=500&resourceVersion=0: net/http: TLS handshake timeout
        * I1024 17:23:06.344980       1 trace.go:116] Trace[1965920693]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (started: 2019-10-24 17:22:56.327230972 +0000 UTC m=+14.477785876) (total time: 10.017633916s):
        * Trace[1965920693]: [10.017633916s] [10.017633916s] END
        * E1024 17:23:06.347634       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: Get https://localhost:8443/apis/storage.k8s.io/v1beta1/csinodes?limit=500&resourceVersion=0: net/http: TLS handshake timeout
        * I1024 17:23:06.349225       1 trace.go:116] Trace[1944607271]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (started: 2019-10-24 17:22:56.329126701 +0000 UTC m=+14.479681612) (total time: 10.019810521s):
        * Trace[1944607271]: [10.019810521s] [10.019810521s] END
        * E1024 17:23:06.349411       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Node: Get https://localhost:8443/api/v1/nodes?limit=500&resourceVersion=0: net/http: TLS handshake timeout
        * I1024 17:23:06.351972       1 trace.go:116] Trace[505700932]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (started: 2019-10-24 17:22:56.326700318 +0000 UTC m=+14.477255220) (total time: 10.025143012s):
        * Trace[505700932]: [10.025143012s] [10.025143012s] END
        * E1024 17:23:06.352129       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Service: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: net/http: TLS handshake timeout
        * I1024 17:23:06.353096       1 trace.go:116] Trace[1059927400]: "Reflector ListAndWatch" name:k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:236 (started: 2019-10-24 17:22:56.33187354 +0000 UTC m=+14.482428555) (total time: 10.020204013s):
        * Trace[1059927400]: [10.020204013s] [10.020204013s] END
        * E1024 17:23:06.353585       1 reflector.go:123] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:236: Failed to list *v1.Pod: Get https://localhost:8443/api/v1/pods?fieldSelector=status.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&limit=500&resourceVersion=0: net/http: TLS handshake timeout
        * I1024 17:23:06.355042       1 trace.go:116] Trace[1292478317]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (started: 2019-10-24 17:22:56.324960263 +0000 UTC m=+14.475515310) (total time: 10.029724236s):
        * Trace[1292478317]: [10.029724236s] [10.029724236s] END
        * E1024 17:23:06.355454       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StorageClass: Get https://localhost:8443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0: net/http: TLS handshake timeout
        * I1024 17:23:06.370869       1 trace.go:116] Trace[996390446]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (started: 2019-10-24 17:22:56.339104984 +0000 UTC m=+14.489660279) (total time: 10.031700635s):
        * Trace[996390446]: [10.031700635s] [10.031700635s] END
        * E1024 17:23:06.371361       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolumeClaim: Get https://localhost:8443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0: net/http: TLS handshake timeout
        * I1024 17:23:06.376685       1 trace.go:116] Trace[437395235]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (started: 2019-10-24 17:22:56.369067285 +0000 UTC m=+14.519622599) (total time: 10.007332062s):
        * Trace[437395235]: [10.007332062s] [10.007332062s] END
        * E1024 17:23:06.377116       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.PodDisruptionBudget: Get https://localhost:8443/apis/policy/v1beta1/poddisruptionbudgets?limit=500&resourceVersion=0: net/http: TLS handshake timeout
        * I1024 17:23:06.382510       1 trace.go:116] Trace[1139266623]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (started: 2019-10-24 17:22:56.350250327 +0000 UTC m=+14.500805423) (total time: 10.032212015s):
        * Trace[1139266623]: [10.032212015s] [10.032212015s] END
        * E1024 17:23:06.382756       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolume: Get https://localhost:8443/api/v1/persistentvolumes?limit=500&resourceVersion=0: net/http: TLS handshake timeout
        * I1024 17:23:13.232099       1 leaderelection.go:241] attempting to acquire leader lease  kube-system/kube-scheduler...
        * I1024 17:23:31.549429       1 leaderelection.go:251] successfully acquired lease kube-system/kube-scheduler
        * 
        * ==> kubelet <==
        * -- Logs begin at Thu 2019-10-24 17:21:52 UTC, end at Thu 2019-10-24 17:27:48 UTC. --
        * Oct 24 17:24:50 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:24:50.314074    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:24:50 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:24:50.316880    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:24:50 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:24:50.316926    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:24:50 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:24:50.317228    2176 pod_workers.go:191] Error syncing pod 08391835-b41d-4564-9a46-6cc4f8294759 ("nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)"), skipping: failed to "CreatePodSandbox" for "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"untrusted\" is configured"
        * Oct 24 17:24:59 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:24:59.256192    2176 pod_workers.go:191] Error syncing pod f658f75b-119a-4cd2-911d-4d8b414601f0 ("gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"), skipping: failed to "StartContainer" for "gvisor" with CrashLoopBackOff: "back-off 40s restarting failed container=gvisor pod=gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"
        * Oct 24 17:25:06 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:06.416798    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:25:06 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:06.418658    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:25:06 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:06.418755    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:25:06 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:06.419184    2176 pod_workers.go:191] Error syncing pod 08391835-b41d-4564-9a46-6cc4f8294759 ("nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)"), skipping: failed to "CreatePodSandbox" for "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"untrusted\" is configured"
        * Oct 24 17:25:06 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:06.931803    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:25:06 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:06.935763    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:25:06 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:06.936076    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:25:06 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:06.942666    2176 pod_workers.go:191] Error syncing pod 86aaab2d-bbd7-4b19-b842-e2add2c62776 ("nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)"), skipping: failed to "CreatePodSandbox" for "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"runsc\" is configured"
        * Oct 24 17:25:14 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:14.322656    2176 pod_workers.go:191] Error syncing pod f658f75b-119a-4cd2-911d-4d8b414601f0 ("gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"), skipping: failed to "StartContainer" for "gvisor" with CrashLoopBackOff: "back-off 40s restarting failed container=gvisor pod=gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"
        * Oct 24 17:25:23 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:23.372097    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:25:23 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:23.383110    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:25:23 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:23.383401    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:25:23 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:23.443908    2176 pod_workers.go:191] Error syncing pod 86aaab2d-bbd7-4b19-b842-e2add2c62776 ("nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)"), skipping: failed to "CreatePodSandbox" for "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"runsc\" is configured"
        * Oct 24 17:25:24 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:24.208184    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:25:24 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:24.209024    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:25:24 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:24.209145    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:25:24 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:24.209855    2176 pod_workers.go:191] Error syncing pod 08391835-b41d-4564-9a46-6cc4f8294759 ("nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)"), skipping: failed to "CreatePodSandbox" for "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"untrusted\" is configured"
        * Oct 24 17:25:36 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:36.307972    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:25:36 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:36.314117    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:25:36 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:36.314616    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:25:36 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:36.316579    2176 pod_workers.go:191] Error syncing pod 86aaab2d-bbd7-4b19-b842-e2add2c62776 ("nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)"), skipping: failed to "CreatePodSandbox" for "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"runsc\" is configured"
        * Oct 24 17:25:36 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:36.863047    2176 pod_workers.go:191] Error syncing pod f658f75b-119a-4cd2-911d-4d8b414601f0 ("gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"), skipping: failed to "StartContainer" for "gvisor" with CrashLoopBackOff: "back-off 1m20s restarting failed container=gvisor pod=gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"
        * Oct 24 17:25:41 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:41.292676    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:25:41 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:41.296035    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:25:41 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:41.297476    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:25:41 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:41.298773    2176 pod_workers.go:191] Error syncing pod 08391835-b41d-4564-9a46-6cc4f8294759 ("nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)"), skipping: failed to "CreatePodSandbox" for "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"untrusted\" is configured"
        * Oct 24 17:25:49 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:49.867033    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:25:49 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:49.871687    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:25:49 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:49.871878    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:25:49 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:49.879249    2176 pod_workers.go:191] Error syncing pod 86aaab2d-bbd7-4b19-b842-e2add2c62776 ("nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)"), skipping: failed to "CreatePodSandbox" for "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"runsc\" is configured"
        * Oct 24 17:25:50 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:50.281779    2176 pod_workers.go:191] Error syncing pod f658f75b-119a-4cd2-911d-4d8b414601f0 ("gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"), skipping: failed to "StartContainer" for "gvisor" with CrashLoopBackOff: "back-off 1m20s restarting failed container=gvisor pod=gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"
        * Oct 24 17:25:57 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:57.949170    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:25:57 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:57.949944    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:25:57 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:57.949997    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:25:57 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:25:57.950390    2176 pod_workers.go:191] Error syncing pod 08391835-b41d-4564-9a46-6cc4f8294759 ("nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)"), skipping: failed to "CreatePodSandbox" for "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"untrusted\" is configured"
        * Oct 24 17:26:03 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:03.267608    2176 pod_workers.go:191] Error syncing pod f658f75b-119a-4cd2-911d-4d8b414601f0 ("gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"), skipping: failed to "StartContainer" for "gvisor" with CrashLoopBackOff: "back-off 1m20s restarting failed container=gvisor pod=gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"
        * Oct 24 17:26:06 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:06.394642    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:26:06 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:06.395006    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:26:06 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:06.395051    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:26:06 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:06.395220    2176 pod_workers.go:191] Error syncing pod 86aaab2d-bbd7-4b19-b842-e2add2c62776 ("nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)"), skipping: failed to "CreatePodSandbox" for "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"runsc\" is configured"
        * Oct 24 17:26:13 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:13.548952    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:26:13 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:13.549431    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:26:13 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:13.549462    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:26:13 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:13.549636    2176 pod_workers.go:191] Error syncing pod 08391835-b41d-4564-9a46-6cc4f8294759 ("nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)"), skipping: failed to "CreatePodSandbox" for "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"untrusted\" is configured"
        * Oct 24 17:26:14 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:14.289656    2176 pod_workers.go:191] Error syncing pod f658f75b-119a-4cd2-911d-4d8b414601f0 ("gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"), skipping: failed to "StartContainer" for "gvisor" with CrashLoopBackOff: "back-off 1m20s restarting failed container=gvisor pod=gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"
        * Oct 24 17:26:23 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:23.749976    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:26:23 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:23.752144    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:26:23 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:23.752201    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:26:23 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:23.752649    2176 pod_workers.go:191] Error syncing pod 86aaab2d-bbd7-4b19-b842-e2add2c62776 ("nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)"), skipping: failed to "CreatePodSandbox" for "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"runsc\" is configured"
        * Oct 24 17:26:27 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:27.253895    2176 pod_workers.go:191] Error syncing pod f658f75b-119a-4cd2-911d-4d8b414601f0 ("gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"), skipping: failed to "StartContainer" for "gvisor" with CrashLoopBackOff: "back-off 1m20s restarting failed container=gvisor pod=gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"
        * Oct 24 17:26:31 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:31.354402    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:26:31 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:31.354623    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:26:31 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:31.354679    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:26:31 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:31.394546    2176 pod_workers.go:191] Error syncing pod 08391835-b41d-4564-9a46-6cc4f8294759 ("nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)"), skipping: failed to "CreatePodSandbox" for "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"untrusted\" is configured"
        * Oct 24 17:26:37 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:37.565733    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:26:37 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:37.576665    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:26:37 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:37.576722    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:26:37 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:37.576927    2176 pod_workers.go:191] Error syncing pod 86aaab2d-bbd7-4b19-b842-e2add2c62776 ("nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)"), skipping: failed to "CreatePodSandbox" for "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"runsc\" is configured"
        * Oct 24 17:26:40 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:40.254854    2176 pod_workers.go:191] Error syncing pod f658f75b-119a-4cd2-911d-4d8b414601f0 ("gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"), skipping: failed to "StartContainer" for "gvisor" with CrashLoopBackOff: "back-off 1m20s restarting failed container=gvisor pod=gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"
        * Oct 24 17:26:46 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:46.523852    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:26:46 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:46.526576    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:26:46 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:46.526624    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:26:46 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:46.526815    2176 pod_workers.go:191] Error syncing pod 08391835-b41d-4564-9a46-6cc4f8294759 ("nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)"), skipping: failed to "CreatePodSandbox" for "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"untrusted\" is configured"
        * Oct 24 17:26:50 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:50.856738    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:26:50 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:50.857555    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:26:50 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:50.857604    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:26:50 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:50.857761    2176 pod_workers.go:191] Error syncing pod 86aaab2d-bbd7-4b19-b842-e2add2c62776 ("nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)"), skipping: failed to "CreatePodSandbox" for "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"runsc\" is configured"
        * Oct 24 17:26:53 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:26:53.255023    2176 pod_workers.go:191] Error syncing pod f658f75b-119a-4cd2-911d-4d8b414601f0 ("gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"), skipping: failed to "StartContainer" for "gvisor" with CrashLoopBackOff: "back-off 1m20s restarting failed container=gvisor pod=gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"
        * Oct 24 17:27:02 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:02.214366    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:27:02 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:02.216051    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:27:02 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:02.216087    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:27:02 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:02.216247    2176 pod_workers.go:191] Error syncing pod 08391835-b41d-4564-9a46-6cc4f8294759 ("nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)"), skipping: failed to "CreatePodSandbox" for "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"untrusted\" is configured"
        * Oct 24 17:27:05 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:05.755408    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:27:05 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:05.755567    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:27:05 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:05.755602    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:27:05 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:05.755699    2176 pod_workers.go:191] Error syncing pod 86aaab2d-bbd7-4b19-b842-e2add2c62776 ("nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)"), skipping: failed to "CreatePodSandbox" for "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"runsc\" is configured"
        * Oct 24 17:27:15 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:15.159185    2176 pod_workers.go:191] Error syncing pod f658f75b-119a-4cd2-911d-4d8b414601f0 ("gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"), skipping: failed to "StartContainer" for "gvisor" with CrashLoopBackOff: "back-off 2m40s restarting failed container=gvisor pod=gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"
        * Oct 24 17:27:17 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:17.527201    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:27:17 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:17.527779    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:27:17 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:17.527822    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:27:17 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:17.527919    2176 pod_workers.go:191] Error syncing pod 08391835-b41d-4564-9a46-6cc4f8294759 ("nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)"), skipping: failed to "CreatePodSandbox" for "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"untrusted\" is configured"
        * Oct 24 17:27:21 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:21.404992    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:27:21 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:21.405117    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:27:21 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:21.406200    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:27:21 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:21.406397    2176 pod_workers.go:191] Error syncing pod 86aaab2d-bbd7-4b19-b842-e2add2c62776 ("nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)"), skipping: failed to "CreatePodSandbox" for "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"runsc\" is configured"
        * Oct 24 17:27:30 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:30.251606    2176 pod_workers.go:191] Error syncing pod f658f75b-119a-4cd2-911d-4d8b414601f0 ("gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"), skipping: failed to "StartContainer" for "gvisor" with CrashLoopBackOff: "back-off 2m40s restarting failed container=gvisor pod=gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"
        * Oct 24 17:27:33 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:33.609031    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:27:33 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:33.609185    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:27:33 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:33.609222    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "untrusted" is configured
        * Oct 24 17:27:33 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:33.609437    2176 pod_workers.go:191] Error syncing pod 08391835-b41d-4564-9a46-6cc4f8294759 ("nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)"), skipping: failed to "CreatePodSandbox" for "nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-untrusted_default(08391835-b41d-4564-9a46-6cc4f8294759)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"untrusted\" is configured"
        * Oct 24 17:27:39 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:39.164082    2176 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:27:39 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:39.165157    2176 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:27:39 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:39.165192    2176 kuberuntime_manager.go:710] createPodSandbox for pod "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured
        * Oct 24 17:27:39 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:39.165347    2176 pod_workers.go:191] Error syncing pod 86aaab2d-bbd7-4b19-b842-e2add2c62776 ("nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)"), skipping: failed to "CreatePodSandbox" for "nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)" with CreatePodSandboxError: "CreatePodSandbox for pod \"nginx-gvisor_default(86aaab2d-bbd7-4b19-b842-e2add2c62776)\" failed: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for \"runsc\" is configured"
        * Oct 24 17:27:45 gvisor-20191024T171027.666717625-13805 kubelet[2176]: E1024 17:27:45.255596    2176 pod_workers.go:191] Error syncing pod f658f75b-119a-4cd2-911d-4d8b414601f0 ("gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"), skipping: failed to "StartContainer" for "gvisor" with CrashLoopBackOff: "back-off 2m40s restarting failed container=gvisor pod=gvisor_kube-system(f658f75b-119a-4cd2-911d-4d8b414601f0)"
        * 
        * ==> kubernetes-dashboard [6f29aa17b1b37a20df6a240e1b2a85f846928aeedfd3300314cf611977b0d32e] <==
        * 2019/10/24 17:23:48 Using namespace: kubernetes-dashboard
        * 2019/10/24 17:23:48 Using in-cluster config to connect to apiserver
        * 2019/10/24 17:23:48 Using secret token for csrf signing
        * 2019/10/24 17:23:48 Initializing csrf token from kubernetes-dashboard-csrf secret
        * 2019/10/24 17:23:48 Starting overwatch
        * 2019/10/24 17:23:48 Empty token. Generating and storing in a secret kubernetes-dashboard-csrf
        * 2019/10/24 17:23:48 Successful initial request to the apiserver, version: v1.16.1
        * 2019/10/24 17:23:48 Generating JWE encryption key
        * 2019/10/24 17:23:48 New synchronizer has been registered: kubernetes-dashboard-key-holder-kubernetes-dashboard. Starting
        * 2019/10/24 17:23:48 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kubernetes-dashboard
        * 2019/10/24 17:23:50 Initializing JWE encryption key from synchronized object
        * 2019/10/24 17:23:50 Creating in-cluster Sidecar client
        * 2019/10/24 17:23:50 Metric client health check failed: the server is currently unable to handle the request (get services dashboard-metrics-scraper). Retrying in 30 seconds.
        * 2019/10/24 17:23:50 Serving insecurely on HTTP port: 9090
        * 2019/10/24 17:24:20 Successful request to sidecar
        * 
        * ==> storage-provisioner [948a4aaaf0b2de87dcd3c61b074912716cd9ba8c7b31139d2932e08f6a2c9503] <==
    gvisor_addon_test.go:38: Sorry that TestGvisorAddon failed :(
    helpers.go:165: (dbg) Run:  out/minikube-linux-amd64 delete -p gvisor-20191024T171027.666717625-13805

</pre>
</details>

### PR DESCRIPTION
**Pull request by tstromberg**
Replaces brittle `LD_LIBRARY_PATH` hack with `chroot` to restart node services from the pod.

This was previously using the Ubuntu `sudo` binary with libraries from the ISO image, which was safe until we updated the ISO image to a new glibc.

Fixes #5724

### CODE REVIEW

File: deploy/gvisor/Dockerfile [hunk 1]
```diff
@@ -12,9 +12,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-FROM ubuntu:18.04
-RUN apt-get update && \
-    apt-get install -y kmod gcc wget xz-utils libc6-dev bc libelf-dev bison flex openssl libssl-dev libidn2-0 sudo libcap2 && \
-    rm -rf /var/lib/apt/lists/*
+# Need an image with chroot
+FROM alpine:3
```
Comment (medyagh) [inline deploy/gvisor/Dockerfile]: I suggest pinning this to a more specific version to avoid future headaches.
alpine:3.10.3 list of versions can be found here https://hub.docker.com/_/alpine

Comment (priyawadhwa) [reply deploy/gvisor/Dockerfile]: Nice this is way better!

File: pkg/gvisor/enable.go [hunk 2]
```diff
@@ -193,28 +200,24 @@ func copyAssetToDest(targetName, dest string) error {
 }
 
 func restartContainerd() error {
-	dir := filepath.Join(nodeDir, "usr/libexec/sudo")
-	if err := os.Setenv("LD_LIBRARY_PATH", dir); err != nil {
-		return errors.Wrap(err, dir)
-	}
+	log.Print("restartContainerd black magic happening")
```
Comment (priyawadhwa) [inline pkg/gvisor/enable.go]: :smile:

File: cmd/gvisor/gvisor.go [hunk 3]
```diff
@@ -17,13 +17,16 @@ limitations under the License.
...
 import (
+	"flag"
 	"log"
 	"os"
 
 	"k8s.io/minikube/pkg/gvisor"
 )
 
 func main() {
+	flag.Parse()
```
Comment (priyawadhwa) [inline cmd/gvisor/gvisor.go]: Is this needed?

File: deploy/gvisor/Dockerfile (hunk 1 above)
Comment (tstromberg) [reply deploy/gvisor/Dockerfile]: Honestly the likelihood of `chroot` failing is pretty low. I'd rather not have to micro-manage patch versions if I can. If this wider pin proves a problem, I'll pin this more tightly.

File: cmd/gvisor/gvisor.go (hunk 3 above)
Comment (tstromberg) [reply cmd/gvisor/gvisor.go]: Not any longer. It was when I accidentally started using glog =)

**Comment by tstromberg** [comment]
@minikube-bot OK to test
