### PR TITLE
Check if Docker installed via Snap Package Manager

### LINKED ISSUE #10772: Fix `no such file or directory` error when Docker installed via Snap
**Los comandos necesarios para reproducir la incidencia**:

**El resultado completo del comando que ha fallado**: <details>
alberts@4lbrts:~/oauth2-proxy-v6.1.1.linux-amd64$ export NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
alberts@4lbrts:~/oauth2-proxy-v6.1.1.linux-amd64$ minikube delete
🔥  Deleting "minikube" in docker ...
🔥  Deleting container "minikube" ...
🔥  Removing /home/alberts/.minikube/machines/minikube ...
💀  Removed all traces of the "minikube" cluster.
alberts@4lbrts:~/oauth2-proxy-v6.1.1.linux-amd64$ minikube start
😄  minikube v1.18.1 on Debian buster/sid
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
✋  Stopping node "minikube"  ...
🛑  Powering off "minikube" via SSH ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset207003446 into minikube:/home/docker/.ssh/authorized_keys, output: lstat /tmp/tmpf-memory-asset207003446: no such file or directory
: exit status 1
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
😿  Failed to start docker container. Running "minikube delete" may fix it: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset508036381 into minikube:/home/docker/.ssh/authorized_keys, output: lstat /tmp/tmpf-memory-asset508036381: no such file or directory
: exit status 1

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset508036381 into minikube:/home/docker/.ssh/authorized_keys, output: lstat /tmp/tmpf-memory-asset508036381: no such file or directory
: exit status 1

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**El resultado del comando `minikube logs`**: <details>
alberts@4lbrts:~/oauth2-proxy-v6.1.1.linux-amd64$ minikube logs

❌  Exiting due to DRV_CP_ENDPOINT: failed to parse ip for ""
💡  Suggestion: 

    Recreate the cluster by running:
    minikube delete
    minikube start

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**La versión del sistema operativo que utilizaste**:
utilizo elementary OS 5.1.7 Hera, basado e ubuntu 18.04
Screenshot from 2021-03-10 12 15 22

### PR DESCRIPTION
**Pull request by spowelljr**
Closes #10772

The root of the issue is that packages installed via Snap have their own tmp folder and can't actually access `/tmp`. minikube writes a memory asset to the `/tmp` folder that Docker later copies, but if installed via Snap fails due to having different tmp dirs. We added code to check if minikube is installed via Snap, and if it is, we write the memory asset to the users home dir instead.

However, the issue is if Docker is installed via Snap and minikube is not, because we only check if minikube is installed via Snap, we write the memory asset to the `/tmp` dir, but Docker can't access `/tmp` so it fails.

I added a check to see if Docker is installed via Snap, and if minikube or Docker is installed via Snap, writes the memory asset to the users home dir instead.

### CODE REVIEW

**Review by medyagh — APPROVED** [review]

File: pkg/minikube/command/kic_runner.go [hunk 1]
```diff
@@ -222,8 +221,8 @@ func tempDirectory(isSnap bool) (string, error) {
 	return home, nil
 }
 
-// isSnapBinary returns true if the binary path includes "snap".
-func isSnapBinary() bool {
+// isMinikubeSnap returns true if the minikube binary path includes "snap".
+func isMinikubeSnap() bool {
```
Comment (medyagh) [inline pkg/minikube/command/kic_runner.go:225]: consider moving these two funcs on detect package

detect.MinikubeInstalledBySnap()

detect.DockerInstalledBySnap()

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/command/kic_runner.go (hunk 1 above)
Comment (spowelljr) [reply pkg/minikube/command/kic_runner.go]: Didn't know that package existed, thanks for the recommendation, moved

**Review by medyagh — APPROVED** [review]
