### PR TITLE
Fix `minikube addons list` output for default addons

### LINKED ISSUE #15710: `minikube addons list` outputs wrong state for default addons
**Reproduce:**
```
$ minikube start --install-addons=false
😄  minikube v1.28.0 on Darwin 13.2 (arm64)
✨  Using the docker driver based on user configuration
📌  Using Docker Desktop driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
🐳  Preparing Kubernetes v1.25.3 on Docker 20.10.22 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

# no storage provisioner
$ kubectl get pods -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-565d847f94-hvhfh           1/1     Running   0          5m59s
kube-system   etcd-minikube                      1/1     Running   0          6m12s
kube-system   kube-apiserver-minikube            1/1     Running   0          6m12s
kube-system   kube-controller-manager-minikube   1/1     Running   0          6m12s
kube-system   kube-proxy-tvr7g                   1/1     Running   0          5m59s
kube-system   kube-scheduler-minikube            1/1     Running   0          6m12s

# incorrectly states addons are enabled
$ minikube addons list
|-----------------------------|----------|--------------|--------------------------------|
|         ADDON NAME          | PROFILE  |    STATUS    |           MAINTAINER           |
|-----------------------------|----------|--------------|--------------------------------|
| ambassador                  | minikube | disabled     | 3rd party (Ambassador)         |
| auto-pause                  | minikube | disabled     | Google                         |
| cloud-spanner               | minikube | disabled     | Google                         |
| csi-hostpath-driver         | minikube | disabled     | Kubernetes                     |
| dashboard                   | minikube | disabled     | Kubernetes                     |
| default-storageclass        | minikube | enabled ✅   | Kubernetes                     |
| efk                         | minikube | disabled     | 3rd party (Elastic)            |
| freshpod                    | minikube | disabled     | Google                         |
| gcp-auth                    | minikube | disabled     | Google                         |
| gvisor                      | minikube | disabled     | Google                         |
| headlamp                    | minikube | disabled     | 3rd party (kinvolk.io)         |
| helm-tiller                 | minikube | disabled     | 3rd party (Helm)               |
| inaccel                     | minikube | disabled     | 3rd party (InAccel             |
|                             |          |              | [info@inaccel.com])            |
| ingress                     | minikube | disabled     | Kubernetes                     |
| ingress-dns                 | minikube | disabled     | Google                         |
| istio                       | minikube | disabled     | 3rd party (Istio)              |
| istio-provisioner           | minikube | disabled     | 3rd party (Istio)              |
| kong                        | minikube | disabled     | 3rd party (Kong HQ)            |
| kubevirt                    | minikube | disabled     | 3rd party (KubeVirt)           |
| logviewer                   | minikube | disabled     | 3rd party (unknown)            |
| metallb                     | minikube | disabled     | 3rd party (MetalLB)            |
| metrics-server              | minikube | disabled     | Kubernetes                     |
| nvidia-driver-installer     | minikube | disabled     | Google                         |
| nvidia-gpu-device-plugin    | minikube | disabled     | 3rd party (Nvidia)             |
| olm                         | minikube | disabled     | 3rd party (Operator Framework) |
| pod-security-policy         | minikube | disabled     | 3rd party (unknown)            |
| portainer                   | minikube | disabled     | 3rd party (Portainer.io)       |
| registry                    | minikube | disabled     | Google                         |
| registry-aliases            | minikube | disabled     | 3rd party (unknown)            |
| registry-creds              | minikube | disabled     | 3rd party (UPMC Enterprises)   |
| storage-provisioner         | minikube | enabled ✅   | Google                         |
| storage-provisioner-gluster | minikube | disabled     | 3rd party (Gluster)            |
| volumesnapshots             | minikube | disabled     | Kubernetes                     |
|-----------------------------|----------|--------------|--------------------------------|
```

The addon list should show all addons as disabled

### PR DESCRIPTION
**Pull request by shubhbapna**
Fixes #15710 

The cause of the issue was in [pkg/node/start.go](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/node/start.go#L232) where it only updated the config if there were any existing addons defined which was not the case when `install-addons` was set to false.

It seems to working locally. Adding output here:
```
$ ./minikube-linux-amd64 start --install-addons=false
😄  minikube v1.29.0 on Fedora 36
🆕  Kubernetes 1.26.1 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.26.1
✨  Using the docker driver based on existing profile
❗  docker is currently using the btrfs storage driver, consider switching to overlay2 for better performance
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
❗  This container is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.23.8 on Docker 20.10.20 ...
🔎  Verifying Kubernetes components...
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

# no storage provisioner
$ kubectl get pods -A
NAMESPACE      NAME                                        READY   STATUS             RESTARTS       AGE
kube-system    coredns-64897985d-dvsrj                     1/1     Running            9 (11m ago)    68d
kube-system    etcd-minikube                               1/1     Running            11 (68s ago)   68d
kube-system    kube-apiserver-minikube                     1/1     Running            10 (68s ago)   68d
kube-system    kube-controller-manager-minikube            1/1     Running            9 (68s ago)    68d
kube-system    kube-proxy-mb8r7                            1/1     Running            9 (68s ago)    68d
kube-system    kube-scheduler-minikube                     1/1     Running            10 (68s ago)   68d

# finally correct states for addons
$ ./minikube-linux-amd64 addons list
|-----------------------------|----------|--------------|--------------------------------|
|         ADDON NAME          | PROFILE  |    STATUS    |           MAINTAINER           |
|-----------------------------|----------|--------------|--------------------------------|
| ambassador                  | minikube | disabled     | 3rd party (Ambassador)         |
| auto-pause                  | minikube | disabled     | Google                         |
| cloud-spanner               | minikube | disabled     | Google                         |
| csi-hostpath-driver         | minikube | disabled     | Kubernetes                     |
| dashboard                   | minikube | disabled     | Kubernetes                     |
| default-storageclass        | minikube | disabled     | Kubernetes                     |
| efk                         | minikube | disabled     | 3rd party (Elastic)            |
| freshpod                    | minikube | disabled     | Google                         |
| gcp-auth                    | minikube | disabled     | Google                         |
| gvisor                      | minikube | disabled     | Google                         |
| headlamp                    | minikube | disabled     | 3rd party (kinvolk.io)         |
| helm-tiller                 | minikube | disabled     | 3rd party (Helm)               |
| inaccel                     | minikube | disabled     | 3rd party (InAccel             |
|                             |          |              | [info@inaccel.com])            |
| ingress                     | minikube | disabled     | Kubernetes                     |
| ingress-dns                 | minikube | disabled     | Google                         |
| istio                       | minikube | disabled     | 3rd party (Istio)              |
| istio-provisioner           | minikube | disabled     | 3rd party (Istio)              |
| kong                        | minikube | disabled     | 3rd party (Kong HQ)            |
| kubevirt                    | minikube | disabled     | 3rd party (KubeVirt)           |
| logviewer                   | minikube | disabled     | 3rd party (unknown)            |
| metallb                     | minikube | disabled     | 3rd party (MetalLB)            |
| metrics-server              | minikube | disabled     | Kubernetes                     |
| nvidia-driver-installer     | minikube | disabled     | Google                         |
| nvidia-gpu-device-plugin    | minikube | disabled     | 3rd party (Nvidia)             |
| olm                         | minikube | disabled     | 3rd party (Operator Framework) |
| pod-security-policy         | minikube | disabled     | 3rd party (unknown)            |
| portainer                   | minikube | disabled     | 3rd party (Portainer.io)       |
| registry                    | minikube | disabled     | Google                         |
| registry-aliases            | minikube | disabled     | 3rd party (unknown)            |
| registry-creds              | minikube | disabled     | 3rd party (UPMC Enterprises)   |
| storage-provisioner         | minikube | disabled     | Google                         |
| storage-provisioner-gluster | minikube | disabled     | 3rd party (Gluster)            |
| volumesnapshots             | minikube | disabled     | Kubernetes                     |
|-----------------------------|----------|--------------|--------------------------------|
```

### CODE REVIEW

File: pkg/addons/addons_test.go [hunk 1]
```diff
@@ -133,10 +133,30 @@ func TestStart(t *testing.T) {
...
+		CPUs:             2,
+		Memory:           2500,
+		KubernetesConfig: config.KubernetesConfig{},
+	}
+
+	UpdateConfigToDisable(cc)
+
+	for name := range assets.Addons {
+		if assets.Addons[name].IsEnabled(cc) {
+			t.Errorf("expected dashboard to be disabled")
```
Comment (spowelljr) [inline pkg/addons/addons_test.go:159]:
```suggestion
			t.Errorf("expected %s to be disabled", name)
```

**Review by spowelljr — CHANGES_REQUESTED** [review]

**Review by spowelljr — CHANGES_REQUESTED** [review]
Hi @shubhbapna, this works great for the existing addons, however if we were to add a new addon that is enabled by default this still outputs the addon as enabled even if it isn't.

```
$ minikube start --install-addons=false

# remove storage-provisioner from config.json to simulate new default addon being added
$ sed -i.bak 's/"storage-provisioner": false,//g' ~/.minikube/profiles/minikube/config.json

# storage-provisoner listed as enabled when it isn't
$ minikube addons list
|-----------------------------|----------|--------------|--------------------------------|
|         ADDON NAME          | PROFILE  |    STATUS    |           MAINTAINER           |
|-----------------------------|----------|--------------|--------------------------------|
| ambassador                  | minikube | disabled     | 3rd party (Ambassador)         |
| auto-pause                  | minikube | disabled     | Google                         |
| cloud-spanner               | minikube | disabled     | Google                         |
| csi-hostpath-driver         | minikube | disabled     | Kubernetes                     |
| dashboard                   | minikube | disabled     | Kubernetes                     |
| default-storageclass        | minikube | disabled     | Kubernetes                     |
| efk                         | minikube | disabled     | 3rd party (Elastic)            |
| freshpod                    | minikube | disabled     | Google                         |
| gcp-auth                    | minikube | disabled     | Google                         |
| gvisor                      | minikube | disabled     | Google                         |
| headlamp                    | minikube | disabled     | 3rd party (kinvolk.io)         |
| helm-tiller                 | minikube | disabled     | 3rd party (Helm)               |
| inaccel                     | minikube | disabled     | 3rd party (InAccel             |
|                             |          |              | [info@inaccel.com])            |
| ingress                     | minikube | disabled     | Kubernetes                     |
| ingress-dns                 | minikube | disabled     | Google                         |
| istio                       | minikube | disabled     | 3rd party (Istio)              |
| istio-provisioner           | minikube | disabled     | 3rd party (Istio)              |
| kong                        | minikube | disabled     | 3rd party (Kong HQ)            |
| kubevirt                    | minikube | disabled     | 3rd party (KubeVirt)           |
| logviewer                   | minikube | disabled     | 3rd party (unknown)            |
| metallb                     | minikube | disabled     | 3rd party (MetalLB)            |
| metrics-server              | minikube | disabled     | Kubernetes                     |
| nvidia-driver-installer     | minikube | disabled     | Google                         |
| nvidia-gpu-device-plugin    | minikube | disabled     | 3rd party (Nvidia)             |
| olm                         | minikube | disabled     | 3rd party (Operator Framework) |
| pod-security-policy         | minikube | disabled     | 3rd party (unknown)            |
| portainer                   | minikube | disabled     | 3rd party (Portainer.io)       |
| registry                    | minikube | disabled     | Google                         |
| registry-aliases            | minikube | disabled     | 3rd party (unknown)            |
| registry-creds              | minikube | disabled     | 3rd party (UPMC Enterprises)   |
| storage-provisioner         | minikube | enabled ✅   | Google                         |
| storage-provisioner-gluster | minikube | disabled     | 3rd party (Gluster)            |
| volumesnapshots             | minikube | disabled     | Kubernetes                     |
|-----------------------------|----------|--------------|--------------------------------|
```

The cause of this whole issue is that if the addon is not found in the config list that it defaults to outputting it's state as it's default state instead of false.
https://github.com/kubernetes/minikube/blob/c80c8852a83c4e9238faa80c161a6b4e8f5e8b67/pkg/minikube/assets/addons.go#L77-L85

**Comment by shubhbapna** [comment]
@spowelljr could you elaborate more on this case? (I haven't worked with addons before)

IMO adding a new addon would have already happened before we start minikube. I tried the same set of commands in this order and the state of addons is still correctly shown
```
# remove storage-provisioner from config.json to simulate new default addon being added
$ sed -i.bak 's/"storage-provisioner": false,//g' ~/.minikube/profiles/minikube/config.json

$ minikube start --install-addons=false

# storage-provisoner is listed as disabled even when the default is enabled
$ minikube addons list
```

**Comment by spowelljr** [comment]
If users are starting minikube for the first time it's fine, but many minikube users have their clusters existing for extended periods of time. For example the user starts minikube with v1.26.0, they upgrade their minikube binary to v1.29.0, but because the cluster was created with v1.26.0 the cluster is missing the new addon added in v1.29.0. That's what the `sed` statement simulates.

**Comment by shubhbapna** [comment]
@spowelljr I am persisting whether `install-addons` was true or false in the config.json and using that to resolve the case you were talking about. Let me know if there is better approach I missed

**Comment by spowelljr** [comment]
I don't think saving `install-addons` to the config is the right thing to do here.

We can ignore my previous case of if a new default addon is added in the future as the chance of this is likely 0. But this will still display wrong if a user started their cluster with an older version of minikube with `--install-addons=false`, updates to a binary with this change, it will still display the wrong table as right now it's only fixing it on creation not in the display logic itself.

The cause of this problem is the use and implementation of the `IsEnabled` function I mentioned in the previous comment.
https://github.com/kubernetes/minikube/blob/c80c8852a83c4e9238faa80c161a6b4e8f5e8b67/pkg/minikube/assets/addons.go#L77-L85

This also stems from the Addon struct
https://github.com/kubernetes/minikube/blob/cde517cd883d0a4b9d2fcfe44bcf6d02cacf235b/pkg/minikube/assets/addons.go#L37-L49

The `enabled` field in the Addon struct is misleading as `enabled` is actually whether it's enabled by default, not whether it's currently enabled or disabled.

This takes us to the `IsEnabled` func, if there's any entry in the config for the addon we're checking it returns it's status in the config, but if it's not in the config it returns `a.enabled`, which as just mentioned actually means enabled by default.

The fix should be changing the fallback for `IsEnabled` to return `false` if it's not found in the config instead of `a.enabled` as that will make the `IsEnabled` function work as the name intends. However, this will break starting minikube because of the following:
https://github.com/kubernetes/minikube/blob/cde517cd883d0a4b9d2fcfe44bcf6d02cacf235b/pkg/addons/addons.go#L538-L543

We rely on `a.enabled` as the backup value for this so we enable the default addons, if these were to return false no addons would be enabled by default. 

What I think we really need is a new function like `IsEnabled` called something like `IsEnabledOrDefault`. The logic for `IsEnabledOrDefault` can be an exact copy paste of `IsEnabled`, and then `IsEnabled` can be updated to return `false` if the value isn't found in the config. And then
https://github.com/kubernetes/minikube/blob/cde517cd883d0a4b9d2fcfe44bcf6d02cacf235b/pkg/addons/addons.go#L538-L543

Can we updated to use the new `IsEnabledOrDefault` so it still enables the default addons on a regular start.

**Review by spowelljr — APPROVED** [review]
Looks good, thanks for the PR!
