### PR TITLE
fix: quit minikube service when there is no available pods

### LINKED ISSUE #14592: Minikube service command should not try to open a URL for a failing pod
### What Happened?

I noticed on our examples on website does not have Arm64 support yet
and when you try to curl the Service URL or open it in the browser it fails.

the real problem was the pod was crashing but minikube still gave me a URL
```
$ kc get pods 
NAMESPACE     NAME                               READY   STATUS             RESTARTS      AGE
default       hello-minikube-5c5f5cddb9-fnvcl    0/1     CrashLoopBackOff   3 (50s ago)   97s
49:41 medya

```

### Attach the log file
```
$ kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4
deployment.apps/hello-minikube created
15:48:04 medya
$ kubectl expose deployment hello-minikube --type=NodePort --port=8080
service/hello-minikube exposed
15:48:12 medya
$ kubectl get services hello-minikube
NAME             TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
hello-minikube   NodePort   10.102.182.152   <none>        8080:31325/TCP   4s
15:48:16 medya
$ minikube service hello-minikube
|-----------|----------------|-------------|---------------------------|
| NAMESPACE |      NAME      | TARGET PORT |            URL            |
|-----------|----------------|-------------|---------------------------|
| default   | hello-minikube |        8080 | http://192.168.49.2:31325 |
|-----------|----------------|-------------|---------------------------|
🏃  Starting tunnel for service hello-minikube.
|-----------|----------------|-------------|------------------------|
| NAMESPACE |      NAME      | TARGET PORT |          URL           |
|-----------|----------------|-------------|------------------------|
| default   | hello-minikube |             | http://127.0.0.1:62242 |
|-----------|----------------|-------------|------------------------|
🎉  Opening service default/hello-minikube in default browser...
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.

```

here is the log for the curl
```
$ curl http://127.0.0.1:62242
curl: (56) Recv failure: Connection reset by peer
15:49:31 medya
$ curl -vv http://127.0.0.1:62242
*   Trying 127.0.0.1:62242...
* Connected to 127.0.0.1 (127.0.0.1) port 62242 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:62242
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

```

### Operating System

MacOs

### Driver

Docker Driver

### PR DESCRIPTION
**Pull request by ComradeProgrammer**
fixes #14592 
When we try to run a deployment who is using a container which crashes immediately(thus no pods will be available), and then try to use minikube service to open a tunnel for it

**Before:** 
```
minikube service hello-minikube
|-----------|----------------|-------------|---------------------------|
| NAMESPACE |      NAME      | TARGET PORT |            URL            |
|-----------|----------------|-------------|---------------------------|
| default   | hello-minikube |        8080 | http://192.168.49.2:31325 |
|-----------|----------------|-------------|---------------------------|
🏃  Starting tunnel for service hello-minikube.
|-----------|----------------|-------------|------------------------|
| NAMESPACE |      NAME      | TARGET PORT |          URL           |
|-----------|----------------|-------------|------------------------|
| default   | hello-minikube |             | http://127.0.0.1:62242 |
|-----------|----------------|-------------|------------------------|
🎉  Opening service default/hello-minikube in default browser...
```
service will be exposed, although it cannot be visited.

**After**

Now if the service has no running pods, output will be like this
```
wsl@win10pc:~/workspace/minikube-fork/out$ ./minikube service bad-node
|-----------|----------|-------------|---------------------------|
| NAMESPACE |   NAME   | TARGET PORT |            URL            |
|-----------|----------|-------------|---------------------------|
| default   | bad-node |        8080 | http://192.168.49.2:32262 |
|-----------|----------|-------------|---------------------------|

❌  Exiting due to SVC_TUNNEL_START: no valid pod for service bad-node found
```

### CODE REVIEW

File: pkg/minikube/service/service.go [hunk 1]
```diff
@@ -378,3 +378,26 @@ func DeleteSecret(cname string, namespace, name string) error {
...
+	if svc.Spec.Type != core.ServiceTypeNodePort && svc.Spec.Type != core.ServiceTypeLoadBalancer {
+		return nil
+	}
+	pods, err := clientset.Pods(namespace).List(context.Background(), meta.ListOptions{
+		LabelSelector: labels.Set(svc.Spec.Selector).AsSelector().String(),
+	})
+	if err != nil {
+		return err
+	}
+
```
Comment (guresonur) [inline pkg/minikube/service/service.go:396]: When there is a deployment has created these `Pods`, `restartPolicy` of the `Deployment` set to `Always` so the `pod.Status.Phase` would return `Running`, even in the case of there is a problem with `Pod` and it would still give URL and try to open web-browser.

So maybe checking the `ContainerStatuses` and readiness state might be helpful?

```
for _, containerStatus := range pod.Status.ContainerStatuses {
			if containerStatus.Ready == true {
				return nil
			}
		}
```

**Review by guresonur — CHANGES_REQUESTED** [review]

**Review by guresonur — CHANGES_REQUESTED** [review]
@ComradeProgrammer  
When there is a deployment has created these `Pods`, `restartPolicy` of the `Deployment` set to `Always` so the `pod.Status.Phase` would return `Running`, even in the case of there is a problem with `Pod` and it would still give URL and try to open web-browser.

So maybe checking the `ContainerStatuses` and readiness state might be helpful?

```
for _, containerStatus := range pod.Status.ContainerStatuses {
			if containerStatus.Ready == true {
				return nil
			}
		}
```

File: cmd/minikube/cmd/service.go [hunk 2]
```diff
@@ -187,6 +187,11 @@ func startKicServiceTunnel(services service.URLs, configName, driverName string)
 		sshPort := strconv.Itoa(port)
 		sshKey := filepath.Join(localpath.MiniPath(), "machines", configName, "id_rsa")
 
+		//check whether all pods of this service is crashed
```
Comment (spowelljr) [inline cmd/minikube/cmd/service.go:190]:
```suggestion
		// check whether all pods of this service is crashed
```

**Review by spowelljr — CHANGES_REQUESTED** [review]

**Review by medyagh — COMMENTED** [review]
thanks for the PR, do u mind putting the before/after this PR in the description ?

**Comment by ComradeProgrammer** [comment]
> thanks for the PR, do u mind putting the before/after this PR in the description ?
before/after has been added

File: cmd/minikube/cmd/service.go [hunk 3]
```diff
@@ -187,6 +187,11 @@ func startKicServiceTunnel(services service.URLs, configName, driverName string)
 		sshPort := strconv.Itoa(port)
 		sshKey := filepath.Join(localpath.MiniPath(), "machines", configName, "id_rsa")
 
+		// check whether all pods of this service is crashed
```
Comment (Aut0R3V) [inline cmd/minikube/cmd/service.go:190]: Hey, I think @spowelljr suggested some changes. Are you still working on this? Thanks!

Comment (ComradeProgrammer) [reply cmd/minikube/cmd/service.go:190]: Yes, I am still working on this, but which changes? I thought all changes suggested by @spowelljr has been accepted, and is there anything else I should do? Did I miss anything?

Comment (ComradeProgrammer) [reply cmd/minikube/cmd/service.go:190]: Sorry I didn't understand, could you please clearly tell me what changes should I do next? I did't see anything changes requested are not accepted

**Review by spowelljr — CHANGES_REQUESTED** [review]
Could a test be added to ensure this is working

**Comment by ComradeProgrammer** [comment]
> Could a test be added to ensure this is working

Thanks for the review, a test has been added, and I've run locally. it works

**Comment by spowelljr** [comment]
@ComradeProgrammer It looks like the tests are failing

**Comment by ComradeProgrammer** [comment]
> @ComradeProgrammer It looks like the tests are failing

I think this time it will work.

Sorry, silly bug. I forgot to write code to start minikube at the beginning of the test. Last time when I ran test locally before, I had a running cluster, that's why nothing wrong happened locally but test failed on the runner.

**Comment by spowelljr** [comment]
@ComradeProgrammer Could you run `make generate-docs` to add the test to the documentation, thanks

**Comment by ComradeProgrammer** [comment]
> @ComradeProgrammer Could you run `make generate-docs` to add the test to the documentation, thanks

added, please trigger the test again. Thanks!

**Comment by ComradeProgrammer** [comment]
Sorry for causing so many inconveniences. Errors in tests on linux platform should have been fixed, please trigger the test. Thanks

**Comment by ComradeProgrammer** [comment]
Well I think all related tests can be passed now, is there any other suggestion?

**Comment by ComradeProgrammer** [comment]
Anything I need to do next?
@medyagh  @spowelljr  @afbjorklund

**Review by spowelljr — CHANGES_REQUESTED** [review]

**Comment by ComradeProgrammer** [comment]
(anything I need to do next?

File: test/integration/status_test.go [hunk 4]
```diff
@@ -99,3 +101,39 @@ func verifyClusterState(t *testing.T, contents []byte) {
 		}
 	}
 }
+
+// TestInvalidService makes sure minikube will not start a tunnel for a unavailable service who has no running pods
+func TestInvalidService(t *testing.T) {
```
Comment (medyagh) [inline test/integration/status_test.go:106]: instead of creating a whole new minikube cluster for this test, we can add a subtest in functioanl test

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/service/service.go [hunk 5]
```diff
@@ -378,3 +378,27 @@ func DeleteSecret(cname string, namespace, name string) error {
 
 	return nil
 }
+
+func CheckServicePods(clientset typed_core.CoreV1Interface, svcName, namespace string) error {
```
Comment (medyagh) [inline pkg/minikube/service/service.go:382]: add comment to all exported funcs

File: pkg/minikube/service/service.go [hunk 6]
```diff
@@ -378,3 +378,27 @@ func DeleteSecret(cname string, namespace, name string) error {
...
+	if err != nil {
+		return errors.Wrap(err, "Fail to get service from kunernetes")
+	}
+	if svc.Spec.Type != core.ServiceTypeNodePort && svc.Spec.Type != core.ServiceTypeLoadBalancer {
+		return nil
+	}
+	pods, err := clientset.Pods(namespace).List(context.Background(), meta.ListOptions{
+		LabelSelector: labels.Set(svc.Spec.Selector).AsSelector().String(),
+	})
+	if err != nil {
```
Comment (medyagh) [inline pkg/minikube/service/service.go:393]: make wrap messages shorter

Comment (medyagh) [reply pkg/minikube/service/service.go:393]: "Fail to get pods associated with this service from kunernetes"
-->
"List Pods"

File: pkg/minikube/service/service.go [hunk 7]
```diff
@@ -378,3 +378,27 @@ func DeleteSecret(cname string, namespace, name string) error {
 
 	return nil
 }
+
+func CheckServicePods(clientset typed_core.CoreV1Interface, svcName, namespace string) error {
+	svc, err := clientset.Services(namespace).Get(context.Background(), svcName, meta.GetOptions{})
+	if err != nil {
+		return errors.Wrap(err, "Fail to get service from kunernetes")
```
Comment (medyagh) [inline pkg/minikube/service/service.go:385]: get service

File: pkg/minikube/reason/reason.go [hunk 8]
```diff
@@ -410,6 +410,8 @@ var (
 	SvcCheckTimeout = Kind{ID: "SVC_CHECK_TIMEOUT", ExitCode: ExSvcTimeout}
 	// minikube was unable to access a service
 	SvcTimeout = Kind{ID: "SVC_TIMEOUT", ExitCode: ExSvcTimeout}
+	// minikube finds that the service has not available pods
+	SvcUnreachable = Kind{ID: "SVC_UNREACHABLE", ExitCode: ExSvcError}
```
Comment (medyagh) [inline pkg/minikube/reason/reason.go:414]: ExSvcError --> ExSvcNotFound

File: cmd/minikube/cmd/service.go [hunk 9]
```diff
@@ -148,6 +148,14 @@ You may select another namespace by using 'minikube service {{.service}} -n <nam
 					out.String(fmt.Sprintf("%s\n", serviceURLs))
 				}
 			}
+			// check whether all pods of this service is crashed
+			clientset, err := kapi.Client(cname)
+			if err != nil {
+				exit.Error(reason.InternalKubernetesClient, "error creating clientset", err)
```
Comment (medyagh) [inline cmd/minikube/cmd/service.go:154]: Failed to acquire Kubernetes client

File: pkg/minikube/service/service.go [hunk 10]
```diff
@@ -378,3 +378,27 @@ func DeleteSecret(cname string, namespace, name string) error {
...
+	}
+	if svc.Spec.Type != core.ServiceTypeNodePort && svc.Spec.Type != core.ServiceTypeLoadBalancer {
```
Comment (medyagh) [inline pkg/minikube/service/service.go:387]: add a comment and explain why !

**Review by medyagh — CHANGES_REQUESTED** [review]

File: cmd/minikube/cmd/service.go [hunk 11]
```diff
@@ -148,6 +148,14 @@ You may select another namespace by using 'minikube service {{.service}} -n <nam
 					out.String(fmt.Sprintf("%s\n", serviceURLs))
 				}
 			}
+			// check whether all pods of this service is crashed
+			clientset, err := kapi.Client(cname)
+			if err != nil {
+				exit.Error(reason.InternalKubernetesClient, "Failed to acquire Kubernetes client", err)
+			}
```
Comment (spowelljr) [inline cmd/minikube/cmd/service.go:155]: If you look at the other functions in `pkg/minikube/service/service.go` they all create the client within the file using `client, err := K8s.GetCoreClient(cname)` so I think it makes sense to reuse the func in that file and pass `cname` into `service.CheckServicePods`.

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: cmd/minikube/cmd/service.go (hunk 11 above)
Comment (ComradeProgrammer) [reply cmd/minikube/cmd/service.go:155]: Changed

File: cmd/minikube/cmd/service.go [hunk 12]
```diff
@@ -148,6 +148,10 @@ You may select another namespace by using 'minikube service {{.service}} -n <nam
 					out.String(fmt.Sprintf("%s\n", serviceURLs))
 				}
 			}
+			// check whether all pods of this service is crashed
+			if err := service.CheckServicePods(cname, svc.Name, namespace); err != nil {
+				exit.Error(reason.SvcUnreachable, "error checking service", err)
```
Comment (spowelljr) [inline cmd/minikube/cmd/service.go:153]: This is a little misleading, if we successfully check the pods but they're not running we still return an error, which will output `error checking service`. But we successfully checked the service, it's just that the pods are not running. Something like `service not available` might be better as it will encapsulate the true meaning

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: test/integration/functional_test.go [hunk 13]
```diff
@@ -2308,3 +2309,27 @@ func validateLicenseCmd(ctx context.Context, t *testing.T, _ string) {
...
+			t.Fatalf("clean up %s failed: %v", rr.Command(), err)
+		}
+	}()
+	if err != nil {
+		t.Fatalf("%s failed: %v", rrApply.Command(), err)
+	}
+	time.Sleep(3 * time.Second)
+
+	// try to expose a service, this action is supposed to fail
+	rrService, err := Run(t, exec.CommandContext(context.TODO(), Target(), "service", "invalid-svc", "-p", profile))
```
Comment (spowelljr) [inline test/integration/functional_test.go:2331]:
```suggestion
	rrService, err := Run(t, exec.CommandContext(ctx, Target(), "service", "invalid-svc", "-p", profile))
```

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: pkg/minikube/reason/reason.go [hunk 14]
```diff
@@ -423,6 +423,8 @@ var (
 	SvcCheckTimeout = Kind{ID: "SVC_CHECK_TIMEOUT", ExitCode: ExSvcTimeout}
 	// minikube was unable to access a service
 	SvcTimeout = Kind{ID: "SVC_TIMEOUT", ExitCode: ExSvcTimeout}
+	// minikube finds that the service has not available pods
```
Comment (spowelljr) [inline pkg/minikube/reason/reason.go:426]:
```suggestion
	// minikube found that the service has no available pods
```

File: test/integration/functional_test.go [hunk 15]
```diff
@@ -2308,3 +2309,27 @@ func validateLicenseCmd(ctx context.Context, t *testing.T, _ string) {
...
+	defer func() {
+		// Cleanup test configurations in advance of future tests
+		rr, err := Run(t, exec.CommandContext(ctx, "kubectl", "--context", profile, "delete", "-f", filepath.Join(*testdataDir, "invalidsvc.yaml")))
+		if err != nil {
+			t.Fatalf("clean up %s failed: %v", rr.Command(), err)
+		}
+	}()
+	if err != nil {
+		t.Fatalf("%s failed: %v", rrApply.Command(), err)
+	}
```
Comment (spowelljr) [inline test/integration/functional_test.go:2327]:
```suggestion
	rrApply, err := Run(t, exec.CommandContext(ctx, "kubectl", "--context", profile, "apply", "-f", filepath.Join(*testdataDir, "invalidsvc.yaml")))
	if err != nil {
		t.Fatalf("%s failed: %v", rrApply.Command(), err)
	}
	defer func() {
		// Cleanup test configurations in advance of future tests
		rr, err := Run(t, exec.CommandContext(ctx, "kubectl", "--context", profile, "delete", "-f", filepath.Join(*testdataDir, "invalidsvc.yaml")))
		if err != nil {
			t.Fatalf("clean up %s failed: %v", rr.Command(), err)
		}
	}()
```

Check for error before defer because if apply failed, delete is not needed

File: cmd/minikube/cmd/service.go [hunk 16]
```diff
@@ -148,6 +148,10 @@ You may select another namespace by using 'minikube service {{.service}} -n <nam
 					out.String(fmt.Sprintf("%s\n", serviceURLs))
 				}
 			}
+			// check whether all pods of this service is crashed
```
Comment (spowelljr) [inline cmd/minikube/cmd/service.go:151]:
```suggestion
			// check whether there are running pods for this service
```
Pods could be pending and this could fail, so update comment to clarify this

**Review by spowelljr — CHANGES_REQUESTED** [review]
