### PR TITLE
vfkit: Bump to Preferred driver on macOs

### LINKED ISSUE #20807: minikube "auto select" driver fails to select vfkit when
on a fresh machine macos I only had vkfit installed and minikube auto driver select failed to choose it,
so when there is no other option like qemu or docker or anything else, why minikube didnt Pick Vfkit ??? thats a bug
``` 
medya-mac:~ medya$ minikube start
😄  minikube v1.35.0 on Darwin 15.5 (arm64)
👎  Unable to pick a default driver. Here is what was considered, in preference order:
💡  Alternatively you could install one of these drivers:
    ▪ docker: Not installed: exec: "docker": executable file not found in $PATH
    ▪ hyperkit: Not installed: exec: "hyperkit": executable file not found in $PATH
    ▪ parallels: Not installed: exec: "prlctl": executable file not found in $PATH
    ▪ qemu2: Not installed: exec: "qemu-system-aarch64": executable file not found in $PATH
    ▪ virtualbox: Not installed: unable to find VBoxManage in $PATH
    ▪ podman: Not installed: exec: "podman": executable file not found in $PATH

❌  Exiting due to DRV_NOT_DETECTED: No possible driver was detected. Try specifying --driver, or see https://minikube.sigs.k8s.io/docs/start/
```

however when I specified it manually it worked

```
medya-mac:~ medya$ minikube start -d vfkit
😄  minikube v1.35.0 on Darwin 15.5 (arm64)
✨  Using the vfkit (experimental) driver based on user configuration
💿  Downloading VM boot image ...
    > minikube-v1.35.0-arm64.iso....:  65 B / 65 B [---------] 100.00% ? p/s 0s
    > minikube-v1.35.0-arm64.iso:  393.15 MiB / 393.15 MiB  100.00% 26.78 MiB p
👍  Starting "minikube" primary control-plane node in "minikube" cluster
💾  Downloading Kubernetes v1.32.0 preload ...
    > preloaded-images-k8s-v18-v1...:  314.92 MiB / 314.92 MiB  100.00% 29.13 M
🔥  Creating vfkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.32.0 on Docker 27.4.0 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

### PR DESCRIPTION
**Pull request by nirs**
vfkit is using the native virtualization framework, provides good best performance and all the features needed by minikube. It is also well maintained and used by other projects like podman.

This fixes the automatic driver selection. When we start minikube on a system with both vfkit and qemu, vfkit is selected:

    % minikube start
    😄  minikube v1.35.0 on Darwin 15.5 (arm64)
    ✨  Automatically selected the vfkit driver. Other choices: qemu2, ssh, podman (experimental)
    👍  Starting "minikube" primary control-plane node in "minikube" cluster
    🔥  Creating vfkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
    🐳  Preparing Kubernetes v1.33.1 on Docker 28.0.4 ...
        ▪ Generating certificates and keys ...
        ▪ Booting up control plane ...
        ▪ Configuring RBAC rules ...
    🔗  Configuring bridge CNI (Container Networking Interface) ...
    🔎  Verifying Kubernetes components...
        ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
    🌟  Enabled addons: default-storageclass, storage-provisioner
    🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

Fixes #20807

### CODE REVIEW

File: pkg/minikube/registry/drvs/vfkit/vfkit.go [hunk 1]
```diff
@@ -41,13 +42,17 @@ const (
 )
 
 func init() {
+	priority := registry.Unknown
+	if runtime.GOOS == "darwin" {
+		priority = registry.Preferred
```
Comment (medyagh) [inline pkg/minikube/registry/drvs/vfkit/vfkit.go:47]: I think is better than preffered registry.Default so it be the same level as qemu,

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/registry/drvs/vfkit/vfkit.go [hunk 2]
```diff
@@ -104,7 +109,7 @@ func configure(cfg config.ClusterConfig, n config.Node) (interface{}, error) {
 func status() registry.State {
 	_, err := exec.LookPath("vfkit")
 	if err != nil {
-		return registry.State{Error: err, Fix: "Run 'brew tap cfergeau/crc && brew install vfkit'", Doc: docURL}
+		return registry.State{Error: err, Fix: "Run 'brew install vfkit'", Doc: docURL}
```
Comment (cfergeau) [inline pkg/minikube/registry/drvs/vfkit/vfkit.go:112]: :+1: 
vfkit in cfergeau/crc will no longer be updated now that it’s in the main repo. I should remove it from this personal tap.

**Review by cfergeau — COMMENTED** [review]
Looks good to me!

File: pkg/minikube/registry/drvs/vfkit/vfkit.go (hunk 2 above)
Comment (medyagh) [reply pkg/minikube/registry/drvs/vfkit/vfkit.go:112]: sure

**Comment by cfergeau** [comment]
> Not long ago starting qemu on M4 was crashing and it took few month until they fixed the issue

For the record, this is not an isolated event, there was a similar problem around the time podman switched to vfkit, qemu hang on startup which took several weeks/months to be fixed.

> Unless we have some important features that does not work on vfkit and work on qemu. I'm not a ware of any.

vfkit has support for virtiofs and rosetta (important features off the top of my head), and the fact that Apple maintains most of the virtualization code is both a plus and a minus, but in my opinion mostly a plus. It overall works well, we had minimal issues over the years, but when there are issues, we are dependent on Apple to fix them, https://github.com/containers/podman/issues/25121 is a recent example of this. This bug only impacted some Intel macs, and is fixed with macOS 15.5
One big missing thing, but I’m not sure qemu has this either, is gpu acceleration support, which I guess could be useful to minikube (?). We’ll know at WWDC in a few weeks if they are going to add this to macOS 16 :)

**Comment by nirs** [comment]
> One big missing thing, but I’m not sure qemu has this either, is gpu acceleration support, which I guess could be useful to minikube (?). We’ll know at WWDC in a few weeks if they are going to add this to macOS 16 :)

I started to work on #20803 for GPU acceleration.

**Comment by afbjorklund** [comment]
The main feature of
QEMU is that it is available on all platforms, something that was previously done by VirtualBox.

Having to split minikube into different hypervisors and different runtimes (not just Docker) complicated things **a lot**.

File: pkg/minikube/registry/drvs/vfkit/vfkit.go (hunk 2 above)
Comment (afbjorklund) [reply pkg/minikube/registry/drvs/vfkit/vfkit.go:112]: From https://github.com/crc-org/vfkit/commit/1228143e04eee309db63d99da03cedcf54cc3ed3
