### PR TITLE
Default to best-available local hypervisor rather than VirtualBox

### LINKED ISSUE #4614: Update hypervisor default from "virtualbox" to best-available
**The exact command to reproduce the issue**: minikube start

**The full output of the command that failed**:

😄  minikube v1.2.0 on linux (amd64)
💿  Downloading Minikube ISO ...
 129.33 MB / 129.33 MB [============================================] 100.00% 0s
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0626 20:40:20.432969   26803 start.go:559] StartHost: create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

💣  Unable to start VM
❌  Error:         [VBOX_NOT_FOUND] create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
💡  Advice:        Install VirtualBox, ensure that VBoxManage is executable and in path, or select an alternative value for --vm-driver
📘  Documentation: https://www.virtualbox.org/wiki/Downloads
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3784
    ▪ https://github.com/kubernetes/minikube/issues/3776

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:

💣  api load: filestore: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The operating system version**: Ubuntu 19.04

**Comments**: Documentation on README says: Requires either the kvm2 driver (recommended), or VirtualBox. I have kvm2 installed.. so it shouldn't give an error. I think even if I didn't have kvm, it should try driver=none by default instead of giving error.

### PR DESCRIPTION
**Pull request by tstromberg**
Fixes #4614

Output change for auto-selection:

```
😄  minikube v1.5.0-beta.0 on Darwin 10.14.6
✨  Automatically selected the 'virtualbox' driver (alternates: [vmwarefusion])
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
```

Warning-only output change for when an unhealthy driver is specified:

```
😄  minikube v1.5.0-beta.0 on Darwin 10.14.6

⚠️  'hyperkit' driver reported a possible issue: exec: "hyperkitz": executable file not found in $PATH
💡  Suggestion: Run 'brew install hyperkit'
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperkit/
```

Output if no driver was found usable:

```
😄  minikube v1.5.0-beta.0 on Darwin 10.14.6
💣  Unable to determine a default driver to use. Try specifying --vm-driver, or visiting https://minikube.sigs.k8s.io/docs/start/
```

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by sharifelgamal** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
Build is failing due to:

```
12:19:55 # k8s.io/minikube/pkg/drivers/kvm
12:19:55 pkg/drivers/kvm/domain.go:110:32: undefined: libvirt.Domain
12:19:55 pkg/drivers/kvm/domain.go:110:49: undefined: libvirt.Connect
12:19:55 pkg/drivers/kvm/domain.go:124:44: undefined: libvirt.Connect
12:19:55 pkg/drivers/kvm/domain.go:133:23: undefined: libvirt.Domain
12:19:55 pkg/drivers/kvm/domain.go:133:45: undefined: libvirt.Connect
12:19:55 pkg/drivers/kvm/domain.go:144:35: undefined: libvirt.Domain
12:19:55 pkg/drivers/kvm/kvm.go:160:23: undefined: libvirt.DomainState
12:19:55 pkg/drivers/kvm/kvm.go:455:44: undefined: libvirt.Domain
12:19:55 pkg/drivers/kvm/kvm.go:470:39: undefined: libvirt.Connect
12:19:55 pkg/drivers/kvm/kvm.go:470:61: undefined: libvirt.Domain
12:19:55 pkg/drivers/kvm/kvm.go:470:61: too many errors
12:20:27 # k8s.io/minikube/pkg/minikube/registry/drvs/hyperv
12:20:27 pkg/minikube/registry/drvs/hyperv/hyperv.go:34:3: cannot use configure (type func(config.MachineConfig) *hyperv.Driver) as type registry.Configurator in field value
12:20:27 pkg/minikube/registry/drvs/hyperv/hyperv.go:35:3: unknown field 'InstallStatus' in struct literal of type registry.DriverDef
12:20:27 pkg/minikube/registry/drvs/hyperv/hyperv.go:52:15: registry.Status is not a type
12:20:27 pkg/minikube/registry/drvs/hyperv/hyperv.go:53:15: undefined: exec
12:20:27 pkg/minikube/registry/drvs/hyperv/hyperv.go:55:25: registry.Status is not a type
12:20:27 pkg/minikube/registry/drvs/hyperv/hyperv.go:58:8: undefined: exec
12:20:27 pkg/minikube/registry/drvs/hyperv/hyperv.go:60:25: registry.Status is not a type
12:20:27 pkg/minikube/registry/drvs/hyperv/hyperv.go:62:24: registry.Status is not a type
12:20:46 make: *** [Makefile:161: out/minikube-linux-arm64] Error 2
12:20:48 make: *** [Makefile:161: out/minikube-linux-amd64] Error 2
12:20:49 make: *** [Makefile:161: out/minikube-windows-amd64] Error 2
12:20:52 Makefile:159: recipe for target 'out/minikube-linux-arm64' failed
12:20:52 make: *** [out/minikube-linux-arm64] Error 2
12:20:52 make: *** Waiting for unfinished jobs....
12:20:53 Makefile:159: recipe for target 'out/minikube-windows-amd64' failed
12:20:53 make: *** [out/minikube-windows-amd64] Error 2
12:20:54 Makefile:159: recipe for target 'out/minikube-linux-amd64' failed
12:20:54 make: *** [out/minikube-linux-amd64] Error 2
```

File: hack/jenkins/osx_integration_tests_virtualbox.sh [hunk 1]
```diff
@@ -30,6 +30,8 @@ VM_DRIVER="virtualbox"
 JOB_NAME="VirtualBox_macOS"
 EXTRA_ARGS="--bootstrapper=kubeadm"
 PARALLEL_COUNT=3
+EXPECTED_DEFAULT_DRIVER="hyperkit"
```
[the remark this answers is not in the document]
Comment (tstromberg) [reply hack/jenkins/osx_integration_tests_virtualbox.sh]: If hyperkit is installed on the machine, this will be hyperkit as it takes precedence. I assume our VirtualBox mac also has hyperkit installed.

File: pkg/minikube/registry/registry.go [hunk 2]
```diff
@@ -21,18 +21,21 @@ import (
...
-
-	// ErrDriverNotFound is the error returned when driver of a given name does
-	// not exist in registry
-	ErrDriverNotFound = errors.New("registry: driver not found")
+// Priority is how we determine what driver to default to
+type Priority int
+
+const (
+	Unknown Priority = iota
+	Discouraged
```
[the remark this answers is not in the document]
Comment (tstromberg) [reply pkg/minikube/registry/registry.go]: Yes, I think so. For instance, I'm OK with defaulting to vmwarefusion, which is deprecated, but not OK with defaulting to 'none' (yet).

File: pkg/minikube/registry/registry.go [hunk 3]
```diff
@@ -47,75 +50,76 @@ type Registry interface {
...
 
-// DriverFactory is a function that loads a byte stream and creates a driver.
-type DriverFactory func() drivers.Driver
+// StatusChecker checks if a driver is available, offering a
+type StatusChecker func() State
+
+// State is the current state of the driver and its dependencies
+type State struct {
+	Installed bool
+	Healthy   bool
```
[the remark this answers is not in the document]
Comment (tstromberg) [reply pkg/minikube/registry/registry.go]: Yes - this is intentional. If a driver is healthy, I want it to be explicitly stated.

File: test/integration/a_serial_test.go [hunk 4]
```diff
@@ -73,17 +74,50 @@ func TestDownloadAndDeleteAll(t *testing.T) {
 						t.Errorf("expected the file for binary exist at %q but got error %v", fp, err)
 					}
 				}
+
+				// Checking if the default driver meets expectations
+				if ExpectedDefaultDriver() == "" {
+					t.Logf("--expected-default-driver=%q, continuing", ExpectedDefaultDriver())
```
[the remark this answers is not in the document]
Comment (tstromberg) [reply test/integration/a_serial_test.go]: Good point. I've moved this to another subtest "ExpectedDefaultDriver" so that I could have clearer behavior and messaging.  PTAL.

File: pkg/minikube/registry/registry.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (sharifelgamal) [reply pkg/minikube/registry/registry.go]: Makes sense.

File: hack/jenkins/osx_integration_tests_virtualbox.sh (hunk 1 above)
[the remark this answers is not in the document]
Comment (sharifelgamal) [reply hack/jenkins/osx_integration_tests_virtualbox.sh]: good point!

File: test/integration/a_serial_test.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (sharifelgamal) [reply test/integration/a_serial_test.go]: yeah, that makes more sense to me

File: cmd/minikube/cmd/start.go [hunk 5]
```diff
@@ -194,7 +195,7 @@ func initKubernetesFlags() {
 
 // initDriverFlags inits the commandline flags for vm drivers
 func initDriverFlags() {
-	startCmd.Flags().String("vm-driver", "", fmt.Sprintf("Driver is one of: %v (defaults to %s)", driver.SupportedDrivers(), driver.Default()))
+	startCmd.Flags().String("vm-driver", "", fmt.Sprintf("Driver is one of: %v (defaults to auto-detect)", driver.SupportedDrivers()))
```
Comment (medyagh) [inline cmd/minikube/cmd/start.go]: just a random thought:
if auto-detect is not expensive, maybe add it to the help message. so the user doesnt have to guess what the auto-detect comes up with ?

File: hack/jenkins/osx_integration_tests_hyperkit.sh [hunk 6]
```diff
@@ -32,6 +32,8 @@ JOB_NAME="HyperKit_macOS"
 EXTRA_ARGS="--bootstrapper=kubeadm"
 EXTRA_START_ARGS=""
 PARALLEL_COUNT=3
+EXPECTED_DEFAULT_DRIVER="hyperkit"
+
```
Comment (medyagh) [inline hack/jenkins/osx_integration_tests_hyperkit.sh]: no need for extra line

File: pkg/minikube/registry/drvs/hyperv/hyperv.go [hunk 7]
```diff
@@ -19,35 +19,57 @@ limitations under the License.
...
+		Config:   configure,
+		Status:   status,
+		Priority: registry.Preferred,
+	}); err != nil {
+		panic(fmt.Sprintf("register: %v", err))
+	}
 }
 
-func createHypervHost(config cfg.MachineConfig) interface{} {
+func configure(config cfg.MachineConfig) interface{} {
```
Comment (medyagh) [inline pkg/minikube/registry/drvs/hyperv/hyperv.go]: I would add a comment for this configure,, does what does it really do ?

and also maybe I would change the config var name to somethign shorter ?

File: pkg/minikube/registry/drvs/kvm2/kvm2.go [hunk 8]
```diff
@@ -78,3 +85,33 @@ func createKVM2Host(mc config.MachineConfig) interface{} {
 		ConnectionURI:  mc.KVMQemuURI,
 	}
 }
+
+func status() registry.State {
```
Comment (medyagh) [inline pkg/minikube/registry/drvs/kvm2/kvm2.go]: I would add a comment for status or choose a better name ?
does it check status of hyperkit or does it check if the binary is available? or does it check if it is out of date version?

**Comment by medyagh** [comment]
this is a solid PR ! I am so grateful that you are doing this ! it will make me as a user of minikube MUCH happier,

output looks good
```
$ ./out/minikube start
😄  minikube v1.5.0-beta.0 on Debian rodete
🔥  Creating kvm2 VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
```

I am wondering if we should have some sign in the console that it is auto detected ....it doesnt have to be big. maybe a * or (auto-detect) ?

File: cmd/minikube/cmd/start.go (hunk 5 above)
Comment (medyagh) [reply cmd/minikube/cmd/start.go]: but thinking again, maybe not !

**Comment by tstromberg** [comment]
> this is a solid PR ! I am so grateful that you are doing this ! it will make me as a user of minikube MUCH happier,
> 
> output looks good
> 
> ```
> $ ./out/minikube start
> 😄  minikube v1.5.0-beta.0 on Debian rodete
> 🔥  Creating kvm2 VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
> ```
> 
> I am wondering if we should have some sign in the console that it is auto detected ....it doesnt have to be big. maybe a * or (auto-detect) ?

Done.

File: cmd/minikube/cmd/start.go [hunk 9]
```diff
@@ -549,6 +549,8 @@ func selectDriver(oldConfig *cfg.Config) string {
 		pick, alts := driver.Choose(options)
 		if len(options) > 1 {
 			out.T(out.Sparkle, `Automatically selected the '{{.driver}}' driver (alternates: {{.alternates}})`, out.V{"driver": pick.Name, "alternates": alts})
+		} else {
+			out.T(out.Sparkle, `Automatically selected the '{{.driver}}' driver`, out.V{"driver": pick.Name})
```
Comment (medyagh) [inline cmd/minikube/cmd/start.go]: Maybe put the version of Virsh or Hyperkit.... would help a lot in debugging ?

Comment (tstromberg) [reply cmd/minikube/cmd/start.go]: Adding driver versions would be useful, but also a fair bit of work, so I would rather not include it in this already large PR.

Comment (medyagh) [reply cmd/minikube/cmd/start.go]: sounds good.

Comment (gbraad) [reply cmd/minikube/cmd/start.go]: This can also be done as part of hte drivers themselves, as libmachine allows to log these values... this way using the verbose/debug logs for this would collect them. This is also what we do for CRC.
