### PR TITLE
minikube update-context: Fix nil pointer dereference

### LINKED ISSUE #8988: minikube update-context: invalid memory address or nil pointer dereference
`minikube update-context` command occurs the following error:
```
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x523891f]
 
 goroutine 1 [running]:
 k8s.io/minikube/pkg/minikube/kubeconfig.UpdateEndpoint(0x57bad36, 0x8, 0xc000bd9410, 0xe, 0x20fb, 0xc00013f560, 0x19, 0x5b32f40, 0xc000bdd560, 0xc000bd9410)
         /private/tmp/minikube-20200812-94589-17snemo/pkg/minikube/kubeconfig/kubeconfig.go:143 +0x2af
 k8s.io/minikube/cmd/minikube/cmd.glob..func31(0x6927200, 0x696cf80, 0x0, 0x0)
         /private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/cmd/update-context.go:37 +0x10a
 github.com/spf13/cobra.(*Command).execute(0x6927200, 0x696cf80, 0x0, 0x0, 0x6927200, 0x696cf80)
         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
 github.com/spf13/cobra.(*Command).ExecuteC(0x6925280, 0x0, 0x1, 0xc00024fbe0)
         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
 github.com/spf13/cobra.(*Command).Execute(...)
         /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
 k8s.io/minikube/cmd/minikube/cmd.Execute()
         /private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/cmd/root.go:106 +0x72c
 main.main()
         /private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/main.go:71 +0x11f
```

**Steps to reproduce the issue:** 

```
$ minikube start --vm-driver virtualbox
😄  minikube v1.12.3 on Darwin 10.15.5
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.12 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
$ cat <<EOL > kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/la-croix/apiserver.crt
    server: 192.168.1.1:8080
  name: la-croix
contexts:
- context:
    cluster: la-croix
    user: la-croix
  name: la-croix
current-context: la-croix
kind: Config
preferences: {}
users:
- name: la-croix
  user:
    client-certificate: /home/la-croix/apiserver.crt
    client-key: /home/la-croix/apiserver.key
EOL
$ KUBECONFIG=./kubeconfig minikube update-context
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x523891f]

goroutine 1 [running]:
k8s.io/minikube/pkg/minikube/kubeconfig.UpdateEndpoint(0x57bad36, 0x8, 0xc000c4c3a0, 0xe, 0x20fb, 0xc00003e22b, 0xc, 0x5b32f40, 0xc0003d2000, 0xc000c4c3a0)
        /private/tmp/minikube-20200812-94589-17snemo/pkg/minikube/kubeconfig/kubeconfig.go:143 +0x2af
k8s.io/minikube/cmd/minikube/cmd.glob..func31(0x6927200, 0x696cf80, 0x0, 0x0)
        /private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/cmd/update-context.go:37 +0x10a
github.com/spf13/cobra.(*Command).execute(0x6927200, 0x696cf80, 0x0, 0x0, 0x6927200, 0x696cf80)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x6925280, 0x0, 0x1, 0xc00053a0c0)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/cmd/root.go:106 +0x72c
main.main()
        /private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/main.go:71 +0x11f
```

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

### PR DESCRIPTION
**Pull request by superbrothers**
Fixes #8988

### CODE REVIEW

File: pkg/minikube/kubeconfig/kubeconfig.go [hunk 1]
```diff
@@ -121,26 +119,11 @@ func UpdateEndpoint(contextName string, hostname string, port int, confpath stri
 		return false, errors.Wrap(err, "read")
 	}
 
-	address := "https://" + hostname + ":" + strconv.Itoa(port)
-
-	// if the kubeconfig is missed, create new one
```
Comment (tstromberg) [inline pkg/minikube/kubeconfig/kubeconfig.go:126]: I think this might remove support for adding the context when it's been removed from `$HOME/.kube/config`

Do you mind checking that this works with your PR:

`minikube start`
`mv $HOME/.kube/config{,.bak}`
`minikube update-context`
`kubectl get po -A`
`mv $HOME/.kube/config{.bak,}`

Comment (superbrothers) [reply pkg/minikube/kubeconfig/kubeconfig.go:126]: Yes, This PR removes support for adding the context when it's been removed from `$HOME/.kube/config`.

```
$ git show --quiet
commit c41a5f19b778ea6fb57a063022c9caceb11fe8ed (HEAD -> fix-nil-pointer-dereference, superbrothers/fix-nil-pointer-dereference)
Author: Kazuki Suda <kazuki.suda@gmail.com>
Date:   Thu Aug 13 12:19:42 2020 +0900

    minikube upate-cotext: Fix nil pointer dereference
$ out/minikube-darwin-amd64 version
minikube version: v1.12.3
commit: c41a5f19b778ea6fb57a063022c9caceb11fe8ed
$ mv $HOME/.kube/config{,.bak}
$ out/minikube-darwin-amd64 start --vm-driver virtualbox
😄  minikube v1.12.3 on Darwin 10.15.5
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.12 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
$ out/minikube-darwin-amd64 update-context

💣  update config: "minikube" does not appear in /Users/ksuda/.kube/config

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
$ mv $HOME/.kube/config{.bak,}
```

Originally, it was assumed that this command occurs an error if the cluster configuration is missed in the kubeconfig. Due to an implementation error in the test code, the following tests have not been ran so far (this is fixed at  a3fe0f5c499245802ee766f6e4a34349f657267c).

https://github.com/kubernetes/minikube/pull/8989/files#diff-289235936c30fdab30825ef3f90de144L298-L305

If we need to keep support for adding context, I would change the testcase above and the code as follows. What do you think?

```go
	// if the cluster setting is missed in the kubeconfig, create new one
	if _, ok := cfg.Clusters[contextName]; !ok {
		lp := localpath.Profile(contextName)
		gp := localpath.MiniPath()
		kcs := &Settings{
			ClusterName:          contextName,
			ClusterServerAddress: address,
			ClientCertificate:    path.Join(lp, "client.crt"),
			ClientKey:            path.Join(lp, "client.key"),
			CertificateAuthority: path.Join(gp, "ca.crt"),
			KeepContext:          false,
		}
		err = PopulateFromSettings(kcs, cfg)
		if err != nil {
			return false, errors.Wrap(err, "populating kubeconfig")
		}
	} else {
		cfg.Clusters[contextName].Server = address
	}
```

**Comment by superbrothers** [comment]
@medyagh OK, I'll add a subtest for Update Context, but we need to decide `update-context` command's behavior first.

If there is no minikube cluster in the kubeconfig (including if no clusters), add cluster, user and context settings to the kubeconfig, and set minikube to the current-context. This is the current behavior, but according to [`TestUpdateIP` in `pkg/minikube/kubeconfig_test.go`](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/kubeconfig/kubeconfig_test.go#L298-L305), `update-context` command is originally expected to result in an error.

```go
func TestUpdateIP(t *testing.T) {

	var tests = []struct {
		description string
		hostname    string
		port        int
		existing    []byte
		err         bool
		status      bool
		expCfg      []byte
	}{
		{
			description: "no minikube cluster",
			hostname:    "192.168.10.100",
			port:        8080,
			existing:    kubeConfigWithoutHTTPS,
			err:         true,
			expCfg:      kubeConfigWithoutHTTPS,
		},
```

File: pkg/minikube/kubeconfig/kubeconfig.go (hunk 1 above)
Comment (tstromberg) [reply pkg/minikube/kubeconfig/kubeconfig.go:126]: We do need support for adding context. The test idea looks good. Thanks!

Comment (superbrothers) [reply pkg/minikube/kubeconfig/kubeconfig.go:126]: I reverted support for adding context at https://github.com/kubernetes/minikube/pull/8989/commits/79d5641c5364c16dcc4d5e7cd64ceedfe78d04ab.

```
$ make out/minikube-darwin-amd64
GOOS="darwin" GOARCH="amd64" \
        go build -tags "container_image_ostree_stub containers_image_openpgp go_getter_nos3 go_getter_nogcs" -ldflags="-X k8s.io/minikube/pkg/version.version=v1.12.3 -X k8s.io/minikube/pkg/version.isoVersion=v1.12.2 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -X k8s.io/minikube/pkg/version.gitCommitID="eb01a2ef73dfde3c3a994b6719ff006b21d5822e" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v2" -a -o out/minikube-darwin-amd64 k8s.io/minikube/cmd/minikube
$ alias minikube="${PWD}/out/minikube-darwin-amd64"
$ git show --quiet
commit eb01a2ef73dfde3c3a994b6719ff006b21d5822e (HEAD -> fix-nil-pointer-dereference, superbrothers/fix-nil-pointer-dereference)
Author: Kazuki Suda <kazuki.suda@gmail.com>
Date:   Sun Aug 16 14:03:41 2020 +0900

    Update an integration test
$ minikube version
minikube version: v1.12.3
commit: eb01a2ef73dfde3c3a994b6719ff006b21d5822e
$ minikube delete
🔥  Deleting "minikube" in virtualbox ...
💀  Removed all traces of the "minikube" cluster.
$ minikube start
😄  minikube v1.12.3 on Darwin 10.15.5
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.12 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
$ mv $HOME/.kube/config{,.bak}
$ minikube update-context
🎉  "minikube" context has been updated to point to 192.168.99.135:8443
$ kubectl get po -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-66bff467f8-st8dt           0/1     Running   0          18s
kube-system   etcd-minikube                      1/1     Running   0          23s
kube-system   kube-apiserver-minikube            1/1     Running   0          23s
kube-system   kube-controller-manager-minikube   1/1     Running   0          23s
kube-system   kube-proxy-qcllm                   1/1     Running   0          18s
kube-system   kube-scheduler-minikube            1/1     Running   0          22s
kube-system   storage-provisioner                1/1     Running   0          23s
$ mv $HOME/.kube/config{.bak,}
mv: overwrite '/Users/ksuda/.kube/config'? y
```

**Comment by superbrothers** [comment]
I updated a subtest to our exiting UpdateContext integration test at https://github.com/kubernetes/minikube/pull/8989/commits/eb01a2ef73dfde3c3a994b6719ff006b21d5822e.

```
$ env TEST_ARGS="-test.run=TestFunctional/parallel/UpdateContextCmd --profile=minikube --cleanup=false" make integration
go test -ldflags="-X k8s.io/minikube/pkg/version.version=v1.12.3 -X k8s.io/minikube/pkg/version.isoVersion=v1.12.2 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -X k8s.io/minikube/pkg/version.gitCommitID="3ecf887959389a85a04f4b3ba34f83f12b88536f-dirty" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v2" -v -test.timeout=90m ./test/integration --tags="integration container_image_ostree_stub containers_image_openpgp go_getter_nos3 go_getter_nogcs" -test.run=TestFunctional/parallel/UpdateContextCmd --profile=minikube --cleanup=false
Found 16 cores, limiting parallelism with --test.parallel=9
=== RUN   TestFunctional
=== PAUSE TestFunctional
=== CONT  TestFunctional
=== RUN   TestFunctional/parallel
=== RUN   TestFunctional/parallel/UpdateContextCmd
=== PAUSE TestFunctional/parallel/UpdateContextCmd
=== CONT  TestFunctional/parallel/UpdateContextCmd
=== RUN   TestFunctional/parallel/UpdateContextCmd/no_changes
=== PAUSE TestFunctional/parallel/UpdateContextCmd/no_changes
=== RUN   TestFunctional/parallel/UpdateContextCmd/no_minikube_cluster
=== PAUSE TestFunctional/parallel/UpdateContextCmd/no_minikube_cluster
=== RUN   TestFunctional/parallel/UpdateContextCmd/no_clusters
=== PAUSE TestFunctional/parallel/UpdateContextCmd/no_clusters
=== CONT  TestFunctional/parallel/UpdateContextCmd/no_changes
=== CONT  TestFunctional/parallel/UpdateContextCmd/no_clusters
=== CONT  TestFunctional/parallel/UpdateContextCmd/no_minikube_cluster
=== CONT  TestFunctional/parallel/UpdateContextCmd/no_changes
    functional_test.go:1082: (dbg) Run:  out/minikube -p minikube update-context --alsologtostderr -v=2
=== CONT  TestFunctional/parallel/UpdateContextCmd/no_minikube_cluster
    functional_test.go:1082: (dbg) Run:  out/minikube -p minikube update-context --alsologtostderr -v=2
=== CONT  TestFunctional/parallel/UpdateContextCmd/no_clusters
    functional_test.go:1082: (dbg) Run:  out/minikube -p minikube update-context --alsologtostderr -v=2
--- PASS: TestFunctional (0.39s)
    --- PASS: TestFunctional/parallel (0.00s)
        --- PASS: TestFunctional/parallel/UpdateContextCmd (0.00s)
            --- PASS: TestFunctional/parallel/UpdateContextCmd/no_changes (0.39s)
            --- PASS: TestFunctional/parallel/UpdateContextCmd/no_minikube_cluster (0.39s)
            --- PASS: TestFunctional/parallel/UpdateContextCmd/no_clusters (0.39s)
PASS
Tests completed in 388.50175ms (result code 0)
ok      k8s.io/minikube/test/integration        1.312s
```

**Comment by superbrothers** [comment]
I'll squash the commits after the changes are reviewed.

**Comment by superbrothers** [comment]
Some tests seem to be failing on items not related to this PR.

**Comment by tstromberg** [comment]
I tested this locally and it works great. Thank you!
