### PR TITLE
Prevent registry-creds configure from failing when a secret does not exist. 

### LINKED ISSUE #5885: registry-creds addon: Temporary Error: secrets "registry-creds-ecr" not found
starting with a fresh cluster on Ubuntu 19.10 using VirtualBox

**minikube start** 
(all is starting fine)

😄  minikube v1.5.2 on Ubuntu 19.10
✨  Automatically selected the 'virtualbox' driver (alternates: [none])
💿  Downloading VM boot image ...
    > minikube-v1.5.1.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.5.1.iso: 143.76 MiB / 143.76 MiB [-] 100.00% 3.09 MiB p/s 47s
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
💾  Downloading kubeadm v1.16.2
💾  Downloading kubelet v1.16.2
🚜  Pulling images ...
🚀  Launching Kubernetes ... 
⌛  Waiting for: apiserver
🏄  Done! kubectl is now configured to use "minikube"

## Then running ecr credentials fails:

**minikube addons configure registry-creds**
(entering all data for ECR)
❌  ERROR creating `registry-creds-ecr` secret: Temporary Error: secrets "registry-creds-ecr" not found
❌  ERROR creating `registry-creds-gcr` secret: Temporary Error: secrets "registry-creds-gcr" not found
⚠️  ERROR creating `registry-creds-dpr` secret
✅  registry-creds was successfully configured

After this procedure no secret has been setup and therefore image Pull fails.

Any Idea ?
Thanks,
detlef

### PR DESCRIPTION
**Pull request by akshaysu12**
…l when a secret does not exist.

closes #5885

### CODE REVIEW

File: pkg/minikube/service/service.go [hunk 1]
```diff
@@ -332,10 +332,7 @@ func CreateSecret(namespace, name string, dataValues map[string]string, labels m
 		return &retry.RetriableError{Err: err}
 	}
 	secrets := client.Secrets(namespace)
-	secret, err := secrets.Get(name, meta.GetOptions{})
-	if err != nil {
-		return &retry.RetriableError{Err: err}
-	}
+	secret, _ := secrets.Get(name, meta.GetOptions{})
```
Comment (tstromberg) [inline pkg/minikube/service/service.go]: At a minimum, this should log or display an error rather than hide it entirely. I'm not exactly sure which is appropriate here, but naively glog.Errorf?

Comment (akshaysu12) [reply pkg/minikube/service/service.go]: Thanks, logging makes sense. I feel a glog.Infof would be most appropriate as I don't think it should be an error when CreateSecrets is unable to get a secret it is going to create.

**Comment by medyagh** [comment]
OK to test
