### PR TITLE
Shared network for vfkit driver using vmnet-helper

### LINKED ISSUE #20557: vfkit: unable to create multi-node cluster
### What Happened?

Creating a cluster with multiple nodes get stuck for long time and finally fails.

## Reproduce

```console
% minikube start --driver vfkit --container-runtime containerd --nodes 2 --cni auto
😄  minikube v1.35.0 on Darwin 15.3.2 (arm64)
✨  Using the vfkit (experimental) driver based on user configuration
💿  Downloading VM boot image ...
    > minikube-v1.35.0-arm64.iso....:  65 B / 65 B [---------] 100.00% ? p/s 0s
    > minikube-v1.35.0-arm64.iso:  393.15 MiB / 393.15 MiB  100.00% 27.82 MiB p
👍  Starting "minikube" primary control-plane node in "minikube" cluster
💾  Downloading Kubernetes v1.32.2 preload ...
    > preloaded-images-k8s-v18-v1...:  357.51 MiB / 357.51 MiB  100.00% 25.96 M
🔥  Creating vfkit VM (CPUs=2, Memory=4050MB, Disk=20000MB) ...
📦  Preparing Kubernetes v1.32.2 on containerd 1.7.23 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner

👍  Starting "minikube-m02" worker node in "minikube" cluster
🔥  Creating vfkit VM (CPUs=2, Memory=4050MB, Disk=20000MB) ...
🌐  Found network options:
    ▪ NO_PROXY=192.168.106.25
📦  Preparing Kubernetes v1.32.2 on containerd 1.7.23 ...
    ▪ env NO_PROXY=192.168.106.25
    > kubectl.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubelet.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubectl:  53.25 MiB / 53.25 MiB [------------] 100.00% 13.69 MiB p/s 4.1s
    > kubeadm:  66.81 MiB / 66.81 MiB [-------------] 100.00% 7.26 MiB p/s 9.4s
    > kubelet:  71.75 MiB / 71.75 MiB [-------------] 100.00% 7.43 MiB p/s 9.9s
E0322 22:46:23.795529   57098 start.go:345] worker node failed to join cluster, will retry: kubeadm join: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.32.2:$PATH" kubeadm join control-plane.minikube.internal:8443 --token l2pqog.yxzqrtilhqoctljj --discovery-token-ca-cert-hash sha256:bd493a4334f125cd2b80c44d186afadca331b667df010302e0ebc9fcfd2be99c --ignore-preflight-errors=all --cri-socket unix:///run/containerd/containerd.sock --node-name=minikube-m02": Process exited with status 1
stdout:
[preflight] Running pre-flight checks

stderr:
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: couldn't validate the identity of the API Server: failed to request the cluster-info ConfigMap: Get "https://control-plane.minikube.internal:8443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp 192.168.106.25:8443: connect: no route to host
To see the stack trace of this error execute with --v=5 or higher

❌  Exiting due to GUEST_START: failed to start node: adding node: join node to cluster: error joining worker node "m02" to cluster: kubeadm join: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.32.2:$PATH" kubeadm join control-plane.minikube.internal:8443 --token l2pqog.yxzqrtilhqoctljj --discovery-token-ca-cert-hash sha256:bd493a4334f125cd2b80c44d186afadca331b667df010302e0ebc9fcfd2be99c --ignore-preflight-errors=all --cri-socket unix:///run/containerd/containerd.sock --node-name=minikube-m02": Process exited with status 1
stdout:
[preflight] Running pre-flight checks

stderr:
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: couldn't validate the identity of the API Server: failed to request the cluster-info ConfigMap: Get "https://control-plane.minikube.internal:8443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp 192.168.106.25:8443: connect: no route to host
To see the stack trace of this error execute with --v=5 or higher


╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

```

## Why it fails?

The vfkit driver use [nat network](https://github.com/crc-org/vfkit/blob/main/doc/usage.md#description-9), which is implemented using [VZNATNetworkDeviceAttachment](https://developer.apple.com/documentation/virtualization/vznatnetworkdeviceattachment?language=objc). This provides an IP address in in 192.168.106/24 network, which is accessible by the host, but other vms in this network cannot access each other.

Example:

```console
% minikube node list   
minikube	192.168.106.25
minikube-m02	192.168.106.26

% minikube ssh 

$ ping 192.168.106.26
PING 192.168.106.26 (192.168.106.26): 56 data bytes
^C
--- 192.168.106.26 ping statistics ---
10 packets transmitted, 0 packets received, 100% packet loss
```

I think this is considered a feature, providing isolation between vms, but it does not work for minikube use case fo multi-node cluster.

### Attach the log file

[log.txt](https://github.com/user-attachments/files/19405539/log.txt)

### Operating System

macOS (Default)

### Driver

None

## Related issues
- https://github.com/crc-org/vfkit/issues/180

### LINKED ISSUE #20558: vfkit: unable to access other other clusters from the node
### What Happened?

We can create multiple clusters using the vfkit driver. They get an ip address and are accessible from the host. But there is no way to access one clusters from the node.

## Reproduce

Create cluster c1:

```
% minikube start -p c1 --driver vfkit --container-runtime containerd
😄  [c1] minikube v1.35.0 on Darwin 15.3.2 (arm64)
✨  Using the vfkit (experimental) driver based on user configuration
👍  Starting "c1" primary control-plane node in "c1" cluster
🔥  Creating vfkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
📦  Preparing Kubernetes v1.32.2 on containerd 1.7.23 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "c1" cluster and "default" namespace by default
```

Create cluster c2:

```
% minikube start -p c2 --driver vfkit --container-runtime containerd
😄  [c2] minikube v1.35.0 on Darwin 15.3.2 (arm64)
✨  Using the vfkit (experimental) driver based on user configuration
👍  Starting "c2" primary control-plane node in "c2" cluster
🔥  Creating vfkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
📦  Preparing Kubernetes v1.32.2 on containerd 1.7.23 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "c2" cluster and "default" namespace by default
```

Profiles:

```
% minikube profile list                                             
|---------|-----------|------------|----------------|------|---------|--------|-------|----------------|--------------------|
| Profile | VM Driver |  Runtime   |       IP       | Port | Version | Status | Nodes | Active Profile | Active Kubecontext |
|---------|-----------|------------|----------------|------|---------|--------|-------|----------------|--------------------|
| c1      | vfkit     | containerd | 192.168.106.27 | 8443 | v1.32.2 | OK     |     1 |                |                    |
| c2      | vfkit     | containerd | 192.168.106.28 | 8443 | v1.32.2 | OK     |     1 |                | *                  |
|---------|-----------|------------|----------------|------|---------|--------|-------|----------------|--------------------|
```

Both clusters are accessible from the host:

```console
% minikube ssh -p c1 ip a show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether aa:95:4d:c5:55:c7 brd ff:ff:ff:ff:ff:ff
    inet 192.168.106.27/24 metric 1024 brd 192.168.106.255 scope global dynamic eth0
       valid_lft 331sec preferred_lft 331sec

% minikube ssh -p c2 ip a show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 6a:28:fd:7c:4b:70 brd ff:ff:ff:ff:ff:ff
    inet 192.168.106.28/24 metric 1024 brd 192.168.106.255 scope global dynamic eth0
       valid_lft 384sec preferred_lft 384sec
```

But we cannot access cluster c2 from c1 or c1 from c2:

```console
% minikube ssh -p c1 -- ping -c 10 192.168.106.28
PING 192.168.106.28 (192.168.106.28): 56 data bytes

--- 192.168.106.28 ping statistics ---
10 packets transmitted, 0 packets received, 100% packet loss
ssh: Process exited with status 1

% minikube ssh -p c2 -- ping -c 10 192.168.106.27
PING 192.168.106.27 (192.168.106.27): 56 data bytes

--- 192.168.106.27 ping statistics ---
10 packets transmitted, 0 packets received, 100% packet loss
ssh: Process exited with status 1
```

## Why it fails?

This another variant of #20557. vfkit `nat` network does not allow access between clusters.

## Cluster c1 logs

[log-c1.txt](https://github.com/user-attachments/files/19405591/log-c1.txt)

## Cluster c2 logs

[log-c2.txt](https://github.com/user-attachments/files/19405592/log-c2.txt)

### Operating System

macOS (Default)

### Driver

None

## Related issues
- https://github.com/crc-org/vfkit/issues/180

### PR DESCRIPTION
**Pull request by nirs**
Add new network option for vfkit "vment-shared", connecting vfkit to the
vmnet shared network. Clusters using this network can access other
clusters in the same network, similar to socket_vment with QEMU driver.

If network is not specified, we default to the "nat" network, keeping
the previous behavior. If network is "vment-shared", the vfkit driver
manages 2 processes: vfkit and vmnet-helper.

Like vfkit, vmnet-helper is started in the background, in a new process
group, so it not terminated if the minikube process group is terminate.

Since vment-helper requires root to start the vmnet interface, we start
it with sudo, creating 2 child processes. vment-helper drops privileges
immediately after starting the vment interface, and run as the user and
group running minikube.

Stopping the cluster will stop sudo, which will stop the vmnet-helper
process. Deleting the cluster kill both sudo and vment-helper by killing
the process group.

This change is not complete, but it is good enough to play with the new
shared network.

Example usage:

1. Install vmnet-helper:
   https://github.com/nirs/vmnet-helper?tab=readme-ov-file#installation

2. Setup vment-helper sudoers rule:
   https://github.com/nirs/vmnet-helper?tab=readme-ov-file#granting-permission-to-run-vmnet-helper

3. Start 2 clusters with vmnet-shared network:

```console
% minikube start -p c1 --driver vfkit --network vment-shared
...

% minikube start -p c2 --driver vfkit --network vmnet-shared
...

% minikube ip -p c1
192.168.105.18

% minikube ip -p c2
192.168.105.19
```

4. Both cluster can access the other cluster:

```console
% minikube -p c1 ssh -- ping -c 3 192.168.105.19
PING 192.168.105.19 (192.168.105.19): 56 data bytes
64 bytes from 192.168.105.19: seq=0 ttl=64 time=0.621 ms
64 bytes from 192.168.105.19: seq=1 ttl=64 time=0.989 ms
64 bytes from 192.168.105.19: seq=2 ttl=64 time=0.490 ms

--- 192.168.105.19 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.490/0.700/0.989 ms

% minikube -p c2 ssh -- ping -c 3 192.168.105.18
PING 192.168.105.18 (192.168.105.18): 56 data bytes
64 bytes from 192.168.105.18: seq=0 ttl=64 time=0.289 ms
64 bytes from 192.168.105.18: seq=1 ttl=64 time=0.798 ms
64 bytes from 192.168.105.18: seq=2 ttl=64 time=0.993 ms

--- 192.168.105.18 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.289/0.693/0.993 ms
```

To complete this work we need:
- Install vmnet-helper on the CI macOS hosts
- Add test using --network vmnet-shared

Fixes #20557
Fixes #20558

### CODE REVIEW

**Comment by nirs** [comment]
@afbjorklund can you review this?

File: pkg/drivers/vmnet/vmnet.go [hunk 1]
```diff
@@ -0,0 +1,267 @@
...
+	return nil
+}
+
+// GetMACAddress reutuns the mac address assigned by vment framework.
+func (h *Helper) GetMACAddress() string {
+	return h.macAddress
+}
+
+// Stop the vmnet-helper child process.
+func (h *Helper) Stop() error {
```
Comment (nirs) [inline pkg/drivers/vmnet/vmnet.go:132]: Replace with signalPidfile() added in #20506

File: pkg/drivers/vmnet/vmnet.go [hunk 2]
```diff
@@ -0,0 +1,267 @@
...
+func (h *Helper) openLogfile() (*os.File, error) {
+	path := h.machinePath(logfileName)
+	return os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o600)
+}
+
+func (h *Helper) machinePath(fileName string) string {
+	return filepath.Join(h.StorePath, "machines", h.MachineName, fileName)
+}
+
+func writePidfile(path string, pid int) error {
```
Comment (nirs) [inline pkg/drivers/vmnet/vmnet.go:203]: Use writePidfile added in #20506

File: pkg/drivers/vmnet/vmnet.go [hunk 3]
```diff
@@ -0,0 +1,267 @@
...
+	data := fmt.Sprintf("%v", pid)
+	if err := os.WriteFile(path, []byte(data), 0600); err != nil {
+		return err
+	}
+	return nil
+}
+
+func readPidfile(path string) (int, error) {
```
Comment (nirs) [inline pkg/drivers/vmnet/vmnet.go:211]: Use readPidfile added in #20506

File: pkg/drivers/vmnet/vmnet.go [hunk 4]
```diff
@@ -0,0 +1,267 @@
...
+		return -1, err
+	}
+	pid, err := strconv.Atoi(strings.TrimSpace(string(data)))
+	if err != nil {
+		return -1, err
+	}
+	return pid, nil
+}
+
+func checkPid(pid int) error {
```
Comment (nirs) [inline pkg/drivers/vmnet/vmnet.go:223]: Use checkPid from vfkit.

File: pkg/drivers/vmnet/vmnet.go [hunk 5]
```diff
@@ -0,0 +1,267 @@
...
+	if err != nil {
+		return err
+	}
+	return process.Signal(syscall.Signal(0))
+}
+
+// uuidFromName generated a random UUID (type 4) from string name. This is
+// useful for creating interface ID from virtual machine name to ensure the same
+// MAC address in all runs.
+func uuidFromName(name string) string {
```
Comment (nirs) [inline pkg/drivers/vmnet/vmnet.go:234]: I'll remove this for now since other drivers use new mac address for new machine, regardless of the machine name.

File: pkg/drivers/vmnet/vmnet.go [hunk 6]
```diff
@@ -0,0 +1,267 @@
...
+	executablePath = "/opt/vmnet-helper/bin/vmnet-helper"
+)
+
+// Helper manages the vmnet-helper process.
+type Helper struct {
+	// The minikube machine name this helper is serving.
+	MachineName string
+
+	// Minikube home directory.
+	StorePath string
```
Comment (nirs) [inline pkg/drivers/vmnet/vmnet.go:51]: Can replace MachineName and StorePath with MachineDir.

File: pkg/drivers/vmnet/vmnet.go [hunk 7]
```diff
@@ -0,0 +1,267 @@
...
+type interfaceInfo struct {
+	MACAddress string `json:"vmnet_mac_address"`
+}
+
+// HelperAvailable tells if vment-helper executable is installed and configured
+// correctly.
+func HelperAvailable() bool {
+	version, err := exec.Command("sudo", "--non-interactive", executablePath, "--version").Output()
+	if err != nil {
+		log.Debugf("Failed to run vmnet-helper: %w", executablePath, err)
```
Comment (nirs) [inline pkg/drivers/vmnet/vmnet.go]: remove exectuablePath

File: pkg/drivers/vmnet/vmnet.go [hunk 8]
```diff
@@ -0,0 +1,267 @@
...
+		return false
+	}
+	log.Debugf("Using vmnet-helper version %q", executablePath, version)
```
Comment (nirs) [inline pkg/drivers/vmnet/vmnet.go]: remove exectuablePath

**Comment by nirs** [comment]
Example machine config when vmnet-shared is used:

```json
{
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "192.168.105.21",
        "MachineName": "minikube",
        "SSHUser": "docker",
        "SSHPort": 22,
        "SSHKeyPath": "",
        "StorePath": "/Users/nir/.minikube",
        "SwarmMaster": false,
        "SwarmHost": "",
        "SwarmDiscovery": "",
        "Boot2DockerURL": "file:///Users/nir/.minikube/cache/iso/arm64/minikube-v1.35.0-arm64.iso",
        "DiskSize": 20000,
        "CPU": 2,
        "Memory": 6000,
        "Cmdline": "",
        "ExtraDisks": 0,
        "Network": "vmnet-shared",
        "MACAddress": "de:a2:9c:71:3c:f7",
        "VmnetHelper": {
            "MachineDir": "/Users/nir/.minikube/machines/minikube",
            "InterfaceID": "a0c43efb-2dcc-4abb-a310-568782c5dc7a"
        }
    },
    "DriverName": "vfkit",
    "HostOptions": {
        "Driver": "",
        "Memory": 0,
        "Disk": 0,
        "EngineOptions": {
            "ArbitraryFlags": null,
            "Dns": null,
            "GraphDir": "",
            "Env": null,
            "Ipv6": false,
            "InsecureRegistry": [
                "10.96.0.0/12"
            ],
            "Labels": null,
            "LogLevel": "",
            "StorageDriver": "",
            "SelinuxEnabled": false,
            "TlsVerify": false,
            "RegistryMirror": [],
            "InstallURL": "https://get.docker.com"
        },
        "SwarmOptions": {
            "IsSwarm": false,
            "Address": "",
            "Discovery": "",
            "Agent": false,
            "Master": false,
            "Host": "",
            "Image": "",
            "Strategy": "",
            "Heartbeat": 0,
            "Overcommit": 0,
            "ArbitraryFlags": null,
            "ArbitraryJoinFlags": null,
            "Env": null,
            "IsExperimental": false
        },
        "AuthOptions": {
            "CertDir": "/Users/nir/.minikube",
            "CaCertPath": "/Users/nir/.minikube/certs/ca.pem",
            "CaPrivateKeyPath": "/Users/nir/.minikube/certs/ca-key.pem",
            "CaCertRemotePath": "",
            "ServerCertPath": "/Users/nir/.minikube/machines/server.pem",
            "ServerKeyPath": "/Users/nir/.minikube/machines/server-key.pem",
            "ClientKeyPath": "/Users/nir/.minikube/certs/key.pem",
            "ServerCertRemotePath": "",
            "ServerKeyRemotePath": "",
            "ClientCertPath": "/Users/nir/.minikube/certs/cert.pem",
            "ServerCertSANs": null,
            "StorePath": "/Users/nir/.minikube"
        }
    },
    "Name": "minikube"
}
```

**Comment by nirs** [comment]
## Example multi-node cluster

```console
% minikube start --network vmnet-shared --nodes 2 --cni auto
😄  minikube v1.35.0 on Darwin 15.3.1 (arm64)
✨  Using the vfkit (experimental) driver based on user configuration
❗  --network flag is only valid with the docker/podman, KVM and Qemu drivers, it will be ignored
👍  Starting "minikube" primary control-plane node in "minikube" cluster
🔥  Creating vfkit VM (CPUs=2, Memory=4050MB, Disk=20000MB) ...
📦  Preparing Kubernetes v1.32.2 on containerd 1.7.23 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner

👍  Starting "minikube-m02" worker node in "minikube" cluster
🔥  Creating vfkit VM (CPUs=2, Memory=4050MB, Disk=20000MB) ...
🌐  Found network options:
    ▪ NO_PROXY=192.168.105.22
📦  Preparing Kubernetes v1.32.2 on containerd 1.7.23 ...
    ▪ env NO_PROXY=192.168.105.22
    > kubelet.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubectl.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubectl:  53.25 MiB / 53.25 MiB [------------] 100.00% 37.13 MiB p/s 1.6s
    > kubelet:  71.75 MiB / 71.75 MiB [------------] 100.00% 12.43 MiB p/s 6.0s
    > kubeadm:  66.81 MiB / 66.81 MiB [------------] 100.00% 10.11 MiB p/s 6.8s
🔎  Verifying Kubernetes components...
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

% kubectl get node                                                           
NAME           STATUS   ROLES           AGE     VERSION
minikube       Ready    control-plane   5m1s    v1.32.2
minikube-m02   Ready    <none>          4m40s   v1.32.2

% kubectl get node -o jsonpath='{.items[*].status.addresses[0].address}{"\n"}'
192.168.105.22 192.168.105.23
```

Each node get its own vment-helper process:

```console
% ps au | grep vmnet-helper | grep -v grep 
nir  60260   0.0  0.0 410743984   3792 s020  S     1:07AM   0:00.71 /opt/vmnet-helper/bin/vmnet-helper --fd 21 --interface-id c9ae713b-5937-42de-9018-bbb95a425506
root 60259   0.0  0.0 410737168   6448 s020  S     1:07AM   0:00.01 sudo --non-interactive --close-from 22 /opt/vmnet-helper/bin/vmnet-helper --fd 21 --interface-id c9ae713b-5937-42de-9018-bbb95a425506
nir  60254   0.0  0.0 410735792   3728 s020  S     1:07AM   0:00.73 /opt/vmnet-helper/bin/vmnet-helper --fd 13 --interface-id cf62fb28-2533-4c25-8d35-1eef1736f707
root 60253   0.0  0.0 410754576   6992 s020  S     1:07AM   0:00.01 sudo --non-interactive --close-from 14 /opt/vmnet-helper/bin/vmnet-helper --fd 13 --interface-id cf62fb28-2533-4c25-8d35-1eef1736f707
```

File: pkg/drivers/vfkit/vfkit.go [hunk 9]
```diff
@@ -193,6 +214,42 @@ func (d *Driver) Create() error {
...
+	}
+
+	log.Infof("Waiting for VM to start (ssh -p %d docker@%s)...", d.SSHPort, d.IPAddress)
+
+	return WaitForTCPWithDelay(fmt.Sprintf("%s:%d", d.IPAddress, d.SSHPort), time.Second)
+}
+
+// startVfkit starts the vfkit child process. If vfkitSock is non nil, vfkit is
+// connected to the vmnet network via the socket instead of "nat" network.
+func (d *Driver) startVfkit(vfkitSock *os.File) error {
```
Comment (cfergeau) [inline pkg/drivers/vfkit/vfkit.go:252]: might be clearer to rename `vfkitSock` to `vmnetSock` in this method.

File: pkg/drivers/vfkit/vfkit.go [hunk 10]
```diff
@@ -152,6 +155,24 @@ func (d *Driver) GetState() (state.State, error) {
...
+	return d.VmnetHelper.GetState()
+}
+
+// GetState returns driver state. Since vfkit driver may use 2 processes
+// (vmnet-helper, vfkit), this returns combined state of both processes.
+func (d *Driver) GetState() (state.State, error) {
+	if vfkitState, err := d.getVfkitState(); err != nil {
+		return state.Error, err
+	} else if vfkitState == state.Running {
+		return state.Running, nil
```
Comment (cfergeau) [inline pkg/drivers/vfkit/vfkit.go:171]: if `getVfkitState` returns `running`, is it guaranteed that vmnet will also be running? or should it be `s/Running/Stopped` in this block?

**Review by cfergeau — COMMENTED** [review]
I also noticed several `vment` typos in commit logs

File: pkg/drivers/vfkit/vfkit.go (hunk 9 above)
Comment (nirs) [reply pkg/drivers/vfkit/vfkit.go:252]: The name come from Start() when we want to make it clear that one socket is for the helper, and one for vfkit. Keeping the same name in startVfkit() to make it easier to follow the code. It is very confusing when using different names to the same thing in different fuctions.

Maybe we can name both vmnetHelperSock and vmnetVfkitSock?

File: pkg/drivers/vfkit/vfkit.go (hunk 10 above)
Comment (nirs) [reply pkg/drivers/vfkit/vfkit.go:171]: Yes, the semantics is returning Running if at least one process is running, since we used it only in stop or delete flows. If some process is running, we need to continue polling and maybe retry the stop or kill.

File: pkg/drivers/vfkit/vfkit.go (hunk 9 above)
Comment (cfergeau) [reply pkg/drivers/vfkit/vfkit.go:252]: This is minor, fine with me if you want to keep the current naming. `vmnetHelperSock`/`vmnetVfkitSock` is good too even if a bit on the "long" side.

File: pkg/drivers/vfkit/vfkit.go (hunk 10 above)
Comment (cfergeau) [reply pkg/drivers/vfkit/vfkit.go:171]: If it's not used in `Start` to wait until the state is `running`, then this should be fine. My worry was if something expects the VM to be running and usable when only one of the 2 processes is up.

File: pkg/drivers/pidfile.go [hunk 11]
```diff
@@ -0,0 +1,79 @@
+/*
```
Comment (medyagh) [inline pkg/drivers/pidfile.go:1]: maybe check it is not installed and Suggest ppl to install it

File: pkg/drivers/vfkit/vfkit.go (hunk 9 above)
Comment (nirs) [reply pkg/drivers/vfkit/vfkit.go:256]: Keeping the current names then.

File: pkg/drivers/vfkit/vfkit.go (hunk 10 above)
Comment (nirs) [reply pkg/drivers/vfkit/vfkit.go:175]: We may need to improve this later if we want to use the state for checking if start finished. Currently Start() is blocking and when it returns we have 2 processes running. (actually 3: vfkit, sudo, vmnet-helper).

**Comment by nirs** [comment]
## Example iperf3 test

### Resources

iperf3-server.yaml:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iperf3
  name: iperf3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - image: networkstatic/iperf3
        imagePullPolicy: Always
        name: iperf3
        command: ["iperf3", "-s"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: iperf3
  name: iperf3
  namespace: default
spec:
  ports:
  - nodePort: 30201
    port: 5201
    protocol: TCP
  selector:
    app: iperf3
  type: NodePort
```

iperf3-client.yaml:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iperf3
  name: iperf3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - image: networkstatic/iperf3
        imagePullPolicy: Always
        name: iperf3
        command: ["sleep", "3600"]
```

### Creating the clusters

```
minikube start -p server --driver vfkit --container-runtime containerd --network vmnet-shared
minikube start -p client --driver vfkit --container-runtime containerd --network vmnet-shared
kubectl apply -f iperf3-server.yaml --context server
kubectl apply -f iperf3-client.yaml --context client
```

### Host to vm benchmark

```console
% iperf3 -c $(minikube ip -p server) --port 30201                              
Connecting to host 192.168.105.37, port 30201
[  5] local 192.168.105.1 port 62342 connected to 192.168.105.37 port 30201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   983 MBytes  8.25 Gbits/sec                  
[  5]   1.00-2.00   sec  1002 MBytes  8.37 Gbits/sec                  
[  5]   2.00-3.00   sec   979 MBytes  8.25 Gbits/sec                  
[  5]   3.00-4.00   sec   981 MBytes  8.21 Gbits/sec                  
[  5]   4.00-5.00   sec   982 MBytes  8.26 Gbits/sec                  
[  5]   5.00-6.00   sec   993 MBytes  8.30 Gbits/sec                  
[  5]   6.00-7.00   sec   986 MBytes  8.29 Gbits/sec                  
[  5]   7.00-8.00   sec   987 MBytes  8.25 Gbits/sec                  
[  5]   8.00-9.00   sec  1002 MBytes  8.44 Gbits/sec                  
[  5]   9.00-10.00  sec  1010 MBytes  8.44 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.00  sec  9.67 GBytes  8.31 Gbits/sec                  sender
[  5]   0.00-10.01  sec  9.67 GBytes  8.30 Gbits/sec                  receiver
```

### VM to host benchmark

```console
% iperf3 -c $(minikube ip -p server) --port 30201 --reverse
Connecting to host 192.168.105.37, port 30201
Reverse mode, remote host 192.168.105.37 is sending
[  5] local 192.168.105.1 port 62348 connected to 192.168.105.37 port 30201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.01   sec  1001 MBytes  8.35 Gbits/sec                  
[  5]   1.01-2.01   sec  1016 MBytes  8.52 Gbits/sec                  
[  5]   2.01-3.01   sec   975 MBytes  8.18 Gbits/sec                  
[  5]   3.01-4.01   sec   949 MBytes  7.96 Gbits/sec                  
[  5]   4.01-5.00   sec  1007 MBytes  8.47 Gbits/sec                  
[  5]   5.00-6.00   sec  1016 MBytes  8.53 Gbits/sec                  
[  5]   6.00-7.00   sec  1008 MBytes  8.47 Gbits/sec                  
[  5]   7.00-8.00   sec  1.00 GBytes  8.57 Gbits/sec                  
[  5]   8.00-9.00   sec  1.00 GBytes  8.61 Gbits/sec                  
[  5]   9.00-10.01  sec  1019 MBytes  8.52 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.01  sec  9.81 GBytes  8.42 Gbits/sec  421            sender
[  5]   0.00-10.01  sec  9.80 GBytes  8.42 Gbits/sec                  receiver
```

### VM to VM benchmark

```console
% kubectl exec deploy/iperf3 --context client -- iperf3 -c $(minikube ip -p server) --port 30201 --forceflush
Connecting to host 192.168.105.37, port 30201
[  5] local 10.244.0.7 port 58638 connected to 192.168.105.37 port 30201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  1.38 GBytes  11.8 Gbits/sec  162   2.60 MBytes       
[  5]   1.00-2.00   sec  1.40 GBytes  12.0 Gbits/sec    0   2.99 MBytes       
[  5]   2.00-3.00   sec  1.40 GBytes  12.0 Gbits/sec    0   3.01 MBytes       
[  5]   3.00-4.00   sec  1.38 GBytes  11.9 Gbits/sec   20   3.01 MBytes       
[  5]   4.00-5.00   sec  1.39 GBytes  11.9 Gbits/sec    0   3.01 MBytes       
[  5]   5.00-6.00   sec  1.40 GBytes  12.0 Gbits/sec    0   3.01 MBytes       
[  5]   6.00-7.00   sec  1.40 GBytes  12.0 Gbits/sec    0   3.01 MBytes       
[  5]   7.00-8.00   sec  1.38 GBytes  11.9 Gbits/sec    0   3.01 MBytes       
[  5]   8.00-9.00   sec  1.39 GBytes  12.0 Gbits/sec    0   3.01 MBytes       
[  5]   9.00-10.00  sec  1.40 GBytes  12.0 Gbits/sec    0   3.01 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  13.9 GBytes  11.9 Gbits/sec  182             sender
[  5]   0.00-10.00  sec  13.9 GBytes  11.9 Gbits/sec                  receiver
```

**Comment by nirs** [comment]
## Comparing to `nat` driver

The `nat` driver does not support VM to VM benchmark so we can test only host-to-vm and vm-to-host.

### Creating the cluster

```
minikube start -p nat --driver vfkit --container-runtime containerd --network nat
kubectl apply -f iper3-server.yaml --context nat
```

### Host to VM benchmark

```console
% iperf3 -c $(minikube ip -p nat) --port 30201                                    
Connecting to host 192.168.106.22, port 30201
[  5] local 192.168.106.1 port 62415 connected to 192.168.106.22 port 30201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.01   sec  1.36 GBytes  11.6 Gbits/sec                  
[  5]   1.01-2.00   sec  1.31 GBytes  11.3 Gbits/sec                  
[  5]   2.00-3.00   sec  1.32 GBytes  11.4 Gbits/sec                  
[  5]   3.00-4.00   sec  1.34 GBytes  11.5 Gbits/sec                  
[  5]   4.00-5.01   sec  1.37 GBytes  11.7 Gbits/sec                  
[  5]   5.01-6.00   sec  1.44 GBytes  12.4 Gbits/sec                  
[  5]   6.00-7.00   sec  1.32 GBytes  11.3 Gbits/sec                  
[  5]   7.00-8.01   sec  1.32 GBytes  11.3 Gbits/sec                  
[  5]   8.01-9.01   sec  1.33 GBytes  11.4 Gbits/sec                  
[  5]   9.01-10.01  sec  1.38 GBytes  11.8 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.01  sec  13.5 GBytes  11.6 Gbits/sec                  sender
[  5]   0.00-10.01  sec  13.5 GBytes  11.6 Gbits/sec                  receiver
```

### VM to host benchmark

```console
% iperf3 -c $(minikube ip -p nat) --port 30201 --reverse
Connecting to host 192.168.106.22, port 30201
Reverse mode, remote host 192.168.106.22 is sending
[  5] local 192.168.106.1 port 62419 connected to 192.168.106.22 port 30201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  7.09 GBytes  60.9 Gbits/sec                  
[  5]   1.00-2.01   sec  7.28 GBytes  62.3 Gbits/sec                  
[  5]   2.01-3.00   sec  7.27 GBytes  62.7 Gbits/sec                  
[  5]   3.00-4.01   sec  7.00 GBytes  60.0 Gbits/sec                  
[  5]   4.01-5.01   sec  6.77 GBytes  58.2 Gbits/sec                  
[  5]   5.01-6.00   sec  7.16 GBytes  61.7 Gbits/sec                  
[  5]   6.00-7.01   sec  7.24 GBytes  62.0 Gbits/sec                  
[  5]   7.01-8.01   sec  7.05 GBytes  60.5 Gbits/sec                  
[  5]   8.01-9.00   sec  7.42 GBytes  63.9 Gbits/sec                  
[  5]   9.00-10.00  sec  6.30 GBytes  54.1 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  70.6 GBytes  60.6 Gbits/sec  2595            sender
[  5]   0.00-10.00  sec  70.6 GBytes  60.6 Gbits/sec                  receiver
```

**Comment by nirs** [comment]
## Comparing to QEMU driver with socket_vmnet

### Creating the clusters

I'm using socket_vment installed from binarry as launchd service:
https://github.com/lima-vm/socket_vmnet?tab=readme-ov-file#from-binary

```console
minikube start -p server --driver qemu --container-runtime containerd --network socket_vmnet
minikube start -p client --driver qemu --container-runtime containerd --network socket_vmnet
kubectl apply -f iper3-server.yaml --context server
kubectl apply -f iper3-client.yaml --context client
```

### Host to VM benchmark

```console
% iperf3 -c $(minikube ip -p server) --port 30201          
Connecting to host 192.168.105.39, port 30201
[  5] local 192.168.105.1 port 59464 connected to 192.168.105.39 port 30201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.01   sec   360 MBytes  3.00 Gbits/sec                  
[  5]   1.01-2.01   sec   364 MBytes  3.05 Gbits/sec                  
[  5]   2.01-3.00   sec   367 MBytes  3.08 Gbits/sec                  
[  5]   3.00-4.01   sec   374 MBytes  3.14 Gbits/sec                  
[  5]   4.01-5.01   sec   368 MBytes  3.08 Gbits/sec                  
[  5]   5.01-6.01   sec   366 MBytes  3.07 Gbits/sec                  
[  5]   6.01-7.01   sec   364 MBytes  3.06 Gbits/sec                  
[  5]   7.01-8.01   sec   358 MBytes  3.00 Gbits/sec                  
[  5]   8.01-9.01   sec   369 MBytes  3.09 Gbits/sec                  
[  5]   9.01-10.01  sec   362 MBytes  3.04 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.01  sec  3.57 GBytes  3.06 Gbits/sec                  sender
[  5]   0.00-10.01  sec  3.56 GBytes  3.06 Gbits/sec                  receiver
```

### VM to host benchmark

```console
% iperf3 -c $(minikube ip -p server) --port 30201 --reverse
Connecting to host 192.168.105.39, port 30201
Reverse mode, remote host 192.168.105.39 is sending
[  5] local 192.168.105.1 port 59470 connected to 192.168.105.39 port 30201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.01   sec   206 MBytes  1.72 Gbits/sec                  
[  5]   1.01-2.00   sec   208 MBytes  1.75 Gbits/sec                  
[  5]   2.00-3.00   sec   209 MBytes  1.74 Gbits/sec                  
[  5]   3.00-4.01   sec   209 MBytes  1.75 Gbits/sec                  
[  5]   4.01-5.01   sec   208 MBytes  1.74 Gbits/sec                  
[  5]   5.01-6.01   sec   209 MBytes  1.75 Gbits/sec                  
[  5]   6.01-7.01   sec   210 MBytes  1.76 Gbits/sec                  
[  5]   7.01-8.01   sec   210 MBytes  1.76 Gbits/sec                  
[  5]   8.01-9.01   sec   189 MBytes  1.58 Gbits/sec                  
[  5]   9.01-10.01  sec   181 MBytes  1.52 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.01  sec  1.99 GBytes  1.71 Gbits/sec  4585            sender
[  5]   0.00-10.01  sec  1.99 GBytes  1.71 Gbits/sec                  receiver
```

### VM to VM benchmark

```console
% kubectl exec deploy/iperf3 --context client -- iperf3 -c $(minikube ip -p server) --port 30201 --forceflush
Connecting to host 192.168.105.39, port 30201
[  5] local 10.244.0.3 port 33452 connected to 192.168.105.39 port 30201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   278 MBytes  2.33 Gbits/sec  378    942 KBytes       
[  5]   1.00-2.00   sec   281 MBytes  2.36 Gbits/sec  435   1.10 MBytes       
[  5]   2.00-3.00   sec   282 MBytes  2.37 Gbits/sec   25   1.26 MBytes       
[  5]   3.00-4.00   sec   282 MBytes  2.37 Gbits/sec    0   1.36 MBytes       
[  5]   4.00-5.00   sec   282 MBytes  2.37 Gbits/sec    0   1.45 MBytes       
[  5]   5.00-6.00   sec   284 MBytes  2.38 Gbits/sec   40   1.55 MBytes       
[  5]   6.00-7.00   sec   281 MBytes  2.36 Gbits/sec   16   1.63 MBytes       
[  5]   7.00-8.00   sec   282 MBytes  2.37 Gbits/sec   49   1.67 MBytes       
[  5]   8.00-9.00   sec   284 MBytes  2.38 Gbits/sec    0   1.75 MBytes       
[  5]   9.00-10.00  sec   278 MBytes  2.33 Gbits/sec    0   1.81 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  2.75 GBytes  2.36 Gbits/sec  943             sender
[  5]   0.00-10.00  sec  2.75 GBytes  2.36 Gbits/sec                  receiver
```

**Comment by nirs** [comment]
## Benchmark results

vfkit with vmnet-shared network is 2.8-5.0 times faster compared with qemu and socket_vment. 

| driver | network      | host to vm   | vm to host   | vm to vm     |
|--------|--------------|--------------|--------------|--------------|
| vfkit  | nat          | 11.6 Gbits/s | 60.6 Gbits/s | n/a          |
| vfkit  | vmnet-shared |  8.3 Gbits/s |  8.4 Gbits/s | 11.9 Gbits/s |
| qemu   | socket_vmnet |  3.0 Gbits/s |  1.7 Gbits/s |  2.4 Gbits/s |

Results are similar to benchmarks with plain vms.

For more complete benchmarks see:
- Comparing to socket_vmnet: https://github.com/nirs/vmnet-helper?tab=readme-ov-file#comparing-to-socket_vment
- Comparing vfkit, krunkit, qemu: https://github.com/nirs/vmnet-helper?tab=readme-ov-file#comparing-different-vms
- All vmnet-helper benchmarks: https://github.com/nirs/vmnet-helper/tree/main/performance

**Comment by nirs** [comment]
@medyagh I rebased and tested again, it should ready now.

File: cmd/minikube/cmd/start_flags.go [hunk 12]
```diff
@@ -503,6 +510,27 @@ func getNetwork(driverName string) string {
 	return n
 }
 
+func validateVfkitNetwork(n string) string {
+	if runtime.GOOS != "darwin" {
+		exit.Message(reason.Usage, "The vfkit driver is only supported on macOS")
+	}
+	switch n {
+	case "nat":
```
Comment (medyagh) [inline cmd/minikube/cmd/start_flags.go:518]: I believe by default the network value is empty, so would "nat" ever be chosen ?

File: cmd/minikube/cmd/start_flags.go [hunk 13]
```diff
@@ -469,9 +470,15 @@ func getCNIConfig(cmd *cobra.Command) string {
 
 func getNetwork(driverName string) string {
 	n := viper.GetString(network)
-	if !driver.IsQEMU(driverName) {
-		return n
+	if driver.IsQEMU(driverName) {
+		return validateQemuNetwork(n)
+	} else if driver.IsVFKit(driverName) {
```
Comment (medyagh) [inline cmd/minikube/cmd/start_flags.go:475]: nit: technically we dont need "else"

File: cmd/minikube/cmd/start_flags.go [hunk 14]
```diff
@@ -503,6 +510,27 @@ func getNetwork(driverName string) string {
...
 
+func validateVfkitNetwork(n string) string {
+	if runtime.GOOS != "darwin" {
+		exit.Message(reason.Usage, "The vfkit driver is only supported on macOS")
+	}
+	switch n {
+	case "nat":
+		// always available
+	case "vmnet-shared":
+		// "vment-shared" provides access between machines, with lower performanced compared to "nat".
```
Comment (medyagh) [inline cmd/minikube/cmd/start_flags.go:521]: performanced-> performance

File: pkg/drivers/vmnet/vmnet.go [hunk 15]
```diff
@@ -0,0 +1,250 @@
...
+)
+
+const (
+	pidfileName    = "vmnet-helper.pid"
+	logfileName    = "vmnet-helper.log"
+	executablePath = "/opt/vmnet-helper/bin/vmnet-helper"
+)
+
+// Helper manages the vmnet-helper process.
+type Helper struct {
```
Comment (medyagh) [inline pkg/drivers/vmnet/vmnet.go:44]: does this need to be exported?

**Review by medyagh — CHANGES_REQUESTED** [review]
thank you @nirs for the PR I left some comments, PTAL, 
additionally, can you plz paste the output of following scenario

1- start minikube with vnmnet-helper
2- delete minikube home folder rm -rf ~/.minikube
3- minikube profile list
4- minikube delete --all 
ideally there should be no left over process but if there is, we should create a follow up issue to clean up the abandoned proceses or left overs

File: cmd/minikube/cmd/start_flags.go (hunk 13 above)
Comment (nirs) [reply cmd/minikube/cmd/start_flags.go:475]: We cannot assume that if it is not QEMU it is vfkit. This is fragile and will lead to bugs when we another driver will use --network and will get the wrong validation from the vfkit case.

File: cmd/minikube/cmd/start_flags.go (hunk 12 above)
Comment (nirs) [reply cmd/minikube/cmd/start_flags.go:518]: Yes, but if you use --network nat we will get "nat" here. If we document that we support "nat" it must be possible to use this value.

File: pkg/drivers/vmnet/vmnet.go (hunk 15 above)
Comment (nirs) [reply pkg/drivers/vmnet/vmnet.go:44]: Yes, the vfkit driver keeps a *vmnet.Helpper in the struct. This helps to call the helper in all the cases that need to access it (start(), Stop(), Kill()).

We can change the design so to have functions accepting the helper arguments but using a Helper seems to fit better with the way drivers are implemented.

File: cmd/minikube/cmd/start_flags.go (hunk 14 above)
Comment (nirs) [reply cmd/minikube/cmd/start_flags.go:521]: Thanks, fixing.

File: pkg/drivers/vmnet/vmnet.go [hunk 16]
```diff
@@ -0,0 +1,250 @@
...
+}
+
+func (h *Helper) pidfilePath() string {
+	return filepath.Join(h.MachineDir, pidfileName)
+}
+
+// Apple recommend receive buffer size to be 4 times the size of the send buffer
+// size, but send buffer size is not used to allocate a buffer in datagram
+// sockets, it only limits the maximum packet size. Must be larger than TSO
+// packets size (65550 bytes).
```
Comment (nirs) [inline pkg/drivers/vmnet/vmnet.go:228]: Update the comment from https://github.com/nirs/vmnet-helper/pull/63/commits/2f103e0181d460068560b0ff159e5fdb353a1d51

File: pkg/drivers/vmnet/vmnet.go [hunk 17]
```diff
@@ -0,0 +1,250 @@
...
+const sendBufferSize = 65 * 1024
+
+// The receive buffer size determine how many packets can be queued by the
+// peer. Using bigger receive buffer size make ENOBUFS error less likely for the
+// peer and improves throughput.
```
Comment (nirs) [inline pkg/drivers/vmnet/vmnet.go:233]: Update the comment from https://github.com/nirs/vmnet-helper/pull/63/commits/2f103e0181d460068560b0ff159e5fdb353a1d51

**Comment by nirs** [comment]
> can you plz paste the output of following scenario

```console
% minikube start --driver vfkit --network vmnet-shared
😄  minikube v1.35.0 on Darwin 15.3.2 (arm64)
✨  Using the vfkit (experimental) driver based on user configuration
👍  Starting "minikube" primary control-plane node in "minikube" cluster
🔥  Creating vfkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
📦  Preparing Kubernetes v1.32.2 on containerd 1.7.23 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default


% rm -rf ~/.minikube 


% minikube profile list

🤹  Exiting due to MK_USAGE_NO_PROFILE: No minikube profile was found.
💡  Suggestion: 

    You can create one using 'minikube start'.
    

% minikube delete --all
🔥  Successfully deleted all profiles


% ps
  PID TTY           TIME CMD
20208 ttys006    0:00.49 /opt/vmnet-helper/bin/vmnet-helper --fd 12 --interface-id 46628bef-da23-4300-b484-55ca102d3cbc
20209 ttys006    0:00.02 vfkit --memory 6000 --cpus 2 --restful-uri unix:///Users/nir/.minikube/machines/minikube/vfkit.sock --device vir
...
```

Tracked in #20605

**Comment by nirs** [comment]
@medyagh thanks for reviewing!

Changes in current version:

- Fix typo in start_flags.go
- Update comments for buffer sizes based on recent changes in vmnet-helper

https://github.com/kubernetes/minikube/compare/7125441c47b515bb30e4e5ff1f8323672c7d158f..4595c49781c9e25c283632264448e235cf0fce36

**Comment by nirs** [comment]
@medyagh anything else to change?

**Comment by nirs** [comment]
Changes in latest version:
- Add minikube version requirement
- Simplify the IMPORTANT alert - github markdown alerts do not work inside tabs
- Make the text more clear
- Fix typos and double words (the the)

https://github.com/kubernetes/minikube/compare/4595c49781c9e25c283632264448e235cf0fce36..27b7ead729a89550bc48203674faa0d1fd2dc93a

@medyagh The PR should be ready now.

**Comment by medyagh** [comment]
thank you @nirs I am excited to try this myself
