### PR TITLE
iso: Enable BTF debug symbols to support eBPF tooling

### LINKED ISSUE #21788: BTF type information is missing since recent kernel update 6.6.95, making eBPF tools such as Tetragon crash on start-up
## Symptom

I was installing [CNCF Tetragon](https://tetragon.io/), a very popular eBPF-based security and observability tool in Minikube v1.37.0 on Windows and it failed with the following message:

```text
level=error msg="Failed to execute tetragon" error="tetragon, aborting kernel autodiscovery failed: kernel version \"6.6.95\" BTF search failed kernel is not included in supported list. Please check Tetragon requirements documentation, then use --btf option to specify BTF path and/or '--kernel' to specify kernel version"
level=info msg="BTF discovery: default kernel btf file does not exist" btf-file=/sys/kernel/btf/vmlinux
level=info msg="BTF discovery: candidate btf file does not exist" btf-file=/var/lib/tetragon/metadata/vmlinux-6.6.95
level=info msg="BTF discovery: candidate btf file does not exist" btf-file=/var/lib/tetragon/btf
```

This worked with Minikube v1.36.0 on Windows.

## Potential root cause

I did some digging in #20995 and found that flags `CONFIG_DEBUG_INFO=y` and `CONFIG_DEBUG_INFO_BTF=y` were removed: https://github.com/kubernetes/minikube/pull/20995/files#diff-fa5e1b16477a9509c25c6d3c289baac93c8456b6a58afb7f087d732842a7a542L519-L520

Was this on purpose? It would be very valuable to have BTF type information, especially in Kubernetes, where many operators use eBPF technology (and BTF type information).

### Footnote

I also came across #19886 and #8556 which mention the tutorial (https://minikube.sigs.k8s.io/docs/tutorials/ebpf_tools_in_minikube/) that seems very outdated; e.g., `minikube ssh -- docker ps` cannot connect to the Docker domain.

### Attach the log file

[log.txt](https://github.com/user-attachments/files/23119865/log.txt)

### Operating System

Windows

### Driver

Hyper-V

### PR DESCRIPTION
**Pull request by blu3r4y**
This PR sets kernel options `CONFIG_DEBUG_INFO_BTF` so that BTF type information is generated, which is necessary for eBPF-based tooling such as Tetragon to work. Additionally, for x86_64 only, it adds the missing, but recommended option `CONFIG_BPF_KPROBE_OVERRIDE` to also support policy enforcement (https://tetragon.io/docs/installation/faq/#what-are-the-linux-kernel-configuration-options-needed-to-run-tetragon).

I already built the image locally and started a cluster like so:

```sh
minikube start --driver=hyperv --iso-url=file://C:/path/to/your/minikube-amd64.iso
```

I temporarily uploaded the ISO files here; I will delete them again in a few weeks:

- [minikube-amd64.iso](https://www.dropbox.com/scl/fi/e5wwqc0q2zjgghrfjlq4u/minikube-amd64.iso?rlkey=sf2r4uc114j09khvz9fmwu80j&st=tf6sere8&dl=0)
- [minikube-arm64.iso](https://www.dropbox.com/scl/fi/lm3bpar7910ybazzh444v/minikube-arm64.iso?rlkey=5gh00huyg6jvdkr5s3ai8sspz&st=xkue2sjr&dl=0)

Tetragon can now successfully discover BTF type information.

```sh
level=info msg="BTF discovery: default kernel btf file found" btf-file=/sys/kernel/btf/vmlinux
level=error msg="unable to read /sys/kernel/security directory" error="open /sys/kernel/security: no such file or directory"
level=info msg="BPF detected features: override_return: true, buildid: true, kprobe_multi: false, uprobe_multi true, fmodret: true, fmodret_syscall: true, signal: true, large: true, link_pin: true, lsm: false, missed_stats_kprobe_multi: false, missed_stats_kprobe: true, batch_update: true"
```

Fixes #21788. Similar intention as closed PR #21622.

I am not sure what other steps are necessary to bump the ISO for minikube.

### CODE REVIEW

**Comment by nirs** [comment]
@blu3r4y thanks! do we have a reason to split this to 2 commits? The commits message do not explain what each commit does and do not provide any justification for the changes.

If there is no reason to split the commits, please squash them. The commit message should explain why every config is needed, since we cannot keep comments in the config files. (they are removed by menuconfig).

It seems that the pr message describes all the details, but this info should be available in git log.

When the change is ready we will build the iso using the iso build job, which will build an iso and add a commit updating minikube to consume this iso.

**Comment by blu3r4y** [comment]
@nirs Squashed the two commits into one and added the full description to the commit message.

**Comment by nirs** [comment]
@blu3r4y thank!

I tested that running linux-menuconfig-* targets does not change the configs and the changes looks good to me.

Can you share instructions on how to test this functionality? Ideally we can add a simple integration tests so future kernel upgrade will not break this functionality again.

/lgtm

**Comment by blu3r4y** [comment]
@nirs I think a simple check if file `/sys/kernel/btf/vmlinux` is present in the image would suffice. I quickly glanced over the existing integration tests and it seems reasonable to add a check to `test/integration/guest_env_test.go`, which is already checking that certain binaries and mounts are available. Something like this could work:

```go
t.Run("Files", func(t *testing.T) {
	// /sys/kernel/btf/vmlinux -- Check if BTF types are present for eBPF tooling
	for _, file := range []string{"/sys/kernel/btf/vmlinux"} {
		file := file
		t.Run(file, func(t *testing.T) {
			t.Parallel()
			rr, err := Run(t, exec.CommandContext(ctx, Target(), "-p", profile, "ssh", fmt.Sprintf("test -f %s && echo 'OK' || echo 'NOT FOUND'", file)))
			if err != nil {
				t.Errorf("failed to verify existence of %q file : args %q: %v", file, rr.Command(), err)
			}

			if !strings.Contains(rr.Stdout.String(), "OK") {
				t.Errorf("expected file %q to exist, but it does not", file)
			}
		})
	}
})
```

I can add another commit to this PR adding a test.

Do you prefer having a test in `guest_env_test.go`, or do you rather prefer having a standalone test?

**Comment by nirs** [comment]
> @nirs I think a simple check if file `/sys/kernel/btf/vmlinux` is present in the image would suffice. I quickly glanced over the existing integration tests and it seems reasonable to add a check to `test/integration/guest_env_test.go`, which is already checking that certain binaries and mounts are available. Something like this could work:
> 
> ```go
> t.Run("Files", func(t *testing.T) {
> 	// /sys/kernel/btf/vmlinux -- Check if BTF types are present for eBPF tooling
> 	for _, file := range []string{"/sys/kernel/btf/vmlinux"} {
> 		file := file
> 		t.Run(file, func(t *testing.T) {
> 			t.Parallel()
> 			rr, err := Run(t, exec.CommandContext(ctx, Target(), "-p", profile, "ssh", fmt.Sprintf("test -f %s && echo 'OK' || echo 'NOT FOUND'", file)))
> 			if err != nil {
> 				t.Errorf("failed to verify existence of %q file : args %q: %v", file, rr.Command(), err)
> 			}
> 
> 			if !strings.Contains(rr.Stdout.String(), "OK") {
> 				t.Errorf("expected file %q to exist, but it does not", file)
> 			}
> 		})
> 	}
> })
> ```
> 
> I can add another commit to this PR adding a test.
> 
> Do you prefer having a test in `guest_env_test.go`, or do you rather prefer having a standalone test?

guest_env_test.go looks perfect for this test.

A generic Files test that we can extend later looks good, but it will help to add a description for every file. Maybe add a more specific BTF test instead? This will make it easy to document the test and add more checks later if we want to test more details.

A link to the issue in the test will help to understand why the test is needed.

**Comment by nirs** [comment]
Tested on macOS with #21801:

```
% go test -v ./test/integration -run TestISO -tags integration -count 1
# github.com/shoenig/go-m1cpu
../../go/pkg/mod/github.com/shoenig/go-m1cpu@v0.1.6/cpu.go:75:17: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
../../go/pkg/mod/github.com/shoenig/go-m1cpu@v0.1.6/cpu.go:77:16: warning: variable length array folded to constant array as an extension [-Wgnu-folding-constant]
Found 12 cores, limiting parallelism with --test.parallel=6
=== RUN   TestISOImage
=== PAUSE TestISOImage
=== CONT  TestISOImage
=== RUN   TestISOImage/Setup
    iso_test.go:46: (dbg) Run:  out/minikube start -p guest-637000 --install-addons=false --memory=3072 --wait=false --disable-metrics=true 
    iso_test.go:46: (dbg) Done: out/minikube start -p guest-637000 --install-addons=false --memory=3072 --wait=false --disable-metrics=true : (16.966088167s)
=== RUN   TestISOImage/Binaries
=== RUN   TestISOImage/Binaries/crictl
=== PAUSE TestISOImage/Binaries/crictl
=== RUN   TestISOImage/Binaries/curl
=== PAUSE TestISOImage/Binaries/curl
=== RUN   TestISOImage/Binaries/docker
=== PAUSE TestISOImage/Binaries/docker
=== RUN   TestISOImage/Binaries/git
=== PAUSE TestISOImage/Binaries/git
=== RUN   TestISOImage/Binaries/iptables
=== PAUSE TestISOImage/Binaries/iptables
=== RUN   TestISOImage/Binaries/podman
=== PAUSE TestISOImage/Binaries/podman
=== RUN   TestISOImage/Binaries/rsync
=== PAUSE TestISOImage/Binaries/rsync
=== RUN   TestISOImage/Binaries/socat
=== PAUSE TestISOImage/Binaries/socat
=== RUN   TestISOImage/Binaries/wget
=== PAUSE TestISOImage/Binaries/wget
=== CONT  TestISOImage/Binaries/crictl
=== CONT  TestISOImage/Binaries/podman
=== NAME  TestISOImage/Binaries/crictl
    iso_test.go:79: (dbg) Run:  out/minikube -p guest-637000 ssh "which crictl"
=== NAME  TestISOImage/Binaries/podman
    iso_test.go:79: (dbg) Run:  out/minikube -p guest-637000 ssh "which podman"
=== CONT  TestISOImage/Binaries/iptables
=== CONT  TestISOImage/Binaries/git
=== CONT  TestISOImage/Binaries/docker
=== CONT  TestISOImage/Binaries/curl
    iso_test.go:79: (dbg) Run:  out/minikube -p guest-637000 ssh "which curl"
=== NAME  TestISOImage/Binaries/docker
    iso_test.go:79: (dbg) Run:  out/minikube -p guest-637000 ssh "which docker"
=== NAME  TestISOImage/Binaries/git
    iso_test.go:79: (dbg) Run:  out/minikube -p guest-637000 ssh "which git"
=== NAME  TestISOImage/Binaries/iptables
    iso_test.go:79: (dbg) Run:  out/minikube -p guest-637000 ssh "which iptables"
=== CONT  TestISOImage/Binaries/socat
    iso_test.go:79: (dbg) Run:  out/minikube -p guest-637000 ssh "which socat"
=== CONT  TestISOImage/Binaries/wget
    iso_test.go:79: (dbg) Run:  out/minikube -p guest-637000 ssh "which wget"
=== CONT  TestISOImage/Binaries/rsync
    iso_test.go:79: (dbg) Run:  out/minikube -p guest-637000 ssh "which rsync"
=== RUN   TestISOImage/PersistentMounts
=== RUN   TestISOImage/PersistentMounts//data
=== PAUSE TestISOImage/PersistentMounts//data
=== RUN   TestISOImage/PersistentMounts//var/lib/docker
=== PAUSE TestISOImage/PersistentMounts//var/lib/docker
=== RUN   TestISOImage/PersistentMounts//var/lib/cni
=== PAUSE TestISOImage/PersistentMounts//var/lib/cni
=== RUN   TestISOImage/PersistentMounts//var/lib/kubelet
=== PAUSE TestISOImage/PersistentMounts//var/lib/kubelet
=== RUN   TestISOImage/PersistentMounts//var/lib/minikube
=== PAUSE TestISOImage/PersistentMounts//var/lib/minikube
=== RUN   TestISOImage/PersistentMounts//var/lib/toolbox
=== PAUSE TestISOImage/PersistentMounts//var/lib/toolbox
=== RUN   TestISOImage/PersistentMounts//var/lib/boot2docker
=== PAUSE TestISOImage/PersistentMounts//var/lib/boot2docker
=== CONT  TestISOImage/PersistentMounts//data
=== CONT  TestISOImage/PersistentMounts//var/lib/minikube
=== CONT  TestISOImage/PersistentMounts//var/lib/cni
=== CONT  TestISOImage/PersistentMounts//var/lib/docker
=== NAME  TestISOImage/PersistentMounts//var/lib/cni
    iso_test.go:100: (dbg) Run:  out/minikube -p guest-637000 ssh "df -t ext4 /var/lib/cni | grep /var/lib/cni"
=== NAME  TestISOImage/PersistentMounts//data
    iso_test.go:100: (dbg) Run:  out/minikube -p guest-637000 ssh "df -t ext4 /data | grep /data"
=== CONT  TestISOImage/PersistentMounts//var/lib/boot2docker
    iso_test.go:100: (dbg) Run:  out/minikube -p guest-637000 ssh "df -t ext4 /var/lib/boot2docker | grep /var/lib/boot2docker"
=== CONT  TestISOImage/PersistentMounts//var/lib/kubelet
    iso_test.go:100: (dbg) Run:  out/minikube -p guest-637000 ssh "df -t ext4 /var/lib/kubelet | grep /var/lib/kubelet"
=== NAME  TestISOImage/PersistentMounts//var/lib/minikube
    iso_test.go:100: (dbg) Run:  out/minikube -p guest-637000 ssh "df -t ext4 /var/lib/minikube | grep /var/lib/minikube"
=== NAME  TestISOImage/PersistentMounts//var/lib/docker
    iso_test.go:100: (dbg) Run:  out/minikube -p guest-637000 ssh "df -t ext4 /var/lib/docker | grep /var/lib/docker"
=== CONT  TestISOImage/PersistentMounts//var/lib/toolbox
    iso_test.go:100: (dbg) Run:  out/minikube -p guest-637000 ssh "df -t ext4 /var/lib/toolbox | grep /var/lib/toolbox"
=== RUN   TestISOImage/eBPFSupport
    iso_test.go:111: (dbg) Run:  out/minikube -p guest-637000 ssh "test -f /sys/kernel/btf/vmlinux && echo 'OK' || echo 'NOT FOUND'"
=== NAME  TestISOImage
    helpers_test.go:175: Cleaning up "guest-637000" profile ...
    helpers_test.go:178: (dbg) Run:  out/minikube delete -p guest-637000
--- PASS: TestISOImage (17.51s)
    --- PASS: TestISOImage/Setup (16.97s)
    --- PASS: TestISOImage/Binaries (0.00s)
        --- PASS: TestISOImage/Binaries/podman (0.08s)
        --- PASS: TestISOImage/Binaries/crictl (0.09s)
        --- PASS: TestISOImage/Binaries/iptables (0.09s)
        --- PASS: TestISOImage/Binaries/git (0.10s)
        --- PASS: TestISOImage/Binaries/curl (0.10s)
        --- PASS: TestISOImage/Binaries/docker (0.10s)
        --- PASS: TestISOImage/Binaries/wget (0.06s)
        --- PASS: TestISOImage/Binaries/socat (0.07s)
        --- PASS: TestISOImage/Binaries/rsync (0.07s)
    --- PASS: TestISOImage/PersistentMounts (0.00s)
        --- PASS: TestISOImage/PersistentMounts//var/lib/boot2docker (0.08s)
        --- PASS: TestISOImage/PersistentMounts//var/lib/kubelet (0.09s)
        --- PASS: TestISOImage/PersistentMounts//var/lib/docker (0.10s)
        --- PASS: TestISOImage/PersistentMounts//data (0.10s)
        --- PASS: TestISOImage/PersistentMounts//var/lib/minikube (0.10s)
        --- PASS: TestISOImage/PersistentMounts//var/lib/cni (0.11s)
        --- PASS: TestISOImage/PersistentMounts//var/lib/toolbox (0.07s)
    --- PASS: TestISOImage/eBPFSupport (0.06s)
PASS
Tests completed in 17.507941083s (result code 0)
ok  	k8s.io/minikube/test/integration	18.736s
```

**Comment by nirs** [comment]
@blu3r4y can you test and confirm that this works for your use case?

You don't need to use any flag, if run minikube built with this PR is will use the right iso.

The tests looks good - the relevant tests are:
- [KVM_Linux](https://storage.googleapis.com/minikube-builds/logs/21800/42072/KVM_Linux.html)
- [KVM_Linux_containerd](https://storage.googleapis.com/minikube-builds/logs/21800/42072/KVM_Linux_containerd.html)
- [KVM_Linux_crio](https://storage.googleapis.com/minikube-builds/logs/21800/42072/KVM_Linux_crio.html) - has 3 known failures
- [Hyper-V_Windows](https://storage.googleapis.com/minikube-builds/logs/21800/42072/Hyper-V_Windows.pending) - never seen this test completed, seems that the CI is broken.

The rest of the tests do not use the ISO.

You can ignore the failing integration-* tests. We are moving tests to [Prow](https://docs.prow.k8s.io/docs/build-test-update/) and unfortunately new broken tests were added recently.

**Comment by blu3r4y** [comment]
@nirs I just built the binary locally of this PR and ran it on Windows 11 for my use case:

```sh
minikube-windows-amd64.exe --driver=hyperv --container-runtime=containerd --kubernetes-version=v1.34.0
```

Then, I installed Tetragon in its standard configuration:

```sh
helm repo add cilium https://helm.cilium.io
helm repo update
helm install tetragon cilium/tetragon -n kube-system
kubectl rollout status -n kube-system ds/tetragon -w
```

Everything is working flawlessly. I also let it execute the full test suite that we have internally, which includes creating and testing a few `TracingPolicy` objects from Tetragon. That is working now with this build. 🎉

**Comment by nirs** [comment]
@medyagh seems ready for merge.

/assign @medyagh

**Comment by nirs** [comment]
@blu3r4y #21801 was merged today. Can you rebase on master and resolve the conflict?

**Comment by blu3r4y** [comment]
@nirs Rebased. If I am not mistaken, I believe the ISO needs to be built again by the bot as well.

**Comment by nirs** [comment]
> @nirs Rebased. If I am not mistaken, I believe the ISO needs to be built again by the bot as well.

If you rebased on master and there was no conflict in this commit:
https://github.com/kubernetes/minikube/pull/21800/commits/610475690f25e81a4dae1529041740c058924ea4

It means that the ISO did not update and the one we built in this PR is still valid. If there was a conflict, it means that the ISO was updated by another PR, and we need to rebuild to build with the latest source.

If we need to build again, delete the ISO commit and we can start a new build.

**Comment by blu3r4y** [comment]
Removed the ISO commit so that it can be rebuilt with the latest source after rebasing (there was a conflict, yes).

File: test/integration/iso_test.go [hunk 1]
```diff
@@ -99,4 +99,17 @@ func TestISOImage(t *testing.T) {
...
+
+	t.Run("eBPFSupport", func(t *testing.T) {
+		// Ensure that BTF type information is available (https://github.com/kubernetes/minikube/issues/21788)
+		btfFile := "/sys/kernel/btf/vmlinux"
+		rr, err := Run(t, exec.CommandContext(ctx, Target(), "-p", profile, "ssh", fmt.Sprintf("test -f %s && echo 'OK' || echo 'NOT FOUND'", btfFile)))
+		if err != nil {
+			t.Errorf("failed to verify existence of %q file: args %q: %v", btfFile, rr.Command(), err)
+		}
+
+		if !strings.Contains(rr.Stdout.String(), "OK") {
```
Comment (nirs) [inline test/integration/iso_test.go:112]: @blu3r4y the strings package is not imported. It was imported before the rebase, but removed when we switched to —no-kubernetes.

Comment (blu3r4y) [reply test/integration/iso_test.go:112]: Sorry for missing that. Fixed.

**Comment by blu3r4y** [comment]
I built the Windows binary locally again with the new ISO and can confirm that Minikube and Tetragon are still working for me.

**Comment by medyagh** [comment]
thank you @blu3r4y for fixing this regression

**Comment by blu3r4y** [comment]
sure thing, thanks @nirs for the amazing guidance and support 👏
