### PR TITLE
none driver: Only require docker for the docker runtime

### LINKED ISSUE #3295: the "none" driver does not use correct container runtime
BUG REPORT

Currently the "none" driver is hardcoded to look for docker: cb8d3c027cd9839fce836418ec59e0442a4a0896

It should look at the `--container-runtime`, and adjust accordingly...

(From #3153)

### PR DESCRIPTION
**Pull request by afbjorklund**
Closes #3295

### CODE REVIEW

**Comment by tstromberg** [comment]
I'm curious what's going on here with the None integration test. Any idea?

```shell
Nov 06 20:11:29 kvm-integration-slave kubelet[27898]: F1106 20:11:29.993813   27898 server.go:233] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Nov 06 20:11:29 kvm-integration-slave systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Nov 06 20:11:29 kvm-integration-slave systemd[1]: kubelet.service: Unit entered failed state.
```

**Comment by afbjorklund** [comment]
@tstromberg: nothing strange, it's a bug in the code - will upload a fixed version

**Comment by tstromberg** [comment]
OK, the existing none failure appears to be an unrelated issue - one that's responsible for 12.7% of 7 day test failures: https://github.com/kubernetes/minikube/issues/3312

I'll get our test host sorted out and retest.

**Comment by tstromberg** [comment]
@minikube-bot OK to test

File: pkg/drivers/none/none.go [hunk 1]
```diff
@@ -54,11 +55,13 @@ func NewDriver(hostName, storePath string) *Driver {
 
 // PreCreateCheck checks for correct privileges and dependencies
 func (d *Driver) PreCreateCheck() error {
-	// check that docker is on path
-	_, err := exec.LookPath("docker")
-	if err != nil {
-		return errors.Wrap(err, "docker cannot be found on the path for this machine. "+
-			"A docker installation is a requirement for using the none driver")
+	if d.ContainerRuntime == "" {
```
Comment (balopat) [inline pkg/drivers/none/none.go]: I'd extract this into a method: `isDockerRuntime`

File: pkg/minikube/config/types.go [hunk 2]
```diff
@@ -35,6 +35,7 @@ type MachineConfig struct {
 	CPUs                int
 	DiskSize            int
 	VMDriver            string
+	ContainerRuntime    string
```
Comment (balopat) [inline pkg/minikube/config/types.go]: 1. this duplicates the config between `MachineConfig` and `KubernetesConfig`  
2. if there is no way to get rid of this duplication, and this is really the best way to propagate this flag to the driver, I'd comment similar to the other fields of this struct `// only used by the None driver`

Comment (afbjorklund) [reply pkg/minikube/config/types.go]: KubernetesConfig is too late, since the provisioning is done before the bootstrapping

File: pkg/drivers/none/none.go (hunk 1 above)
Comment (afbjorklund) [reply pkg/drivers/none/none.go]: Just into a local function ? Sure, that can be done
