### PR TITLE
Change PreloadExists to report no preload for BareMetal drivers

### LINKED ISSUE #11526: TestDownloadOnly failing

### PR DESCRIPTION
**Pull request by andriyDev**
fixes #11526.

Previously, PreloadExists would report true for none driver. Now it doesn't (as expected)!

### CODE REVIEW

**Review by medyagh — CHANGES_REQUESTED** [review]
I belive SSH driver would need the binaries too (maybe)
since that is also without virtualization
I dont think preload works on SSH driver

how about adding a new func here
```

// BareMetal returns if this driver is unisolated
func BareMetal(name string) bool {
	return name == None || name == Mock
}

// IsSSH checks if the driver is ssh
func IsSSH(name string) bool {
	return name == SSH
}
```

that is like

```
driver.NeedsDownloadK8SBinaries....

and then returns true if Baremetal or SSH
```

File: pkg/minikube/download/preload.go [hunk 1]
```diff
@@ -97,8 +98,12 @@ func remoteTarballURL(k8sVersion, containerRuntime string) string {
 	return fmt.Sprintf("https://storage.googleapis.com/%s/%s", PreloadBucket, TarballName(k8sVersion, containerRuntime))
 }
 
+func driverAllowsPreload(driverName string) bool {
```
Comment (medyagh) [inline pkg/minikube/download/preload.go:101]: driver.AllowsPreload(

**Review by medyagh — CHANGES_REQUESTED** [review]

**Comment by medyagh** [comment]
@andriyDev your PR looks good

**Review by medyagh — APPROVED** [review]
