### PR TITLE
drivers/kvm: Use ARP for retrieving interface ip addresses

### LINKED ISSUE #11459: Minikube start failure in CentOS
Hi, we are running CentOS jobs with Minikube in our CI, and builds flake out when minikube starts 20-30% of the time. Below are the **steps to reproduce the issue:** 
1. Centos 8.3 VM running in the Cloud 

```
$cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

```
2. Installed minikube version: v1.20.0 configured with 
`minikube config set vm-driver kvm2`
`minikube config set memory 4096`
3. Below script is run to reproduce the issue. 

```
 #!/bin/bash

MINIKUBE="minikube"

$MINIKUBE config set vm-driver kvm2
$MINIKUBE config set memory 4096

while /bin/true; do  
  $MINIKUBE delete  
  if ! $MINIKUBE start -v=9 --alsologtostderr > /tmp/minikubefail 2>&1; then    
    exit 0  
  fi
done
```

**Full output of `minikube logs` command:**
Logs from Minikube v1.18
```
`+ sudo su -l -c 'minikube start --insecure-registry 192.168.111.1:5000' ****
* minikube v1.18.1 on Centos 8.3.2011 (kvm/amd64)
* minikube 1.19.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.19.0
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

* Using the kvm2 driver based on user configuration

X Exiting due to PROVIDER_KVM2_ERROR: /usr/bin/virsh domcapabilities --virttype kvm failed:

* Suggestion: Follow your Linux distribution instructions for configuring KVM
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/ `
```

Logs from  Minikube v1.19
```
`+ sudo su -l -c 'minikube start --insecure-registry 192.168.111.1:5000' ****
* minikube v1.19.0 on Centos 8.3.2011 (kvm/amd64)
* Using the kvm2 driver based on user configuration
* Downloading VM boot image ...
    > minikube-v1.19.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s    > minikube-v1.19.0.iso: 16.00 MiB / 244.49 MiB [>___________] 6.54% ? p/s ?    > minikube-v1.19.0.iso: 43.95 MiB / 244.49 MiB [->_________] 17.98% ? p/s ?    > minikube-v1.19.0.iso: 48.00 MiB / 244.49 MiB [-->________] 19.63% ? p/s ?    > minikube-v1.19.0.iso: 71.01 MiB / 244.49 MiB  29.05% 91.82 MiB p/s ETA 1s    > minikube-v1.19.0.iso: 92.25 MiB / 244.49 MiB  37.73% 91.82 MiB p/s ETA 1s    > minikube-v1.19.0.iso: 129.89 MiB / 244.49 MiB  53.13% 91.82 MiB p/s ETA 1    > minikube-v1.19.0.iso: 182.14 MiB / 244.49 MiB  74.50% 97.85 MiB p/s ETA 0    > minikube-v1.19.0.iso: 229.50 MiB / 244.49 MiB  93.87% 97.85 MiB p/s ETA 0    > minikube-v1.19.0.iso: 244.49 MiB / 244.49 MiB  100.00% 168.40 MiB p/s 1.6* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.20.2 preload ...
    > preloaded-images-k8s-v10-v1...: 16.00 MiB / 491.71 MiB [>_] 3.25% ? p/s ?    > preloaded-images-k8s-v10-v1...: 48.00 MiB / 491.71 MiB [>_] 9.76% ? p/s ?    > preloaded-images-k8s-v10-v1...: 77.75 MiB / 491.71 MiB [>] 15.81% ? p/s ?    > preloaded-images-k8s-v10-v1...: 120.00 MiB / 491.71 MiB  24.40% 173.19 Mi    > preloaded-images-k8s-v10-v1...: 159.17 MiB / 491.71 MiB  32.37% 173.19 Mi    > preloaded-images-k8s-v10-v1...: 190.86 MiB / 491.71 MiB  38.82% 173.19 Mi    > preloaded-images-k8s-v10-v1...: 238.47 MiB / 491.71 MiB  48.50% 174.77 Mi    > preloaded-images-k8s-v10-v1...: 257.19 MiB / 491.71 MiB  52.30% 174.77 Mi    > preloaded-images-k8s-v10-v1...: 304.64 MiB / 491.71 MiB  61.95% 174.77 Mi    > preloaded-images-k8s-v10-v1...: 344.00 MiB / 491.71 MiB  69.96% 174.82 Mi    > preloaded-images-k8s-v10-v1...: 349.69 MiB / 491.71 MiB  71.12% 174.82 Mi    > preloaded-images-k8s-v10-v1...: 379.53 MiB / 491.71 MiB  77.19% 174.82 Mi    > preloaded-images-k8s-v10-v1...: 430.19 MiB / 491.71 MiB  87.49% 172.82 Mi    > preloaded-images-k8s-v10-v1...: 438.08 MiB / 491.71 MiB  89.09% 172.82 Mi    > preloaded-images-k8s-v10-v1...: 480.00 MiB / 491.71 MiB  97.62% 172.82 Mi    > preloaded-images-k8s-v10-v1...: 491.71 MiB / 491.71 MiB  100.00% 164.22 M* Creating kvm2 VM (CPUs=2, Memory=4096MB, Disk=20000MB) ...
* Deleting "minikube" in kvm2 ...
! StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute
* Creating kvm2 VM (CPUs=2, Memory=4096MB, Disk=20000MB) ...
* Failed to start kvm2 VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute
* 
* If the above advice does not help, please let us know: 
  https://github.com/kubernetes/minikube/issues/new/choose  `
```

**Full output of failed command:**

Output of minikubefail file: [paste.openstack](http://paste.openstack.org/show/805488/)

### PR DESCRIPTION
**Pull request by anoopcs9**
On platforms where dhcp lease status is not updated immediately after domain creation it fails to list ip addresses until next refresh happens resulting in the following error:
```
🔥  Creating kvm2 VM (CPUs=2, Memory=4096MB, Disk=20480MB) ...
🔥  Deleting "minikube" in kvm2 ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute
🔥  Creating kvm2 VM (CPUs=2, Memory=4096MB, Disk=20480MB) ...
😿  Failed to start kvm2 VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP not available after waiting: machine minikube didn't return IP after 1 minute
```
Using ARP instead of LEASE for ip address query is justifiable as listing is done following the domain creation.

fixes #11459

### CODE REVIEW

**Comment by medyagh** [comment]
@anoopcs9 I an curious do u mind listing what platfroms are like that ?

and should we fall back to the old system in case this one fails as a fail over?

File: pkg/drivers/kvm/network.go [hunk 1]
```diff
@@ -478,7 +478,7 @@ func ifListFromAPI(conn *libvirt.Connect, domain string) ([]libvirt.DomainInterf
 	}
 	defer func() { _ = dom.Free() }()
 
-	ifs, err := dom.ListAllInterfaceAddresses(libvirt.DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE)
+	ifs, err := dom.ListAllInterfaceAddresses(libvirt.DOMAIN_INTERFACE_ADDRESSES_SRC_ARP)
```
Comment (medyagh) [inline pkg/drivers/kvm/network.go:481]: how about in case of Error, we try the Old way ? as a fail over

**Comment by medyagh** [comment]
@anoopcs9 Thank you for this PR, do u mind sigining the CLA so we could accept contributions?

File: pkg/drivers/kvm/network.go (hunk 1 above)
Comment (anoopcs9) [reply pkg/drivers/kvm/network.go:481]: Hm..not sure.

There are 2 possibilities(as we have with `DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE`):
* `ListAllinterfaceAddresses` is success and returns nothing(very rare to occur. we should at least have address from **default** network)
* `ListAllinterfaceAddresses` fails to list returning an error

Here's my suggestion. We can fall back in case `DOMAIN_INTERFACE_ADDRESSES_SRC_ARP` fails but log differently in above two scenarios.

**Comment by anoopcs9** [comment]
> @anoopcs9 I an curious do u mind listing what platfroms are like that ?

I was facing problems with CentOS 8(8.5) as mentioned in linked issue #11459. I have also shared my findings as a [comment](https://github.com/kubernetes/minikube/issues/11459#issuecomment-1020396625) on the issue.
 
> and should we fall back to the old system in case this one fails as a fail over?

see my inline reply

**Comment by anoopcs9** [comment]
> @anoopcs9 Thank you for this PR, do u mind sigining the CLA so we could accept contributions?

I think I did as soon as bot told me its missing(see above [comment](https://github.com/kubernetes/minikube/pull/13482#issuecomment-1020941528)). It says **COVERED**. May be CLA check is not (re)run afterwards??

File: pkg/drivers/kvm/network.go (hunk 1 above)
Comment (medyagh) [reply pkg/drivers/kvm/network.go:481]: yeah that sounds like a good idea lets do a fall back and log

Comment (anoopcs9) [reply pkg/drivers/kvm/network.go:481]: Done

**Comment by anoopcs9** [comment]
> Too many tests failed - See test logs for more details.

@medyagh, What to do with these failures? I hope the change from this PR is not the culprit :-/

**Comment by spowelljr** [comment]
> > Too many tests failed - See test logs for more details.
> 
> @medyagh, What to do with these failures? I hope the change from this PR is not the culprit :-/

The failures are not unexpected, the rightmost column is what % of the time they fail.

File: pkg/drivers/kvm/network.go [hunk 2]
```diff
@@ -478,9 +478,19 @@ func ifListFromAPI(conn *libvirt.Connect, domain string) ([]libvirt.DomainInterf
 	}
 	defer func() { _ = dom.Free() }()
 
-	ifs, err := dom.ListAllInterfaceAddresses(libvirt.DOMAIN_INTERFACE_ADDRESSES_SRC_LEASE)
-	if err != nil {
-		return nil, fmt.Errorf("failed listing network interface addresses of domain %s: %w", domain, err)
+	ifs, err := dom.ListAllInterfaceAddresses(libvirt.DOMAIN_INTERFACE_ADDRESSES_SRC_ARP)
+	if ifs == nil {
+		if err != nil {
+			log.Debugf("failed listing network interace addresses of domain %s(source=arp): %w", domain, err)
```
Comment (medyagh) [inline pkg/drivers/kvm/network.go:484]: log.Debugf("failed listing network interace addresses of domain %s(source=arp): %w", domain, err)
```suggestion
			log.Debugf("failed listing network interface addresses of domain %s(source=arp): %w", domain, err)
```

**Comment by medyagh** [comment]
thank you very  much @anoopcs9 for improving the KVM driver, just a minor spelling error then we are good to go !

File: pkg/drivers/kvm/network.go (hunk 2 above)
Comment (anoopcs9) [reply pkg/drivers/kvm/network.go]: Ah..
..and fixed now.

**Comment by anoopcs9** [comment]
I signed it

**Comment by anoopcs9** [comment]
> > @anoopcs9 Thank you for this PR, do u mind sigining the CLA so we could accept contributions?
> 
> I think I did as soon as bot told me its missing(see above [comment](https://github.com/kubernetes/minikube/pull/13482#issuecomment-1020941528)). It says **COVERED**. May be CLA check is not (re)run afterwards??

My bad. I had accidentally revoked authorization for **Linux Foundation: EasyCLA** OAuth App. I have reauthorized and it passes now.

**Comment by anoopcs9** [comment]
I signed it

**Comment by medyagh** [comment]
@anoopcs9  I am curious hve u signed the CLA with the same email in your git config from the time u did "git commit"

do u mind checking ?
```
 cat ~/.gitconfig | grep email
```

**Comment by anoopcs9** [comment]
> @anoopcs9 I am curious hve u signed the CLA with the same email in your git config from the time u did "git commit"
> 
> do u mind checking ?
> 
> ```
>  cat ~/.gitconfig | grep email
> ```

It was to do with my LF account.
Finally. after fiddling with LF account-username-email modifications, CLA check now passes.

**Review by sharifelgamal — APPROVED** [review]

**Comment by sharifelgamal** [comment]
Thank you for your contribution!
