### PR TITLE
Validate minimum docker version

### LINKED ISSUE #10282: Add solution message for unsupported legacy docker versions
We do not support old docker daemon versions in docker driver  because of `docker network inspect minikube` output format. But the error message is very confusing (see below).  We need to check docker version on start and if it's too old (>18.06.3 should be fine, but need to verify) we should report an error and exit

```
ilyaz@debian:~$ minikube start 
* minikube v1.17.0 on Debian 8.11
* Using the docker driver based on existing profile
! For improved Docker performance, enable the overlay Linux kernel module using 'modprobe overlay'
! docker is currently using the aufs storage driver, consider switching to overlay2 for better performance
* Starting control plane node minikube in cluster minikube
* Updating the running docker "minikube" container ...
* Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...| E0127 11:53:35.789213    2598 start.go:99] Unable to get host IP: network inspect: docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}": exit status 64
stdout:

stderr:
Template parsing error: template: :1: unexpected "=" in operand
E0127 11:53:35.789800    2598 out.go:330] unable to execute Failed to setup kubeconfig: network inspect: docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}": exit status 64
stdout:

stderr:
Template parsing error: template: :1: unexpected "=" in operand
: template: Failed to setup kubeconfig: network inspect: docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}": exit status 64
stdout:

stderr:
Template parsing error: template: :1: unexpected "=" in operand
:1:253: executing "Failed to setup kubeconfig: network inspect: docker network inspect minikube --format \"{\"Name\": \"{{.Name}}\",\"Driver\": \"{{.Driver}}\",\"Subnet\": \"{{range .IPAM.Config}}{{.Subnet}}{{end}}\",\"Gateway\": \"{{range .IPAM.Config}}{{.Gateway}}{{end}}\",\"MTU\": {{if (index .Options \"com.docker.network.driver.mtu\")}}{{(index .Options \"com.docker.network.driver.mtu\")}}{{else}}0{{end}},{{$first := true}} \"ContainerIPs\": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}\"{{$v.IPv4Address}}\"{{end}}]}\": exit status 64\nstdout:\n\nstderr:\nTemplate parsing error: template: :1: unexpected \"=\" in operand\n" at <index .Options "com.docker.network.driver.mtu">: error calling index: index of untyped nil - returning raw string.


X Exiting due to GUEST_START: Failed to setup kubeconfig: network inspect: docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}": exit status 64
stdout:

stderr:
Template parsing error: template: :1: unexpected "=" in operand

* 
* If the above advice does not help, please let us know: 
  - https://github.com/kubernetes/minikube/issues/new/choose
 ```

```
ilyaz@debian:~$ uname -a
Linux debian 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux
```
```
ilyaz@debian:~$ docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:28:55 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:27:21 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
```
ilyaz@debian:~$ minikube version
minikube version: v1.17.0
commit: 691a62dc8fffc4ce30befa53980d7b680b23a31f
```
```
ilyaz@debian:~$ cat /etc/issue
Debian GNU/Linux 8 \n \l
```

### PR DESCRIPTION
**Pull request by daehyeok**
fix #10282

### CODE REVIEW

File: pkg/minikube/registry/drvs/docker/docker.go [hunk 1]
```diff
@@ -37,6 +38,7 @@ import (
 )
 
 var docURL = "https://minikube.sigs.k8s.io/docs/drivers/docker/"
+var minDockerVersion = []int{18, 7, 0}
```
Comment (medyagh) [inline pkg/minikube/registry/drvs/docker/docker.go:41]: lets to our documentation to let them know the min version supported is 18.7.0

https://minikube.sigs.k8s.io/docs/drivers/docker/

Comment (daehyeok) [reply pkg/minikube/registry/drvs/docker/docker.go:41]: Add ' 18.07 or higher' statement into `site/content/en/docs/drivers/includes/docker_usage.inc` file

File: pkg/minikube/registry/drvs/docker/docker.go [hunk 2]
```diff
@@ -130,6 +132,75 @@ func status() registry.State {
...
+		if k > minDockerVersion[i] {
+			return registry.State{Installed: true, Healthy: true, Error: nil}
+		} else if k < minDockerVersion[i] {
+			return registry.State{
+				Reason:           "PROVIDER_DOCKER_VERSION_LOW",
+				Error:            oci.ErrMinDockerVersion,
+				Installed:        true,
+				Healthy:          false,
+				NeedsImprovement: true,
+				Fix:              fmt.Sprintf("Upgrade docker server to a newer version (Minimum supproted version is %2d.%2d.%2d)", minDockerVersion[0], minDockerVersion[1], minDockerVersion[2]),
```
Comment (medyagh) [inline pkg/minikube/registry/drvs/docker/docker.go:196]: no need to say docker server, you should also use this function
https://github.com/medyagh/minikube/blob/72443005764661ff12dafedee6c0afed4829b379/pkg/minikube/driver/driver.go#L193

driver.FullName(ds.Name)

so it will give the right name for the user

simmilar to 
https://github.com/medyagh/minikube/blob/72443005764661ff12dafedee6c0afed4829b379/cmd/minikube/cmd/start.go#L716

File: pkg/minikube/registry/drvs/docker/docker_test.go [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+	patchPostFix := "20180720214833-f61e0f7"
+
+	vs := fmt.Sprintf("%02d.%02d.%d", v[0], v[1], v[2])
+	appendedTc = append(appendedTc, []testCase{
+		{
+			version: fmt.Sprintf("linux-%s", vs),
+			expect:  reason,
+		},
+		{
+			version: fmt.Sprintf("linux-%s-%s", vs, patchPostFix),
```
Comment (medyagh) [inline pkg/minikube/registry/drvs/docker/docker_test.go:46]: can we add unit test for Mac Os Docker Versions too ? ensure the output of docker verison on mac os and windows are covered in the unit test

**Review by medyagh — CHANGES_REQUESTED** [review]

File: site/content/en/docs/drivers/includes/docker_usage.inc [hunk 4]
```diff
@@ -1,6 +1,6 @@
 ## Requirements
 
-- [Install Docker](https://hub.docker.com/search?q=&type=edition&offering=community&sort=updated_at&order=desc)
+- [Install Docker](https://hub.docker.com/search?q=&type=edition&offering=community&sort=updated_at&order=desc) 18.07 or higher
```
Comment (afbjorklund) [inline site/content/en/docs/drivers/includes/docker_usage.inc:3]: Docker 18.07 does not exist, I think you meant 18.09 ?

See https://docs.docker.com/engine/release-notes/

**Review by afbjorklund — CHANGES_REQUESTED** [review]

File: site/content/en/docs/drivers/includes/docker_usage.inc (hunk 4 above)
Comment (medyagh) [reply site/content/en/docs/drivers/includes/docker_usage.inc:3]: I agree, lets go with 18.09

Comment (daehyeok) [reply site/content/en/docs/drivers/includes/docker_usage.inc:3]: Fix both of code and doc to 18.09

File: pkg/minikube/registry/drvs/docker/docker_test.go [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+		expect:  reason,
+	})
+
+	// postfix string for unstable channel or patch. https://docs.docker.com/engine/install/
+	patchPostFix := "20180720214833-f61e0f7"
+
+	vs := fmt.Sprintf("%02d.%02d.%d", v[0], v[1], v[2])
+	appendedTc = append(appendedTc, []testCase{
+		{
+			version: fmt.Sprintf("linux-%s", vs),
```
Comment (medyagh) [inline pkg/minikube/registry/drvs/docker/docker_test.go:42]: add example of windows and mac os docker verions in the unit tests

**Review by medyagh — CHANGES_REQUESTED** [review]

**Review by medyagh — APPROVED** [review]
