### PR TITLE
hyperv: Run "sudo poweroff" before stopping VM

### LINKED ISSUE #4661: minikube VM on Hyper-V is in "Shutting Down" state since 30+ minutes
**The exact command to reproduce the issue**:
Ensure that there is no cluster already on the machine.
`.\minikube-windows-amd64.exe start --vm-driver=hyperv --hyperv-virtual-switch="Default Switch" --v=8 `
`.\minikube-windows-amd64.exe stop`

**The full output of the command that failed**:
<details><summary><code>
Output
</code></summary><br><pre>
PS C:\utilities> .\minikube-windows-amd64.exe stop
* Stopping "minikube" in hyperv ...
* Stopping "minikube" in hyperv ...
* Stopping "minikube" in hyperv ...
* Stopping "minikube" in hyperv ...
* Stopping "minikube" in hyperv ...

X Unable to stop VM: Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
</pre></details>

**The output of the `minikube logs` command**:
<details><summary><code>minikube logs</code></summary><br><pre>
PS C:\utilities> .\minikube-windows-amd64.exe logs

X command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
</pre></details>

**The operating system version**:
Windows 10 Enterprise.

The VM in Hyper-V has been in Shutting down state since 35 minutes -
image

This seems as if something has blocked the shutting down process inside the `minikube` virtual machine. I haven't seen this happening with any other Linux machines.

I have the following questions as well -

- Do we know what is the username/password to login to the `minikube` virtual machine so that I can check the logs?
- How many times does Minikube retry and for many seconds does it wait?
- Do we have a logic to force turn off the VM if the VM is still in Shutting down phase?

Related to #2914

-Pranav

### PR DESCRIPTION
**Pull request by blueelvis**
Fixes #4661 #2914 

- If the driver is Hyper-V, `minikube stop` will first run `sudo poweroff` via SSH into the minikube Virtual Machine and then proceed ahead with the normal stop related procedures.
- Reduced the number of retries from 5 to 3. 5 seems to be quite high.

### CODE REVIEW

File: pkg/minikube/cluster/cluster.go [hunk 1]
```diff
@@ -212,22 +212,23 @@ func adjustGuestClock(h hostRunner, t time.Time) error {
 	return err
 }
 
-// trySSHPowerOff runs the poweroff command on the guest VM to speed up deletion
-func trySSHPowerOff(h *host.Host) {
+// TrySSHPowerOff runs the poweroff command on the guest VM to speed up deletion
+func TrySSHPowerOff(h *host.Host) error {
```
Comment (tstromberg) [inline pkg/minikube/cluster/cluster.go]: This method should be kept private until some other package needs access to it.

File: pkg/minikube/cluster/cluster.go [hunk 2]
```diff
@@ -237,6 +238,12 @@ func StopHost(api libmachine.API) error {
 		return errors.Wrapf(err, "load")
 	}
 	console.OutStyle(console.Stopping, "Stopping %q in %s ...", cfg.GetMachineName(), host.DriverName)
+	if host.DriverName == constants.DriverHyperv {
+		glog.Infof("As there are issues with stopping Hyper-V VMs using API, trying to shut down using SSH")
+		if err := TrySSHPowerOff(host); err != nil {
+			return errors.Wrapf(err, "Unable to Power off cluster on %q using SSH", host.DriverName)
```
Comment (tstromberg) [inline pkg/minikube/cluster/cluster.go]: This error message makes assumptions that the API cannot guarantee. Let TrySSHPowerOff supply the rich error message. This one should just say something like:

`errors.Wrap(err, "ssh power off")`

This way, when the error is ultimately handled by the program's main function, it will provide a clear causal chain from the root problem to the overall failures reminiscent of a NASA accident investigation:

`genesis: crashed: no parachute: G-switch failed: bad relay orientation`

File: pkg/minikube/cluster/cluster.go [hunk 3]
```diff
@@ -255,7 +262,9 @@ func DeleteHost(api libmachine.API) error {
 	}
 	// This is slow if SSH is not responding, but HyperV hangs otherwise, See issue #2914
 	if host.Driver.DriverName() == constants.DriverHyperv {
-		trySSHPowerOff(host)
+		if err := TrySSHPowerOff(host); err != nil {
+			return errors.Wrap(err, "Unable to power off minikube because the host was not found.")
```
Comment (tstromberg) [inline pkg/minikube/cluster/cluster.go]: Make this into a logged warning: failure to power the VM off should not prevent it from being deleted.

**Comment by tstromberg** [comment]
@minikube-bot OK to test

File: pkg/minikube/cluster/cluster.go (hunk 1 above)
Comment (medyagh) [reply pkg/minikube/cluster/cluster.go]: agree, lets keep methods private unless others use them.

**Comment by medyagh** [comment]
@blueelvis the PR looks good to me, after the above comments are fixed.

**Comment by medyagh** [comment]
I mark this WIP, please ping me when updated

**Comment by tstromberg** [comment]
Tests look good. I am very eager to see this merged once review comments are addressed.

File: pkg/minikube/cluster/cluster.go (hunk 2 above)
Comment (blueelvis) [reply pkg/minikube/cluster/cluster.go]: Roger that. I was not aware of how NASA accident investigations are done. Thanks for the insight!

**Comment by blueelvis** [comment]
@medyagh - Done. Sorry for the delay, got caught up in office. Let me know once you are about to configure Windows tests. Would love to see how you set it up :)

@tstromberg - Glad to hear that! Just curious though that even after I have marked your comments as resolved, the robot is still saying that there are changes requested.


-Pranav

**Comment by medyagh** [comment]
@blueelvis thank you for resolving the requests, I will hook up the windows tests next week. have you tested them locally?

**Comment by blueelvis** [comment]
@medyagh - Sure. Let me know once they have been hooked up. Yes, I have tested them locally and the issues mentioned above are being fixed with this PR.
