### PR TITLE
Only run deleteHosts if running a VM

### LINKED ISSUE #7097: delete: docker inspect -f {{.State.Status}} minikube: Error: No such object: minikube: exit status 1
If you start a Docker VM:

```
% ./out/minikube start --driver=docker                                                                                                                   😄  minikube v1.9.0-beta.1 on Darwin 10.15.3
✨  Using the docker driver based on user configuration
🔥  Creating Kubernetes in docker container with (CPUs=2) (6 available), Memory=3889MB (3937MB available) ...
🐳  Preparing Kubernetes v1.18.0-rc.1 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🚀  Launching Kubernetes ... 
🌟  Enabling addons: default-storageclass, storage-provisioner
⌛  Waiting for cluster to come online ...
🏄  Done! kubectl is now configured to use "minikube"

❗  /usr/local/bin/kubectl is v1.16.3, which may be incompatible with Kubernetes v1.18.0-rc.1.
💡  You can also use 'minikube kubectl -- get pods' to invoke a matching version
```

Deletion shows a scary error message:

```
%./out/minikube delete --all                                                                                                                                   
❗  Unable to get host status for "minikube": state: docker inspect -f {{.State.Status}} minikube: Error: No such object: minikube: exit status 1
🔥  Removing /Users/tstromberg/.minikube/machines/minikube ...
💀  Removed all traces of the "minikube" cluster.
🔥  Successfully deleted all profiles
```

### PR DESCRIPTION
**Pull request by priyawadhwa**
If minikube is started with the docker driver, all containers and volumes will be deleted in the call to `deleteProfileContainersAndVolumes`. If we then try to call `deleteHosts` on it, we get this warning:

```
❗  Unable to get host status for "minikube": state: docker inspect -f {{.State.Status}} minikube: Error: No such object: minikube: exit status 1
```

which will always happen because we've already deleted the container.

cc @medyagh does this seem reasonable to you?

Should fix #7097

### CODE REVIEW

File: cmd/minikube/cmd/delete.go [hunk 1]
```diff
@@ -239,7 +239,9 @@ func deleteProfile(profile *config.Profile) error {
 		out.T(out.FailureType, "Failed to kill mount process: {{.error}}", out.V{"error": err})
 	}
 
-	deleteHosts(api, cc)
+	if driver.IsVM(cc.Driver) {
```
Comment (tstromberg) [inline cmd/minikube/cmd/delete.go]: This doesn't cover the `none` case, so perhaps this should be `if !driver.IsKIC`.

It feels weird to special case KIC here, so I'm OK with calling `delete` twice, but so long as the error isn't displayed. I feel like it should be able to interpret the lack of container as "nothing to do" rather than outputting a warning message.

Comment (priyawadhwa) [reply cmd/minikube/cmd/delete.go]: sounds good -- I changed it so that if we get an error when getting host status, we assume that the host no longer exists and return
