### PR TITLE
Exit if --kubernetes-version and --no-kubernetes are specified.

### LINKED ISSUE #12871: --no-kubernetes fails if "kubernetes-version" defined in config
Running `minikube start --no-kubernetes` fails if "kubernetes-version" is defined in config (or passed vi command argument).

```
$ minikube version
minikube version: v1.24.0
commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b
```

**Steps to reproduce the issue:** 

1. define kubernetes version in `~/.minikube/config/config.json`, e.g.
```
{
  "kubernetes-version": "1.21.5"
}
```
2. run `minikube start --no-kubernetes`
```
$ minikube start --no-kubernetes
* minikube v1.24.0 on Microsoft Windows [...]
* Kubernetes 1.22.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.22.3
* Using the virtualbox driver based on existing profile
* Starting minikube without Kubernetes minikube in cluster minikube
* Updating the running virtualbox "minikube" VM ...
* Preparing Kubernetes v1.21.5 on Docker 20.10.8 ...

X Exiting due to K8S_INSTALL_FAILED: kubeadm images: version too old: 0.0.0
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
```

More: it also fails as above if the version is defined in the command line (independently of config file contents): `minikube start --no-kubernetes --kubernetes-version=1.22.3` and although this command doesn't make much sense in I would still expect the kubernetes version to simply be ignored.

Thanks!

### PR DESCRIPTION
**Pull request by klaases**
Fixes #12871 

Disallow running minikube with both --no-kubernetes and --kubernetes-version

With config:

```
{
  "kubernetes-version": "1.21.5"
}
```

Before:

`minikube start --no-kubernetes`

```
😄  minikube v1.24.0 on Darwin 11.6.1
🆕  Kubernetes 1.22.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.22.3
✨  Using the docker driver based on existing profile
👍  Starting minikube without Kubernetes minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.21.5 on Docker 20.10.8 ...

❌  Exiting due to K8S_INSTALL_FAILED: kubeadm images: version too old: 0.0.0

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
```

After:

`minikube start --no-kubernetes`

```
😄  minikube v1.24.0 on Darwin 11.6.1

❌  Exiting due to MK_USAGE: cannot specify --kubernetes-version with --no-kubernetes,
to unset a global config run:

$ minikube config unset kubernetes-version

```

### CODE REVIEW

**Comment by sharifelgamal** [comment]
the lint error is a cyclotomic complexity issue, i guess a refactor is in order

File: pkg/minikube/node/start.go [hunk 1]
```diff
@@ -89,7 +89,10 @@ type Starter struct {
 // Start spins up a guest and starts the Kubernetes node.
 func Start(starter Starter, apiServer bool) (*kubeconfig.Settings, error) {
 	var kcs *kubeconfig.Settings
-	if starter.Node.KubernetesVersion == constants.NoKubernetesVersion { // do not bootstrap cluster if --no-kubernetes
+	// Do not bootstrap cluster if --no-kubernetes.
+	if viper.GetBool("no-kubernetes") ||
+		starter.Node.KubernetesVersion == constants.NoKubernetesVersion {
```
Comment (medyagh) [inline pkg/minikube/node/start.go:94]: lets make this code more readable

Comment (klaases) [reply pkg/minikube/node/start.go]: Yes, I have removed this code, thanks for the note.

**Review by klaases — COMMENTED** [review]
I have refactored this code.

**Review by klaases — COMMENTED** [review]
Exit if --kubernetes-version and --no-kubernetes are specified.

File: cmd/minikube/cmd/start.go [hunk 2]
```diff
@@ -1541,6 +1541,11 @@ func isBaseImageApplicable(drv string) bool {
 
 func getKubernetesVersion(old *config.ClusterConfig) string {
 	if viper.GetBool(noKubernetes) {
+		// Exit if --kubernetes-version is specified.
```
Comment (medyagh) [inline cmd/minikube/cmd/start.go:1544]: lets add integraiton test for it

**Comment by klaases** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
> ok-to-build-iso

@klaases we shouldn't build iso for this PR as this PR has not touched iso files

File: test/integration/no_kubernetes_test.go [hunk 3]
```diff
@@ -70,6 +71,17 @@ func TestNoKubernetes(t *testing.T) {
 	})
 }
 
+// ErrorStartNoK8sWithVersion expect an error when starting a minikube cluster without kubernetes and with a kubernetes version.
+func errorStartNoK8sWithVersion(ctx context.Context, t *testing.T, profile string) {
```
Comment (medyagh) [inline test/integration/no_kubernetes_test.go:75]: simmilar to other helper functions, the name should validate..Something. so it can be used in the document generation

File: test/integration/no_kubernetes_test.go [hunk 4]
```diff
@@ -70,6 +71,17 @@ func TestNoKubernetes(t *testing.T) {
 	})
 }
 
+// ErrorStartNoK8sWithVersion expect an error when starting a minikube cluster without kubernetes and with a kubernetes version.
```
Comment (medyagh) [inline test/integration/no_kubernetes_test.go:74]: func name here in comment should match the func

File: test/integration/no_kubernetes_test.go [hunk 5]
```diff
@@ -45,6 +45,7 @@ func TestNoKubernetes(t *testing.T) {
 			name      string
 			validator validateFunc
 		}{
+			{"ErrorStartNoK8sWithVersion", errorStartNoK8sWithVersion},
```
Comment (medyagh) [inline test/integration/no_kubernetes_test.go:48]: dont we need to add a new Step to Delete the cluster ? so the Next subtest "start" can actually start without K8s?

**Review by medyagh — CHANGES_REQUESTED** [review]

File: test/integration/no_kubernetes_test.go (hunk 5 above)
Comment (medyagh) [reply test/integration/no_kubernetes_test.go:48]: forget this one, maybe we dont need. since the First one wont actually create a Config ? and second "start" is still Fresh?

Comment (klaases) [reply test/integration/no_kubernetes_test.go:48]: errorStartNoK8sWithVersion() should not successfully create a cluster, so we won't have to delete.

Yes, errorStartNoK8sWithVersion() won't create a config, and will allow for a fresh start.

File: test/integration/no_kubernetes_test.go (hunk 4 above)
Comment (klaases) [reply test/integration/no_kubernetes_test.go:74]: Yes, applied suggestion.

File: test/integration/no_kubernetes_test.go (hunk 3 above)
Comment (klaases) [reply test/integration/no_kubernetes_test.go:75]: Yes, applied suggestion.

**Review by klaases — COMMENTED** [review]
Applied suggestions.

File: cmd/minikube/cmd/start.go [hunk 6]
```diff
@@ -1541,6 +1541,11 @@ func isBaseImageApplicable(drv string) bool {
...
+		if viper.GetString(kubernetesVersion) != "" {
+			exit.Message(reason.Usage, "cannot specify --kubernetes-version with --no-kubernetes")
```
Comment (medyagh) [inline cmd/minikube/cmd/start.go:1546]: this seems to only handle it the case when it is specified in the Global Config
```
$ mk start --no-kubernetes
😄  minikube v1.24.0 on Darwin 11.6 (arm64)

❌  Exiting due to MK_USAGE: cannot specify --kubernetes-version with --no-kubernetes
```

Please update the Exit with the command that user has to run 
which is "minikube config unset kubernetes-version"
consider this:
```

exit.Message(reason.Usage, "cannot specify --kubernetes-version with --no-kubernetes 
to unset a global config run:

   $ config minikube config unset kubernetes-version
")
```


but if there is an existing cluster running it is not doing the right thing (It is okay if we do it as a follow up PR) See bellow:

```

$ mk start --kubernetes-version=v1.22.1
😄  minikube v1.24.0 on Darwin 11.6 (arm64)
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=1988MB) ...
    > kubectl.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubelet.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubectl: 41.44 MiB / 41.44 MiB [-------------] 100.00% 19.69 MiB p/s 2.3s
    > kubeadm: 40.50 MiB / 40.50 MiB [-------------] 100.00% 15.08 MiB p/s 2.9s
    > kubelet: 137.29 MiB / 137.29 MiB [-----------] 100.00% 20.66 MiB p/s 6.8s

    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
12:35:31 medya/workspace/minikube
go5 ✓
$ mk start --no-kubernetes
😄  minikube v1.24.0 on Darwin 11.6 (arm64)
✨  Using the docker driver based on existing profile
👍  Starting minikube without Kubernetes minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
🏄  Done! minikube is ready without Kubernetes!
╭───────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                       │
│                       💡  Things to try without Kubernetes ...                        │
│                                                                                       │
│    - "minikube ssh" to SSH into minikube's node.                                      │
│    - "minikube docker-env" to point your docker-cli to the docker inside minikube.    │
│    - "minikube image" to build images without docker.                                 │
│                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────╯

```

**Review by medyagh — CHANGES_REQUESTED** [review]

File: cmd/minikube/cmd/start.go (hunk 6 above)
Comment (klaases) [reply cmd/minikube/cmd/start.go]: Yes, have updated the exit message to show config unset command.

Yes, will address the second issue in #12989

**Review by medyagh — APPROVED** [review]
looks good to me ! thank you @klaases
