### PR TITLE
docker-env: improve detecting powershell if SSHed from linux

### LINKED ISSUE #10626: Failing test: TestForceSystemdFlag on Windows Docker
https://storage.googleapis.com/minikube-builds/logs/10603/fb9f08b/Docker_Windows.html#fail_TestForceSystemdFlag

### PR DESCRIPTION
**Pull request by hetong07**
Fix #10626, #10627 

Make the minikube correctly detect it is running in powershell. The actual fix is [here](https://github.com/machine-drivers/machine/pull/33) and this PR is only to reflect it in minikube. Also fix a character bug in test.

**Before PR**:
```
PS > \minikube-windows-amd64.exe docker-env
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.101:2376"
export DOCKER_CERT_PATH="C:\Users\imwise\.minikube\certs"
export MINIKUBE_ACTIVE_DOCKERD="minikube"

# To point your shell to minikube's docker-daemon, run:
# eval $(minikube -p minikube docker-env)
```
**After PR**:
```
PS > .\minikube-windows-amd64.exe docker-env
$Env:DOCKER_TLS_VERIFY = "1"
$Env:DOCKER_HOST = "tcp://192.168.99.101:2376"
$Env:DOCKER_CERT_PATH = "C:\Users\imwise\.minikube\certs"
$Env:MINIKUBE_ACTIVE_DOCKERD = "minikube"
# To point your shell to minikube's docker-daemon, run:
# & minikube -p minikube docker-env | Invoke-Expression

```

### CODE REVIEW

File: cmd/minikube/cmd/docker-env.go [hunk 1]
```diff
@@ -250,7 +251,7 @@ var dockerEnvCmd = &cobra.Command{
 			}
 		}
 		sh := shell.EnvConfig{
-			Shell: shl,
+			Shell: strings.TrimSuffix(shl, filepath.Ext(shl)),
```
Comment (medyagh) [inline cmd/minikube/cmd/docker-env.go:254]: can u add a comment what u is Before the Trim ?
and maybe we could limit doing this only on windows and powershell so we don't do un-intentional side effect for others ?

**Review by medyagh — CHANGES_REQUESTED** [review]
thanks @hetong07

File: cmd/minikube/cmd/docker-env.go (hunk 1 above)
Comment (hetong07) [reply cmd/minikube/cmd/docker-env.go:254]: According to my experiment, if I run `minikube docker-env` through ssh, the shl returned is *powershell.exe*, but if I run the same command on directly on windows, the shl is assigned to *powershell*.

**SSH on windows**
```
PS >.\minikube-windows-amd64.exe docker-env -v=8 --alsologtostderr
I0303 23:50:26.148593   17808 out.go:229] Setting OutFile to fd 280 ...
I0303 23:50:26.150141   17808 out.go:281] isatty.IsTerminal(280) = true
I0303 23:50:26.150141   17808 out.go:242] Setting ErrFile to fd 284...
I0303 23:50:26.150141   17808 out.go:281] isatty.IsTerminal(284) = true
W0303 23:50:26.159300   17808 docker-env.go:248] !!!!!!!!!!!! powershell.exe
I0303 23:50:26.160422   17808 mustload.go:66] Loading cluster: minikube
```
I think this caused the problem.

Comment (ilya-zuyev) [reply cmd/minikube/cmd/docker-env.go:254]: Would be also nice to add a unit test to verify correct processing on different platforms

Comment (hetong07) [reply cmd/minikube/cmd/docker-env.go:254]: @ilya-zuyev But this case is not easy to add a unit test. This *shl* is set by `shell.Detect()` and ultimately it is set by the libmachine API. And this function call resides in an anonymous function defined for Combra,  I am not sure how to add a unit test case for this?

```
Run: func(cmd *cobra.Command, args []string) {
	var err error
	shl := shell.ForceShell
	if shl == "" {
		shl, err = shell.Detect()
		if err != nil {
			exit.Error(reason.InternalShellDetect, "Error detecting shell", err)
		}
	}
	sh := shell.EnvConfig{
		Shell: strings.TrimSuffix(shl, filepath.Ext(shl)),
	}
```
Therefore, test it in integration test may be a better way?
Besides, do we really need a unit test here? the integration test itself, if passes, could already verify its correctness?

Comment (medyagh) [reply cmd/minikube/cmd/docker-env.go:254]: @hetong07 feel free to make a PR to libmachine, we have our own fork once u improve this in libmachine, it will be better
here is link to the fork
https://github.com/machine-drivers/machine

once made the PR there plz ping me or @afbjorklund to merge it

Comment (hetong07) [reply cmd/minikube/cmd/docker-env.go:254]: Created this PR https://github.com/machine-drivers/machine/pull/33.

**Comment by hetong07** [comment]
This change seems to be better happen in https://github.com/machine-drivers/machine, so create a PR there https://github.com/machine-drivers/machine/pull/33

**Review by medyagh — CHANGES_REQUESTED** [review]
now that this is fixed in libmachine, please update the go.mod replace section to use latest libmachine fork

https://github.com/machine-drivers/machine/pull/33

**Comment by hetong07** [comment]
@medyagh Updated via `go get github.com/machine-drivers/machine`.

**Review by medyagh — APPROVED** [review]

**Review by medyagh — CHANGES_REQUESTED** [review]
The dockerEnv test still fails
https://storage.googleapis.com/minikube-builds/logs/10722/cb626a1/Docker_Windows.html#fail_TestFunctional%2fparallel%2fDockerEnv

```
-- /stdout --
** stderr ** 
	export : The term 'export' is not recognized as the name of a cmdlet, function, script file, or operable program. 
	Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
	At line:1 char:1
	+ export DOCKER_TLS_VERIFY="1"
	+ ~~~~~~
	    + CategoryInfo          : ObjectNotFound: (export:String) [], CommandNotFoundException
	    + FullyQualifiedErrorId : CommandNotFoundException

```

File: go.mod [hunk 2]
```diff
@@ -56,6 +56,7 @@ require (
 	github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
 	github.com/libvirt/libvirt-go v3.4.0+incompatible
 	github.com/machine-drivers/docker-machine-driver-vmware v0.1.1
+	github.com/machine-drivers/machine v0.16.2 // indirect
```
Comment (medyagh) [inline go.mod:59]: @hetong07 
how about only keeping github.com/machine-drivers/machine

and then removing the 
```
github.com/docker/machine
```

(and ensure u rebase from upstream and `go mod tidy`)

**Review by medyagh — CHANGES_REQUESTED** [review]

**Comment by hetong07** [comment]
@medyagh This is because the PR to machine-drivers has not be correctly reflected. Solving this by
```
go mod edit -replace github.com/docker/machine=github.com/machine-drivers/machine@master 
go mod download github.com/docker/machine
```

**Comment by medyagh** [comment]
@hetong07 this time we got passed initial error `export : The term 'export' is not recognized as the name of a cmdlet`  but we got another error, do u mind trying it manually ? is the command given by minikube missing a Dot ?
https://storage.googleapis.com/minikube-builds/logs/10722/c7a4943/Docker_Windows.html#fail_TestFunctional%2fparallel%2fDockerEnv
```
** stderr ** 
	Invoke-Expression : At line:1 char:36
	+ REM To point your shell to minikube's docker-daemon, run:
	+                                    ~~~~~~~~~~~~~~~~~~~~~~
	The string is missing the terminator: '.
	At line:1 char:79
	+ ... functional-20210310191609-6496 docker-env | Invoke-Expression ; docke ...
	+                                                 ~~~~~~~~~~~~~~~~~
	    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
	    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString,Microsoft.PowerShell.Commands.InvokeExpressionCommand
	 
** /stderr ***
```
