### PR TITLE
Remove obsolete 'vmwarefusion' driver, add friendly message

### LINKED ISSUE #8374: Remove obsolete vmwarefusion driver in preference to vmware driver (HostIP not yet implemented)
**Steps to reproduce the issue:** 

1. Installed fresh kubectl on Mac OS (version 1.18.3)
2. Installed fresh minikube (through Brew) (version 1.11.0)
3. After successful install tried to start by running "minikube start --driver=vmwarefusion"

```
VMWare Fusion Professional Version 11.5.3

**Full output of failed command:** 
I0604 20:09:27.400837   36534 start.go:98] hostinfo: {"hostname":"Antons-MacBook-Pro.local","uptime":1382301,"bootTime":1589911866,"procs":509,"os":"darwin","platform":"darwin","platformFamily":"","platformVersion":"10.15.4","kernelVersion":"19.4.0","virtualizationSystem":"","virtualizationRole":"","hostid":"ab0aa7ee-3d03-3c21-91ad-5719d79d7af6"}
W0604 20:09:27.400945   36534 start.go:106] gopshost.Virtualization returned error: not implemented yet
😄  minikube v1.11.0 on Darwin 10.15.4
I0604 20:09:27.417137   36534 notify.go:125] Checking for updates...
I0604 20:09:27.418145   36534 driver.go:253] Setting default libvirt URI to qemu:///system
✨  Using the vmwarefusion driver based on existing profile
I0604 20:09:27.421764   36534 start.go:214] selected driver: vmwarefusion
I0604 20:09:27.421779   36534 start.go:611] validating driver "vmwarefusion" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:6000 CPUs:2 DiskSize:20000 Driver:vmwarefusion HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP:172.16.160.136 Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0604 20:09:27.421873   36534 start.go:617] status for vmwarefusion: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0604 20:09:27.421997   36534 iso.go:118] acquiring lock: {Name:mk3148ba7c19ff448c71b75525615a43a9d14637 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
👍  Starting control plane node minikube in cluster minikube
I0604 20:09:27.429738   36534 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0604 20:09:27.429853   36534 preload.go:103] Found local preload: /Users/antondegoede/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4
I0604 20:09:27.429872   36534 cache.go:49] Caching tarball of preloaded images
I0604 20:09:27.429898   36534 preload.go:129] Found /Users/antondegoede/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0604 20:09:27.429905   36534 cache.go:52] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0604 20:09:27.430048   36534 profile.go:156] Saving config to /Users/antondegoede/.minikube/profiles/minikube/config.json ...
I0604 20:09:27.431221   36534 cache.go:152] Successfully downloaded all kic artifacts
I0604 20:09:27.431267   36534 start.go:240] acquiring machines lock for minikube: {Name:mk069d4f3ffa2674cee4ea265bbeb74e3b79f1e9 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0604 20:09:27.431375   36534 start.go:244] acquired machines lock for "minikube" in 88.226µs
I0604 20:09:27.431406   36534 start.go:88] Skipping create...Using existing machine configuration
I0604 20:09:27.431418   36534 fix.go:53] fixHost starting: 
I0604 20:09:27.431767   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:27.590410   36534 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0604 20:09:27.590450   36534 fix.go:131] unexpected machine state, will restart: <nil>
🏃  Updating the running vmwarefusion "minikube" VM ...
I0604 20:09:27.606005   36534 machine.go:88] provisioning docker machine ...
I0604 20:09:27.606027   36534 buildroot.go:163] provisioning hostname "minikube"
I0604 20:09:27.606181   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:27.757053   36534 main.go:110] libmachine: MAC address in VMX: 00:0c:29:d6:67:05
I0604 20:09:27.757333   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
I0604 20:09:27.757476   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:01:192.168.175.1]
I0604 20:09:27.757490   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
I0604 20:09:27.757568   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:08:172.16.160.1]
I0604 20:09:27.757625   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
I0604 20:09:27.757695   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
I0604 20:09:27.757804   36534 main.go:110] libmachine: IP found in DHCP lease table: 172.16.160.136
I0604 20:09:27.757848   36534 main.go:110] libmachine: Using SSH client type: native
I0604 20:09:27.757985   36534 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x43b87d0] 0x43b87a0 <nil>  [] 0s} 172.16.160.136 22 <nil> <nil>}
I0604 20:09:27.757994   36534 main.go:110] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I0604 20:09:27.838869   36534 main.go:110] libmachine: SSH cmd err, output: <nil>: minikube

I0604 20:09:27.839047   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:27.989711   36534 main.go:110] libmachine: MAC address in VMX: 00:0c:29:d6:67:05
I0604 20:09:27.989998   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
I0604 20:09:27.990120   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:01:192.168.175.1]
I0604 20:09:27.990134   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
I0604 20:09:27.990211   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:08:172.16.160.1]
I0604 20:09:27.990265   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
I0604 20:09:27.990365   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
I0604 20:09:27.990463   36534 main.go:110] libmachine: IP found in DHCP lease table: 172.16.160.136
I0604 20:09:27.990520   36534 main.go:110] libmachine: Using SSH client type: native
I0604 20:09:27.990634   36534 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x43b87d0] 0x43b87a0 <nil>  [] 0s} 172.16.160.136 22 <nil> <nil>}
I0604 20:09:27.990647   36534 main.go:110] libmachine: About to run SSH command:

		if ! grep -xq '.*\sminikube' /etc/hosts; then
			if grep -xq '127.0.1.1\s.*' /etc/hosts; then
				sudo sed -i 's/^127.0.1.1\s.*/127.0.1.1 minikube/g' /etc/hosts;
			else 
				echo '127.0.1.1 minikube' | sudo tee -a /etc/hosts; 
			fi
		fi
I0604 20:09:28.068137   36534 main.go:110] libmachine: SSH cmd err, output: <nil>: 
I0604 20:09:28.068182   36534 buildroot.go:169] set auth options {CertDir:/Users/antondegoede/.minikube CaCertPath:/Users/antondegoede/.minikube/certs/ca.pem CaPrivateKeyPath:/Users/antondegoede/.minikube/certs/ca-key.pem CaCertRemotePath:/etc/docker/ca.pem ServerCertPath:/Users/antondegoede/.minikube/machines/server.pem ServerKeyPath:/Users/antondegoede/.minikube/machines/server-key.pem ClientKeyPath:/Users/antondegoede/.minikube/certs/key.pem ServerCertRemotePath:/etc/docker/server.pem ServerKeyRemotePath:/etc/docker/server-key.pem ClientCertPath:/Users/antondegoede/.minikube/certs/cert.pem ServerCertSANs:[] StorePath:/Users/antondegoede/.minikube}
I0604 20:09:28.068217   36534 buildroot.go:171] setting up certificates
I0604 20:09:28.068235   36534 provision.go:82] configureAuth start
I0604 20:09:28.068355   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:28.219213   36534 main.go:110] libmachine: MAC address in VMX: 00:0c:29:d6:67:05
I0604 20:09:28.219609   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
I0604 20:09:28.219818   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:01:192.168.175.1]
I0604 20:09:28.219831   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
I0604 20:09:28.219947   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:08:172.16.160.1]
I0604 20:09:28.220061   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
I0604 20:09:28.220133   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
I0604 20:09:28.220274   36534 main.go:110] libmachine: IP found in DHCP lease table: 172.16.160.136
I0604 20:09:28.220286   36534 provision.go:131] copyHostCerts
I0604 20:09:28.220332   36534 exec_runner.go:91] found /Users/antondegoede/.minikube/cert.pem, removing ...
I0604 20:09:28.220407   36534 exec_runner.go:98] cp: /Users/antondegoede/.minikube/certs/cert.pem --> /Users/antondegoede/.minikube/cert.pem (1090 bytes)
I0604 20:09:28.220638   36534 exec_runner.go:91] found /Users/antondegoede/.minikube/key.pem, removing ...
I0604 20:09:28.220713   36534 exec_runner.go:98] cp: /Users/antondegoede/.minikube/certs/key.pem --> /Users/antondegoede/.minikube/key.pem (1679 bytes)
I0604 20:09:28.220899   36534 exec_runner.go:91] found /Users/antondegoede/.minikube/ca.pem, removing ...
I0604 20:09:28.220965   36534 exec_runner.go:98] cp: /Users/antondegoede/.minikube/certs/ca.pem --> /Users/antondegoede/.minikube/ca.pem (1050 bytes)
I0604 20:09:28.221081   36534 provision.go:105] generating server cert: /Users/antondegoede/.minikube/machines/server.pem ca-key=/Users/antondegoede/.minikube/certs/ca.pem private-key=/Users/antondegoede/.minikube/certs/ca-key.pem org=antondegoede.minikube san=[172.16.160.136 localhost 127.0.0.1]
I0604 20:09:28.311838   36534 provision.go:159] copyRemoteCerts
I0604 20:09:28.311900   36534 ssh_runner.go:148] Run: sudo mkdir -p /etc/docker /etc/docker /etc/docker
I0604 20:09:28.311957   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:28.451297   36534 main.go:110] libmachine: MAC address in VMX: 00:0c:29:d6:67:05
I0604 20:09:28.451740   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
I0604 20:09:28.451933   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:01:192.168.175.1]
I0604 20:09:28.451960   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
I0604 20:09:28.452076   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:08:172.16.160.1]
I0604 20:09:28.452176   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
I0604 20:09:28.452259   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
I0604 20:09:28.452364   36534 main.go:110] libmachine: IP found in DHCP lease table: 172.16.160.136
I0604 20:09:28.452376   36534 sshutil.go:44] new ssh client: &{IP:172.16.160.136 Port:22 SSHKeyPath:/Users/antondegoede/.minikube/machines/minikube/id_rsa Username:docker}
I0604 20:09:28.492356   36534 ssh_runner.go:215] scp /Users/antondegoede/.minikube/certs/ca.pem --> /etc/docker/ca.pem (1050 bytes)
I0604 20:09:28.503153   36534 ssh_runner.go:215] scp /Users/antondegoede/.minikube/machines/server.pem --> /etc/docker/server.pem (1135 bytes)
I0604 20:09:28.512862   36534 ssh_runner.go:215] scp /Users/antondegoede/.minikube/machines/server-key.pem --> /etc/docker/server-key.pem (1679 bytes)
I0604 20:09:28.521424   36534 provision.go:85] duration metric: configureAuth took 453.172082ms
I0604 20:09:28.521438   36534 buildroot.go:186] setting minikube options for container-runtime
I0604 20:09:28.521660   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:28.666652   36534 main.go:110] libmachine: MAC address in VMX: 00:0c:29:d6:67:05
I0604 20:09:28.667076   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
I0604 20:09:28.667197   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:01:192.168.175.1]
I0604 20:09:28.667210   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
I0604 20:09:28.667283   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:08:172.16.160.1]
I0604 20:09:28.667343   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
I0604 20:09:28.667493   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
I0604 20:09:28.667723   36534 main.go:110] libmachine: IP found in DHCP lease table: 172.16.160.136
I0604 20:09:28.667808   36534 main.go:110] libmachine: Using SSH client type: native
I0604 20:09:28.667941   36534 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x43b87d0] 0x43b87a0 <nil>  [] 0s} 172.16.160.136 22 <nil> <nil>}
I0604 20:09:28.667948   36534 main.go:110] libmachine: About to run SSH command:
df --output=fstype / | tail -n 1
I0604 20:09:28.741656   36534 main.go:110] libmachine: SSH cmd err, output: <nil>: tmpfs

I0604 20:09:28.741674   36534 buildroot.go:70] root file system type: tmpfs
I0604 20:09:28.741889   36534 provision.go:290] Updating docker unit: /lib/systemd/system/docker.service ...
I0604 20:09:28.742012   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:28.893546   36534 main.go:110] libmachine: MAC address in VMX: 00:0c:29:d6:67:05
I0604 20:09:28.893833   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
I0604 20:09:28.894015   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:01:192.168.175.1]
I0604 20:09:28.894029   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
I0604 20:09:28.894169   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:08:172.16.160.1]
I0604 20:09:28.894266   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
I0604 20:09:28.894435   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
I0604 20:09:28.894604   36534 main.go:110] libmachine: IP found in DHCP lease table: 172.16.160.136
I0604 20:09:28.894687   36534 main.go:110] libmachine: Using SSH client type: native
I0604 20:09:28.894963   36534 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x43b87d0] 0x43b87a0 <nil>  [] 0s} 172.16.160.136 22 <nil> <nil>}
I0604 20:09:28.895080   36534 main.go:110] libmachine: About to run SSH command:
sudo mkdir -p /lib/systemd/system && printf %s "[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target  minikube-automount.service docker.socket
Requires= minikube-automount.service docker.socket 

[Service]
Type=notify



# This file is a systemd drop-in unit that inherits from the base dockerd configuration.
# The base configuration already specifies an 'ExecStart=...' command. The first directive
# here is to clear out that command inherited from the base configuration. Without this,
# the command from the base configuration and the command specified here are treated as
# a sequence of commands, which is not the desired behavior, nor is it valid -- systemd
# will catch this invalid input and refuse to start the service with an error like:
#  Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services.

# NOTE: default-ulimit=nofile is set to an arbitrary number for consistency with other
# container runtimes. If left unlimited, it may result in OOM issues with MySQL.
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=vmwarefusion --insecure-registry 10.96.0.0/12 
ExecReload=/bin/kill -s HUP $MAINPID

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target
" | sudo tee /lib/systemd/system/docker.service.new
I0604 20:09:28.972257   36534 main.go:110] libmachine: SSH cmd err, output: <nil>: [Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target  minikube-automount.service docker.socket
Requires= minikube-automount.service docker.socket 

[Service]
Type=notify



# This file is a systemd drop-in unit that inherits from the base dockerd configuration.
# The base configuration already specifies an 'ExecStart=...' command. The first directive
# here is to clear out that command inherited from the base configuration. Without this,
# the command from the base configuration and the command specified here are treated as
# a sequence of commands, which is not the desired behavior, nor is it valid -- systemd
# will catch this invalid input and refuse to start the service with an error like:
#  Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services.

# NOTE: default-ulimit=nofile is set to an arbitrary number for consistency with other
# container runtimes. If left unlimited, it may result in OOM issues with MySQL.
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=vmwarefusion --insecure-registry 10.96.0.0/12 
ExecReload=/bin/kill -s HUP 

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target

I0604 20:09:28.972420   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:29.115468   36534 main.go:110] libmachine: MAC address in VMX: 00:0c:29:d6:67:05
I0604 20:09:29.115838   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
I0604 20:09:29.116068   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:01:192.168.175.1]
I0604 20:09:29.116084   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
I0604 20:09:29.116229   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:08:172.16.160.1]
I0604 20:09:29.116342   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
I0604 20:09:29.116411   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
I0604 20:09:29.116517   36534 main.go:110] libmachine: IP found in DHCP lease table: 172.16.160.136
I0604 20:09:29.116558   36534 main.go:110] libmachine: Using SSH client type: native
I0604 20:09:29.116672   36534 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x43b87d0] 0x43b87a0 <nil>  [] 0s} 172.16.160.136 22 <nil> <nil>}
I0604 20:09:29.116686   36534 main.go:110] libmachine: About to run SSH command:
sudo diff -u /lib/systemd/system/docker.service /lib/systemd/system/docker.service.new || { sudo mv /lib/systemd/system/docker.service.new /lib/systemd/system/docker.service; sudo systemctl -f daemon-reload && sudo systemctl -f enable docker && sudo systemctl -f restart docker; }
I0604 20:09:29.193543   36534 main.go:110] libmachine: SSH cmd err, output: <nil>: 
I0604 20:09:29.193572   36534 machine.go:91] provisioned docker machine in 1.587536041s
I0604 20:09:29.193581   36534 start.go:203] post-start starting for "minikube" (driver="vmwarefusion")
I0604 20:09:29.193588   36534 start.go:213] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0604 20:09:29.193678   36534 ssh_runner.go:148] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0604 20:09:29.193762   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:29.346101   36534 main.go:110] libmachine: MAC address in VMX: 00:0c:29:d6:67:05
I0604 20:09:29.346463   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
I0604 20:09:29.346714   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:01:192.168.175.1]
I0604 20:09:29.346820   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
I0604 20:09:29.347095   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:08:172.16.160.1]
I0604 20:09:29.347274   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
I0604 20:09:29.347377   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
I0604 20:09:29.347572   36534 main.go:110] libmachine: IP found in DHCP lease table: 172.16.160.136
I0604 20:09:29.347582   36534 sshutil.go:44] new ssh client: &{IP:172.16.160.136 Port:22 SSHKeyPath:/Users/antondegoede/.minikube/machines/minikube/id_rsa Username:docker}
I0604 20:09:29.387028   36534 ssh_runner.go:148] Run: cat /etc/os-release
I0604 20:09:29.389565   36534 info.go:96] Remote host: Buildroot 2019.02.10
I0604 20:09:29.389582   36534 filesync.go:118] Scanning /Users/antondegoede/.minikube/addons for local assets ...
I0604 20:09:29.389666   36534 filesync.go:118] Scanning /Users/antondegoede/.minikube/files for local assets ...
I0604 20:09:29.389712   36534 start.go:206] post-start completed in 196.120522ms
I0604 20:09:29.389790   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:29.533201   36534 main.go:110] libmachine: MAC address in VMX: 00:0c:29:d6:67:05
I0604 20:09:29.533674   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
I0604 20:09:29.533883   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:01:192.168.175.1]
I0604 20:09:29.533898   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
I0604 20:09:29.533984   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:08:172.16.160.1]
I0604 20:09:29.534043   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
I0604 20:09:29.534117   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
I0604 20:09:29.534225   36534 main.go:110] libmachine: IP found in DHCP lease table: 172.16.160.136
I0604 20:09:29.534269   36534 main.go:110] libmachine: Using SSH client type: native
I0604 20:09:29.534380   36534 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x43b87d0] 0x43b87a0 <nil>  [] 0s} 172.16.160.136 22 <nil> <nil>}
I0604 20:09:29.534388   36534 main.go:110] libmachine: About to run SSH command:
date +%s.%N
I0604 20:09:29.607220   36534 main.go:110] libmachine: SSH cmd err, output: <nil>: 1591294169.628506947

I0604 20:09:29.607245   36534 fix.go:208] guest clock: 1591294169.628506947
I0604 20:09:29.607253   36534 fix.go:221] Guest: 2020-06-04 20:09:29.628506947 +0200 CEST Remote: 2020-06-04 20:09:29.389718 +0200 CEST m=+2.061590635 (delta=238.788947ms)
I0604 20:09:29.607292   36534 fix.go:192] guest clock delta is within tolerance: 238.788947ms
I0604 20:09:29.607298   36534 fix.go:55] fixHost completed within 2.175856216s
I0604 20:09:29.607302   36534 start.go:75] releasing machines lock for "minikube", held for 2.175887883s
I0604 20:09:29.607405   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:29.759086   36534 main.go:110] libmachine: MAC address in VMX: 00:0c:29:d6:67:05
I0604 20:09:29.759468   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
I0604 20:09:29.759698   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:01:192.168.175.1]
I0604 20:09:29.759712   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
I0604 20:09:29.759827   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:08:172.16.160.1]
I0604 20:09:29.759893   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
I0604 20:09:29.759992   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
I0604 20:09:29.760212   36534 main.go:110] libmachine: IP found in DHCP lease table: 172.16.160.136
I0604 20:09:29.761069   36534 ssh_runner.go:148] Run: curl -sS -m 2 https://k8s.gcr.io/
I0604 20:09:29.761103   36534 ssh_runner.go:148] Run: systemctl --version
I0604 20:09:29.761242   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:29.761248   36534 main.go:110] libmachine: executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0604 20:09:29.910232   36534 main.go:110] libmachine: MAC address in VMX: 00:0c:29:d6:67:05
I0604 20:09:29.910232   36534 main.go:110] libmachine: MAC address in VMX: 00:0c:29:d6:67:05
I0604 20:09:29.910667   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
I0604 20:09:29.910690   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
I0604 20:09:29.910763   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:01:192.168.175.1]
I0604 20:09:29.910776   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
I0604 20:09:29.910792   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:01:192.168.175.1]
I0604 20:09:29.910805   36534 main.go:110] libmachine: Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
I0604 20:09:29.910938   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:08:172.16.160.1]
I0604 20:09:29.910974   36534 main.go:110] libmachine: Following IPs found map[00:50:56:c0:00:08:172.16.160.1]
I0604 20:09:29.911005   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
I0604 20:09:29.911085   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
I0604 20:09:29.911153   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
I0604 20:09:29.911205   36534 main.go:110] libmachine: Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
I0604 20:09:29.911334   36534 main.go:110] libmachine: IP found in DHCP lease table: 172.16.160.136
I0604 20:09:29.911362   36534 sshutil.go:44] new ssh client: &{IP:172.16.160.136 Port:22 SSHKeyPath:/Users/antondegoede/.minikube/machines/minikube/id_rsa Username:docker}
I0604 20:09:29.911438   36534 main.go:110] libmachine: IP found in DHCP lease table: 172.16.160.136
I0604 20:09:29.911446   36534 sshutil.go:44] new ssh client: &{IP:172.16.160.136 Port:22 SSHKeyPath:/Users/antondegoede/.minikube/machines/minikube/id_rsa Username:docker}
I0604 20:09:29.950601   36534 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0604 20:09:29.950655   36534 preload.go:103] Found local preload: /Users/antondegoede/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4
I0604 20:09:29.950741   36534 ssh_runner.go:148] Run: docker images --format {{.Repository}}:{{.Tag}}
I0604 20:09:29.971975   36534 docker.go:379] Got preloaded images: -- stdout --
k8s.gcr.io/kube-proxy:v1.18.3
k8s.gcr.io/kube-scheduler:v1.18.3
k8s.gcr.io/kube-apiserver:v1.18.3
k8s.gcr.io/kube-controller-manager:v1.18.3
kubernetesui/dashboard:v2.0.0
k8s.gcr.io/pause:3.2
k8s.gcr.io/coredns:1.6.7
k8s.gcr.io/etcd:3.4.3-0
kubernetesui/metrics-scraper:v1.0.2
gcr.io/k8s-minikube/storage-provisioner:v1.8.1

-- /stdout --
I0604 20:09:29.971995   36534 docker.go:317] Images already preloaded, skipping extraction
I0604 20:09:29.972078   36534 ssh_runner.go:148] Run: sudo systemctl cat docker.service
I0604 20:09:29.977754   36534 ssh_runner.go:148] Run: sudo systemctl is-active --quiet service containerd
I0604 20:09:29.984711   36534 ssh_runner.go:148] Run: sudo systemctl is-active --quiet service crio
I0604 20:09:29.992643   36534 ssh_runner.go:148] Run: sudo systemctl daemon-reload
I0604 20:09:30.048964   36534 ssh_runner.go:148] Run: sudo systemctl start docker
I0604 20:09:30.055182   36534 ssh_runner.go:148] Run: docker version --format {{.Server.Version}}
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
E0604 20:09:30.095896   36534 start.go:94] Unable to get host IP: HostIP not yet implemented for "vmwarefusion" driver
I0604 20:09:30.096420   36534 exit.go:58] WithError(failed to start node)=startup failed: Failed to setup kubeconfig: HostIP not yet implemented for "vmwarefusion" driver called from:
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.14.3/libexec/src/runtime/debug/stack.go:24 +0x9d
k8s.io/minikube/pkg/minikube/exit.WithError(0x569d02d, 0x14, 0x597ff80, 0xc00039e420)
	/private/tmp/minikube-20200529-7642-1nlmruw/pkg/minikube/exit/exit.go:58 +0x34
k8s.io/minikube/cmd/minikube/cmd.runStart(0x66d87a0, 0xc000534480, 0x0, 0x2)
	/private/tmp/minikube-20200529-7642-1nlmruw/cmd/minikube/cmd/start.go:203 +0x7f7
github.com/spf13/cobra.(*Command).execute(0x66d87a0, 0xc000534460, 0x2, 0x2, 0x66d87a0, 0xc000534460)
	/private/tmp/minikube-20200529-7642-1nlmruw/.brew_home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x66d77e0, 0x0, 0x1, 0xc0003ea090)
	/private/tmp/minikube-20200529-7642-1nlmruw/.brew_home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/minikube-20200529-7642-1nlmruw/.brew_home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/private/tmp/minikube-20200529-7642-1nlmruw/cmd/minikube/cmd/root.go:112 +0x72c
main.main()
	/private/tmp/minikube-20200529-7642-1nlmruw/cmd/minikube/main.go:66 +0xe6
W0604 20:09:30.096514   36534 out.go:201] failed to start node: startup failed: Failed to setup kubeconfig: HostIP not yet implemented for "vmwarefusion" driver

💣  failed to start node: startup failed: Failed to setup kubeconfig: HostIP not yet implemented for "vmwarefusion" driver

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

### PR DESCRIPTION
**Pull request by tstromberg**
The vmwarefusion driver has been broken for 6+ months.  Fixes #8374

With this PR, this is the behavior when `--driver=vmwarefusion` is provided:

```
😄  minikube v1.15.1 on Darwin 10.15.7
✨  Using the vmwarefusion driver based on user configuration

🤷  Exiting due to PROVIDER_VMWAREFUSION_OBSOLETE: The 'vmwarefusion' driver is no longer available
💡  Suggestion: Switch to the newer 'vmware' driver by using '--driver=vmware'. This may require first deleting your existing cluster
📘  Documentation: https://minikube.sigs.k8s.io/docs/drivers/vmware/
```

### CODE REVIEW

**Comment by afbjorklund** [comment]
@tstromberg :
Apparently the "newer" vmware driver doesn't support the new versions just yet ?

> This driver requires VMware Workstation 14 (Windows/Linux) or VMware Fusion 10 (MacOS) to be installed on your host. Earlier versions of Workstation/Fusion might still work with this driver, but it's not officially supported.

The are issues opened against both Workstation 15 and against Fusion 11.
https://github.com/machine-drivers/docker-machine-driver-vmware/issues

* Workstation 16: https://www.vmware.com/products/workstation-pro.html
* Fusion 12: https://www.vmware.com/products/fusion.html

See https://www.vmware.com/products/desktop-hypervisor.html

Interestingly, they recommend minikube for kubernetes even despite that:

> **How to create a Kubernetes cluster?**

> You can create and deploy a Kubernetes cluster on either a physical or a virtual machine. It is recommended for new users to start creating a Kubernetes cluster by using Minikube. Minikube is an open-source tool that is compatible with Linux, Mac and
Windows operating systems. Minikube can be used to create and deploy a simple, streamlined cluster that contains only one worker node.

https://www.vmware.com/topics/glossary/content/kubernetes-cluster

**Comment by afbjorklund** [comment]
We should still obsolete the "vmwarefusion" driver, just that "vmware" needs fixing too...

File: pkg/minikube/driver/driver.go [hunk 1]
```diff
@@ -47,7 +47,7 @@ const (
 	HyperKit = "hyperkit"
 	// VMware driver
 	VMware = "vmware"
-	// VMwareFusion driver
+	// VMwareFusion driver (obsolete)
```
Comment (afbjorklund) [inline pkg/minikube/driver/driver.go:50]: You could also just delete it ? That is what we did with kvm and xhyve, for instance (0332f7335)

**Review by afbjorklund — APPROVED** [review]
