### PR TITLE
preload: fix bug for windows file separators

### LINKED ISSUE #6944: Cannot preload container runtime docker on windows client
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:<details>
$ minikube start --v=8
* minikube v1.8.1 on Microsoft Windows 7 Enterprise Service Pack 1 6.1.7601 Build 7601
* Automatically selected the virtualbox driver
* Downloading VM boot image ...
    > minikube-v1.8.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.8.0.iso: 173.56 MiB / 173.56 MiB [ 100.00% 1.97 MiB p/s 1m28s
* Creating virtualbox VM (CPUs=2, Memory=4051MB, Disk=20000MB) ...
* Downloading preloaded images tarball for k8s v1.17.3 ...
    > preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4: 116.25 MiB / 499* Found network options:
  - HTTP_PROXY=http://10.43.216.8:8080
  - HTTPS_PROXY=http://10.43.216.8:8080
  - NO_PROXY=localhost,minikube,127.0.0.1,192.168.99.100
  - http_proxy=http://10.43.216.8:8080
  - https_proxy=http://10.43.216.8:8080
  - no_proxy=localhost,minikube,127.0.0.1,192.168.99.100
    > preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4: 499.26 MiB / 499
E0307 22:08:30.857999   10480 config.go:71] Failed to preload container runtime Docker: copying file: sudo test -d \ && sudo scp -t \ && sudo touch -d "2020-03-07 22:08:29.4839996 +0100" \/preloaded.tar.lz4: Process exited with status 1
output: , falling back to caching images
</details>

**The operating system version**:
Windows 7 x64

I think it is related to
https://github.com/kubernetes/minikube/blob/cbda04cf6bbe65e987ae52bb393c10099ab62014/pkg/minikube/cruntime/docker.go#L278

The command is generated with windows filepath.Dir and filepath.Base whereas it is executed in the VM so with linux path separators

### PR DESCRIPTION
**Pull request by priyawadhwa**
should fix #6944

### CODE REVIEW

File: pkg/minikube/cruntime/docker.go [hunk 1]
```diff
@@ -272,15 +271,19 @@ func (r *Docker) SystemLogCmd(len int) string {
 // 3. Remove the tarball within the VM
 func (r *Docker) Preload(k8sVersion string) error {
 	tarballPath := download.TarballPath(k8sVersion)
-	dest := "/preloaded.tar.lz4"
+	targetDir := "/"
+	targetName := "preloaded.tar.lz4"
+	// don't use filepath.Join so that we maintain Linux file separators
+	// so that this still works on Windows
+	dest := targetDir + targetName
```
Comment (medyagh) [inline pkg/minikube/cruntime/docker.go]: you can use path.Join instead of filepath.Join here

Comment (priyawadhwa) [reply pkg/minikube/cruntime/docker.go]: done
