### PR TITLE
Fix crash when deleting the cluster but it doesn't exist

### LINKED ISSUE #4459: hyperv: If there is no VM , minikube delete should be able to proceed
`minikube delete` should be able to delete the `.minikube` folder even if the Hyper-V VM does not exist. For some reason if the Hyper V VM Creation fails, the directory is created but then the `minikube delete` starts failing. Now, deleting the `.minikube` directory is the only option as `minikube start` will also not run.

Maybe add a `-force` flag to the delete command?

**The exact command to reproduce the issue**:
1. `.\minikube start --vm-driver "hyperv" --hyperv-virtual-switch "Default Switch" --memory 10 -v 9999` (This will fail stating "'minikube' failed to modify device 'Memory'. (Virtual machine ID 3B02F3CF-034C-4E0A-8972-9567905AF923)
Invalid startup memory amount assigned for 'minikube'. The minimum amount of memory you can assign to this virtual machine is '32' MB.")
2. `minikube delete -v 9999`
**The full output of the command that failed**:
```
PS C:\utilities> .\minikube delete -v 9999
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM


* Deleting "minikube" from hyperv ...
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM


[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Remove-VM minikube -Force
[stdout =====>] :
[stderr =====>] : Hyper-V\Remove-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:1
+ Hyper-V\Remove-VM minikube -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Remove-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.RemoveVM



X Failed to delete cluster: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
PS C:\utilities>
```
**The output of the `minikube logs` command**:
```
PS C:\utilities> .\minikube.exe logs

X command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
```
**The operating system version**:
Windows 10 Enterprise

### PR DESCRIPTION
**Pull request by blueelvis**
Fixes #4459 

I think that we should have a force deletion switch as well where it deletes the `.minikube` folder as well. What do you think?

-Pranav

### CODE REVIEW

**Comment by afbjorklund** [comment]
Can you please fix your line endings to not insert the ^M (`\r`) on every line ?

https://help.github.com/en/articles/configuring-git-to-handle-line-endings

It is making the changes to the build_guide.md look much bigger than what it is...

Thanks!

**Comment by blueelvis** [comment]
Sorry about that. Fixed the issue. For some reason, the other files were in LF. Let me know if this requires any more edits :)

Thanks!

**Comment by RA489** [comment]
@minikube-bot OK to test

File: cmd/minikube/cmd/delete.go [hunk 1]
```diff
@@ -69,7 +70,7 @@ func runDelete(cmd *cobra.Command, args []string) {
 	if err = cluster.DeleteHost(api); err != nil {
 		switch err := errors.Cause(err).(type) {
 		case mcnerror.ErrHostDoesNotExist:
-			out.T(out.Meh, `"{{.name}}" cluster does not exist`, out.V{"name": profile})
+			out.T(out.Meh, `"{{.name}}" cluster does not exist. Proceeding ahead with cleanup.`, out.V{"name": err.Name})
```
Comment (tstromberg) [inline cmd/minikube/cmd/delete.go]: Just curious: why the change from profile to err.Name?

**Comment by tstromberg** [comment]
> Fixes #4459
> 
> I think that we should have a force deletion switch as well where it deletes the `.minikube` folder as well. What do you think?
> 
> -Pranav

I'm not sure what you mean here. `delete`, if successful, should always remove the profile from `~/.minikube/profiles`. I don't think it should delete `~/.minikube`, as it may cause inadvertent data loss.

File: cmd/minikube/cmd/delete.go (hunk 1 above)
Comment (blueelvis) [reply cmd/minikube/cmd/delete.go]: Just that this seems to align more with the error being returned i.e. `ErrHostDoesNotExist`. It could be that the profile exists but the host itself has been deleted. Would be happy to revert it back though.

**Comment by blueelvis** [comment]
Agreed that it could cause the deletion of the entire `.minikube` folder. We should provide a flag to delete that as well. It could cause the data loss but asking the users to go and manually delete seems a bit lengthy when we can add a flag to do the same. Although it could always ask for confirmation and then also display a big warning. 

If you agree, I can implement this in this same PR as well.

**Comment by sharifelgamal** [comment]
@blueelvis This looks to be ready to merge once it's rebased.

**Comment by blueelvis** [comment]
@sharifelgamal @tstromberg - I am creating a new issue to delete the `.minikube` folder as well. This PR 's conflicts have been fixed. Please merge.

-Pranav

**Comment by tstromberg** [comment]
```
pkg/minikube/cluster/cluster.go:287: File is not `goimports`-ed (goimports)
		exit.WithCodeT(exit.Failure,"Unable to get the status of the cluster.")
cmd/minikube/cmd/delete.go:82:107: err.Name undefined (type error has no field or method Name) (typecheck)
			out.T(out.Meh, `"{{.name}}" cluster does not exist. Proceeding ahead with cleanup.`, out.V{"name": err.Name})
```

**Comment by blueelvis** [comment]
@tstromberg - I fixed the linting and the above error mentioned. Any idea why Jenkins is failing? Doesn't seem to be related to this PR.

**Comment by tstromberg** [comment]
hyperkit:  https://github.com/kubernetes/minikube/issues/4206
virtualbox: Fixed in https://github.com/kubernetes/minikube/pull/5438
none: https://github.com/kubernetes/minikube/issues/5332

**Comment by tstromberg** [comment]
Thank you!
