### PR TITLE
Ensure download_test doesn't hit GCR by using mocked getChecksum func

### LINKED ISSUE #11439: unit test should not fail when there is no generated preload version
```
--- FAIL: TestDownload (0.82s)
    --- FAIL: TestDownload/PreloadDownloadPreventsMultipleDownload (0.22s)
        download_test.go:94: Failed to download preload: open /home/runner/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v11-v1.20.2-docker-overlay2-amd64.tar.lz4.690737788: no such file or directory
            tempfile
            k8s.io/minikube/pkg/minikube/download.Preload
            	/home/runner/work/minikube/minikube/pkg/minikube/download/preload.go:163
            k8s.io/minikube/pkg/minikube/download.testPreloadDownloadPreventsMultipleDownload.func4
            	/home/runner/work/minikube/minikube/pkg/minikube/download/download_test.go:93
            runtime.goexit
            	/opt/hostedtoolcache/go/1.16.4/x64/src/runtime/asm_amd64.s:1371
        download_test.go:94: Failed to download preload: open /home/runner/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v11-v1.20.2-docker-overlay2-amd64.tar.lz4.470237611: no such file or directory
            tempfile
            k8s.io/minikube/pkg/minikube/download.Preload
            	/home/runner/work/minikube/minikube/pkg/minikube/download/preload.go:163
            k8s.io/minikube/pkg/minikube/download.testPreloadDownloadPreventsMultipleDownload.func4
            	/home/runner/work/minikube/minikube/pkg/minikube/download/download_test.go:93
            runtime.goexit
            	/opt/hostedtoolcache/go/1.16.4/x64/src/runtime/asm_amd64.s:1371
        download_test.go:105: Expected only 1 download attempt but got 0!
FAIL
```

### PR DESCRIPTION
**Pull request by dinever**
Hi, this one closes #11439

Just a simple fix to ignore the error when the preload version is not generated yet.

See https://github.com/kubernetes/minikube/pull/11426#issuecomment-842798211

### CODE REVIEW

File: pkg/minikube/download/download_test.go [hunk 1]
```diff
@@ -91,7 +91,7 @@ func testPreloadDownloadPreventsMultipleDownload(t *testing.T) {
 	group.Add(2)
 	dlCall := func() {
 		if err := Preload(constants.DefaultKubernetesVersion, constants.DefaultContainerRuntime); err != nil {
```
Comment (medyagh) [inline pkg/minikube/download/download_test.go:93]: @dinever thanks for picking up this task, since this is a unit test, how about instead of Really checking and donwloading preload, we simply Mock the Preload func ?

similar to this test https://github.com/medyagh/minikube/blob/cd73e832dd80a5b0d5c055a93b99a4654fca02f3/pkg/drivers/kic/oci/network_create_test.go#L26

```
var dockerInspectGetterMock = func(name string) (*RunResult, error) {
	var responseInBytes bytes.Buffer
	responseInBytes.WriteString(dockerResponse)
	response := &RunResult{Stdout: responseInBytes}

	return response, nil
}

```

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/download/download_test.go (hunk 1 above)
Comment (dinever) [reply pkg/minikube/download/download_test.go:93]: Sounds good! WIll do. Thanks!

**Comment by dinever** [comment]
Hi @medyagh, thanks for the feedback!

I've pushed b9292bde0dcab5e231df5192d84b759c98e5add9 to make sure unit tests doesn't hit GCR.

We already have a mock for the downloading part, and #11462 added a nice mock for the `getChecksum` part as well. However, when looking at the code I found one more place calling GCR during unit tests:

https://github.com/kubernetes/minikube/blob/9db3ae665c96d5e27525395a2b78ee5480ae950a/pkg/minikube/download/preload.go#L212-L220

It looks like when saving the checksum to a file, we did one extra call to GCR to get the checksum. So I refactored the code a little bit and use the checksum we already got by `getChecksum` instead of calling GCR again. This way we can make sure unit tests don't hit GCR.

Let me know what you think, thanks!

**Review by medyagh — APPROVED** [review]
thank you @dinever
