### PR TITLE
Gracefully exit if container runtime is misspelled

### LINKED ISSUE #7426: do not crash, when missplelled container runtime
```
./out/minikube start --driver=docker --container-runtime=conatinerd
😄  minikube v1.9.2 on Darwin 10.13.6
✨  Using the docker driver based on user configuration

💣  Failed to generate config: unknown runtime type: "conatinerd"

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

in this case i misspelled containerd
and instead of crying and crashing and asking user to create an issue, we could say "conatinerd" is not a valid container-runtime,
the valid options are ...

### PR DESCRIPTION
**Pull request by sunny-b**
This fixes #7426 by creating a simple lookup for valid container runtimes `(docker crio containerd)` and adding it in the `validateFlags` check.

Before:
```bash
$ ./out/minikube-darwin-amd64 start --driver=docker --container-runtime=conatinerd                                                                                                                 
😄  minikube v1.12.0-beta.0 on Darwin 10.14.6
✨  Using the docker driver based on existing profile
🆕  Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3

💣  error provisioning host: Failed to generate config: new runtime manager: unknown runtime type: "conatinerd"

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

After:
```bash
$ ./out/minikube-darwin-amd64 start --driver=docker --container-runtime=conatinerd                                                         
😄  minikube v1.12.0-beta.0 on Darwin 10.14.6
✨  Using the docker driver based on existing profile
💡  Invalid Container Runtime: "conatinerd". Valid runtimes are: docker, crio, containerd
```

### CODE REVIEW

File: pkg/minikube/cruntime/cruntime.go [hunk 1]
```diff
@@ -47,6 +47,11 @@ func (cs ContainerState) String() string {
 	return [...]string{"all", "running", "paused"}[cs]
 }
 
+// ValidRuntimes lists the supported container runtimes
+func ValidRuntimes() []string {
+	return []string{"docker", "crio", "containerd"}
```
Comment (afbjorklund) [inline pkg/minikube/cruntime/cruntime.go:52]: The default spelling is supposed to be "cri-o", like in https://cri-o.io/

But we accept **both** as parameters (and normalize "crio" to "cri-o")

Comment (sunny-b) [reply pkg/minikube/cruntime/cruntime.go:52]: Gotcha. Would you prefer that to be list in the docs as well? Currently, it has it spelt as `crio`:
`--container-runtime='docker': The container runtime to be used (docker, crio, containerd).`

Should that stay the same continue to silently accept `cri-o` or should `cri-o` be included in the docs?

Comment (medyagh) [reply pkg/minikube/cruntime/cruntime.go:52]: I think the doc should be one way but we should accept alternative spellings . Thank you for this contribution

Comment (sunny-b) [reply pkg/minikube/cruntime/cruntime.go:52]: I'm still slightly confused. Just to clarify, the docs should stay the same (spelling `crio` as `cri-o`) but I should ensure that both spellings are accepted. Do I have that correct?

Comment (medyagh) [reply pkg/minikube/cruntime/cruntime.go]: sorry for the lack of clarity, 
the docs should say cri-o
and our help text should also say cri-o
but we should also accept it if the user provides crio as an option.

Comment (sunny-b) [reply pkg/minikube/cruntime/cruntime.go]: Ah gotcha. Will update that!

Comment (afbjorklund) [reply pkg/minikube/cruntime/cruntime.go]: Upstream is confused as well (the project is called cri-o, the binary is called crio)

Comment (afbjorklund) [reply pkg/minikube/cruntime/cruntime.go]: I'm actually not sure if "Cry... Oh!" (CRI-O) is any better than "Ociieed!" (OCID)

Comment (afbjorklund) [reply pkg/minikube/cruntime/cruntime.go]: https://www.redhat.com/en/blog/introducing-cri-o-10

**Comment by sunny-b** [comment]
Is it normal for the `TestPreload` integration test to fail? Is it flaky? I ran it locally and it passed fine. The logs in the failed test don't really show why it failed.

**Comment by afbjorklund** [comment]
The Docker Desktop VM on the Mac looks sad: `failed to "StartContainer" for "etcd" with CreateContainerConfigError: "open /var/lib/kubelet/pods/6817a9c8a9aa865ba50269ccfa66b9f2/etc-hosts: read-only file system"`

**Comment by sunny-b** [comment]
Okay I've updated it to use `crio` for backwards compatibility and convert `cri-o` to `crio` if passed in.
