### PR TITLE
cache add: improved error message when image does not exist

### LINKED ISSUE #9217: "cache add" command: improve error message for not existing image.
```
PS C:\Users\jenkins> minikube cache add doesnt_exist_thing:haha
E0910 18:30:13.540553    3980 cache.go:63] save image to file "doesnt_exist_thing:haha" -> "C:\\Users\\jenkins\\.minikube\\cache\\images\\doesnt_exist_thing_haha" failed: nil image for doesnt_exist_thing:haha: GET https://index.docker.io/v2/library/doesnt_exist_thing/manifests/haha: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/doesnt_exist_thing Type:repository]]

X Exiting due to MK_CACHE_LOAD: save to dir: caching images: caching image "C:\\Users\\jenkins\\.minikube\\cache\\images\\doesnt_exist_thing_haha": nil image for doesnt_exist_thing:haha: GET https://index.docker.io/v2/library/doesnt_exist_thing/manifests/haha: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/doesnt_exist_thing Type:repository]]
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

```

### PR DESCRIPTION
**Pull request by tripolkaandrey**
Fixes #9217
Improved error message by adding message suggested by @Evalle in the corresponding issue.

**Before**
```
PS C:\Users\jenkins> minikube cache add doesnt_exist_thing:haha
E0910 18:30:13.540553    3980 cache.go:63] save image to file "doesnt_exist_thing:haha" -> "C:\\Users\\jenkins\\.minikube\\cache\\images\\doesnt_exist_thing_haha" failed: nil image for doesnt_exist_thing:haha: GET https://index.docker.io/v2/library/doesnt_exist_thing/manifests/haha: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/doesnt_exist_thing Type:repository]]

X Exiting due to MK_CACHE_LOAD: save to dir: caching images: caching image "C:\\Users\\jenkins\\.minikube\\cache\\images\\doesnt_exist_thing_haha": nil image for doesnt_exist_thing:haha: GET https://index.docker.io/v2/library/doesnt_exist_thing/manifests/haha: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/doesnt_exist_thing Type:repository]]
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose
 ```
 
 **After**
 ```
❗  "minikube cache" will be deprecated in upcoming versions, please switch to "minikube image load"
❗  The image you are trying to add ubuntu doesn't exist!
```

### CODE REVIEW

File: pkg/minikube/image/cache.go [hunk 1]
```diff
@@ -60,7 +60,11 @@ func SaveToDir(images []string, cacheDir string) error {
 			dst := filepath.Join(cacheDir, image)
 			dst = localpath.SanitizeCacheDir(dst)
 			if err := saveToTarFile(image, dst); err != nil {
-				klog.Errorf("save image to file %q -> %q failed: %v", image, dst, err)
+				klog.Errorf("save image to file %q -> %q failed: \n" +
```
Comment (medyagh) [inline pkg/minikube/image/cache.go:63]: this doesnt help the user in the UI, Suggest instead of logging klog.Errr we should add out.Warn with simnple english (an no long error)

out.WarningT("The image you are trying to add (NAME_OF_IMAGE) doesn't exist ! ")

Comment (medyagh) [reply pkg/minikube/image/cache.go:63]: and also I recommend creating an ErrorType simmilar to https://github.com/medyagh/minikube/blob/ff0e25ada888cf1bd7b262857ce96531c1231e69/pkg/drivers/kic/oci/errors.go#L37

so you can return a specific Error type in case of cache not existing
and then you can chceck if errr == ErrCacheImageDoesntExist {
out.WarningT("The image you are trying to add (NAME_OF_IMAGE) doesn't exist ! ")
} else {
return it like we used to do before and make ugly crash, since we dont know what is going on !
}

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/image/cache.go (hunk 1 above)
Comment (tripolkaandrey) [reply pkg/minikube/image/cache.go:63]: Thank you for a detailed comment. That really helps a new newcomer(meaning me). I will follow your advice

Comment (tripolkaandrey) [reply pkg/minikube/image/cache.go:63]: @medyagh Do I understand correctly that I need to create a separate folder named cache in pkg/minikube/ in which cache_errors.go will be created with ErrCacheImageDoesntExist. Or there is a better way to do it?

Comment (medyagh) [reply pkg/minikube/image/cache.go:63]: no probolem, if we only have one error, we dont need to create a new file.

**Comment by tripolkaandrey** [comment]
@medyagh please take a look

File: pkg/minikube/image/cache.go [hunk 2]
```diff
@@ -31,9 +31,22 @@ import (
 	"k8s.io/klog/v2"
 	"k8s.io/minikube/pkg/minikube/constants"
 	"k8s.io/minikube/pkg/minikube/localpath"
+	"k8s.io/minikube/pkg/minikube/out"
 	"k8s.io/minikube/pkg/util/lock"
 )
 
+// FailFastError type is an error that could not be solved by trying again
+type FailFastError struct {
```
Comment (medyagh) [inline pkg/minikube/image/cache.go:39]: this is doesnt need to be called fail fast error, this is about cache, that made sense in the conext of oci

Comment (medyagh) [reply pkg/minikube/image/cache.go:39]: also this is NOT used anywhere outside, so please make it "private"

**Review by medyagh — CHANGES_REQUESTED** [review]

**Comment by medyagh** [comment]
@tripolkaandrey please also update the PR description with the new UI before and after this PR

File: pkg/minikube/image/cache.go (hunk 2 above)
Comment (tripolkaandrey) [reply pkg/minikube/image/cache.go]: Thank you. Got it.

**Comment by tripolkaandrey** [comment]
@medyagh I have updated PR description. What do you think about taking the image name in parentheses and rephrasing it like that:
```
❗  The image (ubuntu) you are trying to add doesn't exist!
```

**Review by medyagh — APPROVED** [review]

**Comment by tripolkaandrey** [comment]
@medyagh may you help please? I have read the pr process and I guess this PR should be already merged. Did I get something wrong? Also what do you think about my suggestion above?

**Review by medyagh — APPROVED** [review]
