### PR TITLE
cmd/minikube: delete accept no arguments

### LINKED ISSUE #1683: Add a confirmation for minikube delete
After executing `minikube delete namespace <foo>` the command ignored the extra parameters and indeed deleted the Minikube instance.

Of course, that was wrong as I meant to issue `kubectl delete namespace <foo>`. But, it's too late and my error is not recoverable or undoable.

Given that `minikube delete` is a permanent action (visualize death star) and can easily be substituted with the less destructive `kubectl delete x` perhaps an added safeguard confirmation for delete might be appreciated.

### PR DESCRIPTION
**Pull request by darkowlzz**
This changeset makes it necessary to pass a profile/machine name in order
to delete. This would help avoid accidental deletion of machine by just
delete command.

Fixes #1683

### CODE REVIEW

**Comment by darkowlzz** [comment]
Bump to verify CLA

**Comment by darkowlzz** [comment]
oops! This isn't ready. Doesn't accepts the argument as profile. Fixing... 😅

**Comment by r2d4** [comment]
@minikube-bot ok to test

**Comment by darkowlzz** [comment]
Some help with the failing test?
The test times out after 30 minutes. I'm not sure what's causing that. The `delete` command after the test seems to work and delete the vm.

File: cmd/minikube/cmd/delete.go [hunk 1]
```diff
@@ -21,18 +21,27 @@ import (
...
 	"k8s.io/minikube/pkg/minikube/machine"
 )
 
 // deleteCmd represents the delete command
 var deleteCmd = &cobra.Command{
-	Use:   "delete",
-	Short: "Deletes a local kubernetes cluster",
-	Long: `Deletes a local kubernetes cluster. This command deletes the VM, and removes all
-associated files.`,
+	Use:   "delete MINIKUBE_PROFILE_NAME",
```
Comment (r2d4) [inline cmd/minikube/cmd/delete.go]: I don't think we want to break the default `minikube delete` case.

As a fix for #1683, I think we should just make sure to error on unknown arguments after command, rather than silently ignore them. i.e., ` $ minikube delete arg1 arg2` should fail, since we shouldn't ignore unknown arguments

As far as profiles go, each command accepts the `--profile` flag. 

` $ minikube delete`, should work and delete the default machine
` $ minikube delete --profile vm2` should delete the minikube profile vm2

I'm not a huge fan of moving the profile flag behavior to an optional noun after `minikube <start, stop, delete>` since we'd probably have to have every command behave that way.  Sorry if my original comment on the issue was unclear,
> minikube delete either takes no args or just the machine name

I think it really can't take the machine name without a pretty big change to the UX (since all commands should behave similarly.)  But the enforcing the former (no unknown args) is definitely something we should do. 

Let me know if that makes sense

Comment (darkowlzz) [inline cmd/minikube/cmd/delete.go]: Yep, that makes sense. Consistency among the commands :)
I have updated the PR and made delete not accept any argument.

**Comment by darkowlzz** [comment]
Failing again 🤷‍♀️

**Comment by javajon** [comment]
As the original requester for #1683 it is great to see this enhancement added.  Thanks all.
