### PR TITLE
windows: support renaming binary to `kubectl.exe` and  running as kubectl

### LINKED ISSUE #11838: Fix TestFunctional/serial/MinikubeKubectlCmdDirectly on Windows
This is a failing test on Windows that should be fixed.

### PR DESCRIPTION
**Pull request by spowelljr**
Closes #11838

We support renaming the minikube binary to `kubectl` and the binary will run as kubectl. However, we don't support renaming the binary to `kubectl.exe` on Windows and running as kubectl.

This PR adds support for this and also makes the the Windows test pass.

### CODE REVIEW

File: cmd/minikube/cmd/root.go [hunk 1]
```diff
@@ -101,7 +101,8 @@ func Execute() {
 
 	_, callingCmd := filepath.Split(os.Args[0])
 
-	if callingCmd == "kubectl" {
+	isExe := callingCmd == "kubectl.exe" && runtime.GOOS == "windows"
```
Comment (medyagh) [inline cmd/minikube/cmd/root.go:104]: could it also be called as kubectl on windows ? (without user typing .exe) 
so maybe we should call it isExe in case of `kubectl` && runtime.GOOS == "windows ?

Comment (spowelljr) [reply cmd/minikube/cmd/root.go:104]: The line below is `if callingCmd == "kubectl" || isExe`
So if they're calling `kubectl` on Windows it will be caught by `callingCmd == "kubectl"`

**Review by sharifelgamal — APPROVED** [review]
