### PR TITLE
Explicitly remove podman volume and network

### LINKED ISSUE #9705: Podman driver doesn't remove volume or network on delete
This makes the _next_ create attempt fail:

```
🤦  StartHost failed, but will try again: creating host: create: creating: setting up container node: creating volume for minikube container: sudo -n podman volume create minikube --label name.minikube.sigs.k8s.io=minikube --label created_by.minikube.sigs.k8s.io=true: exit status 125
stdout:

stderr:
Error: volume with name minikube already exists: volume already exists

🔄  Restarting existing podman container for "minikube" ...
😿  Failed to start podman container. Running "minikube delete" may fix it: podman inspect ip minikube: sudo -n podman container inspect -f {{.NetworkSettings.IPAddress}} minikube: exit status 125
stdout:

stderr:
Error: error inspecting object: no such container minikube
```

### PR DESCRIPTION
**Pull request by afbjorklund**
The --filter and --label functionality was broken,
in earlier versions of podman (before version 3.0)

Closes #9705

### CODE REVIEW

File: pkg/drivers/kic/oci/volumes.go [hunk 1]
```diff
@@ -29,6 +30,47 @@ import (
 	"k8s.io/klog/v2"
 )
 
+// RemoveVolume removes a volume
+func RemoveVolume(ociBin string, name string) error {
+	if !volumeExists(ociBin, name) {
```
Comment (medyagh) [inline pkg/drivers/kic/oci/volumes.go:35]: nit: what is the performance implication of running this ? would it be better if we just try remove it regardless if it exists or not ? and if it errors out we could check if error is Volume doesn't exist?

**Review by medyagh — COMMENTED** [review]
look good @afbjorklund , but needs rebase

File: pkg/drivers/kic/oci/volumes.go (hunk 1 above)
Comment (afbjorklund) [reply pkg/drivers/kic/oci/volumes.go:35]: Most of the code is just copy/pasted from the network, there are no specific performance considerations. The volume is normally removed with the container (the `-v`) so it is just fallback really.

File: pkg/drivers/kic/oci/volumes.go [hunk 2]
```diff
@@ -30,6 +31,47 @@ import (
 	"k8s.io/klog/v2"
 )
 
+// RemoveVolume removes a volume
+func RemoveVolume(ociBin string, name string) error {
```
Comment (medyagh) [inline pkg/drivers/kic/oci/volumes.go:35]: this func is not used anywhere ?

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/drivers/kic/oci/volumes.go [hunk 3]
```diff
@@ -30,6 +31,47 @@ import (
...
+	if !volumeExists(ociBin, name) {
+		return nil
+	}
+	rr, err := runCmd(exec.Command(ociBin, "volume", "rm", name))
```
Comment (medyagh) [inline pkg/drivers/kic/oci/volumes.go:39]: should we use -f here (force) ?

File: pkg/drivers/kic/oci/volumes.go (hunk 2 above)
Comment (afbjorklund) [reply pkg/drivers/kic/oci/volumes.go:35]: For some reason, the "delete" command (above) is talking directly to oci module. And the usual Delete() is never called ?

oci.RemoveVolume
oci.DeleteAllVolumesByLabel

oci.RemoveNetwork
oci.DeleteKICNetworks

Comment (afbjorklund) [reply pkg/drivers/kic/oci/volumes.go:35]: The naming of those functions is not great, and it seems like the network deletion could do with a specific label ?

File: pkg/drivers/kic/oci/volumes.go (hunk 3 above)
Comment (afbjorklund) [reply pkg/drivers/kic/oci/volumes.go:39]: Hmm, "Remove a volume by force, even if it is being used by a container"

I don't think the volume should be in use, we just deleted the container ?

**Review by medyagh — APPROVED** [review]

**Comment by BLasan** [comment]
@afbjorklund Are we able to close the issue #10379 from this commit as well?
