### PR TITLE
fix images for aliyun registry

### LINKED ISSUE #11476: 无法从registry.cn-hangzhou.aliyuncs.com/google_containers下载镜像
你好：我是中国大陆用户，我无法从registry.cn-hangzhou.aliyuncs.com/google_containers下载相关镜像

**重现问题所需的命令**：minikube start --image-mirror-country=cn  和  minikube dashboard

**失败的命令的完整输出**：<details>

kube-system                    storage-provisioner                                             0/1     ImagePullBackOff   0          5m3s
kubernetes-dashboard   dashboard-metrics-scraper-8554f74445-9x4qb   0/1     ImagePullBackOff   0          6s
kubernetes-dashboard   kubernetes-dashboard-6c87f58d7c-f7txl             0/1     ErrImagePull       0          6s  

</details>

**`minikube logs`命令的输出**： <details>
May 21 14:11:00 minikube kubelet[4547]: E0521 14:11:00.448797    4547 pod_workers.go:191] Error syncing pod f9d0cab0-f1f7-470d-b64f-8bbc36ebc82e ("kubernetes-dashboard-6c87f58d7c-f7txl_kubernetes-dashboard(f9d0cab0-f1f7-470d-b64f-8bbc36ebc82e)"), skipping: failed to "StartContainer" for "kubernetes-dashboard" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: pull access denied for registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetesui/dashboard, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
May 21 14:11:05 minikube kubelet[4547]: E0521 14:11:05.536787    4547 pod_workers.go:191] Error syncing pod 981c80bc-461d-4f63-83a9-227b3e5af388 ("storage-provisioner_kube-system(981c80bc-461d-4f63-83a9-227b3e5af388)"), skipping: failed to "StartContainer" for "storage-provisioner" with ImagePullBackOff: "Back-off pulling image \"registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-minikube/storage-provisioner:v5\""
May 21 14:11:08 minikube kubelet[4547]: E0521 14:11:08.546653    4547 pod_workers.go:191] Error syncing pod c1a886ec-5a49-4fcc-874e-b96b18fdc495 ("dashboard-metrics-scraper-8554f74445-9x4qb_kubernetes-dashboard(c1a886ec-5a49-4fcc-874e-b96b18fdc495)"), skipping: failed to "StartContainer" for "dashboard-metrics-scraper" with ImagePullBackOff: "Back-off pulling image \"registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetesui/metrics-scraper:v1.0.4@sha256:555981a24f184420f3be0c79d4efb6c948a85cfce84034f85a563f4151a81cbf\""
May 21 14:11:14 minikube kubelet[4547]: E0521 14:11:14.539581    4547 pod_workers.go:191] Error syncing pod f9d0cab0-f1f7-470d-b64f-8bbc36ebc82e ("kubernetes-dashboard-6c87f58d7c-f7txl_kubernetes-dashboard(f9d0cab0-f1f7-470d-b64f-8bbc36ebc82e)"), skipping: failed to "StartContainer" for "kubernetes-dashboard" with ImagePullBackOff: "Back-off pulling image \"registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetesui/dashboard:v2.1.0@sha256:7f80b5ba141bead69c4fee8661464857af300d7d7ed0274cf7beecedc00322e6\""
May 21 14:11:17 minikube kubelet[4547]: E0521 14:11:17.535651    4547 pod_workers.go:191] Error syncing pod 981c80bc-461d-4f63-83a9-227b3e5af388 ("storage-provisioner_kube-system(981c80bc-461d-4f63-83a9-227b3e5af388)"), skipping: failed to "StartContainer" for "storage-provisioner" with ImagePullBackOff: "Back-off pulling image \"registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-minikube/storage-provisioner:v5\""

</details>

**使用的操作系统版本**：win10

### PR DESCRIPTION
**Pull request by brian14708**
for aliyun registry must strip namespace for addon images, e.g.
`registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-minikube/storage-provisioner:v5` will not work, but
`registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v5` does work

fixes #11476

related to kubernetes/minikube#10770

### CODE REVIEW

File: pkg/minikube/assets/addons.go [hunk 1]
```diff
@@ -770,6 +771,22 @@ func SelectAndPersistImages(addon *Addon, cc *config.ClusterConfig) (images, cus
...
 
+// fixes addon image names according to image repository used
+func fixAddonImages(repo string, images map[string]string) map[string]string {
+	if repo == "registry.cn-hangzhou.aliyuncs.com/google_containers" {
+		// for aliyun registry must strip namespace from image name, e.g.
+		//   registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-minikube/storage-provisioner:v5 will not work
+		//   registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v5 does work
+		newImages := make(map[string]string)
+		for name, image := range images {
+			tmp := strings.Split(image, "/")
```
Comment (sharifelgamal) [inline pkg/minikube/assets/addons.go:782]: instead of splitting the image here, could you just use `strings.TrimPrefix(image, "k8s-minkube/")`? this will prevent accidentally trimming something we don't want to.

File: pkg/minikube/bootstrapper/bsutil/kubeadm.go [hunk 2]
```diff
@@ -150,6 +151,10 @@ func GenerateKubeadmYAML(cc config.ClusterConfig, n config.Node, r cruntime.Mana
 	if version.GTE(semver.MustParse("1.17.0")) {
 		configTmpl = ktmpl.V1Beta2
 	}
+	// handle the renaming of the coredns image from "coredns" to "coredns/coredns"
+	if version.GTE(semver.MustParse("1.21.0-alpha.1")) && opts.ImageRepository != "" {
```
Comment (medyagh) [inline pkg/minikube/bootstrapper/bsutil/kubeadm.go:155]: sorry for the late review on this PR,

do u mind clarifying is this change related to this PR ?
or could it be a separate PR ? to me it appears like a different PR's problem

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/bootstrapper/bsutil/kubeadm.go (hunk 2 above)
Comment (brian14708) [reply pkg/minikube/bootstrapper/bsutil/kubeadm.go]: removed from current PR, split into #12411

**Review by sharifelgamal — APPROVED** [review]
