### PR TITLE
Fix race condition in cluster setup.

### LINKED ISSUE #85: certificate signed by unknown authority
I was using minikube, then I started using an AWS cluster then switched back to minikube and now I get this :(
```
➜  minikube git:(master) kubectl cluster-info
error: couldn't read version from server: Get https://192.168.99.100:443/api: x509: certificate signed by unknown authority
```
I don't really understand what's going on here?

### PR DESCRIPTION
**Pull request by dlorenc**
We now explicitly generate certs before starting the cluster. This way we can be sure the certs exist when we copy them.

This fixes #85

### CODE REVIEW

**Comment by luxas** [comment]
What was the problem with creating them before localkube started?

**Comment by dlorenc** [comment]
I couldn't reproduce it, but they're was a range condition where minikube would try to copy the certificates before they were actually created. We could put retries/waits there, but i think this is better.

**Comment by luxas** [comment]
I'm sorry, but I think we should find a better option than this.
I would not like `localkube` to have a `generate_certs` option, it seems quite unideomatic
`localkube` should just create them if required, and minikube should make sure it copies the right certs

`localkube` should just work with one command (and I think we should get rid of `start` soon, and convert `version` to `--version=bool`)

WDYT? Is there a better approach we may apply when writing the certs from the VM to the local computer?

**Comment by dlorenc** [comment]
Good point. What about just leaving it in both places. That way localkube can still be started with one command, but if you need to synchronize copying the certs you can call it with two commands.

**Comment by dlorenc** [comment]
To be clear, the main issue is that without a separate command minikube has no way of knowing when the certs are ready. Generating them explicitly seems more idiomatic to me than generating them implicitly, it's how Docker and most other kubernetes systems create and user certificates.

**Comment by luxas** [comment]
What about a flag to `localkube` `--generate-certs=bool` that `minikube` sets to false, and uses the util package for creating them by itself and transferring to the VM before it starts localkube?
That seems like the best solution to me.

As said above, I'd like to get rid of start soon, and convert version to --version=bool, i.e. make localkube a command-less program

**Comment by dlorenc** [comment]
> What about a flag to localkube --generate-certs=bool that minikube sets to false, and uses the util package for creating them by itself and transferring to the VM before it starts localkube?
> That seems like the best solution to me.
> 
> As said above, I'd like to get rid of start soon, and convert version to --version=bool, i.e. make localkube a command-less program

I don't understand the bit about --version=bool.

Minikube could create certs and pass them into the VM, but it's a bit harder for minikube to know all the possible IPs localkube might be listening on.

I don't understand the objection to having a separate command for localkube to generate certs. Could you explain more? It's not exclusive with your goal of making it command-less, users only need to call that command if they need a guarantee the certs are created.

**Comment by luxas** [comment]
`localkube` is a Kubernetes server binary, and they should behave in the same manner.
That means, no commands like `localkube start` or `localkube generate-certs`.
Instead, everything should be passed via flags.
So, I propose to remove the start command, and instead always start it. The `version` command should be a `--version`, and if `--version` is true, the binary should just print the version and exit.

`--generate-certs` is a good flag, after all, it's an option if we want to generate the certs before starting the binary.

Kubernetes _client_ binaries on the other hand, like minikube and kubectl, should have (lots of) commands.

If we then want to expose e.g. status information, a way of stopping localkube without interrupting it via the command line, or some other function, we should do that via a web api, that minikube or whatever other program may call.

**Comment by dlorenc** [comment]
Switched it up to generate certs in minikube and pass them into the VM before starting localkube. PTAL.

File: pkg/localkube/crypto.go [hunk 1]
```diff
@@ -31,10 +31,6 @@ import (
 	"time"
 )
 
-// You may also specify additional subject alt names (either ip or dns names) for the certificate
-// The certificate will be created with file mode 0644. The key will be created with file mode 0600.
-// If the certificate or key files already exist, they will be overwritten.
-// Any parent directories of the certPath or keyPath will be created as needed with file mode 0755.
 func GenerateSelfSignedCert(certPath, keyPath string, ips []net.IP, alternateDNS []string) error {
```
Comment (luxas) [inline pkg/localkube/crypto.go]: Remove this here as you've moved it to `pkg/util`

File: pkg/minikube/cluster/cluster.go [hunk 2]
```diff
@@ -178,17 +183,32 @@ func UpdateCluster(d drivers.Driver) error {
 }
 
 // GetCreds gets the generated credentials required to talk to the APIServer.
-func GetCreds(h sshAble) error {
+func GetCreds(d drivers.Driver) error {
```
Comment (luxas) [inline pkg/minikube/cluster/cluster.go]: Rename to `SetupCerts`?
Also consider moving to `pkg/minikube/cluster/credentials.go`

File: pkg/minikube/cluster/cluster.go [hunk 3]
```diff
@@ -35,7 +36,7 @@ import (
 )
 
 const (
-	remotePath = "/var/lib/localkube/certs"
+	remotePath = "/var/lib/localkube/certs/"
```
Comment (luxas) [inline pkg/minikube/cluster/cluster.go]: Rename to `remoteCertPath`.
Is the `/var/lib/localkube/` path already a constant on the minikube side, or may one change that?

File: pkg/localkube/localkube.go [hunk 4]
```diff
@@ -153,9 +154,8 @@ func (lk LocalkubeServer) GenerateCerts() error {
 		return nil
 	}
 	fmt.Println("Creating cert with IPs: ", ips)
-	alternateDNS := []string{fmt.Sprintf("%s.%s", "kubernetes.default.svc", lk.DNSDomain), "kubernetes.default.svc", "kubernetes.default", "kubernetes"}
 
-	if err := GenerateSelfSignedCert(lk.GetPublicKeyCertPath(), lk.GetPrivateKeyCertPath(), ips, alternateDNS); err != nil {
+	if err := util.GenerateSelfSignedCert(lk.GetPublicKeyCertPath(), lk.GetPrivateKeyCertPath(), ips, util.AlternateDNS); err != nil {
```
Comment (luxas) [inline pkg/localkube/localkube.go]: This makes `util.AlternateDNS` always be `kubernetes.default.svc.cluster.local` even if the flag says something other.

File: pkg/util/contants.go [hunk 5]
```diff
@@ -0,0 +1,9 @@
+package util
+
+import "fmt"
+
+const LocalkubeDirectory = "/var/lib/localkube"
```
Comment (luxas) [inline pkg/util/contants.go]: What about
```go
const (
    DefaultLocalkubeDirectory = "/var/lib/localkube"
    DefaultDNSDomain = "cluster.local"
)

func GetAlternateDNS(domain string) []string {
    return []string{fmt.Sprintf("%s.%s", "kubernetes.default.svc", domain), "kubernetes.default.svc", "kubernetes.default", "kubernetes"}
}
```

File: pkg/util/contants.go [hunk 6]
```diff
@@ -0,0 +1,9 @@
+package util
```
Comment (luxas) [inline pkg/util/contants.go]: typo, should be `pkg/util/constants.go`...

**Comment by luxas** [comment]
I think this is much better :)

I had some comments for you to address, then probably LGTM

File: pkg/minikube/cluster/cluster.go (hunk 3 above)
Comment (dlorenc) [inline pkg/minikube/cluster/cluster.go]: Constant.

Comment (luxas) [inline pkg/minikube/cluster/cluster.go]: Maybe unite with `pkg/util/constants.go` then?

**Comment by dlorenc** [comment]
Cool, I think everything is addressed now.

**Comment by luxas** [comment]
LGTM
