### PR TITLE
service: fix --url mode, add integration tests

### LINKED ISSUE #5789: minikube service opens in browser when it should not
**The exact command to reproduce the issue**:

minikube service --namespace mynamespace --url mynodeportservice

**The full output of the command that failed**:<details>

In versions of minikube through 1.3.1, this output the service URL to stdout, and _did not_ open the URL in the default browser.  In 1.5.1, it outputs the URL and the "🎉  Opening kubernetes service ..." message to stdout, and it opens in the default browser.

With --url=false, it does not open in the browser, but now it outputs an ascii-art table instead of the plain URL.
With --url=true, it behaves the same as with --url.

Based on finding #5699, I tried using --format="{{ .IP }}".  That leads to even greater insanity... it emits the message about opening the service in the default browser, but then fails to do so because it tries to open a file in the current directory matching the IP address, and errors out.

Please restore the older behavior so scripts can get the URL for a service, and fix --format to _not_ try to open the resulting string in the default browser.
</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
Mojave
minikube 1.5.1 installed via homebrew

### PR DESCRIPTION
**Pull request by tstromberg**
The service command was opening URL's, even if `--url` mode was specified. This was caused by a subtle regression in #5718

Fixes #5789

### CODE REVIEW

File: cmd/minikube/cmd/service.go [hunk 1]
```diff
@@ -74,21 +75,26 @@ var serviceCmd = &cobra.Command{
...
-			serviceURLTemplate, serviceURLMode, https, wait, interval)
+		urls, err := service.WaitForService(api, namespace, svc, serviceURLTemplate, serviceURLMode, https, wait, interval)
 		if err != nil {
 			exit.WithError("Error opening service", err)
 		}
 
-		if len(urlString) != 0 {
-			out.T(out.Celebrate, "Opening kubernetes service  {{.namespace_name}}/{{.service_name}} in default browser...", out.V{"namespace_name": namespace, "service_name": svc})
+		for _, u := range urls {
+			_, err := url.Parse(u)
```
Comment (retracile) [inline cmd/minikube/cmd/service.go]: If --format has been passed, will `u` contain that formatted value?  If so, this would imply that `--urls --format {{.IP}}` would generate a warning, when it really shouldn't.  If my understanding is correct, I'd think you'd want the `if serviceURLMode` to come before the `url.Parse(u)` call.

Comment (retracile) [reply cmd/minikube/cmd/service.go]: Based on some local testing, apparently that's not an issue
