### PR TITLE
Use the appropriate OCI for deletePossibleKicLeftOver when known

### LINKED ISSUE #7958: deleting Docker cluster hangs on password prompt: `sudo podman ps`
**Steps to reproduce the issue:** 

1. I start minikube with `./out/minikube start`
2. I try to delete all minikube clusters with `./out/minikube delete --all`

The start command looks good. The delete command leads to a prompt from sudo (actually nine prompts since I always answer with just RETURN). Expected is no prompt from sudo. Is this a regression or a changed behaviour? Last  time (a couple of days ago) I tried the same sequence of commands, the `delete` step worked without any sudo prompt. After the third unsuccessful attempt to get something done via sudo, the delete command seems to work and there are no logs left over (./out/minikube logs answers `There is no local cluster named "minikube"`). I feel there's something not correct in this setup. What shall I try?

**Full output of failed command:** 
% ./out/minikube delete --all --alsologtostderr    
I0501 11:28:55.690433   31894 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io --format {{.Names}}
I0501 11:28:55.768173   31894 cli_runner.go:108] Run: docker ps -a --filter label=created_by.minikube.sigs.k8s.io=true --format {{.Names}}
I0501 11:28:55.857771   31894 cli_runner.go:108] Run: docker inspect minikube --format={{.State.Status}}
I0501 11:28:55.945993   31894 cli_runner.go:108] Run: docker exec --privileged -t minikube /bin/bash -c "sudo init 0"
I0501 11:28:57.153000   31894 cli_runner.go:108] Run: docker inspect minikube --format={{.State.Status}}
I0501 11:28:57.355540   31894 oci.go:504] container minikube status is Stopped
I0501 11:28:57.355566   31894 oci.go:516] Successfully shutdown container minikube
I0501 11:28:57.355612   31894 cli_runner.go:108] Run: docker rm -f -v minikube
I0501 11:28:57.489665   31894 volumes.go:34] trying to delete all docker volumes with label created_by.minikube.sigs.k8s.io=true
I0501 11:28:57.490017   31894 cli_runner.go:108] Run: docker volume ls --filter label=created_by.minikube.sigs.k8s.io=true --format {{.Name}}
I0501 11:28:57.557507   31894 cli_runner.go:108] Run: docker volume rm --force minikube
I0501 11:28:57.920941   31894 volumes.go:56] trying to prune all docker volumes with label created_by.minikube.sigs.k8s.io=true
I0501 11:28:57.921009   31894 cli_runner.go:108] Run: docker volume prune -f --filter label=created_by.minikube.sigs.k8s.io=true
🔥  Deleting "minikube" in docker ...
I0501 11:28:58.006147   31894 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}
I0501 11:28:58.087536   31894 volumes.go:34] trying to delete all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0501 11:28:58.087599   31894 cli_runner.go:108] Run: docker volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}
I0501 11:28:58.179693   31894 volumes.go:56] trying to prune all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0501 11:28:58.179757   31894 cli_runner.go:108] Run: docker volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube
I0501 11:28:58.258713   31894 cli_runner.go:108] Run: sudo podman ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for sand: 
Sorry, try again.
[sudo] password for sand: 
Sorry, try again.
[sudo] password for sand: 
I0501 11:29:06.663100   31894 cli_runner.go:147] Completed: sudo podman ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}: (8.404352766s)
I0501 11:29:06.663135   31894 volumes.go:34] trying to delete all podman volumes with label name.minikube.sigs.k8s.io=minikube
I0501 11:29:06.663208   31894 cli_runner.go:108] Run: sudo podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for sand: 

Sorry, try again.
[sudo] password for sand: 
Sorry, try again.
[sudo] password for sand: 
I0501 11:29:14.111421   31894 cli_runner.go:147] Completed: sudo podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}: (7.448182524s)
W0501 11:29:14.111462   31894 delete.go:211] error deleting volumes (might be okay).
To see the list of volumes run: 'docker volume ls'
:[listing volumes by label "name.minikube.sigs.k8s.io=minikube": sudo podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}: exit status 1
stdout:

stderr:
sudo: 3 incorrect password attempts
]
I0501 11:29:14.111580   31894 volumes.go:56] trying to prune all podman volumes with label name.minikube.sigs.k8s.io=minikube
I0501 11:29:14.111655   31894 cli_runner.go:108] Run: sudo podman volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for sand: 
Sorry, try again.
[sudo] password for sand: 
Sorry, try again.
[sudo] password for sand: 
I0501 11:29:23.003258   31894 cli_runner.go:147] Completed: sudo podman volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube: (8.891577654s)
W0501 11:29:23.003307   31894 delete.go:216] error pruning volume (might be okay):
[prune volume by label name.minikube.sigs.k8s.io=minikube: sudo podman volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube: exit status 1
stdout:

stderr:
sudo: 3 incorrect password attempts
]
I0501 11:29:23.005642   31894 cli_runner.go:108] Run: docker inspect minikube --format={{.State.Status}}
I0501 11:29:23.086619   31894 delete.go:75] Unable to get host status for minikube, assuming it has already been deleted: state: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:

stderr:
Error: No such object: minikube
🔥  Removing /home/sand/.minikube/machines/minikube ...
I0501 11:29:23.097300   31894 lock.go:35] WriteFile acquiring /home/sand/.kube/config: {Name:mk505f793881700367e2a950c92de29206d7625a Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
💀  Removed all traces of the "minikube" cluster.
🔥  Successfully deleted all profiles

**Full output of `minikube start` command used, if not already included:**
% ./out/minikube start                                                                      
😄  minikube v1.10.0-beta.2 on Debian bullseye/sid (xen/amd64)
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.18.1 preload ...
    > preloaded-images-k8s-v3-v1.18.1-docker-overlay2-amd64.tar.lz4: 525.47 MiB
🔥  Creating docker container (CPUs=2, Memory=3200MB) ...
🐳  Preparing Kubernetes v1.18.1 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

### PR DESCRIPTION
**Pull request by tstromberg**
Partially resolves #7958

Important changes:

- deletePossibleKicLeftOver is now only called once
- deletePossibleKicLeftOver is now called inside DeleteProfiles if a profile is known, and after DeleteProfiles if it's orphaned
- deletePossibleKicLeftOver now takes a driver name. If unknown, Docker is passed in.
 
Other changes:

- deleteContainersAndVolumes only runs docker commands if docker is found
- extra logging added

## Old Behavior

Deleting a known Docker profile:

```
I0507 15:27:06.349053   24786 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io --format {{.Names}}
I0507 15:27:06.416720   24786 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}
🔥  Deleting container "minikube" ...
I0507 15:27:06.461363   24786 cli_runner.go:108] Run: docker inspect minikube --format={{.State.Status}}
I0507 15:27:06.503719   24786 cli_runner.go:108] Run: docker exec --privileged -t minikube /bin/bash -c "sudo init 0"
I0507 15:27:07.800099   24786 cli_runner.go:108] Run: docker inspect minikube --format={{.State.Status}}
I0507 15:27:07.838059   24786 oci.go:519] temporary error: container minikube status is Running but expect it to be exited
I0507 15:27:07.838109   24786 oci.go:525] Successfully shutdown container minikube
I0507 15:27:07.838230   24786 cli_runner.go:108] Run: docker rm -f -v minikube
I0507 15:27:08.213716   24786 volumes.go:34] trying to delete all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:27:08.213876   24786 cli_runner.go:108] Run: docker volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}
I0507 15:27:08.247632   24786 cli_runner.go:108] Run: docker volume rm --force minikube
I0507 15:27:08.655286   24786 volumes.go:56] trying to prune all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:27:08.655443   24786 cli_runner.go:108] Run: docker volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube
I0507 15:27:08.688318   24786 cli_runner.go:108] Run: podman ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}
I0507 15:27:08.688363   24786 volumes.go:34] trying to delete all podman volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:27:08.688439   24786 cli_runner.go:108] Run: podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}
W0507 15:27:08.688457   24786 delete.go:211] error deleting volumes (might be okay).
To see the list of volumes run: 'docker volume ls'
:[listing volumes by label "name.minikube.sigs.k8s.io=minikube": podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}: exec: "podman": executable file not found in $PATH
stdout:

stderr:
]
I0507 15:27:08.689139   24786 volumes.go:56] trying to prune all podman volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:27:08.689249   24786 cli_runner.go:108] Run: podman volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube
W0507 15:27:08.689277   24786 delete.go:216] error pruning volume (might be okay):
[prune volume by label name.minikube.sigs.k8s.io=minikube: podman volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube: exec: "podman": executable file not found in $PATH
stdout:

stderr:
]
🔥  Deleting "minikube" in docker ...
I0507 15:27:08.712940   24786 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}
I0507 15:27:08.749170   24786 volumes.go:34] trying to delete all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:27:08.749329   24786 cli_runner.go:108] Run: docker volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}
I0507 15:27:08.781812   24786 volumes.go:56] trying to prune all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:27:08.781945   24786 cli_runner.go:108] Run: docker volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube
I0507 15:27:08.815468   24786 cli_runner.go:108] Run: podman ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}
I0507 15:27:08.815497   24786 volumes.go:34] trying to delete all podman volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:27:08.815562   24786 cli_runner.go:108] Run: podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}
W0507 15:27:08.815581   24786 delete.go:211] error deleting volumes (might be okay).
To see the list of volumes run: 'docker volume ls'
:[listing volumes by label "name.minikube.sigs.k8s.io=minikube": podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}: exec: "podman": executable file not found in $PATH
stdout:

stderr:
]
I0507 15:27:08.815593   24786 volumes.go:56] trying to prune all podman volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:27:08.815663   24786 cli_runner.go:108] Run: podman volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube
W0507 15:27:08.815682   24786 delete.go:216] error pruning volume (might be okay):
[prune volume by label name.minikube.sigs.k8s.io=minikube: podman volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube: exec: "podman": executable file not found in $PATH
stdout:

stderr:
]
I0507 15:27:08.816516   24786 cli_runner.go:108] Run: docker inspect minikube --format={{.State.Status}}
I0507 15:27:08.869693   24786 delete.go:75] Unable to get host status for minikube, assuming it has already been deleted: state: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:


stderr:
Error: No such object: minikube
🔥  Removing /Users/tstromberg/.minikube/machines/minikube ...
I0507 15:27:08.891006   24786 lock.go:35] WriteFile acquiring /Users/tstromberg/.kube/config: {Name:mke11dbcd579c84d4d098461d9cff60a03fa7a38 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
💀  Removed all traces of the "minikube" cluster.
```

Deleting a non-existent profile:

```
I0507 15:27:28.695001   24859 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io --format {{.Names}}
🙄  "minikube" profile does not exist, trying anyways.
I0507 15:27:28.727648   24859 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}
I0507 15:27:28.758055   24859 volumes.go:34] trying to delete all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:27:28.758224   24859 cli_runner.go:108] Run: docker volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}
I0507 15:27:28.790737   24859 volumes.go:56] trying to prune all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:27:28.790897   24859 cli_runner.go:108] Run: docker volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube
I0507 15:27:28.823814   24859 cli_runner.go:108] Run: podman ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}
I0507 15:27:28.824224   24859 volumes.go:34] trying to delete all podman volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:27:28.824348   24859 cli_runner.go:108] Run: podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}
W0507 15:27:28.824371   24859 delete.go:211] error deleting volumes (might be okay).
To see the list of volumes run: 'docker volume ls'
:[listing volumes by label "name.minikube.sigs.k8s.io=minikube": podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}: exec: "podman": executable file not found in $PATH
stdout:

stderr:
]
I0507 15:27:28.825341   24859 volumes.go:56] trying to prune all podman volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:27:28.825490   24859 cli_runner.go:108] Run: podman volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube
W0507 15:27:28.825518   24859 delete.go:216] error pruning volume (might be okay):
[prune volume by label name.minikube.sigs.k8s.io=minikube: podman volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube: exec: "podman": executable file not found in $PATH
stdout:

stderr:
]
I0507 15:27:28.827318   24859 lock.go:35] WriteFile acquiring /Users/tstromberg/.kube/config: {Name:mke11dbcd579c84d4d098461d9cff60a03fa7a38 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
💀  Removed all traces of the "minikube" cluster.
```

## New Behavior

Deleting a known Docker profile:

```
I0507 15:25:17.974658   24496 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io --format {{.Names}}
I0507 15:25:18.049231   24496 delete.go:189] DeleteProfiles
I0507 15:25:18.049256   24496 delete.go:249] Deleting minikube
I0507 15:25:18.049267   24496 delete.go:252] minikube configuration: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:982 CPUs:2 DiskSize:20000 Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.1 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[{Component:kubeadm Key:pod-network-cidr Value:10.244.0.0/16}] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP:172.17.0.3 Port:8443 KubernetesVersion:v1.18.1 ControlPlane:true Worker:true}] Addons:map[default-storageclass:true storage-provisioner:true] VerifyComponents:map[apiserver:true system_pods:true]}
🔥  Deleting "minikube" in docker ...
I0507 15:25:18.062225   24496 delete.go:212] deleting possible KIC leftovers for minikube (driver=docker) ...
I0507 15:25:18.062419   24496 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}
🔥  Deleting container "minikube" ...
I0507 15:25:18.107310   24496 cli_runner.go:108] Run: docker inspect minikube --format={{.State.Status}}
I0507 15:25:18.153675   24496 cli_runner.go:108] Run: docker exec --privileged -t minikube /bin/bash -c "sudo init 0"
I0507 15:25:19.449497   24496 cli_runner.go:108] Run: docker inspect minikube --format={{.State.Status}}
I0507 15:25:19.505777   24496 oci.go:519] temporary error: container minikube status is Running but expect it to be exited
I0507 15:25:19.505816   24496 oci.go:525] Successfully shutdown container minikube
I0507 15:25:19.505940   24496 cli_runner.go:108] Run: docker rm -f -v minikube
I0507 15:25:19.953547   24496 volumes.go:34] trying to delete all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:25:19.953700   24496 cli_runner.go:108] Run: docker volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}
I0507 15:25:19.989498   24496 cli_runner.go:108] Run: docker volume rm --force minikube
I0507 15:25:20.422175   24496 volumes.go:56] trying to prune all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:25:20.422329   24496 cli_runner.go:108] Run: docker volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube
I0507 15:25:20.457190   24496 cli_runner.go:108] Run: docker inspect minikube --format={{.State.Status}}
I0507 15:25:20.513857   24496 delete.go:75] Unable to get host status for minikube, assuming it has already been deleted: state: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:


stderr:
Error: No such object: minikube
🔥  Removing /Users/tstromberg/.minikube/machines/minikube ...
I0507 15:25:20.526813   24496 lock.go:35] WriteFile acquiring /Users/tstromberg/.kube/config: {Name:mke11dbcd579c84d4d098461d9cff60a03fa7a38 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
💀  Removed all traces of the "minikube" cluster.
```

Deleting a non-existent profile:

```
I0507 15:25:40.120023   24583 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io --format {{.Names}}
🙄  "minikube" profile does not exist, trying anyways.
I0507 15:25:40.156649   24583 delete.go:189] DeleteProfiles
I0507 15:25:40.156661   24583 delete.go:249] Deleting minikube
I0507 15:25:40.156673   24583 delete.go:260] minikube has no configuration, will try to make it work anyways
I0507 15:25:40.158487   24583 lock.go:35] WriteFile acquiring /Users/tstromberg/.kube/config: {Name:mke11dbcd579c84d4d098461d9cff60a03fa7a38 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
💀  Removed all traces of the "minikube" cluster.
I0507 15:25:40.174158   24583 delete.go:212] deleting possible KIC leftovers for minikube (driver=docker) ...
I0507 15:25:40.174329   24583 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}
I0507 15:25:40.214958   24583 volumes.go:34] trying to delete all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:25:40.215113   24583 cli_runner.go:108] Run: docker volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}
I0507 15:25:40.247956   24583 volumes.go:56] trying to prune all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0507 15:25:40.248109   24583 cli_runner.go:108] Run: docker volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube
```

### CODE REVIEW

File: cmd/minikube/cmd/delete.go [hunk 1]
```diff
@@ -143,16 +152,22 @@ func runDelete(cmd *cobra.Command, args []string) {
...
 
-		deletePossibleKicLeftOver(cname)
-
 		errs := DeleteProfiles([]*config.Profile{profile})
 		if len(errs) > 0 {
 			HandleDeletionErrors(errs)
 		}
+
+		if orphan {
+			// TODO: generalize for non-KIC drivers
```
Comment (medyagh) [inline cmd/minikube/cmd/delete.go:168]: add ISSUE number for this
