### PR TITLE
Get latest valid tag for each image during cacheing

### LINKED ISSUE #13136: k8s v1.24.0-alpha.1: The image 'k8s.gcr.io/coredns/coredns:1.8.4' was not found; unable to add it to cache.
### What Happened?

Using minikube from HEAD: 90300a4c5263a47a5457e9868bdb732f0a7f07d2

`./out/minikube start --kubernetes-version=v1.24.0-alpha.1`:

```
😄  minikube v1.24.0 on Darwin 11.5.2
✨  Automatically selected the hyperkit driver
...
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
❗  The image 'k8s.gcr.io/coredns/coredns:1.8.4' was not found; unable to add it to cache.
🐳  Preparing Kubernetes v1.24.0-alpha.1 on Docker 20.10.8 ...
❌  Unable to load cached images: loading cached images: stat /Users/tstromberg/.minikube/cache/images/k8s.gcr.io/coredns/coredns_1.8.4: no such file or directory
```

It does successfully progress

### Attach the log file

Filtered for coredns:

```
I1209 15:26:17.455637   91527 image.go:134] retrieving image: k8s.gcr.io/coredns/coredns:1.8.4
I1209 15:26:17.496764   91527 image.go:180] daemon lookup for k8s.gcr.io/coredns/coredns:1.8.4: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
W1209 15:26:17.499631   91527 image.go:190] authn lookup for k8s.gcr.io/coredns/coredns:1.8.4 (trying anon): error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
I1209 15:26:17.909258   91527 image.go:194] remote lookup for k8s.gcr.io/coredns/coredns:1.8.4: GET https://k8s.gcr.io/v2/coredns/coredns/manifests/1.8.4: MANIFEST_UNKNOWN: Failed to fetch "1.8.4" from request "/v2/coredns/coredns/manifests/1.8.4".
I1209 15:26:17.909368   91527 cache.go:96] cache image "k8s.gcr.io/coredns/coredns:1.8.4" -> "/Users/tstromberg/.minikube/cache/images/k8s.gcr.io/coredns/coredns_1.8.4" took 454.875267ms
W1209 15:26:17.909472   91527 out.go:241] ❗  The image 'k8s.gcr.io/coredns/coredns:1.8.4' was not found; unable to add it to cache.
I1209 15:26:34.984641   91527 cache_images.go:83] LoadImages start: [k8s.gcr.io/kube-apiserver:v1.24.0-alpha.1 k8s.gcr.io/kube-controller-manager:v1.24.0-alpha.1 k8s.gcr.io/kube-scheduler:v1.24.0-alpha.1 k8s.gcr.io/kube-proxy:v1.24.0-alpha.1 k8s.gcr.io/pause:3.6 k8s.gcr.io/etcd:3.5.0-0 k8s.gcr.io/coredns/coredns:1.8.4 gcr.io/k8s-minikube/storage-provisioner:v5 docker.io/kubernetesui/dashboard:v2.3.1 docker.io/kubernetesui/metrics-scraper:v1.0.7]
I1209 15:26:34.985874   91527 image.go:76] couldn't find image digest k8s.gcr.io/coredns/coredns:1.8.4 from local daemon: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
I1209 15:26:34.985921   91527 image.go:134] retrieving image: k8s.gcr.io/coredns/coredns:1.8.4
I1209 15:26:34.986257   91527 image.go:180] daemon lookup for k8s.gcr.io/coredns/coredns:1.8.4: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
W1209 15:26:34.986630   91527 image.go:190] authn lookup for k8s.gcr.io/coredns/coredns:1.8.4 (trying anon): error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
I1209 15:26:35.885809   91527 image.go:194] remote lookup for k8s.gcr.io/coredns/coredns:1.8.4: GET https://k8s.gcr.io/v2/coredns/coredns/manifests/1.8.4: MANIFEST_UNKNOWN: Failed to fetch "1.8.4" from request "/v2/coredns/coredns/manifests/1.8.4".
I1209 15:26:35.885832   91527 image.go:93] error retrieve Image k8s.gcr.io/coredns/coredns:1.8.4 ref Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
I1209 15:26:35.885850   91527 cache_images.go:111] "k8s.gcr.io/coredns/coredns:1.8.4" needs transfer: got empty img digest "" for k8s.gcr.io/coredns/coredns:1.8.4
I1209 15:26:35.885877   91527 docker.go:239] Removing image: k8s.gcr.io/coredns/coredns:1.8.4
I1209 15:26:35.886017   91527 ssh_runner.go:195] Run: docker rmi k8s.gcr.io/coredns/coredns:1.8.4
I1209 15:26:35.969676   91527 cache_images.go:281] Loading image from: /Users/tstromberg/.minikube/cache/images/k8s.gcr.io/coredns/coredns_1.8.4
W1209 15:27:05.604679   91527 out.go:241] ❌  Unable to load cached images: loading cached images: stat /Users/tstromberg/.minikube/cache/images/k8s.gcr.io/coredns/coredns_1.8.4: no such file or directory
```

### Operating System

macOS (Default)

### Driver

HyperKit

### PR DESCRIPTION
**Pull request by ckannon**
fixes #13136 
Get tags from k8s.gcr.io, fall back to hard coded tag if cannot get

### CODE REVIEW

**Comment by ckannon** [comment]
@spowelljr this is the fix we talked about

File: pkg/minikube/bootstrapper/images/images.go [hunk 1]
```diff
@@ -28,15 +32,21 @@ import (
 	"k8s.io/minikube/pkg/version"
 )
 
+const (
+	tagUrlTemplate = "https://%s/v2/%s/tags/list"
```
Comment (medyagh) [inline pkg/minikube/bootstrapper/images/images.go:36]: lets add comment here please

File: pkg/minikube/bootstrapper/images/images.go [hunk 2]
```diff
@@ -64,14 +74,53 @@ func componentImage(name string, v semver.Version, mirror string) string {
 	return fmt.Sprintf("%s:v%s", path.Join(kubernetesRepo(mirror), name), v)
 }
 
+func getLatestTag(url string, lastKnownGood string) string {
```
Comment (medyagh) [inline pkg/minikube/bootstrapper/images/images.go:77]: comment here, also consider change name to something more meaningful, usually in golang word get is implied and not needed to be added to the name.

Comment (medyagh) [reply pkg/minikube/bootstrapper/images/images.go:77]: also lets comment why we need this maybe link to an issue or describing what we are trying to solve here.

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/bootstrapper/images/images.go (hunk 1 above)
Comment (ckannon) [reply pkg/minikube/bootstrapper/images/images.go:37]: fixed

File: pkg/minikube/bootstrapper/images/images.go (hunk 2 above)
Comment (ckannon) [reply pkg/minikube/bootstrapper/images/images.go]: fixed!

**Comment by medyagh** [comment]
> fixes #13136 Get tags from k8s.gcr.io, fall back to hard coded tag if cannot get

Wouldn't this be wrong for if the user wants to use an old kubernetes version ?
for example minikube start --kubernetes-version=1.17.1 ? in that case is this PR gonna try to use Latest Pause image for that kuberentes version first ? If yes then the PR is wrong

**Comment by ckannon** [comment]
> 

Hey Medya, No, earlier versions are drawn from a map of kubernetes version to image version (constants.KubeadmImages[majorMinorVersion][imageName]). This is just the fallback version if the map does not contain the selected k8s version (for example if you use a beta or nightly). In the past, this version was just randomly hardcoded (if you look at the diffs you can see where it was hardcoded to 1.8.4 for coredns, which isn't even a valid version, v1.8.4 is the correct version number).

**Comment by ckannon** [comment]
@spowelljr @medyagh can I snag an ok-to-test please?

**Comment by medyagh** [comment]
> > 
> 
> Hey Medya, No, earlier versions are drawn from a map of kubernetes version to image version (constants.KubeadmImages[majorMinorVersion][imageName]). This is just the fallback version if the map does not contain the selected k8s version (for example if you use a beta or nightly). In the past, this version was just randomly hardcoded (if you look at the diffs you can see where it was hardcoded to 1.8.4 for coredns, which isn't even a valid version, v1.8.4 is the correct version number).

thank you for clarifying

File: pkg/minikube/bootstrapper/images/images.go [hunk 3]
```diff
@@ -64,14 +76,54 @@ func componentImage(name string, v semver.Version, mirror string) string {
 	return fmt.Sprintf("%s:v%s", path.Join(kubernetesRepo(mirror), name), v)
 }
 
+// fixes 13136 by getting the latest image version from the k8s.gcr.io repository instead of hardcoded
+func findLatestTagFromRepository(url string, lastKnownGood string) string {
+	client := &http.Client{}
+	req, err := http.NewRequest("GET", url, nil)
+
+	if err != nil {
+		klog.Infof("Failed to get latest image version for %s, reverting to version %s\n", url, lastKnownGood)
```
Comment (spowelljr) [inline pkg/minikube/bootstrapper/images/images.go:85]: Since this is somewhat of a failure, I wonder if it would make more sense to make this `klog.Warningf`, what are your thought?

File: pkg/minikube/bootstrapper/images/images.go [hunk 4]
```diff
@@ -64,14 +76,54 @@ func componentImage(name string, v semver.Version, mirror string) string {
...
+
+	type TagsResponse struct {
+		Name string   `json:"name"`
+		Tags []string `json:"tags"`
+	}
+
+	tags := TagsResponse{}
+	err = json.Unmarshal(body, &tags)
+	if err != nil || len(tags.Tags) < 1 {
+		klog.Infof("Failed to read latest image version for %s, reverting to version %s\n", url, lastKnownGood)
```
Comment (spowelljr) [inline pkg/minikube/bootstrapper/images/images.go:111]: I feel if we error out here it's possible the JSON structure changed and could be valuable to include the `err` in the log, thoughts?

Could also argue the other errors could be important as well, but if we error on those likely the user just can't connect the internet and there's not much debugging could help with.

File: pkg/minikube/bootstrapper/images/images.go [hunk 5]
```diff
@@ -64,14 +76,54 @@ func componentImage(name string, v semver.Version, mirror string) string {
...
+
+	if err != nil || resp.StatusCode != http.StatusOK {
+		klog.Infof("Failed to get latest image version for %s, reverting to version %s\n", url, lastKnownGood)
+		return lastKnownGood
+	}
+	defer resp.Body.Close()
+
+	body, err := io.ReadAll(resp.Body)
+	if err != nil {
+		klog.Infof("Failed to read latest image version for %s, reverting to version %s\n", url, lastKnownGood)
```
Comment (spowelljr) [inline pkg/minikube/bootstrapper/images/images.go:99]: Since all the error messages match, `fmt.Sprintf` this string and reuse it?

Comment (yardik) [reply pkg/minikube/bootstrapper/images/images.go:99]: Fixed

File: pkg/minikube/bootstrapper/images/images.go (hunk 4 above)
Comment (yardik) [reply pkg/minikube/bootstrapper/images/images.go:111]: fixed!

File: pkg/minikube/bootstrapper/images/images.go (hunk 3 above)
Comment (yardik) [reply pkg/minikube/bootstrapper/images/images.go:85]: Agreed, and fixed

File: pkg/minikube/bootstrapper/images/images.go (hunk 4 above)
Comment (ckannon) [reply pkg/minikube/bootstrapper/images/images.go]: > I feel if we error out here it's possible the JSON structure changed and could be valuable to include the `err` in the log, thoughts?
> 
> Could also argue the other errors could be important as well, but if we error on those likely the user just can't connect the internet and there's not much debugging could help with.

Yeah.. I think the err might be best included for all. Even if it's a network problem, or they need a proxy set, the err should Identity that for them. Will fix.

File: pkg/minikube/bootstrapper/images/images.go (hunk 3 above)
Comment (ckannon) [reply pkg/minikube/bootstrapper/images/images.go]: +1

**Comment by ckannon** [comment]
Validated flaked tests are OK. This PR should be ready to merge now.

File: pkg/minikube/bootstrapper/images/images.go [hunk 6]
```diff
@@ -18,25 +18,37 @@ limitations under the License.
...
 // Pause returns the image name to pull for a given Kubernetes version
 func Pause(v semver.Version, mirror string) string {
 	// Note: changing this logic requires bumping the preload version
 	// Should match `PauseVersion` in:
 	// https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go
 	// https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants_unix.go
 	pv := "3.6"
-	majorMinorVersion := fmt.Sprintf("v%d.%d", v.Major, v.Minor)
 	imageName := "pause"
+	pv = findLatestTagFromRepository(fmt.Sprintf(tagURLTemplate, kubernetesRepo(mirror), imageName), pv)
```
Comment (spowelljr) [inline pkg/minikube/bootstrapper/images/images.go:49]: I think it would make sense to move this to the `else` case if we don't find the image in `constants.KubeadmImages` because right now we're committing to a network call which may be overwritten anyway. This case makes more sense to be the fallback if not found in the constants

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: pkg/minikube/bootstrapper/images/images.go (hunk 6 above)
Comment (ckannon) [reply pkg/minikube/bootstrapper/images/images.go]: Agreed. Fixed.

File: pkg/minikube/bootstrapper/images/images.go [hunk 7]
```diff
@@ -90,10 +144,12 @@ func etcd(v semver.Version, mirror string) string {
 	// Should match `DefaultEtcdVersion` in:
 	// https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go
 	ev := "3.5.0-0"
-	majorMinorVersion := fmt.Sprintf("v%d.%d", v.Major, v.Minor)
 	imageName := "etcd"
+	majorMinorVersion := fmt.Sprintf("v%d.%d", v.Major, v.Minor)
 	if eVersion, ok := constants.KubeadmImages[majorMinorVersion][imageName]; ok {
 		ev = eVersion
+	} else {
+		ev = findLatestTagFromRepository(fmt.Sprintf(tagURLTemplate, kubernetesRepo(mirror), ev), ev)
```
Comment (spowelljr) [inline pkg/minikube/bootstrapper/images/images.go:152]:
```suggestion
		ev = findLatestTagFromRepository(fmt.Sprintf(tagURLTemplate, kubernetesRepo(mirror), imageName), ev)
```
The version is getting passed in instead of the name

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: pkg/minikube/bootstrapper/images/images.go (hunk 7 above)
Comment (ckannon) [reply pkg/minikube/bootstrapper/images/images.go]: Oh wow.. nice catch @spowelljr!

File: pkg/minikube/bootstrapper/images/images.go [hunk 8]
```diff
@@ -64,24 +77,65 @@ func componentImage(name string, v semver.Version, mirror string) string {
...
+func findLatestTagFromRepository(url string, lastKnownGood string) string {
+	client := &http.Client{}
+	req, err := http.NewRequest("GET", url, nil)
+	errorMsg := fmt.Sprintf("Failed to get latest image version for %s, reverting to version %s.", url, lastKnownGood)
+	if err != nil {
+		klog.Warningf("%s Error %v", errorMsg, err)
+		return lastKnownGood
+	}
+
+	resp, err := client.Do(req)
```
Comment (spowelljr) [inline pkg/minikube/bootstrapper/images/images.go:90]: This can be changed to
```
resp, err := client.Get(url)
```
Which will remove these lines
```
	client := &http.Client{}
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		klog.Warningf("%s Error %v", errorMsg, err)
		return lastKnownGood
	}
```

Comment (ckannon) [reply pkg/minikube/bootstrapper/images/images.go]: Thanks! Changed.

**Review by spowelljr — APPROVED** [review]

**Comment by ckannon** [comment]
Nope, earlier versions are drawn from a map of kubernetes version to image
version. This is just the fallback version if the map does not contain the
selected k8s version (for example if you use a beta or nightly). In the
past, this version was just randomly hardcoded (if you look at the diffs
you can see where)
