### PR TITLE
Fix syntax of minikube kubectl example command

### LINKED ISSUE #6238: `minikube kubectl` documentation is incorrect and confusing
To reproduce:

- I installed minikube via brew on a Mac machine: `brew install minikube`
- I started minikube:

```
$ minikube start
😄  minikube v1.6.2 on Darwin 10.15
✨  Selecting 'hyperkit' driver from existing profile (alternates: [virtualbox])
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running hyperkit "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
🚀  Launching Kubernetes ...
🏄  Done! kubectl is now configured to use "minikube"
⚠️  /Users/jameswen/google-cloud-sdk/bin/kubectl is version 1.13.11-dispatcher, and is incompatible with Kubernetes 1.17.0. You will need to update /Users/jameswen/google-cloud-sdk/bin/kubectl or use 'minikube kubectl' to connect with this cluster
```

This presumably sets up my local kubectl to talk to the minikube K8s cluster. However, my local `kubectl version` is outdated as seen by the last output message. I decide to use `minikube kubectl` as the output message suggests.

- I'm able to use `minikube kubectl` to execute kubectl commands that don't require a `--namespace` flag:

```
$ minikube kubectl create namespace testing
💾  Downloading kubectl v1.17.0
namespace/testing created
$ minikube kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
$ minikube kubectl get pods
No resources found in default namespace.
```

- However, I'm not able to use `minikube kubectl` to execute `kubectl` commands that require a `--namespace` flag:

```
$ minikube kubectl get pods --namespace kube-system
Error: unknown flag: --namespace


Usage:
  minikube kubectl [flags] [options]

Use "minikube kubectl options" for a list of global command-line options (applies to all commands).
```

```
$ minikube kubectl get pods -n kube-system
Error: unknown shorthand flag: 'n' in -n


Usage:
  minikube kubectl [flags] [options]

Use "minikube kubectl options" for a list of global command-line options (applies to all commands).
```

```
$ minikube kubectl -n kube-system get pods
Error: unknown shorthand flag: 'n' in -n


Usage:
  minikube kubectl [flags] [options]

Use "minikube kubectl options" for a list of global command-line options (applies to all commands).
```

### PR DESCRIPTION
**Pull request by afbjorklund**
Need to terminate the minikube flags with --,
before starting with the kubectl command flags.

Fixes #6238

### CODE REVIEW

File: cmd/minikube/cmd/kubectl.go [hunk 1]
```diff
@@ -41,7 +41,7 @@ var kubectlCmd = &cobra.Command{
 	Long: `Run the kubernetes client, download it if necessary.
 Examples:
```
Comment (tstromberg) [inline cmd/minikube/cmd/kubectl.go]: Can you explicitly call out and mention that `--` is required before passing any flags into kubectl?

Comment (medyagh) [reply cmd/minikube/cmd/kubectl.go]: I agree ! I wonder is there a way we can add the -- ourselves for all of them ?

Comment (afbjorklund) [reply cmd/minikube/cmd/kubectl.go]: This goes for all commands, including ssh. So it's nothing special for the "kubectl" command.

Would be nice if something could be done on the generic level, since it is the generated help...

**Comment by afbjorklund** [comment]
It is slightly better now, but the generic usage information printed can still be misleading:

```
Run the kubernetes client, download it if necessary.
Examples:
minikube kubectl -- --help
minikube kubectl -- get pods --namespace kube-system

Usage:
  minikube kubectl [flags] [options]

Use "minikube options" for a list of global command-line options (applies to all commands).
```

It doesn't mention any flags to `kubectl` commands, so it has the same issue as `ssh`.

Log into or run a command on a machine with SSH; similar to 'docker-machine ssh'.

```
Options:
      --native-ssh=true: Use native Golang SSH client (default true). Set to 'false' to use the command line 'ssh'
command when accessing the docker machine. Useful for the machine drivers when they will not start with 'Waiting for
SSH'.

Usage:
  minikube ssh [flags] [options]

Use "minikube options" for a list of global command-line options (applies to all commands).
```

That is, if you want to pass flags to kubectl or to the command you run with ssh, you need `--`.

File: cmd/minikube/cmd/kubectl.go (hunk 1 above)
Comment (afbjorklund) [reply cmd/minikube/cmd/kubectl.go]: Added explicit warning

**Comment by afbjorklund** [comment]
Also it would be nice if you could run the dashboard without having to install kubectl...
