### PR TITLE
fix insufficient memory issues

### LINKED ISSUE #11029: Tests Flake due to insufficient memory
with insufficient memory, all different weird kind of issues happen, seen several tests frequently failing b/c of that, and containerd timeouts are one of them

example:
https://storage.googleapis.com/minikube-builds/logs/11006/74537ca/KVM_Linux_containerd.html#fail_TestForceSystemdFlag
https://storage.googleapis.com/minikube-builds/logs/11006/74537ca/KVM_Linux_containerd.html#fail_TestForceSystemdEnv

> ❯ minikube start -p memless --memory=1800 --force-systemd --alsologtostderr -v=9 --driver=kvm2  --container-runtime=containerd

```
...
I0408 23:23:42.109960   32694 crio.go:119] couldn't verify netfilter by "sudo sysctl net.bridge.bridge-nf-call-iptables" which might be okay. error: sudo sysctl net.bridge.bridge-nf-call-iptables: Process exited with status 255
...
W0408 23:25:18.298509   32694 out.go:222] ❌  Exiting due to RUNTIME_ENABLE: stat /run/containerd/containerd.sock: Process exited with status 1
stdout:

stderr:
stat: cannot stat '/run/containerd/containerd.sock': No such file or directory
...
```

inside the vm:

```
# crictl images --output json
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x11121fe, 0x16)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/panic.go:1116 +0x72 fp=0x7fff8c7be3d0 sp=0x7fff8c7be3a0 pc=0x435bb2
runtime.sysMap(0xc000000000, 0x4000000, 0x1917418)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/mem_linux.go:169 +0xc6 fp=0x7fff8c7be410 sp=0x7fff8c7be3d0 pc=0x418f86
runtime.(*mheap).sysAlloc(0x18fc580, 0x400000, 0x0, 0x4)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/malloc.go:727 +0x1e5 fp=0x7fff8c7be4b8 sp=0x7fff8c7be410 pc=0x40c925
runtime.(*mheap).grow(0x18fc580, 0x1, 0x0)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/mheap.go:1344 +0x85 fp=0x7fff8c7be520 sp=0x7fff8c7be4b8 pc=0x4284a5
runtime.(*mheap).allocSpan(0x18fc580, 0x1, 0x656c6d656d002a00, 0x1917428, 0x0)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/mheap.go:1160 +0x6b6 fp=0x7fff8c7be5a0 sp=0x7fff8c7be520 pc=0x428256
runtime.(*mheap).alloc.func1()
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/mheap.go:907 +0x65 fp=0x7fff8c7be5f8 sp=0x7fff8c7be5a0 pc=0x461b65
runtime.(*mheap).alloc(0x18fc580, 0x1, 0x12a, 0x0)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/mheap.go:901 +0x85 fp=0x7fff8c7be648 sp=0x7fff8c7be5f8 pc=0x427725
runtime.(*mcentral).grow(0x190f438, 0x0)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/mcentral.go:506 +0x7a fp=0x7fff8c7be690 sp=0x7fff8c7be648 pc=0x41895a
runtime.(*mcentral).cacheSpan(0x190f438, 0x40000)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/mcentral.go:177 +0x3e5 fp=0x7fff8c7be708 sp=0x7fff8c7be690 pc=0x4186e5
runtime.(*mcache).refill(0x7f501fdc6108, 0x2a)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/mcache.go:142 +0xa5 fp=0x7fff8c7be728 sp=0x7fff8c7be708 pc=0x418085
runtime.(*mcache).nextFree(0x7f501fdc6108, 0x18e482a, 0x7f501fdc6108, 0x7f4ffb4a6000, 0x7fff8c7be7b8)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/malloc.go:880 +0x8d fp=0x7fff8c7be760 sp=0x7fff8c7be728 pc=0x40d1ad
runtime.mallocgc(0x180, 0x10fbec0, 0x7fff8c7be801, 0x7fff8c7be860)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/malloc.go:1061 +0x834 fp=0x7fff8c7be800 sp=0x7fff8c7be760 pc=0x40db94
runtime.newobject(0x10fbec0, 0x4608a0)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/malloc.go:1195 +0x38 fp=0x7fff8c7be830 sp=0x7fff8c7be800 pc=0x40e038
runtime.malg(0x8000, 0x0)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/proc.go:3493 +0x31 fp=0x7fff8c7be870 sp=0x7fff8c7be830 pc=0x440751
runtime.mpreinit(0x18e4820)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/os_linux.go:340 +0x29 fp=0x7fff8c7be890 sp=0x7fff8c7be870 pc=0x432969
runtime.mcommoninit(0x18e4820, 0xffffffffffffffff)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/proc.go:663 +0xf7 fp=0x7fff8c7be8d8 sp=0x7fff8c7be890 pc=0x4399b7
runtime.schedinit()
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/proc.go:565 +0xa5 fp=0x7fff8c7be930 sp=0x7fff8c7be8d8 pc=0x439545
runtime.rt0_go(0x7fff8c7be968, 0x4, 0x7fff8c7be968, 0x0, 0x0, 0x4, 0x7fff8c7beefe, 0x7fff8c7bef05, 0x7fff8c7bef0c, 0x7fff8c7bef15, ...)
	/nix/store/r5wsnvxfc14badlg8fcx4fyvji3lksz6-go-1.15/share/go/src/runtime/asm_amd64.s:214 +0x125 fp=0x7fff8c7be938 sp=0x7fff8c7be930 pc=0x468fc5
```
```
# free
              total        used        free      shared  buff/cache   available
Mem:        1782984      129504       80684     1551104     1572796       17924
Swap:             0           0           0

```

/assign

### PR DESCRIPTION
**Pull request by prezha**
fixes #11029

examples and oom issue details are given in the description of the original issue #11029

proposed solution: increase (recommended) min memory to 2048 MiB

### CODE REVIEW

File: cmd/minikube/cmd/start_flags.go [hunk 1]
```diff
@@ -96,7 +96,7 @@ const (
 	waitTimeout             = "wait-timeout"
 	nativeSSH               = "native-ssh"
 	minUsableMem            = 1800 // Kubernetes (kubeadm) will not start with less
-	minRecommendedMem       = 1900 // Warn at no lower than existing configurations
+	minRecommendedMem       = 2048 // Warn at no lower than existing configurations
```
Comment (afbjorklund) [inline cmd/minikube/cmd/start_flags.go:99]: We need to fix this, because the value is _also_ used for looking at the available memory _inside_ the VM...

So we should be using 2048 MiB on the "outside", but look for at least 1700 MiB on the "inside"

```go:
        // ControlPlaneNumCPU is the number of CPUs required on control-plane
        ControlPlaneNumCPU = 2

        // ControlPlaneMem is the number of megabytes of memory required on the control-plane
        // Below that amount of RAM running a stable control plane would be difficult.
        ControlPlaneMem = 1700
```

There is a force flag to run it it anyway, but we should do the complaint (the same as kubeadm)

**Review by afbjorklund — CHANGES_REQUESTED** [review]

**Comment by afbjorklund** [comment]
We should remove the current constants, and provide two new ones. Also need to clear up the MB vs MiB confusion...

When I run the regular VM (with the minimum 2048 MiB), I get 1985 MiB total - as reported by the `free` command.

🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

```
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ free -m
              total        used        free      shared  buff/cache   available
Mem:           1985         645          85         611        1254         582
Swap:             0           0           0
```

Checking for 1700 or 1800 doesn't matter, but 1900 can have some false positives* (and there is much less available)

\* I think some of the cloud images ended up with like 1892 (for 2 GiB VM), but that shouldn't need any user concern

**Comment by afbjorklund** [comment]
I opened #10808 to provide some better documentation on the requirements

**Comment by afbjorklund** [comment]
> proposed solution: increase (recommended) min memory to 2048 MiB

We should definitely use --memory 2048, my comment was about the code

**Comment by prezha** [comment]
@afbjorklund thanks for your comments!

would you agree then with this pr - to fix the flaking tests (focusing on --memory 2048) due to the lack of memory, and we have a follow-up pr to better handle customer user mem params, proposed min memory (for different envs)?

**Comment by afbjorklund** [comment]
> @afbjorklund thanks for your comments!
> 
> would you agree then with this pr - to fix the flaking tests (focusing on --memory 2048) due to the lack of memory and clear that one out, and we can have a separate pr to better handle customer user mem params, proposed min memory (for different envs) in line with your #10808?

Yes, changing the VM to use --memory=2048 can be done any time. The other is more of a backlog item.

**Comment by prezha** [comment]
great, thanks!
i see still a lot of tests flake bc of this, so it will be much clearer when we rule this one out :)

File: cmd/minikube/cmd/start_flags.go (hunk 1 above)
Comment (medyagh) [reply cmd/minikube/cmd/start_flags.go:99]: agree with anders, I think we should not bump this, but check fo the outter VM memory

Comment (prezha) [reply cmd/minikube/cmd/start_flags.go:99]: the focus of this pr was to eliminate tests flake due to insufficient memory errors - shall i just remove this change then and leave the changes in how much memory tests allocate?

Comment (prezha) [reply cmd/minikube/cmd/start_flags.go]: i've reverted this specific change as it's irrelevant for the specific issue it tries to solve for flake tests and should be instead addressed under a separate issue/pr

**Review by medyagh — APPROVED** [review]
