### PR TITLE
kvm: provide solution if user doesn't belong to libvirt group

### LINKED ISSUE #5617: kvm2 driver: check if user in "libvirt" group and exit if they are not
Please, add that user starting minikube should be in "libvirt" group. Because without adding user in "libvirt" group will be an error "authentification unavailable"

### LINKED ISSUE #10070: kvm add solution message for when user needs to reload the terminal to get libvirt permissions
when user adds their user to the libvir group, they still need to reload the terminal, 

```
$ /snap/google-cloud-sdk/current/bin/minikube start --driver=kvm2
😄  minikube v1.16.0 on Ubuntu 20.10
✨  Using the kvm2 driver based on user configuration

💣  Exiting due to PROVIDER_KVM2_ERROR: /usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied
💡  Suggestion: Follow your Linux distribution instructions for configuring KVM
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/
```

minikube should instead of that error, give users Advice that Might help if we get that specific error

https://github.com/medyagh/minikube/blob/199ea3425b8343e533d8d1982ad750a8dab7d59e/pkg/minikube/reason/known_issues.go#L1003

additional information @spowelljr 

```

$ virt-host-validate
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : PASS
  QEMU: Checking if device /dev/kvm is accessible                            : FAIL (Check /dev/kvm is world writable or you are in a group that is allowed to access it)
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : PASS
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS
  QEMU: Checking for device assignment IOMMU support                         : PASS
  QEMU: Checking if IOMMU is enabled by kernel                               : WARN (IOMMU appears to be disabled in kernel. Add intel_iommu=on to kernel cmdline arguments)
  QEMU: Checking for secure guest support                                    : WARN (Unknown if this platform has Secure Guest support)
   LXC: Checking for Linux >= 2.6.26                                         : PASS
   LXC: Checking for namespace ipc                                           : PASS
   LXC: Checking for namespace mnt                                           : PASS
   LXC: Checking for namespace pid                                           : PASS
   LXC: Checking for namespace uts                                           : PASS
   LXC: Checking for namespace net                                           : PASS
   LXC: Checking for namespace user                                          : PASS
   LXC: Checking for cgroup 'cpu' controller support                         : PASS
   LXC: Checking for cgroup 'cpuacct' controller support                     : PASS
   LXC: Checking for cgroup 'cpuset' controller support                      : PASS
   LXC: Checking for cgroup 'memory' controller support                      : PASS
   LXC: Checking for cgroup 'devices' controller support                     : PASS
   LXC: Checking for cgroup 'freezer' controller support                     : PASS
   LXC: Checking for cgroup 'blkio' controller support                       : PASS
   LXC: Checking if device /sys/fs/fuse/connections exists                   : PASS
$ virsh -c qemu:///system list --all
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied
$ virsh net-list
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied

```

### PR DESCRIPTION
**Pull request by prezha**
fixes #5617
fixes #10070

for kvm driver, as described in original issues, if user does not belong to libvirt group, we fail with a generic confusing message
here we check that and provide a more descriptive solution message if not

### example (after)
```
❯ id
uid=1000(prezha) gid=100(users) groups=100(users),459(docker)
```
```
❯ minikube start --driver=kvm2
😄  minikube v1.18.0 on Opensuse-Tumbleweed
✨  Using the kvm2 driver based on user configuration

🚫  Exiting due to PR_KVM_USER_PERMISSION: libvirt group membership check failed:
user is not a member of the appropriate libvirt group
💡  Suggestion: Ensure that you are a member of the appropriate libvirt group (remember to relogin for group changes to take effect!)
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/5617
    ▪ https://github.com/kubernetes/minikube/issues/10070
```

```
❯ minikube start --driver=kvm2 --alsologtostderr -v=9
I0304 01:28:48.201151    1629 out.go:239] Setting OutFile to fd 1 ...
I0304 01:28:48.201206    1629 out.go:291] isatty.IsTerminal(1) = true
I0304 01:28:48.201211    1629 out.go:252] Setting ErrFile to fd 2...
I0304 01:28:48.201215    1629 out.go:291] isatty.IsTerminal(2) = true
I0304 01:28:48.201284    1629 root.go:308] Updating PATH: /home/prezha/.minikube/bin
I0304 01:28:48.201437    1629 out.go:246] Setting JSON to false
I0304 01:28:48.225822    1629 start.go:108] hostinfo: {"hostname":"codex.triplepoint.tech","uptime":7886,"bootTime":1614813443,"procs":416,"os":"linux","platform":"opensuse-tumbleweed","platformFamily":"","platformVersion":"","kernelVersion":"5.10.16-1-default","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"8fbb1ced-553b-443c-a3a1-fd6724e8ce90"}
I0304 01:28:48.226056    1629 start.go:118] virtualization: kvm host
I0304 01:28:48.237151    1629 out.go:129] 😄  minikube v1.18.0 on Opensuse-Tumbleweed
😄  minikube v1.18.0 on Opensuse-Tumbleweed
I0304 01:28:48.237467    1629 notify.go:126] Checking for updates...
I0304 01:28:48.237777    1629 driver.go:323] Setting default libvirt URI to qemu:///system
I0304 01:28:48.243203    1629 out.go:129] ✨  Using the kvm2 driver based on user configuration
✨  Using the kvm2 driver based on user configuration
I0304 01:28:48.243272    1629 start.go:276] selected driver: kvm2
I0304 01:28:48.243297    1629 start.go:718] validating driver "kvm2" against <nil>
I0304 01:28:48.243335    1629 start.go:729] status for kvm2: {Installed:true Healthy:false Running:true NeedsImprovement:false Error:libvirt group membership check failed:
user is not a member of the appropriate libvirt group Reason:PR_KVM_USER_PERMISSION Fix:Check that libvirtd is properly installed and that you are a member of the appropriate libvirt group (remember to relogin for group changes to take effect!) Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/}
I0304 01:28:48.246662    1629 out.go:129]

W0304 01:28:48.246878    1629 out.go:191] 🚫  Exiting due to PR_KVM_USER_PERMISSION: libvirt group membership check failed:
user is not a member of the appropriate libvirt group
🚫  Exiting due to PR_KVM_USER_PERMISSION: libvirt group membership check failed:
user is not a member of the appropriate libvirt group
W0304 01:28:48.247126    1629 out.go:191] 💡  Suggestion: Ensure that you are a member of the appropriate libvirt group (remember to relogin for group changes to take effect!)
💡  Suggestion: Ensure that you are a member of the appropriate libvirt group (remember to relogin for group changes to take effect!)
W0304 01:28:48.247252    1629 out.go:191] 📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/
W0304 01:28:48.247350    1629 out.go:191] 🍿  Related issues:
🍿  Related issues:
W0304 01:28:48.247497    1629 out.go:191]     ▪ https://github.com/kubernetes/minikube/issues/5617
    ▪ https://github.com/kubernetes/minikube/issues/5617
W0304 01:28:48.247615    1629 out.go:191]     ▪ https://github.com/kubernetes/minikube/issues/10070
    ▪ https://github.com/kubernetes/minikube/issues/10070
I0304 01:28:48.253543    1629 out.go:129]
```

### CODE REVIEW

File: pkg/minikube/registry/drvs/kvm2/kvm2.go [hunk 1]
```diff
@@ -113,16 +114,55 @@ func status() registry.State {
 		return registry.State{Error: err, Fix: "Install libvirt", Doc: docURL}
 	}
 
+	// check if the current user is a member of "libvirt*" group
+	lvMember := false
```
Comment (ilya-zuyev) [inline pkg/minikube/registry/drvs/kvm2/kvm2.go:118]: May be add a function for this check? Just to make `status()` still fit in in one screen. something like `curUserLibvirt() (bool, error)`? Need to find a better name though :)

Comment (medyagh) [reply pkg/minikube/registry/drvs/kvm2/kvm2.go:118]: agree with @ilya-zuyev , lets add a helper function that this get called, for better code readablity @prezha

**Review by medyagh — CHANGES_REQUESTED** [review]

File: pkg/minikube/registry/drvs/kvm2/kvm2.go (hunk 1 above)
Comment (prezha) [reply pkg/minikube/registry/drvs/kvm2/kvm2.go]: @ilya-zuyev , @medyagh thank you for your review: i agree and moved the check into a separate helper func

**Review by medyagh — APPROVED** [review]

**Comment by offlinehacker** [comment]
This check breaks if using libvirt over tcp. I am running libvirt inside docker container and this breaks minikube. It also kinda does not make sense to force this check.

**Comment by prezha** [comment]
@offlinehacker i think this check has been there for a while now and was asked by users with an idea to prevent a number of issues (eg, #5617)

for your specific setup, did you try `--force` flag (it should emit an error but not exit then)?
