### PR TITLE
Separate cached kubernetes binaries by OS on host machine

### LINKED ISSUE #6559: addon enable fails after update: kubectl: cannot execute binary file
**The exact command to reproduce the issue**: minikube addons enable ingress

**The full output of the command that failed**:
💣  enable failed: running callbacks: [addon apply: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.17.0/kubectl apply -f /etc/kubernetes/addons/ingress-configmap.yaml -f /etc/kubernetes/addons/ingress-rbac.yaml -f /etc/kubernetes/addons/ingress-dp.yaml: Process exited with status 126
stdout:

stderr:
/var/lib/minikube/binaries/v1.17.0/kubectl: /var/lib/minikube/binaries/v1.17.0/kubectl: cannot execute binary file
]

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**: macOSv10.15.2

### PR DESCRIPTION
**Pull request by priyawadhwa**
This way, all kubernetes binaries stored in ~/.minikube/cache/linux will be copied over to the VM and used for `minikube kubectl` on linux machines. kubectl will be stored in `~/.minikube/cache/{windows or darwin}` on windows/darwin so that `minikube kubectl` still works.

Should fix #6559

### CODE REVIEW

**Comment by afbjorklund** [comment]
This means that the current cache will be invalidated, right ?

Should we set up a backwards compatible link or something

File: pkg/minikube/machine/cache_binaries.go [hunk 1]
```diff
@@ -63,7 +64,7 @@ func KubernetesReleaseURLSHA1(binaryName, version, osName, archName string) stri
 
 // CacheBinary will cache a binary on the host
 func CacheBinary(binary, version, osName, archName string) (string, error) {
-	targetDir := localpath.MakeMiniPath("cache", version)
+	targetDir := localpath.MakeMiniPath(filepath.Join("cache", osName), version)
```
Comment (afbjorklund) [inline pkg/minikube/machine/cache_binaries.go]: I think you can use `MakeMiniPath("cache", osName, version)` here

**Comment by afbjorklund** [comment]
@priyawadhwa : do you think we need to add the architecture to the path as well ?

hypothetical case about a linux-arm64 host running towards a linux-amd64 cluster

then again we can probably worry about that later, when we support remote machines
the image caching infrastructure, so we will need to fix more than just this single place

at the moment, all non-amd64 platforms requires using the `none` driver anyway.
that means that the linux binaries will be for the local platform, including kubernetes

**Comment by afbjorklund** [comment]
This will also fix #6583

**Comment by priyawadhwa** [comment]
@afbjorklund Yah I agree, I don't think we need to factor in architectures right now. 

I also don't think it's super necessary to set up a backwards compatible link. On the first run it'll take a few seconds to cache binaries in the right spot, but after that it shouldn't matter again. Unless you feel strongly, in which case I can add it in.

File: pkg/minikube/machine/cache_binaries.go (hunk 1 above)
Comment (priyawadhwa) [reply pkg/minikube/machine/cache_binaries.go]: thanks, updated!

**Comment by tstromberg** [comment]
Looks good. Do you mind following this up with a PR to add a `kubectl` command integration test to assert that we don't break it again in the future?

**Comment by afbjorklund** [comment]
Sounds good, can worry about arch later - better to fix the darwin/Mac use case now.

File: test/integration/aaa_download_only_test.go [hunk 2]
```diff
@@ -74,7 +74,7 @@ func TestDownloadOnly(t *testing.T) {
 
 				for _, img := range imgs {
 					img = strings.Replace(img, ":", "_", 1) // for example kube-scheduler:v1.15.2 --> kube-scheduler_v1.15.2
-					fp := filepath.Join(localpath.MiniPath(), "cache", "images", img)
+					fp := filepath.Join(localpath.MiniPath(), "cache", runtime.GOOS, "images", img)
```
Comment (afbjorklund) [inline test/integration/aaa_download_only_test.go]: hmm, did we add some code changes for the images ? couldn't see any

Comment (priyawadhwa) [reply test/integration/aaa_download_only_test.go]: nope, i added that to the wrong spot. just pushed the fix.

**Comment by tstromberg** [comment]
These tests don't look good:

https://storage.googleapis.com/minikube-builds/logs/6586/VirtualBox_macOS.html

File: test/integration/aaa_download_only_test.go [hunk 3]
```diff
@@ -83,7 +84,7 @@ func TestDownloadOnly(t *testing.T) {
 
 				// checking binaries downloaded (kubelet,kubeadm)
 				for _, bin := range constants.KubernetesReleaseBinaries {
-					fp := filepath.Join(localpath.MiniPath(), "cache", v, bin)
+					fp := filepath.Join(localpath.MiniPath(), "cache", runtime.GOOS, v, bin)
```
Comment (medyagh) [inline test/integration/aaa_download_only_test.go]: for kubeadm,kubelet we always want linux, since we run it in linux VM or linux container.

**Comment by medyagh** [comment]
we shouldn't cache kubeadm for mac os ! we need kubeadm and kublet always be linux !

File: test/integration/aaa_download_only_test.go (hunk 3 above)
Comment (medyagh) [inline test/integration/aaa_download_only_test.go]: the test should check for linux for kubeadm,kubelet...always.
since those are run always inside linux

Comment (priyawadhwa) [reply test/integration/aaa_download_only_test.go]: done

Comment (priyawadhwa) [reply test/integration/aaa_download_only_test.go]: done

**Comment by medyagh** [comment]
thank you

**Comment by afbjorklund** [comment]
Did you make kubectl download mandatory ? Though it was “on demand”

**Comment by priyawadhwa** [comment]
@afbjorklund I figured it should be downloaded if `--download-only` is specified so that users can still use `minikube kubectl`

**Comment by afbjorklund** [comment]
@priyawadhwa : good idea! I think I missed the context, when I just looked at the diff...
