### PR TITLE
Don't allow profile names that conflict with a multi-node name

### LINKED ISSUE #10061: Potential profile naming conflict with multi-node cluster.
Minikube doesn't have a restriction on profile name. It have a potential conflict with multi-node cluster.
E.g) create test-profile with multiple node will fail if test-profile-m02 profile already exists.

Naming rule for profile or check routine should be added before create new profile(node).

```
❯ minikube start -p test-profile-m02
😄  [test-profile-m02] minikube v1.16.0 on Darwin 10.15.7
✨  Automatically selected the docker driver
👍  Starting control plane node test-profile-m02 in cluster test-profile-m02
🔥  Creating docker container (CPUs=2, Memory=1988MB) ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "test-profile-m02" cluster and "default" namespace by default
❯ minikube start -p test-profile -n 2
😄  [test-profile] minikube v1.16.0 on Darwin 10.15.7
✨  Automatically selected the docker driver
👍  Starting control plane node test-profile in cluster test-profile
🔥  Creating docker container (CPUs=2, Memory=1988MB) ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass

👍  Starting node test-profile-m02 in cluster test-profile
🏃  Updating the running docker "test-profile-m02" container ...
🌐  Found network options:
    ▪ NO_PROXY=192.168.59.2
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
    ▪ env NO_PROXY=192.168.59.2

❌  Exiting due to GUEST_START: adding node: joining cluster: joining cp: kubeadm join: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.0:$PATH kubeadm join control-plane.minikube.internal:8443 --token 15q92i.1cqpjd2yesbv0apv     --discovery-token-ca-cert-hash sha256:da216a960016510720e6ed9ad47804e0906ffe31de0cfb884810698f7f56351c --ignore-preflight-errors=all --node-name=test-profile-m02": Process exited with status 1
stdout:
[preflight] Running pre-flight checks

stderr:
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
        [WARNING Swap]: running with swap on is not supported. Please disable swap
        [WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.0. Latest validated version: 19.03
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: couldn't validate the identity of the API Server: Get "https://control-plane.minikube.internal:8443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": context deadline exceeded
To see the stack trace of this error execute with --v=5 or higher


😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose

```

### PR DESCRIPTION
**Pull request by daehyeok**
Check profile and node name before add to prevent conflict with
machine name on multinode cluster.

Fixes #10061

### CODE REVIEW

File: cmd/minikube/cmd/start.go [hunk 1]
```diff
@@ -638,6 +639,29 @@ func hostDriver(existing *config.ClusterConfig) string {
 	return h.Driver.DriverName()
 }
 
+// validateProfileName makes sure that new profile name not duplicated with any of machine names in existing multi-node clusters.
+func validateProfileName(existing *config.ClusterConfig) {
+	if existing != nil {
+		return
+	}
+
+	validPs, _, err := config.ListProfiles()
```
Comment (medyagh) [inline cmd/minikube/cmd/start.go:648]: I think this is an expensive call, since it checks the status of all Profiles
two options
1- Create a Light Weight ListProfile
config.ListProfileLight() 
which only returns list of profile names and doesnt check if they are running or valid

2- do not allow anyone to create any profile named "name-m0X"
so it never creates that problem.

what do u think ?

**Review by medyagh — CHANGES_REQUESTED** [review]

File: cmd/minikube/cmd/start.go (hunk 1 above)
Comment (daehyeok) [reply cmd/minikube/cmd/start.go]: I think first option is better idea. May be it can be used in other place and don't bother user if they already created -m0x profile.

**Review by medyagh — APPROVED** [review]
looks good, I would like to see example of it in the PR description

**Review by medyagh — COMMENTED** [review]
can we add integration test for this here ? https://github.com/medyagh/minikube/blob/89a8cdc794098f9ba0550fbb5eeb19bc3dd8774d/test/integration/multinode_test.go#L46

**Comment by medyagh** [comment]
TestMultiNode/serial/RestartMultiNode fails on both Docker and KVM i wonder if it is related?

**Comment by daehyeok** [comment]
> TestMultiNode/serial/RestartMultiNode fails on both Docker and KVM i wonder if it is related?

Fixed it.
	https://github.com/kubernetes/minikube/blob/fb0658c1984d8b5a6a4422a719fcc181104d3748/pkg/minikube/node/node.go#L48-L50

**Comment by medyagh** [comment]
@daehyeok do u mind pulling upstream master on this PR ?

**Comment by daehyeok** [comment]
> @daehyeok do u mind pulling upstream master on this PR ?

rebased with upstream master branch

File: cmd/minikube/cmd/start.go [hunk 2]
```diff
@@ -638,6 +639,29 @@ func hostDriver(existing *config.ClusterConfig) string {
 	return h.Driver.DriverName()
 }
 
+// validateProfileName makes sure that new profile name not duplicated with any of machine names in existing multi-node clusters.
+func validateProfileName(existing *config.ClusterConfig) {
+	if existing != nil {
```
Comment (priyawadhwa) [inline cmd/minikube/cmd/start.go:644]: Shouldn't this be

```go
if existing == nil {
  return
}
```

Either way, it doesn't look like `existing` is used at all in this function. If that's intentional, I would probably remove this if statement and rewrite the function header to:


```go
func validateProfileName(_ *config.ClusterConfig) {
```

File: pkg/minikube/config/profile.go [hunk 3]
```diff
@@ -223,7 +223,25 @@ func ListProfiles(miniHome ...string) (validPs []*Profile, inValidPs []*Profile,
 	return validPs, inValidPs, nil
 }
 
-// removeDupes removes duplicates
+// ListProfilesLight returns profiles in minikube home dir
+// Unlike `ListProfiles` this function doens't try to get profile from container
+func ListProfilesLight(miniHome ...string) (ps []*Profile, err error) {
```
Comment (priyawadhwa) [inline pkg/minikube/config/profile.go:228]: I would rename this function to `ListValidProfiles` to more accurately describe what is happening

File: test/integration/multinode_test.go [hunk 4]
```diff
@@ -308,3 +309,39 @@ func validateDeleteNodeFromMultiNode(ctx context.Context, t *testing.T, profile
...
+	rr, err = Run(t, exec.CommandContext(ctx, Target(), startArgs...))
+	if err != nil {
+		t.Errorf("failed to start profile. args %q : %v", rr.Command(), err)
+	}
+
+	// Add a node to the current cluster. It's expected failture
+	addArgs := []string{"node", "add", "-p", profile}
+	rr, err = Run(t, exec.CommandContext(ctx, Target(), addArgs...))
+	if err == nil {
+		t.Errorf("expected add node command to fail fail. args %q : %v", rr.Command(), err)
```
Comment (priyawadhwa) [inline test/integration/multinode_test.go:340]: nit: "fail fail" should just be "fail"

Comment (daehyeok) [reply test/integration/multinode_test.go:340]: Oops, fixed

File: cmd/minikube/cmd/start.go (hunk 2 above)
Comment (daehyeok) [reply cmd/minikube/cmd/start.go:644]: Remove argument, and changed to call function only existing is not nil.

```
if existing != nil {
		upgradeExistingConfig(existing)
		validateProfileName()
	}
```

File: pkg/minikube/config/profile.go (hunk 3 above)
Comment (daehyeok) [reply pkg/minikube/config/profile.go:228]: Fixed.

**Review by sharifelgamal — APPROVED** [review]

**Review by medyagh — APPROVED** [review]
