### PR TITLE
fix: "profile list" shows paused clusters as "Running"

### LINKED ISSUE #8920: "profile list" shows paused clusters as "Running"
With a paused cluster, run "minikube profile list":

```
|----------|-----------|------------|--------------|------|--------------|---------|
| Profile  | VM Driver |  Runtime   |      IP      | Port |   Version    | Status  |
|----------|-----------|------------|--------------|------|--------------|---------|
| crio     | docker    | crio       | 172.17.0.3   | 8443 | v1.18.3      | Running |
| minikube | docker    | containerd | 172.17.0.4   | 8443 | v1.18.3      | Running |
| v119     | hyperkit  | docker     | 192.168.64.3 | 8443 | v1.19.0-rc.4 | Running |
|----------|-----------|------------|--------------|------|--------------|---------|
```

All 3 of these clusters are paused. For comparison, here's the JSON output showing the cluster as paused:

```
% minikube status -p v119 -o json --layout=cluster | jq                                                                                                                                         {
  "Name": "v119",
  "StatusCode": 418,
  "StatusName": "Paused",
  "Step": "Done",
  "StepDetail": "⏯️  Paused 14 containers in: kube-system, kubernetes-dashboard, storage-gluster, istio-operator",
  "BinaryVersion": "v1.12.2",
  "Components": {
    "kubeconfig": {
      "Name": "kubeconfig",
      "StatusCode": 200,
      "StatusName": ""
    }
  },
  "Nodes": [
    {
      "Name": "v119",
      "StatusCode": 200,
      "StatusName": "OK",
      "Components": {
        "apiserver": {
          "Name": "apiserver",
          "StatusCode": 418,
          "StatusName": "Paused"
        },
        "kubelet": {
          "Name": "kubelet",
          "StatusCode": 405,
          "StatusName": "Stopped"
        }
      }
    }
  ]
}
```

I believe the root cause of this is that `profile list` shows the host state rather than the apiserver staet.

### PR DESCRIPTION
**Pull request by taciomcosta**
<!-- 🎉 Thank you for contributing to minikube! 🎉 Here are some hints to get your PR merged faster:

1. Your PR title will be included in the release notes, choose it carefully
2. If the PR fixes an issue, add "fixes #<issue number>" to the description.
3. If the PR is a user interface change, please include a "before" and "after" example.
4. If the PR is a large design change, please include an enhancement proposal:
https://github.com/kubernetes/minikube/tree/master/enhancements
-->

fixes #8920 

__Before__

```
[kubernetes/minikube]$ minikube profile list
|----------|-----------|---------|---------------|------|---------|---------|
| Profile  | VM Driver | Runtime |      IP       | Port | Version | Status  |
|----------|-----------|---------|---------------|------|---------|---------|
| minikube | kvm2      | docker  | 192.168.39.24 | 8443 | v1.19.0 | Running |
|----------|-----------|---------|---------------|------|---------|---------|

[kubernetes/minikube]$ minikube pause
⏸️  Pausing node minikube ... 
⏯️  Paused 14 containers in: kube-system, kubernetes-dashboard, storage-gluster, istio-operator

[kubernetes/minikube]$ minikube profile list
|----------|-----------|---------|---------------|------|---------|---------|
| Profile  | VM Driver | Runtime |      IP       | Port | Version | Status  |
|----------|-----------|---------|---------------|------|---------|---------|
| minikube | kvm2      | docker  | 192.168.39.24 | 8443 | v1.19.0 | Running |
|----------|-----------|---------|---------------|------|---------|---------|

[kubernetes/minikube]$ minikube profile list -o json | jq

{                                                                                                                                                                                                                                                                                             
  "valid": [                                                                                                                                       
    {                                                                                                                                              
      "Name": "minikube",                                                                                                                          
      "Status": "Running",                                                                                                                          
      "Config": {                                                                                                                                  
        "Name": "minikube",                
...
```

__After__

```
[kubernetes/minikube]$ minikube profile list
|----------|-----------|---------|---------------|------|---------|---------|
| Profile  | VM Driver | Runtime |      IP       | Port | Version | Status  |
|----------|-----------|---------|---------------|------|---------|---------|
| minikube | kvm2      | docker  | 192.168.39.24 | 8443 | v1.19.0 | Running |
|----------|-----------|---------|---------------|------|---------|---------|

[kubernetes/minikube]$ minikube pause
⏸️  Pausing node minikube ... 
⏯️  Paused 14 containers in: kube-system, kubernetes-dashboard, storage-gluster, istio-operator

[kubernetes/minikube]$ minikube profile list
|----------|-----------|---------|---------------|------|---------|--------|
| Profile  | VM Driver | Runtime |      IP       | Port | Version | Status |
|----------|-----------|---------|---------------|------|---------|--------|
| minikube | kvm2      | docker  | 192.168.39.24 | 8443 | v1.19.0 | Paused |
|----------|-----------|---------|---------------|------|---------|--------|

[kubernetes/minikube]$ minikube profile list -o json | jq

{                                                                                                                                                                                                                                                                                             
  "valid": [                                                                                                                                       
    {                                                                                                                                              
      "Name": "minikube",                                                                                                                          
      "Status": "Paused",                                                                                                                          
      "Config": {                                                                                                                                  
        "Name": "minikube",                
...
```

### CODE REVIEW

File: cmd/minikube/cmd/config/profile_list.go [hunk 1]
```diff
@@ -56,98 +58,111 @@ var profileListCmd = &cobra.Command{
...
 	}
+}
 
-	var body = map[string]interface{}{}
+func printProfilesJSON() {
+	validProfiles, invalidProfiles, err := config.ListProfiles()
 
+	updateProfilesStatus(validProfiles)
+
+	var body = map[string]interface{}{}
```
Comment (n0npax) [inline cmd/minikube/cmd/config/profile_list.go:162]: I see `body`  `contains only []*config.Profile`.
is it possible to replace interface here with exact type?

File: cmd/minikube/cmd/config/profile_list.go [hunk 2]
```diff
@@ -56,98 +58,111 @@ var profileListCmd = &cobra.Command{
...
 
+	cr, err := machine.CommandRunner(host)
 	if err != nil {
-		glog.Warningf("error loading profiles: %v", err)
+		return ""
 	}
 
-}
+	hostname, _, port, err := driver.ControlPlaneEndpoint(p.Config, &cp, host.DriverName)
+	if err != nil {
```
Comment (n0npax) [inline cmd/minikube/cmd/config/profile_list.go:106]: I'm not sure if this is the best approach.
In case of error, I'd prefer to log what errored.

maybe even return "unknown" :man_shrugging:

File: cmd/minikube/cmd/config/profile_list.go [hunk 3]
```diff
@@ -56,98 +58,111 @@ var profileListCmd = &cobra.Command{
...
-	table.SetCenterSeparator("|")
+func printProfilesTable() {
 	validProfiles, invalidProfiles, err := config.ListProfiles()
 
-	if len(validProfiles) == 0 || err != nil {
+	if len(validProfiles) == 0 {
 		exit.UsageT("No minikube profile was found. You can create one using `minikube start`.")
 	}
+
+	if err != nil {
```
[the remark this answers is not in the document]
Comment (taciomcosta) [reply cmd/minikube/cmd/config/profile_list.go:64]: Fixed.

File: cmd/minikube/cmd/config/profile_list.go (hunk 2 above)
Comment (taciomcosta) [reply cmd/minikube/cmd/config/profile_list.go:108]: Fixed. 
Logging and returning Unknown now.

File: cmd/minikube/cmd/config/profile_list.go (hunk 1 above)
Comment (taciomcosta) [reply cmd/minikube/cmd/config/profile_list.go:165]: About this one, we are assigning `body["erorr"] = err` a couple of lines after.
That's why I kept it this one.

File: cmd/minikube/cmd/config/profile_list.go (hunk 2 above)
Comment (taciomcosta) [reply cmd/minikube/cmd/config/profile_list.go:108]: Thank you for the comments. Let me know for any improvements! (:

**Review by priyawadhwa — COMMENTED** [review]
Hey @taciomcosta thanks for fixing this! Could you please provide a before and after output in your PR description?

**Comment by medyagh** [comment]
@taciomcosta do you mind adding a before after output in the description ?

**Comment by taciomcosta** [comment]
Done! Sorry for the delay.

**Review by medyagh — APPROVED** [review]
