### PR TITLE
Stop K8s if running, when '--no-kubernetes' flag used

### LINKED ISSUE #12989: Stop kubernetes when start --no-kubernetes is called, if it is already running.
Currently, minikube will continue running kubernetes. When start --no-kubernetes is called, we should stop kubernetes.

**Steps to reproduce the issue:** 

1. minikube start
2. minikube start --no kubernetes

```
$ minikube start --kubernetes-version=v1.22.1
😄  minikube v1.24.0 on Darwin 11.6 (arm64)
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=1988MB) ...
    > kubectl.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubelet.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubectl: 41.44 MiB / 41.44 MiB [-------------] 100.00% 19.69 MiB p/s 2.3s
    > kubeadm: 40.50 MiB / 40.50 MiB [-------------] 100.00% 15.08 MiB p/s 2.9s
    > kubelet: 137.29 MiB / 137.29 MiB [-----------] 100.00% 20.66 MiB p/s 6.8s

    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" 
```

```
$ minikube start --no-kubernetes
😄  minikube v1.24.0 on Darwin 11.6 (arm64)
✨  Using the docker driver based on existing profile
👍  Starting minikube without Kubernetes minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
🏄  Done! minikube is ready without Kubernetes!
╭───────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                       │
│                       💡  Things to try without Kubernetes ...                        │
│                                                                                       │
│    - "minikube ssh" to SSH into minikube's node.                                      │
│    - "minikube docker-env" to point your docker-cli to the docker inside minikube.    │
│    - "minikube image" to build images without docker.                                 │
│                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────╯
```

### PR DESCRIPTION
**Pull request by klaases**
Fixes #12989

If the user starts minikube with Kubernetes, and then later starts minikube with "--no-kubernetes" flag, stop Kubernetes.

Before:

`minikube start`

```
😄  minikube v1.24.0 on Darwin 11.6.1
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=1985MB) ...
🐳  Preparing Kubernetes v1.22.4 on Docker 20.10.8 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

`minikube status`

```
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured
```

`minikube start --no-kubernetes`

```
😄  minikube v1.24.0 on Darwin 11.6.1
✨  Using the docker driver based on existing profile
👍  Starting minikube without Kubernetes minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
🏄  Done! minikube is ready without Kubernetes!
╭───────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                       │
│                       💡  Things to try without Kubernetes ...                        │
│                                                                                       │
│    - "minikube ssh" to SSH into minikube's node.                                      │
│    - "minikube docker-env" to point your docker-cli to the docker inside minikube.    │
│    - "minikube image" to build images without docker.                                 │
│                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────╯
```

`minikube status`

```
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured
```

After:

`minikube start`

```
😄  minikube v1.24.0 on Darwin 11.6.1
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=1985MB) ...
🐳  Preparing Kubernetes v1.22.4 on Docker 20.10.8 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

`minikube status`

```
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured
```

`minikube start --no-kubernetes`

```
😄  minikube v1.24.0 on Darwin 11.6.1
✨  Using the docker driver based on existing profile
👍  Starting minikube without Kubernetes minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
    ▪ Kubernetes: Stopping ...
    ▪ Kubernetes: Stopped
🏄  Done! minikube is ready without Kubernetes!
╭───────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                       │
│                       💡  Things to try without Kubernetes ...                        │
│                                                                                       │
│    - "minikube ssh" to SSH into minikube's node.                                      │
│    - "minikube docker-env" to point your docker-cli to the docker inside minikube.    │
│    - "minikube image" to build images without docker.                                 │
│                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────╯
```

`minikube status`

```
minikube
type: Control Plane
host: Running
kubelet: Stopped
apiserver: Stopped
kubeconfig: Configured
```

### CODE REVIEW

**Review by medyagh — COMMENTED** [review]
lets add before and after this PR in the description for easier PR review

File: pkg/minikube/bootstrapper/kubeadm/kubeadm.go [hunk 1]
```diff
@@ -801,6 +801,30 @@ func (k *Bootstrapper) GenerateToken(cc config.ClusterConfig) (string, error) {
 	return joinCmd, nil
 }
 
+// StopKubernetes stops existing kubernetes.
+func StopKubernetes(stop bool, cr cruntime.Manager, k8s config.KubernetesConfig, runner command.Runner) {
```
Comment (medyagh) [inline pkg/minikube/bootstrapper/kubeadm/kubeadm.go:805]: I suggest we still return the error  and the caller should log the error with klog.Warn that only shows up in verbose logs

Comment (klaases) [reply pkg/minikube/bootstrapper/kubeadm/kubeadm.go]: Hi, I have updated this function. In this case the function does not return a value, and we are retaining the logging of the original error:

`klog.Warningf("stop kubelet: %v", err)`

Have added additional out.Infof to indicate the Kubernetes status a the end of the function as well.

**Review by klaases — COMMENTED** [review]
Have updated description and resolved lint errors, including resolving the cyclomatic complexity.

File: test/integration/no_kubernetes_test.go [hunk 2]
```diff
@@ -82,6 +86,42 @@ func validateStartNoK8sWithVersion(ctx context.Context, t *testing.T, profile st
...
+	if err != nil {
+		t.Fatalf("failed to start minikube with args: %q : %v", rr.Command(), err)
+	}
+
+	if k8sStatus := getK8sStatus(ctx, t, profile); k8sStatus != "Running" {
+		t.Errorf("Kubernetes status, got: %s, want: Running", k8sStatus)
+	}
+}
+
+// validateStartWithStopK8s starts a minikube cluster while stopping Kubernetes.
```
Comment (medyagh) [inline test/integration/no_kubernetes_test.go:104]: Add more comment of all the thing this test does
Since it's used in auto generated docs.
This test also deletes . So comment should say all things it does in the test and maybe rename subtest to include delete in it too

**Review by medyagh — CHANGES_REQUESTED** [review]

**Comment by klaases** [comment]
Refactor of `handleAPIServer()` to reduce cyclomatic complexity of `node.Start()`, in order satisfy lint checking.

**Review by sharifelgamal — APPROVED** [review]
