### PR TITLE
Fix the error output of minikube version --components command

### LINKED ISSUE #12083: `minikube version --components` docker error
```
% minikube version --components
...

docker:
error

...
```
MacOS: 11.5.1
Docker: 20.10.7

### PR DESCRIPTION
**Pull request by afbjorklund**
The daemons might not be running, and it was duplicating some of the information.

Also sort the output and remove some of the line noise (especially crio is _awful_ here)

Fixes #12083

Nothing much we can do, about the total lack of formatting of the --version commands. 😔

----

BEFORE
```
minikube version: v1.22.0
commit: a03fbcf166e6f74ef224d4a63be4277d017bb62e

runc:
runc version 1.0.0-rc95
commit: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
spec: 1.0.2-dev
go: go1.13.15
libseccomp: 2.5.1

containerd:
containerd containerd.io 1.4.6 d71fcd7d8303cbf684402823e425e9dd2e99285d

podman:
Version:      3.2.2
API Version:  3.2.2
Go Version:   go1.15.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64

crictl:
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.20.3
RuntimeApiVersion:  v1alpha1

docker:
error

crio:
Version:       1.20.3
GitCommit:     50065140109e8dc4b8fd6dc5d2b587e5cb7ed79d
GitTreeState:  clean
BuildDate:     2021-06-03T20:25:45Z
GoVersion:     go1.15.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic

buildctl:
buildctl github.com/moby/buildkit v0.8.2 9065b18ba4633c75862befca8188de4338d9f94a

ctr:
error
```

AFTER
```
minikube version: v1.22.0
commit: 6e571d830f76ccc87dd56cf893f50e2e8f8c6306

buildctl:
buildctl github.com/moby/buildkit v0.8.2 9065b18ba4633c75862befca8188de4338d9f94a

containerd:
containerd containerd.io 1.4.6 d71fcd7d8303cbf684402823e425e9dd2e99285d

crictl:
crictl version unknown

crio:
crio version 1.20.3

ctr:
ctr containerd.io 1.4.6

docker:
Docker version 20.10.7, build f0df350

dockerd:
Docker version 20.10.7, build b0f5bc3

podman:
podman version 3.2.2

runc:
runc version 1.0.0-rc95
```

### CODE REVIEW

File: cmd/minikube/cmd/version.go [hunk 1]
```diff
@@ -53,13 +54,14 @@ var versionCmd = &cobra.Command{
...
-				"docker":     exec.Command("docker", "version", "--format={{.Client.Version}}"),
+				"docker":     exec.Command("docker", "--version"),
+				"dockerd":    exec.Command("dockerd", "--version"),
 				"containerd": exec.Command("containerd", "--version"),
-				"crio":       exec.Command("crio", "version"),
-				"podman":     exec.Command("sudo", "podman", "version"),
-				"crictl":     exec.Command("sudo", "crictl", "version"),
+				"crio":       exec.Command("crio", "--version"),
+				"podman":     exec.Command("sudo", "podman", "--version"),
+				"crictl":     exec.Command("sudo", "crictl", "--version"),
```
Comment (spowelljr) [inline cmd/minikube/cmd/version.go:62]: It seems `--version` is not a valid flag for crictl
```
% sudo crictl --version
crictl version unknown

% sudo crictl version
Version:  0.1.0
RuntimeName:  docker
RuntimeVersion:  20.10.7
RuntimeApiVersion:  1.41.0
```

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: cmd/minikube/cmd/version.go (hunk 1 above)
Comment (afbjorklund) [reply cmd/minikube/cmd/version.go:62]: It's a valid flag, just that the old binaries didn't have any version information. The newer binaries work:

```
$ sudo crictl --version
crictl version v1.21.0
```

The `crictl version` cmd doesn't output any information about `crictl`, only about the CRI and the API...

See #10610 for the bug

**Review by spowelljr — APPROVED** [review]

**Comment by afbjorklund** [comment]
Missing `crun`  and `buildkitd`, but those should be simple one-liner afterwards.
