### PR TITLE
Fix `minikube start` in order to be able to  start VM even if machine does not exist

### LINKED ISSUE #5509: vbox: Cannot delete or start minikube if VM is deleted outside of minikube
**The exact command to reproduce the issue**:
```bash
minikube start
😄  minikube v1.4.0 on Darwin 10.14.6
🔥  Creating virtualbox VM (CPUs=2, Memory=6500MB, Disk=20000MB) ...
^C
```
Cancelled the start with `Ctrl+c`

```bash
minikube start
```

Failed:
```bash
😄  minikube v1.4.0 on Darwin 10.14.6
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Retriable failure: Error getting state for host: machine does not exist
```

Try to delete
```bash
minikube delete
```

Failed
```bash
💣  Unable to get the status of the cluster.
```

To fix the problem 
```bash
rm -r ~/.minikube/machines/minikube
```

You can reproduce the issue if you run `minikube start` and then delete the vm in the hypervisor GUI. 

**The output of the `minikube logs` command**:<details>

💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
Mac OS 10.14.6

### PR DESCRIPTION
**Pull request by govargo**
### What type of PR is this?
/kind bug

### What this PR does / why we need it:

When minikube machine does not exist, the Virtual Machine fails starting.
If the host config exists but machine does not exist, we should start recreate VM automatically.
This PR fixes out of control error.

### Which issue(s) this PR fixes:
Fixes #5509

### Does this PR introduce a user-facing change?

Yes. 
This PR fixes bug in order to `minikube start` command work successfully even if machine does not exist.

**Before this PR, `minikube start` command fails, when machine does not exist**
```
1. minikube start (and stop command by Ctrl + C after this)
minikube start
😄  minikube v1.4.0 on Darwin 10.14.6
🔥  Creating virtualbox VM (CPUs=2, Memory=6500MB, Disk=20000MB) ...
^C

# Restart Minikube
2. minikube start
😄  minikube v1.4.0 on Darwin 10.14.6
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Retriable failure: Error getting state for host: machine does not exist
```

**After this PR, `minikube start` command success, even if machine does not exist**
```
1. minikube start (and stop command by Ctrl + C after this)
$ out/minikube start
😄  minikube v1.5.0-beta.0 on Darwin 10.14.6
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
^C

# Restart Minikube
2. out/minikube start
😄  minikube v1.5.0-beta.0 on Darwin 10.14.5
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🙄  "machine minikube" does not exist. Proceeding ahead with recreating VM.
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
```

### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```
NONE
```

### CODE REVIEW

File: pkg/minikube/cluster/cluster.go [hunk 1]
```diff
@@ -112,6 +113,17 @@ func StartHost(api libmachine.API, config cfg.MachineConfig) (*host.Host, error)
 	s, err := h.Driver.GetState()
 	glog.Infoln("Machine state: ", s)
 	if err != nil {
+		if driver.BareMetal(config.VMDriver) || config.VMDriver == driver.VirtualBox {
```
Comment (medyagh) [inline pkg/minikube/cluster/cluster.go]: Lets add a comment before the if statement, stating an example when this happens ( ctrl+c...)

**Comment by medyagh** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
that is a good improvement ! I was always annoyed by ctrl+c destroying things. thank you for working on this

File: pkg/minikube/cluster/cluster.go (hunk 1 above)
Comment (govargo) [reply pkg/minikube/cluster/cluster.go]: Thank you for your review!
With the comment, It's easier to understand for developer as you mentioned.
I added comment about the situation.

File: pkg/minikube/cluster/cluster.go [hunk 2]
```diff
@@ -112,6 +113,18 @@ func StartHost(api libmachine.API, config cfg.MachineConfig) (*host.Host, error)
 	s, err := h.Driver.GetState()
 	glog.Infoln("Machine state: ", s)
 	if err != nil {
+		// If VirtualBox Machine does not exist due to user interrupt cancel(i.e. Ctrl + C), recreate VirtualBox Machine
+		if driver.BareMetal(config.VMDriver) || config.VMDriver == driver.VirtualBox {
```
Comment (medyagh) [inline pkg/minikube/cluster/cluster.go]: could you please remind me why we need this check for none driver ?
``` driver.BareMetal(config.VMDriver)``` ?

**Comment by medyagh** [comment]
the tests failures are not related to this PR

**Comment by medyagh** [comment]
@govargo sorry for the delay in the PR review, I left one comment.

File: pkg/minikube/cluster/cluster.go (hunk 2 above)
Comment (govargo) [reply pkg/minikube/cluster/cluster.go]: Thanks for your point out.
I thought that Mock driver judgement is needed and `driver.BareMetal` is its method.
But I misunderstood.

I modified this `driver.BareMetal` → `config.VMDriver == driver.Mock`.

**Comment by govargo** [comment]
@medyagh

Thanks for your review.

I merged v1.5.2 codebase into this branch.
And I noticed that v1.5.2 contains many changes in the codebase.

In v1.5.2, func startMachine has `preExists` flag.
If `preExists` flag is true, the bootstrapper skips pulling necessary images and minikube fails to starting.

https://github.com/kubernetes/minikube/blob/a583cbec1311b6ad8af847ea1668fb4d105e493b/cmd/minikube/cmd/start.go#L337

https://github.com/kubernetes/minikube/blob/a583cbec1311b6ad8af847ea1668fb4d105e493b/cmd/minikube/cmd/start.go#L1181-L1186

I changed the following code to avoid skipping pulling necessary images.

https://github.com/kubernetes/minikube/pull/5730/files#diff-221fdad1b39f75fb2d0214c25944dcb3R116-R134

https://github.com/kubernetes/minikube/pull/5730/files#diff-ed78cd81495af3964aba5fbc898c33a2R984-R991

**Comment by govargo** [comment]
Updated code to resolve conflict(latest codebase edited the same file)

**Comment by govargo** [comment]
Umm.. ↑ Is there anything I can do?

> Updating 1d0ca6c..e611b38

It looks master commit range...

**Comment by govargo** [comment]
I rebased for latest codebase.

File: pkg/minikube/cluster/cluster_test.go [hunk 3]
```diff
@@ -147,6 +149,48 @@ func TestStartHostExists(t *testing.T) {
 	}
 }
 
+func TestStartHostErrMachineNotExist(t *testing.T) {
+	RegisterMockDriver(t)
+	api := tests.NewMockAPI(t)
+	// Create an incomplete host with machine does not exist error(i.e. User Interrupt Cancel)
+	api.NotExistError = true
+	ih, err := createHost(api, defaultMachineConfig)
+	if err != nil {
```
Comment (medyagh) [inline pkg/minikube/cluster/cluster_test.go]: hoe about return a error type like ErrMachineNotFound and compare to that error type, instead checkig if there its not nil ?

File: pkg/minikube/tests/driver_mock.go [hunk 4]
```diff
@@ -91,6 +97,10 @@ func (d *MockDriver) GetSSHKeyPath() string {
 // GetState returns the state of the driver
 func (d *MockDriver) GetState() (state.State, error) {
 	d.Logf("MockDriver.GetState: %v", d.CurrentState)
+	if d.NotExistError {
+		d.CurrentState = state.Error
+		return d.CurrentState, errors.New("machine does not exist")
```
Comment (medyagh) [inline pkg/minikube/tests/driver_mock.go]: return error type instead of string.

File: pkg/minikube/cluster/cluster_test.go [hunk 5]
```diff
@@ -147,6 +149,48 @@ func TestStartHostExists(t *testing.T) {
...
+	}
+
+	md := &tests.MockDetector{Provisioner: &tests.MockProvisioner{}}
+	provision.SetDetector(md)
+
+	mc := defaultMachineConfig
+	mc.Name = ih.Name
+
+	// This should pass with creating host, while machine does not exist.
+	ih, err = StartHost(api, mc)
```
Comment (medyagh) [inline pkg/minikube/cluster/cluster_test.go]: how about StartHost returns its own ErrorMachineNotFound so we dont depend on virtualbox and it is extensible for other drivers?

File: pkg/minikube/cluster/cluster.go [hunk 6]
```diff
@@ -113,6 +114,25 @@ func StartHost(api libmachine.API, config cfg.MachineConfig) (*host.Host, error)
 	s, err := h.Driver.GetState()
```
Comment (medyagh) [inline pkg/minikube/cluster/cluster.go]: we could make our own ErrorType for not found and then make all drivers return that so we can use it as a generic machine not found across all drivers

**Comment by govargo** [comment]
@medyagh 
Thank you for the review.
As you mentioned, the ErrorType will be better for all drivers.
I'll check it and work on later.

**Comment by govargo** [comment]
> we could make our own ErrorType for not found and then make all drivers return that so we can use it as a generic machine not found across all drivers

I investigated that where the drivers(& registries) return machine status.
And I found it returned in disjointed places(e.g. [docker/machine](https://github.com/docker/machine), [minikube repository](https://github.com/kubernetes/minikube/tree/master/pkg/minikube/registry/drvs)).

I think that I will make check function which check MachineDoesNotExist in somewhere file.
And I will make ErrorType there.

In the check function, it will absorb the difference of all drivers error(hyperkit, kvm2, hyperv...).

I think I have to check the all driver's MachineDoesNotExist Error case.
So, it takes more time to check and test...
I'm sorry to keep you waiting. Please wait🙂

File: pkg/minikube/cluster/cluster_test.go (hunk 3 above)
Comment (govargo) [reply pkg/minikube/cluster/cluster_test.go]: Added new error ErrorMachineNotExist.

File: pkg/minikube/tests/driver_mock.go (hunk 4 above)
Comment (govargo) [reply pkg/minikube/tests/driver_mock.go]: I added new error ErrorMachineNotExist but I didn't use it here.
I avoid import cycle because package `cluster` & `tests` depend on each other.
I added that comment.

FYI) `cluster` → `tests` → `cluster`

File: pkg/minikube/cluster/cluster_test.go (hunk 5 above)
Comment (govargo) [reply pkg/minikube/cluster/cluster_test.go]: I added new function `isMachineExists`.
This func checks all driver's MachineDoesNotError.

File: pkg/minikube/cluster/cluster.go (hunk 6 above)
Comment (govargo) [reply pkg/minikube/cluster/cluster.go]: I added new function isMachineExists.
This func checks all driver's ErrorMachineNotExist.

**Comment by govargo** [comment]
@medyagh 
I updated following 2 point.
・Add new Error ErrMachineNotExist
・Check the all driver's error case - func `isMachineExists `

I use `ErrMachineNotExist` instead of `ErrMachineNotFound` because virtualbox & parallels use this ErrMachineNotExist.
I thought that the err name should be unified.
However, if you have different thought, I would like to hear that(any other review too).

File: pkg/minikube/cluster/cluster.go [hunk 7]
```diff
@@ -646,3 +671,57 @@ func IsMinikubeRunning(api libmachine.API) bool {
 	}
 	return true
 }
+
+// isMachineExists checks if virtual machine does not exist
+// if the virtual machine exists, return true
+func isMachineExists(vmDriver string, s state.State, err error) (bool, error) {
```
Comment (medyagh) [inline pkg/minikube/cluster/cluster.go]: english nit: change this to, MachineExists , or DoesMachineExists. (shorter better)

File: pkg/minikube/cluster/cluster.go [hunk 8]
```diff
@@ -646,3 +671,57 @@ func IsMinikubeRunning(api libmachine.API) bool {
...
+		if s == state.None || s == state.Stopped {
+			return false, ErrorMachineNotExist
+		}
+		return true, err
+	case driver.VMwareFusion:
+		if s == state.Stopped {
+			return false, ErrorMachineNotExist
+		}
+		return true, err
+	case driver.Mock:
```
Comment (medyagh) [inline pkg/minikube/cluster/cluster.go]: add a case dor kic driver (Docker)

File: pkg/minikube/cluster/cluster.go (hunk 7 above)
Comment (govargo) [reply pkg/minikube/cluster/cluster.go]: renamed to machineExists func

File: pkg/minikube/cluster/cluster.go (hunk 8 above)
Comment (govargo) [reply pkg/minikube/cluster/cluster.go]: Added kic(docker) case

**Comment by tstromberg** [comment]
Do you mind fixing the merge conflict? Otherwise this PR appears to be ready to merge.

File: pkg/minikube/cluster/cluster.go (hunk 8 above)
Comment (govargo) [reply pkg/minikube/cluster/cluster.go]: Added other case for kic.
I noticed kic return other behavior depending on whether the kic image is pulled or not.

https://github.com/kubernetes/minikube/pull/5730/files#diff-68ced156bfe1892e288da479d66535f2R244

**Comment by govargo** [comment]
@tstromberg
I fixed merge conflict!
I adjusted to #6484.

**Comment by medyagh** [comment]
the integreation test failures are all time out waiting for a pod doesnt seem to be related to this PR
/

**Comment by medyagh** [comment]
@govargo thank you very much for this PR ! and your persistence  to fix all the code review comments.
