### PR TITLE
pkg/proxy: walk RoundTripper wrappers to strip proxy on inner *http.Transport

### LINKED ISSUE #22896: TestErrorSpam/setup fails on every PR after k8s-dependencies bump (proxy.go RoundTripper cast)
### What Happened?

`TestErrorSpam/setup` is failing on every PR's prow integration tests since the k8s-dependencies bump in [#22876](https://github.com/kubernetes/minikube/pull/22876) (commit `f711fb429`) merged on 2026-04-24. The failure is reproducible on at minimum docker, containerd, kvm and crio runtimes across both x86 and arm.

The test asserts that `minikube start` produces no unexpected stderr. After the dep bump, every `minikube start` now emits:

```
E0425 20:01:48.250329   63697 proxy.go:152] Error while casting RoundTripper (of type *transport.trackedTransport) to *http.Transport : false
E0425 20:01:48.368989   63697 proxy.go:152] Error while casting RoundTripper (of type *transport.trackedTransport) to *http.Transport : false
E0425 20:01:48.369055   63697 proxy.go:152] Error while casting RoundTripper (of type *transport.trackedTransport) to *http.Transport : false
```

`TestErrorSpam` flags the lines as unexpected stderr and fails:

```
--- FAIL: TestErrorSpam/setup (14.80s)
    error_spam_test.go:100: unexpected stderr: "E0425 20:01:48.250329   63697 proxy.go:152] Error while casting RoundTripper (of type *transport.trackedTransport) to *http.Transport : false"
    ...
```

### Attach the log file

Any PR opened against current `master` reproduces. Verified across at least:

- #22862 (this is what surfaced the regression): https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/minikube/22862/pull-minikube-docker-docker-linux-x86/2048128180010618880
- #22895 (an unrelated kubevirt addon bump, only TestErrorSpam/setup fails): https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/minikube/22895/pull-minikube-docker-containerd-linux-x86/2047970412591058944

The failure is the sole `Fail` in test_summary.json on most lanes, with `Pass` numbers in the high 300s, so the rest of the integration suite is healthy. Master itself almost certainly fails the same way; this is blocking PR merges across the repo.

### Operating System

None

### Driver

None

### PR DESCRIPTION
**Pull request by abedegno**
## Summary

After [#22876](https://github.com/kubernetes/minikube/pull/22876) bumped `k8s.io/client-go` from 0.35.1 to 0.36.0, [`kubernetes/client-go@f5fc1e5f`](https://github.com/kubernetes/client-go/commit/f5fc1e5f67e9f487e6e1b96384c16788e1a9db9a) wraps the cached HTTP transport in `*trackedTransport` to anchor garbage collection of the TLS transport cache. `proxy.UpdateTransport` was downcasting directly to `*http.Transport`; that assertion now fails on every minikube start, logging three `Errorf` lines and tripping `TestErrorSpam/setup` on every PR against current master.

This PR walks `RoundTripperWrapper` layers via `WrappedRoundTripper()` until the underlying `*http.Transport` is reached, then nils `Proxy` in place. The outer wrapper is returned unchanged so client-go's TLS cache GC anchoring continues to work.

## Changes

- Extracts the proxy-disable logic into `disableProxyOnTransport` so it can be unit-tested without `UpdateTransport`'s closure scaffolding.
- `UpdateTransport`'s `WrapTransport` closure delegates to the new helper; behavior is unchanged on the no-wrapping path that worked before client-go 0.36.
- Adds `TestUpdateTransport/wrapped`, the regression test (wraps `*http.Transport` in a fake `RoundTripperWrapper`, asserts inner `Proxy` is nilled).
- Adds `TestUpdateTransport/proxy-stripping`, pinning the no-wrap branch so it does not silently regress in future refactors.

## Test plan

- [x] `go test ./pkg/minikube/proxy/...` passes locally
- [x] `go build ./...` clean
- [x] `gocyclo` clean on `pkg/minikube/proxy/proxy.go`
- [x] End-to-end: `minikube start` produces zero `Error while casting RoundTripper` lines on stderr (was three per start)
- [ ] CI green

## Related

Fixes #22896. #22901 reports the same `TestErrorSpam/setup` symptom; both should resolve once this lands.

### CODE REVIEW

File: pkg/minikube/proxy/proxy.go [hunk 1]
```diff
@@ -145,17 +146,38 @@ func UpdateTransport(cfg *rest.Config) *rest.Config {
...
+// returned value is rt itself; mutation happens in place on the inner
+// transport, and the wrapper holds the inner by reference so the change
+// is visible through it. Returning the outer wrapper preserves whatever
+// reference the caller intends to hold (notably, client-go 0.36 anchors
+// its TLS transport cache on a *trackedTransport wrapper). If the chain
+// does not bottom out at a *http.Transport the proxy is not disabled and
+// the failure is logged at Errorf so any future client-go change that
+// re-breaks this surface is loudly visible rather than silently disabling
+// proxy stripping for users behind corporate proxies.
+func disableProxyOnTransport(rt http.RoundTripper) http.RoundTripper {
```
Comment (medyagh) [inline pkg/minikube/proxy/proxy.go]: consider adding the link to the Github issue and also a more simplified comment on what does this func do (maybe add a summery ? )

**Review by medyagh — COMMENTED** [review]
thank you @abedegno please see comment and also copilot's comment

File: pkg/minikube/proxy/proxy.go (hunk 1 above)
Comment (abedegno) [reply pkg/minikube/proxy/proxy.go]: @medyagh - done.

File: pkg/minikube/proxy/proxy.go [hunk 2]
```diff
@@ -145,17 +146,38 @@ func UpdateTransport(cfg *rest.Config) *rest.Config {
...
+	for {
+		switch t := cur.(type) {
+		case *http.Transport:
+			t.Proxy = nil
+			return rt
+		case utilnet.RoundTripperWrapper:
+			cur = t.WrappedRoundTripper()
+		default:
+			klog.Errorf("transport %T could not be unwrapped to *http.Transport; proxy stripping was skipped", cur)
+			return rt
```
[the remark this answers is not in the document]
Comment (abedegno) [reply pkg/minikube/proxy/proxy.go]: Added an early `if rt == nil { return rt }` at the top of `disableProxyOnTransport`. `TestUpdateTransport/nil` now runs silently (it was previously logging the spurious Errorf even though the test passed).

File: pkg/minikube/proxy/proxy_test.go [hunk 3]
```diff
@@ -188,6 +188,18 @@ func TestExcludeIP(t *testing.T) {
...
+// future wrapping layer) interposes between WrapTransport callers and the
+// underlying *http.Transport.
+type fakeRoundTripperWrapper struct{ rt http.RoundTripper }
+
+func (f *fakeRoundTripperWrapper) RoundTrip(req *http.Request) (*http.Response, error) {
+	return f.rt.RoundTrip(req)
+}
+
+func (f *fakeRoundTripperWrapper) WrappedRoundTripper() http.RoundTripper { return f.rt }
+
```
Comment (nirs) [inline pkg/minikube/proxy/proxy_test.go:203]: Faking this means that when the real client will change, the test will continue to pass while the real code will break. We need an integration test using a real client and detecting changes in the client.

File: pkg/minikube/proxy/proxy.go [hunk 4]
```diff
@@ -145,17 +146,35 @@ func UpdateTransport(cfg *rest.Config) *rest.Config {
...
 	}
 	return cfg
 }
 
+// disableProxyOnTransport finds the *http.Transport at the bottom of any
+// RoundTripperWrapper chain wrapping rt and sets its Proxy to nil. The
+// outer rt is returned unchanged (mutation happens in place on the inner
+// transport). A nil rt is a no-op. See
+// https://github.com/kubernetes/minikube/issues/22896 for context.
+func disableProxyOnTransport(rt http.RoundTripper) http.RoundTripper {
```
Comment (nirs) [inline pkg/minikube/proxy/proxy.go]: returning rt from disableProxyOnTransport(rt) looks strange. Why this need to return anything?

File: pkg/minikube/proxy/proxy.go [hunk 5]
```diff
@@ -145,17 +146,35 @@ func UpdateTransport(cfg *rest.Config) *rest.Config {
...
+	for {
+		switch t := cur.(type) {
+		case *http.Transport:
+			t.Proxy = nil
+			return rt
+		case utilnet.RoundTripperWrapper:
+			cur = t.WrappedRoundTripper()
+		default:
+			klog.Errorf("transport %T could not be unwrapped to *http.Transport; proxy stripping was skipped", cur)
+			return rt
```
Comment (nirs) [inline pkg/minikube/proxy/proxy.go]: Did consider simplifying the function to return the *http.Transport, replacing the type assertion in line 148?

```go
t := wrappedHTTPTransport(rt)
t.Proxy = nil
```

**Comment by medyagh** [comment]
@abedegno thank you for fixing it ! I tink this also fixed the StartWithProxy test https://github.com/kubernetes/minikube/issues/22900

File: pkg/minikube/proxy/proxy.go (hunk 1 above)
Comment (medyagh) [reply pkg/minikube/proxy/proxy.go]: @abedegno plz also check nir's comments and see if they are valid

File: pkg/minikube/proxy/proxy_test.go (hunk 3 above)
Comment (abedegno) [reply pkg/minikube/proxy/proxy_test.go:203]: I think the integration coverage you're describing already exists - it's `TestErrorSpam/setup`, the test that surfaced this regression in the first place?

**Comment by medyagh** [comment]
thank you @abedegno this actually fixes the failure on startwithproxy test too
https://github.com/kubernetes/minikube/issues/22900

**Comment by medyagh** [comment]
@abedegno btw if you have slack feel free to join our minikube channel on slack 
https://kubernetes.slack.com/archives/C1F5CT6Q1/p1777572942023289
