### PR TITLE
none-driver: check cri-dockerd & dockerd runtimes

### LINKED ISSUE #14410: unable to start minikube with docker without cri-dockerd
### What Happened?

I have installed minikube on aws ec2 instance followed all the steps.
Please find the logs attached for your reference 

### Attach the log file

root@ip-172-31-47-92:~# cat logs.txt
*
* ==> Audit <==
* |---------|-------------------------|----------|------|---------|---------------------|---------------------|
| Command |          Args           | Profile  | User | Version |     Start Time      |      End Time       |
|---------|-------------------------|----------|------|---------|---------------------|---------------------|
| start   | --vm-driver=none        | minikube | root | v1.26.0 | 24 Jun 22 03:57 UTC |                     |
| delete  |                         | minikube | root | v1.26.0 | 24 Jun 22 04:00 UTC | 24 Jun 22 04:00 UTC |
| start   | --driver=docker         | minikube | root | v1.26.0 | 24 Jun 22 04:00 UTC |                     |
| delete  |                         | minikube | root | v1.26.0 | 24 Jun 22 04:00 UTC | 24 Jun 22 04:00 UTC |
| start   |                         | minikube | root | v1.26.0 | 24 Jun 22 04:00 UTC |                     |
| start   | --force --driver=docker | minikube | root | v1.26.0 | 24 Jun 22 04:01 UTC |                     |
| start   | --driver=none           | minikube | root | v1.26.0 | 24 Jun 22 04:01 UTC |                     |
| start   |                         | minikube | root | v1.26.0 | 24 Jun 22 04:02 UTC |                     |
|---------|-------------------------|----------|------|---------|---------------------|---------------------|

*
* ==> Last Start <==
* Log file created at: 2022/06/24 04:02:49
Running on machine: ip-172-31-47-92
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0624 04:02:49.109566    6897 out.go:296] Setting OutFile to fd 1 ...
I0624 04:02:49.109700    6897 out.go:348] isatty.IsTerminal(1) = true
I0624 04:02:49.109705    6897 out.go:309] Setting ErrFile to fd 2...
I0624 04:02:49.109712    6897 out.go:348] isatty.IsTerminal(2) = true
I0624 04:02:49.109921    6897 root.go:329] Updating PATH: /root/.minikube/bin
W0624 04:02:49.110036    6897 root.go:307] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0624 04:02:49.110148    6897 out.go:303] Setting JSON to false
I0624 04:02:49.110933    6897 start.go:115] hostinfo: {"hostname":"ip-172-31-47-92","uptime":493,"bootTime":1656042876,"procs":122,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"5.4.0-1078-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec29327a-c75c-82bd-d5d2-09198152d1c4"}
I0624 04:02:49.110994    6897 start.go:125] virtualization: xen guest
I0624 04:02:49.113713    6897 out.go:177] 😄  minikube v1.26.0 on Ubuntu 18.04 (xen/amd64)
W0624 04:02:49.116051    6897 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0624 04:02:49.116256    6897 notify.go:193] Checking for updates...
I0624 04:02:49.116293    6897 config.go:178] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.1
I0624 04:02:49.116332    6897 driver.go:360] Setting default libvirt URI to qemu:///system
I0624 04:02:49.116647    6897 exec_runner.go:51] Run: systemctl --version
I0624 04:02:49.122833    6897 out.go:177] ✨  Using the none driver based on existing profile
I0624 04:02:49.125045    6897 start.go:284] selected driver: none
I0624 04:02:49.125059    6897 start.go:805] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.47.92 Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0624 04:02:49.125144    6897 start.go:816] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0624 04:02:49.125166    6897 start.go:1541] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0624 04:02:49.125609    6897 cni.go:95] Creating CNI manager for ""
I0624 04:02:49.125617    6897 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0624 04:02:49.125632    6897 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.47.92 Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0624 04:02:49.131832    6897 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I0624 04:02:49.134339    6897 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0624 04:02:49.134543    6897 cache.go:208] Successfully downloaded all kic artifacts
I0624 04:02:49.134579    6897 start.go:352] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0624 04:02:49.134751    6897 start.go:356] acquired machines lock for "minikube" in 146.017µs
I0624 04:02:49.134771    6897 start.go:94] Skipping create...Using existing machine configuration
I0624 04:02:49.134778    6897 fix.go:55] fixHost starting: m01
W0624 04:02:49.134971    6897 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0624 04:02:49.134981    6897 api_server.go:165] Checking apiserver status ...
I0624 04:02:49.135007    6897 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0624 04:02:49.147114    6897 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0624 04:02:49.147151    6897 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0624 04:02:49.156870    6897 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0624 04:02:49.156885    6897 fix.go:129] unexpected machine state, will restart: <nil>
I0624 04:02:49.159426    6897 out.go:177] 🔄  Restarting existing none bare metal machine for "minikube" ...
I0624 04:02:49.162619    6897 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0624 04:02:49.162753    6897 start.go:306] post-start starting for "minikube" (driver="none")
I0624 04:02:49.162762    6897 start.go:316] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0624 04:02:49.162803    6897 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0624 04:02:49.169850    6897 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0624 04:02:49.169872    6897 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0624 04:02:49.169883    6897 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0624 04:02:49.175670    6897 out.go:177] ℹ️  OS release is Ubuntu 18.04.6 LTS
I0624 04:02:49.180296    6897 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0624 04:02:49.180353    6897 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0624 04:02:49.180373    6897 start.go:309] post-start completed in 17.610894ms
I0624 04:02:49.180382    6897 fix.go:57] fixHost completed within 45.605194ms
I0624 04:02:49.180388    6897 start.go:81] releasing machines lock for "minikube", held for 45.62773ms
I0624 04:02:49.180936    6897 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0624 04:02:49.181000    6897 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0624 04:02:49.202779    6897 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0624 04:02:49.367152    6897 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0624 04:02:49.510093    6897 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0624 04:02:49.686716    6897 exec_runner.go:51] Run: sudo systemctl restart docker
I0624 04:02:49.964699    6897 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0624 04:02:49.977302    6897 out.go:177]
W0624 04:02:49.980229    6897 out.go:239] ❌  Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

W0624 04:02:49.980260    6897 out.go:239]
W0624 04:02:49.984043    6897 out.go:239] ╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
I0624 04:02:49.986533    6897 out.go:177]

### Operating System

Other

### Driver

_No response_

### PR DESCRIPTION
**Pull request by klaases**
Fixes #14410, #14460

Check for `cri-dockerd` and `dockerd` in addition to `docker`, to help the user tell whether they have all the requirements to run the docker container runtime.

Checks for both `cri-dockerd` and `dockerd` only apply if the Kubernetes version is greater than or equal to v1.24.

---

Run minikube with `none` driver:
`sudo -E ./out/minikube start --driver=none`

---

If CONNTRACK is missing, install with: `sudo apt-get install -y conntrack`
```
❌  Exiting due to GUEST_MISSING_CONNTRACK: Sorry, Kubernetes 1.24.2 requires conntrack to be installed in root's path
```
---

**Before**: Linux system without `cri-dockerd` installed with k8s >= v.1.24.

```
$ sudo -E ./out/minikube start --driver=none
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
✨  Using the none driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=48, Memory=181315MB, Disk=142997MB) ...
ℹ️  OS release is Debian GNU/Linux rodete

❌  Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
time="2022-07-15T18:33:39Z" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""


╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
```
---
**After**: Linux system without `cri-dockerd` installed with k8s >= v.1.24.

```
$ sudo -E ./out/minikube start --driver=none
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...

🐳  Exiting due to NOT_FOUND_CRI_DOCKERD:

💡  Suggestion: 

    The none driver with Kubernetes v1.24+ and the docker container-runtime requires cri-dockerd.
    
    Please install cri-dockerd using these instructions:
    
    https://github.com/Mirantis/cri-dockerd#build-and-install
```

---
Next, install `cri-dockerd`, ([installation guide](https://github.com/Mirantis/cri-dockerd#build-and-install)).

Note: if you encounter the error `crictl` not found:

```
$ sudo -E ./out/minikube start --driver=none
[sudo] password for klaases: 
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Debian GNU/Linux rodete

❌  Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
...

```
By default, `crictl` will work from `/usr/local/bin/`, however minikube requires `crictl` to be in `/usr/bin/` ([more information](https://github.com/kubernetes/minikube/issues/5547#issuecomment-556984525)).

Manually fix `sudo crictl` by running the following command:
`sudo cp /usr/local/bin/crictl /usr/bin/crictl`

---

**After**: Linux system with `cri-dockerd` installed with Kubernetes >= 1.24.

```
sudo -E ./out/minikube start --driver=none
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running none "minikube" bare metal machine ...
ℹ️  OS release is Debian GNU/Linux rodete
🐳  Preparing Kubernetes v1.24.2 on Docker 20.10.2 ...
🤹  Configuring local host environment ...

❗  The 'none' driver is designed for experts who need to integrate with an existing VM
💡  Most users should use the newer 'docker' driver instead, which does not require root!
📘  For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

❗  kubectl and minikube configuration will be stored in /root
❗  To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:

    ▪ sudo mv /root/.kube /root/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

---
**After**: Linux system without `cri-dockerd` installed and with older version of Kubernetes less than 1.24.

---

1. Uninstall `cri-dockerd`, or make unavailable with:`sudo mv cri-dockerd cri-dockerd1`
2. Downgrade Kubernetes (this did not work, need to instead use a minikube flag like `--kubernetes-version=v1.23.0`):

   - `curl -LO https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl`
   - `sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl`
   - `kubectl version --client`
   - `Client Version: version.Info{Major:"1", Minor:"23" ...`

Note: that a profile cannot be used with the `none` driver.
```
❌  Exiting due to DRV_UNSUPPORTED_PROFILE: The 'none driver does not support multiple profiles: https://minikube.sigs.k8s.io/docs/reference/drivers/none/
```

Note: downgrading with `--kubernetes-version=v1.23.0` also did not work.
```
sudo -E ./out/minikube start --driver=none --kubernetes-version=v1.23.0
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)

🙈  Exiting due to K8S_DOWNGRADE_UNSUPPORTED: Unable to safely downgrade existing Kubernetes v1.24.2 cluster to v1.23.0
💡  Suggestion: 

    1) Recreate the cluster with Kubernetes 1.23.0, by running:
    
    minikube delete
    minikube start --kubernetes-version=v1.23.0
    
    2) Create a second cluster with Kubernetes 1.23.0, by running:
    
    minikube start -p minikube2 --kubernetes-version=v1.23.0
    
    3) Use the existing cluster at version Kubernetes 1.24.2, by running:
    
    minikube start --kubernetes-version=v1.24.2
```

Running `minikube delete` and `minikube start --kubernetes-version=v1.23.0` work, however even after running minikube with v.1.23, `sudo -E ./out/minikube start --driver=none --kubernetes-version=v1.23.0` produces the above error.

The solution was to **completely restart the Linux system**.

Subsequent tests with and without `--force` and both worked as expected.

```
$ sudo -E ./out/minikube start --driver=none --kubernetes-version=v1.23.0 --force
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
❗  minikube skips various validations when --force is supplied; this may lead to unexpected behavior
✨  Using the none driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=48, Memory=181315MB, Disk=142997MB) ...
ℹ️  OS release is Debian GNU/Linux rodete
🐳  Preparing Kubernetes v1.23.0 on Docker 20.10.2 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🤹  Configuring local host environment ...

❗  The 'none' driver is designed for experts who need to integrate with an existing VM
💡  Most users should use the newer 'docker' driver instead, which does not require root!
📘  For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

❗  kubectl and minikube configuration will be stored in /root
❗  To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:

    ▪ sudo mv /root/.kube /root/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

### CODE REVIEW

File: pkg/minikube/cruntime/docker.go [hunk 1]
```diff
@@ -106,8 +106,17 @@ func (r *Docker) SocketPath() string {
 
 // Available returns an error if it is not possible to use this runtime on a host
 func (r *Docker) Available() error {
-	_, err := exec.LookPath("docker")
-	return err
+	var err error
+	if _, err = exec.LookPath("docker"); err == nil {
```
Comment (spowelljr) [inline pkg/minikube/cruntime/docker.go:110]: Won't this return if `docker` is found? But this doesn't guarentee that `cri-docker` is installed.

**Review by spowelljr — CHANGES_REQUESTED** [review]

**Review by medyagh — CHANGES_REQUESTED** [review]
can you please put Before/After this PR in the description ?

with one linux system without cri-dockerd installed and another with that installed

also please put output of a none driver with older k8s verison (without cir-dockerd) and it should not exit or warn user

File: pkg/minikube/cruntime/docker.go (hunk 1 above)
Comment (klaases) [reply pkg/minikube/cruntime/docker.go]: Thanks, updated to return an error if docker is not found, then check for either `cri-dockerd` or `dockerd`.

File: pkg/minikube/cruntime/docker.go [hunk 2]
```diff
@@ -106,8 +106,17 @@ func (r *Docker) SocketPath() string {
...
-	_, err := exec.LookPath("docker")
-	return err
+	var err error
+	if _, err = exec.LookPath("docker"); err != nil {
+		return err
+	}
+	if _, err = exec.LookPath("cri-dockerd"); err == nil {
+		return nil
+	}
+	if _, err = exec.LookPath("dockerd"); err == nil {
```
Comment (spowelljr) [inline pkg/minikube/cruntime/docker.go:116]: It looks like that if `docker` and `cri-dockerd` are installed the check for `dockerd` doesn't occur, but we need to make sure all three of them are there.

File: pkg/minikube/cruntime/docker.go [hunk 3]
```diff
@@ -106,8 +106,17 @@ func (r *Docker) SocketPath() string {
 
 // Available returns an error if it is not possible to use this runtime on a host
 func (r *Docker) Available() error {
-	_, err := exec.LookPath("docker")
-	return err
+	var err error
+	if _, err = exec.LookPath("docker"); err != nil {
+		return err
+	}
+	if _, err = exec.LookPath("cri-dockerd"); err == nil {
```
Comment (spowelljr) [inline pkg/minikube/cruntime/docker.go:113]: Also, `cri-dockerd` and `dockerd` only need to be checked if they're using Kubernetes v1.24+, right now it's checking for past Kubernetes versions which don't require them.

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: pkg/minikube/cruntime/docker.go (hunk 2 above)
Comment (klaases) [reply pkg/minikube/cruntime/docker.go]: Thanks for taking a look, now ensuring that all three are there.

File: pkg/minikube/cruntime/docker.go (hunk 3 above)
Comment (klaases) [reply pkg/minikube/cruntime/docker.go]: Yes, now checking for greater than or equal to k8s v1.24 per https://github.com/kubernetes/minikube/issues/14460#issuecomment-1169575735

**Comment by klaases** [comment]
> can you please put Before/After this PR in the description ?
> 
> with one linux system without cri-dockerd installed and another with that installed
> 
> also please put output of a none driver with older k8s verison (without cir-dockerd) and it should not exit or warn user

What is the best way to downgrade k8s version for minikube?

I tried installing an older version as well as passing `--kubernetes-version=v1.23.0`, but these did not work with `--driver=none`.

**Comment by klaases** [comment]
After restarting Linux, minikube was able to start with Kubernetes less than v.1.24, and without `cri-dockerd` being available.

/ok-to-test

**Comment by klaases** [comment]
Updated before section with the following:



**Before**: Linux system without `cri-dockerd` installed with k8s >= v.1.24.

```
$ sudo -E ./out/minikube start --driver=none
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
✨  Using the none driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=48, Memory=181315MB, Disk=142997MB) ...
ℹ️  OS release is Debian GNU/Linux rodete

❌  Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
time="2022-07-15T18:33:39Z" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""


╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
```

Before the error was:

```
❌  Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:
```

After the error is:

```
❌  Exiting due to RT_DOCKER_MISSING_CRI_DOCKER_NONE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:
```


This should make it easier to tell that CRI-DOCKER needs to be installed.

**Comment by klaases** [comment]
Thanks @spowelljr for indicating that`cri-dockerd` was still running and helping me to remove it by providing the following commands:

```
sudo rm /var/run/cri-dockerd.sock
sudo rm /etc/systemd/system/cri-docker.service
sudo rm /etc/systemd/system/cri-docker.socket
sudo systemctl daemon-reload
```

```
sudo -E ./out/minikube delete
sudo -E ./out/minikube start --driver none
```

However now the **before** code returns the following error:

```
❌  Exiting due to RT_DOCKER_MISSING_CRI_DOCKER_NONE: sudo systemctl enable cri-docker.socket: exit status 1
```

TODO: confirm whether the Available() is actually being called.

**Comment by medyagh** [comment]
please ensure the PR description is correct, 
```
Checks for both cri-dockerd and dockerd only apply if the Kubernetes version is less than v1.24.
```
it should be greater or equal to

File: pkg/minikube/cruntime/docker.go [hunk 4]
```diff
@@ -106,6 +106,15 @@ func (r *Docker) SocketPath() string {
 
 // Available returns an error if it is not possible to use this runtime on a host
 func (r *Docker) Available() error {
+	// If Kubernetes version >= 1.24, require both cri-dockerd and dockerd.
+	if r.KubernetesVersion.GTE(semver.Version{Major: 1, Minor: 24}) {
+		if _, err := exec.LookPath("cri-dockerd"); err != nil {
+			return err
```
Comment (medyagh) [inline pkg/minikube/cruntime/docker.go:112]: nit pick but I suggest wrapping these two errors

File: pkg/minikube/cruntime/docker.go [hunk 5]
```diff
@@ -106,6 +106,15 @@ func (r *Docker) SocketPath() string {
...
+		}
+		if _, err := exec.LookPath("dockerd"); err != nil {
+			return err
+		}
+	}
 	_, err := exec.LookPath("docker")
```
Comment (medyagh) [inline pkg/minikube/cruntime/docker.go:118]: I dont see where in the code we are doing the check for these Errors and Printing a solution message? is that file not commited to this PR ?

**Review by medyagh — CHANGES_REQUESTED** [review]

**Review by medyagh — CHANGES_REQUESTED** [review]
I would like this PR to Proactively return a clean message instead of Failing and letting the failure to go to the RegEx matching
instead of 
```
$ sudo -E ./out/minikube start --driver=none
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
✨  Using the none driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=48, Memory=181315MB, Disk=142997MB) ...
ℹ️  OS release is Debian GNU/Linux rodete

❌  Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
time="2022-07-15T18:33:39Z" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""


╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
```
it should Exit before it Fails and goes to our already RegEx matching (the solution message is already there) the point of this PR is to prevent it to go further before it fails

it should be something like:
```
$ sudo -E ./out/minikube start --driver=none
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
✨  Using the none driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=48, Memory=181315MB, Disk=142997MB) ...
ℹ️  OS release is Debian GNU/Linux rodete
❌   cri-dockerd is not installed , please install ...using the instruction in this URL ...

```

File: pkg/minikube/cruntime/docker.go (hunk 4 above)
Comment (klaases) [reply pkg/minikube/cruntime/docker.go:114]: Yes, adding in an error template with installation instructions.

File: pkg/minikube/cruntime/docker.go (hunk 5 above)
Comment (klaases) [reply pkg/minikube/cruntime/docker.go:121]: Yes, added the additional error output as requested.

**Comment by klaases** [comment]
> to achieve this you can use ErrorTypes simmilar to the ones we have in the OCI package, and when the Error is returned the caller of the function can check if the ErrorType is "NoneDependencyCriDockerd" then prints a clean solution message before it goes and fails

Yes, from the `oci package` I found reference to the `out package` which was very helpful. Added in errors for `cri-dockerd` and `dockerd` with the `style.Fatal` and a message pointing to the installation URLs.

**Comment by klaases** [comment]
Update: in order to more accurately update the PR's description, I tried running the necessary commands on Linux, however it looks like the `none-driver` itself is unsupported in this instance:

```
$ sudo -E ./out/minikube start --driver=none
😄  minikube v1.26.0 on Darwin 12.4 (arm64)

❌  Exiting due to DRV_UNSUPPORTED_OS: The driver 'none' is not supported on darwin/arm64
```

**Comment by klaases** [comment]
In this case I am not sure why the new error message is not printing out in Linux:

The code we are using is the same as the `oci package` suggestion, the `out package`: `"k8s.io/minikube/pkg/minikube/out"`.

I will keep investigating this to figure out if there is better error handling method.

```
$ sudo -E ./out/minikube start --driver=none
[sudo] password for klaases: 
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Debian GNU/Linux rodete

❌  Exiting due to RT_DOCKER_MISSING_CRI_DOCKER_NONE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

💡  Suggestion: Using Kubernetes v1.24+ with the Docker runtime requires cri-docker to be installed
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/none
🍿  Related issue: https://github.com/kubernetes/minikube/issues/14410
```

**Comment by klaases** [comment]
> This is normal, Kubernetes (i.e. kubeadm/"none") requires Linux. It should work OK (in a VM) on arm64, though.
> 
> i.e. if you try to run minikube with the none driver, in a VM that you have provisioned yourself "some other way"
> 
> e.g. Lima.

Thanks for the confirmation, will focus on getting Linux working for now.

> Looking for "dockerd" is not required as such (only a working Docker), so you can just leave out if it is trouble ?

Yes, that works for me, will leave out for now.

**Comment by klaases** [comment]
Found another reference to an error handling method, with a clean printout and exit pattern, would something like this be preferable:

```
exit.Message(reason.ExProgramNotFound, "cri-dockerd is not installed, please install using these instructions: https://github.com/Mirantis/cri-dockerd#build-and-install")
```

**Comment by klaases** [comment]
> I would like this PR to Proactively return a clean message instead of Failing and letting the failure to go to the RegEx matching

Yes, I see what you mean, not just checking for `cri-dockerd`, but preventing the user from getting to the error in the first place.

I have updated the code, which now also performs the checks closer to the start process, and immediately exits if requirements are not met. Plus, we now display a helpful error message indicating necessary installation instructions.

(Updated description above as well)

```
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...

🐳  Exiting due to NOT_FOUND_CRI_DOCKERD: 💡  Suggestion: 

    The none driver with Kubernetes v1.24+ requires cri-dockerd.
    
    Please install cri-dockerd using these instructions:
    
    https://github.com/Mirantis/cri-dockerd#build-and-install
```

**Comment by klaases** [comment]
> can you please clarify in the PR description if this check happens Before or After minikube tries to install Kubernetes? (I suggest attaching the lastStart log file

[lastStart.txt](https://github.com/kubernetes/minikube/files/9172413/lastStart.txt) is attached.

Below is a comprehensive log file, as far as I can tell, the Kubernetes profile was loaded `Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.2` but was not yet installed.

Output from `sudo -E ./out/minikube start --driver=none --alsologtostderr -v=4`:

```
I0722 21:50:43.125676  778055 out.go:296] Setting OutFile to fd 1 ...
I0722 21:50:43.126719  778055 out.go:348] isatty.IsTerminal(1) = true
I0722 21:50:43.126743  778055 out.go:309] Setting ErrFile to fd 2...
I0722 21:50:43.126750  778055 out.go:348] isatty.IsTerminal(2) = true
I0722 21:50:43.127371  778055 root.go:329] Updating PATH: /root/.minikube/bin
I0722 21:50:43.127625  778055 out.go:303] Setting JSON to false
I0722 21:50:43.131300  778055 start.go:115] hostinfo: {"hostname":"jklaas1.c.googlers.com","uptime":225065,"bootTime":1658301578,"procs":1053,"os":"linux","platform":"debian","platformFamily":"debian","platformVersion":"rodete","kernelVersion":"5.17.11-1rodete2-amd64","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"guest","hostId":"40687802-9b9c-c2dc-4387-161d7115fc33"}
I0722 21:50:43.131376  778055 start.go:125] virtualization: kvm guest
I0722 21:50:43.136566  778055 out.go:177] 😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
W0722 21:50:43.138527  778055 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0722 21:50:43.138677  778055 notify.go:193] Checking for updates...
I0722 21:50:43.138933  778055 config.go:178] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.2
I0722 21:50:43.139292  778055 exec_runner.go:51] Run: systemctl --version
I0722 21:50:43.142755  778055 driver.go:365] Setting default libvirt URI to qemu:///system
I0722 21:50:43.145036  778055 out.go:177] ✨  Using the none driver based on existing profile
✨  Using the none driver based on existing profile
I0722 21:50:43.147167  778055 start.go:284] selected driver: none
I0722 21:50:43.147189  778055 start.go:808] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase-builds:v0.0.32-1656700284-14481@sha256:96d18f055abcf72b9f587e13317d6f9b5bb6f60e9fa09d6c51e11defaf9bf842 Memory:6000 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.66.129 Port:8443 KubernetesVersion:v1.24.2 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0722 21:50:43.147365  778055 start.go:819] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0722 21:50:43.151414  778055 cni.go:95] Creating CNI manager for ""
I0722 21:50:43.151469  778055 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0722 21:50:43.151480  778055 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase-builds:v0.0.32-1656700284-14481@sha256:96d18f055abcf72b9f587e13317d6f9b5bb6f60e9fa09d6c51e11defaf9bf842 Memory:6000 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.66.129 Port:8443 KubernetesVersion:v1.24.2 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0722 21:50:43.155121  778055 out.go:177] 👍  Starting control plane node minikube in cluster minikube
👍  Starting control plane node minikube in cluster minikube
I0722 21:50:43.157210  778055 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0722 21:50:43.157439  778055 cache.go:208] Successfully downloaded all kic artifacts
I0722 21:50:43.157505  778055 start.go:370] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0722 21:50:43.157767  778055 start.go:374] acquired machines lock for "minikube" in 235.678µs
I0722 21:50:43.157796  778055 start.go:95] Skipping create...Using existing machine configuration
I0722 21:50:43.157870  778055 fix.go:55] fixHost starting: m01
W0722 21:50:43.158518  778055 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0722 21:50:43.158547  778055 api_server.go:165] Checking apiserver status ...
I0722 21:50:43.158582  778055 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0722 21:50:43.289367  778055 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0722 21:50:43.289456  778055 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0722 21:50:43.414166  778055 fix.go:103] recreateIfNeeded on minikube: state=Running err=<nil>
W0722 21:50:43.414230  778055 fix.go:129] unexpected machine state, will restart: <nil>
I0722 21:50:43.417290  778055 out.go:177] 🏃  Updating the running none "minikube" bare metal machine ...
🏃  Updating the running none "minikube" bare metal machine ...
I0722 21:50:43.419469  778055 start.go:307] post-start starting for "minikube" (driver="none")
I0722 21:50:43.421600  778055 out.go:177] 

W0722 21:50:43.423360  778055 out.go:239] 🐳  Exiting due to NOT_FOUND_CRI_DOCKERD: 
🐳  Exiting due to NOT_FOUND_CRI_DOCKERD: W0722 21:50:43.423457  778055 out.go:239] 💡  Suggestion: 

    The none driver with Kubernetes v1.24+ requires cri-dockerd.
    
    Please install cri-dockerd using these instructions:
    
    https://github.com/Mirantis/cri-dockerd#build-and-install
💡  Suggestion: 

    The none driver with Kubernetes v1.24+ requires cri-dockerd.
    
    Please install cri-dockerd using these instructions:
    
    https://github.com/Mirantis/cri-dockerd#build-and-install
I0722 21:50:43.425626  778055 out.go:177] 
```

**Comment by klaases** [comment]
Updated `dockerd` installation link to: https://docs.docker.com/engine/install/

**Comment by spowelljr** [comment]
```
$ sudo -E ./out/minikube start --driver=none
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...

🐳  Exiting due to NOT_FOUND_CRI_DOCKERD: 💡  Suggestion: 

    The none driver with Kubernetes v1.24+ requires cri-dockerd.
    
    Please install cri-dockerd using these instructions:
    
    https://github.com/Mirantis/cri-dockerd#build-and-install
```

Could you get the `💡  Suggestion:` on it's own line, looks a little odd bring on the same line as `🐳  Exiting due to NOT_FOUND_CRI_DOCKERD:`

**Comment by klaases** [comment]
> Could you get the `💡 Suggestion:` on it's own line, looks a little odd being on the same line as `🐳 Exiting due to NOT_FOUND_CRI_DOCKERD:`

Yes, added line breaks before `💡 Suggestion:`.

File: pkg/minikube/reason/reason.go [hunk 6]
```diff
@@ -460,4 +460,25 @@ var (
 		`),
 		Style: style.SeeNoEvil,
 	}
+
+	NotFoundCriDockerD = Kind{
```
Comment (spowelljr) [inline pkg/minikube/reason/reason.go:464]: nit: Based on the official capitalization of `Systemd` I think it makes sense for the trailing `D` to be lowercase.

File: pkg/minikube/reason/reason.go [hunk 7]
```diff
@@ -460,4 +460,25 @@ var (
...
+		ID:       "NOT_FOUND_CRI_DOCKERD",
+		ExitCode: ExProgramNotFound,
+		Advice: translate.T(`The none driver with Kubernetes v1.24+ requires cri-dockerd.
+		
+		Please install cri-dockerd using these instructions:
+
+		https://github.com/Mirantis/cri-dockerd#build-and-install`),
+		Style: style.Docker,
+	}
+	NotFoundDockerD = Kind{
```
Comment (spowelljr) [inline pkg/minikube/reason/reason.go:474]: nit: Same as above

File: pkg/minikube/reason/reason.go (hunk 6 above)
Comment (klaases) [reply pkg/minikube/reason/reason.go]: Sounds good, applied suggestion.

File: pkg/minikube/reason/reason.go (hunk 7 above)
Comment (klaases) [reply pkg/minikube/reason/reason.go]: Sounds good, applied suggestion (2).

**Comment by spowelljr** [comment]
Someone pushed a change to your branch, you're going to have to remove the commit to pass the CLA check.

https://github.com/kubernetes/minikube/pull/14555/commits/8b6fdbf4c78cc2c09ce29248800605f761a39450

**Comment by klaases** [comment]
> Someone pushed a change to your branch, you're going to have to remove the commit to pass the CLA check.
> 
> [8b6fdbf](https://github.com/kubernetes/minikube/commit/8b6fdbf4c78cc2c09ce29248800605f761a39450)

Removed unwanted commit: 8b6fdbf4c78cc2c09ce29248800605f761a39450

Theory: we make the preceding commit the parent instead.

`git rebase --onto 50c75e951c6020f97265ea8d1682b01c9c80df37 8b6fdbf4c78cc2c09ce29248800605f761a39450`

After `rebase` must run with `-f` for force:

`git push origin doc1 -f`

Else the following errors occur:
```
> git push origin doc1:doc1
To github.com:klaases/minikube.git
 ! [rejected]            doc1 -> doc1 (non-fast-forward)
error: failed to push some refs to 'github.com:klaases/minikube.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

File: pkg/minikube/machine/start.go [hunk 8]
```diff
@@ -313,6 +314,23 @@ func postStartSetup(h *host.Host, mc config.ClusterConfig) error {
 		return nil
 	}
 
+	if driver.IsNone(h.DriverName) {
```
Comment (spowelljr) [inline pkg/minikube/machine/start.go:317]: `cri-dockerd` & `dockerd` are only required if the `docker` container-runtime is being used, but currently it's being checked for all container-runtimes.

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: pkg/minikube/reason/reason.go [hunk 9]
```diff
@@ -460,4 +460,25 @@ var (
 		`),
 		Style: style.SeeNoEvil,
 	}
+
+	NotFoundCriDockerd = Kind{
+		ID:       "NOT_FOUND_CRI_DOCKERD",
+		ExitCode: ExProgramNotFound,
+		Advice: translate.T(`The none driver with Kubernetes v1.24+ requires cri-dockerd.
```
Comment (spowelljr) [inline pkg/minikube/reason/reason.go:467]: We should also mention only when using the `docker` container-runtime.

File: pkg/minikube/reason/reason.go [hunk 10]
```diff
@@ -460,4 +460,25 @@ var (
...
+		
+		Please install cri-dockerd using these instructions:
+
+		https://github.com/Mirantis/cri-dockerd#build-and-install`),
+		Style: style.Docker,
+	}
+	NotFoundDockerd = Kind{
+		ID:       "NOT_FOUND_DOCKERD",
+		ExitCode: ExProgramNotFound,
+		Advice: translate.T(`The none driver with Kubernetes v1.24+ requires dockerd.
```
Comment (spowelljr) [inline pkg/minikube/reason/reason.go:477]: Same as above..

**Review by spowelljr — CHANGES_REQUESTED** [review]

File: pkg/minikube/reason/reason.go (hunk 9 above)
Comment (klaases) [reply pkg/minikube/reason/reason.go]: Appreciate the suggestion, updated with:

`The none driver with Kubernetes v1.24+ and the docker container-runtime requires cri-dockerd.`

File: pkg/minikube/reason/reason.go (hunk 10 above)
Comment (klaases) [reply pkg/minikube/reason/reason.go]: Yes, also updated with:

`The none driver with Kubernetes v1.24+ and the docker container-runtime requires dockerd.`

**Comment by klaases** [comment]
Updated messaging per above requests.

/ok-to-test

File: pkg/minikube/machine/start.go (hunk 8 above)
Comment (klaases) [reply pkg/minikube/machine/start.go]: Added check for docker container-runtime:

```
// If none driver with docker container-runtime, require cri-dockerd and dockerd.
	if driver.IsNone(h.DriverName) && mc.KubernetesConfig.ContainerRuntime == constants.Docker {
...
```

**Review by spowelljr — APPROVED** [review]

**Comment by medyagh** [comment]
lets have a better PR tittle for this, the goal is, we should be able to say what the PR is doing in the changelog
