### PR TITLE
config: transform os.ENOENT error into config.ErrNotExist

### LINKED ISSUE #15593: minikube profile list --output json fails with ENONT after fresh install
### What Happened?

After minikube on a fresh machine, running:

    minikube profile list --output json

Fails, writing error to stdout:

    {"error":{"Op":"open","Path":"/home/runner/.minikube/profiles","Err":2}}

The expected output:

    {"invalid":[],"valid":[]}

Issues:
- Missing ~/.minikube/profiles not handled gracefully
- Reporting errors to stdout
- Reporting error number (2) instead of description (No such file or directory).

Workaround:
- Create .minikube/profiles manually before running the command

### Attach the log file

Full reproducer:

Add this github workflow:
```
name: CI
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Reproduce minikube bug
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube --alsologtostderr --v=7 profile list --output json
```

Example run:

```
I0104 21:22:57.498168    1632 out.go:296] Setting OutFile to fd 1 ...
I0104 21:22:57.498301    1632 out.go:343] TERM=,COLORTERM=, which probably does not support color
I0104 21:22:57.498306    1632 out.go:309] Setting ErrFile to fd 2...
I0104 21:22:57.498311    1632 out.go:343] TERM=,COLORTERM=, which probably does not support color
I0104 21:22:57.503171    1632 root.go:334] Updating PATH: /home/runner/.minikube/bin
W0104 21:22:57.503308    1632 root.go:311] Error reading config file at /home/runner/.minikube/config/config.json: open /home/runner/.minikube/config/config.json: no such file or directory
I0104 21:22:57.503638    1632 out.go:303] Setting JSON to true
I0104 21:22:57.503749    1632 notify.go:220] Checking for updates...
{"error":{"Op":"open","Path":"/home/runner/.minikube/profiles","Err":2}}
```

Can also be reproduced by removing (an empty) `~/.minikube/profiles` directory.

### Operating System

Ubuntu

### Driver

N/A

### PR DESCRIPTION
**Pull request by raghavendra-talur**
fixes #15593

### CODE REVIEW

**Comment by raghavendra-talur** [comment]
This fix is based on the [suggestion](https://github.com/kubernetes/minikube/pull/15594#discussion_r1062839181 ) provided in a previous PR that attempted to fix this problem.

File: pkg/minikube/config/profile.go [hunk 1]
```diff
@@ -301,6 +301,10 @@ func profileDirs(miniHome ...string) (dirs []string, err error) {
 	}
 	pRootDir := filepath.Join(miniPath, "profiles")
 	items, err := os.ReadDir(pRootDir)
+	if err == os.IsNotExist(err) {
+		return dirs, &ErrNotExist{fmt.Sprintf("profiles dir %s does not exist", pRootDir)}
+	}
```
Comment (nirs) [inline pkg/minikube/config/profile.go:306]: I think the best way to handle this is to return here empty list of directories and no error since this is an expected condition before any profile was created, or if a user deleted the profiles directory.

However if we report an error, we should do the check correctly - it seems that you are adding here a wrong check:

    if err == os.IsNotExist(err)

And you fix it in the next commit? Did you forget to squash the next commit into this?

**Comment by raghavendra-talur** [comment]
@medyagh @sharifelgamal Could you please take a look at this PR in your next review cycle?

Any feedback or suggestions are most welcome.

**Comment by raghavendra-talur** [comment]
@medyagh Just checking if you have any feedback for this PR. I can close this if you think it is not worth fixing.

**Comment by nirs** [comment]
Any chance to get a review of for this tiny fix?

**Review by medyagh — COMMENTED** [review]
thank you @nirs and @raghavendra-talur for this PR and the review and sorry this PR got lost in the long list of PRs, will run test on it

**Comment by medyagh** [comment]
thank you for this PR !
