### PR TITLE
Use noninteractive sudo when running podman

### LINKED ISSUE #7958: deleting Docker cluster hangs on password prompt: `sudo podman ps`
**Steps to reproduce the issue:** 

1. I start minikube with `./out/minikube start`
2. I try to delete all minikube clusters with `./out/minikube delete --all`

The start command looks good. The delete command leads to a prompt from sudo (actually nine prompts since I always answer with just RETURN). Expected is no prompt from sudo. Is this a regression or a changed behaviour? Last  time (a couple of days ago) I tried the same sequence of commands, the `delete` step worked without any sudo prompt. After the third unsuccessful attempt to get something done via sudo, the delete command seems to work and there are no logs left over (./out/minikube logs answers `There is no local cluster named "minikube"`). I feel there's something not correct in this setup. What shall I try?

**Full output of failed command:** 
% ./out/minikube delete --all --alsologtostderr    
I0501 11:28:55.690433   31894 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io --format {{.Names}}
I0501 11:28:55.768173   31894 cli_runner.go:108] Run: docker ps -a --filter label=created_by.minikube.sigs.k8s.io=true --format {{.Names}}
I0501 11:28:55.857771   31894 cli_runner.go:108] Run: docker inspect minikube --format={{.State.Status}}
I0501 11:28:55.945993   31894 cli_runner.go:108] Run: docker exec --privileged -t minikube /bin/bash -c "sudo init 0"
I0501 11:28:57.153000   31894 cli_runner.go:108] Run: docker inspect minikube --format={{.State.Status}}
I0501 11:28:57.355540   31894 oci.go:504] container minikube status is Stopped
I0501 11:28:57.355566   31894 oci.go:516] Successfully shutdown container minikube
I0501 11:28:57.355612   31894 cli_runner.go:108] Run: docker rm -f -v minikube
I0501 11:28:57.489665   31894 volumes.go:34] trying to delete all docker volumes with label created_by.minikube.sigs.k8s.io=true
I0501 11:28:57.490017   31894 cli_runner.go:108] Run: docker volume ls --filter label=created_by.minikube.sigs.k8s.io=true --format {{.Name}}
I0501 11:28:57.557507   31894 cli_runner.go:108] Run: docker volume rm --force minikube
I0501 11:28:57.920941   31894 volumes.go:56] trying to prune all docker volumes with label created_by.minikube.sigs.k8s.io=true
I0501 11:28:57.921009   31894 cli_runner.go:108] Run: docker volume prune -f --filter label=created_by.minikube.sigs.k8s.io=true
🔥  Deleting "minikube" in docker ...
I0501 11:28:58.006147   31894 cli_runner.go:108] Run: docker ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}
I0501 11:28:58.087536   31894 volumes.go:34] trying to delete all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0501 11:28:58.087599   31894 cli_runner.go:108] Run: docker volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}
I0501 11:28:58.179693   31894 volumes.go:56] trying to prune all docker volumes with label name.minikube.sigs.k8s.io=minikube
I0501 11:28:58.179757   31894 cli_runner.go:108] Run: docker volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube
I0501 11:28:58.258713   31894 cli_runner.go:108] Run: sudo podman ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for sand: 
Sorry, try again.
[sudo] password for sand: 
Sorry, try again.
[sudo] password for sand: 
I0501 11:29:06.663100   31894 cli_runner.go:147] Completed: sudo podman ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}: (8.404352766s)
I0501 11:29:06.663135   31894 volumes.go:34] trying to delete all podman volumes with label name.minikube.sigs.k8s.io=minikube
I0501 11:29:06.663208   31894 cli_runner.go:108] Run: sudo podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for sand: 

Sorry, try again.
[sudo] password for sand: 
Sorry, try again.
[sudo] password for sand: 
I0501 11:29:14.111421   31894 cli_runner.go:147] Completed: sudo podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}: (7.448182524s)
W0501 11:29:14.111462   31894 delete.go:211] error deleting volumes (might be okay).
To see the list of volumes run: 'docker volume ls'
:[listing volumes by label "name.minikube.sigs.k8s.io=minikube": sudo podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}: exit status 1
stdout:

stderr:
sudo: 3 incorrect password attempts
]
I0501 11:29:14.111580   31894 volumes.go:56] trying to prune all podman volumes with label name.minikube.sigs.k8s.io=minikube
I0501 11:29:14.111655   31894 cli_runner.go:108] Run: sudo podman volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for sand: 
Sorry, try again.
[sudo] password for sand: 
Sorry, try again.
[sudo] password for sand: 
I0501 11:29:23.003258   31894 cli_runner.go:147] Completed: sudo podman volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube: (8.891577654s)
W0501 11:29:23.003307   31894 delete.go:216] error pruning volume (might be okay):
[prune volume by label name.minikube.sigs.k8s.io=minikube: sudo podman volume prune -f --filter label=name.minikube.sigs.k8s.io=minikube: exit status 1
stdout:

stderr:
sudo: 3 incorrect password attempts
]
I0501 11:29:23.005642   31894 cli_runner.go:108] Run: docker inspect minikube --format={{.State.Status}}
I0501 11:29:23.086619   31894 delete.go:75] Unable to get host status for minikube, assuming it has already been deleted: state: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:

stderr:
Error: No such object: minikube
🔥  Removing /home/sand/.minikube/machines/minikube ...
I0501 11:29:23.097300   31894 lock.go:35] WriteFile acquiring /home/sand/.kube/config: {Name:mk505f793881700367e2a950c92de29206d7625a Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
💀  Removed all traces of the "minikube" cluster.
🔥  Successfully deleted all profiles

**Full output of `minikube start` command used, if not already included:**
% ./out/minikube start                                                                      
😄  minikube v1.10.0-beta.2 on Debian bullseye/sid (xen/amd64)
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.18.1 preload ...
    > preloaded-images-k8s-v3-v1.18.1-docker-overlay2-amd64.tar.lz4: 525.47 MiB
🔥  Creating docker container (CPUs=2, Memory=3200MB) ...
🐳  Preparing Kubernetes v1.18.1 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

### PR DESCRIPTION
**Pull request by afbjorklund**
To avoid asking for a password in the middle of minikube commands.

The setup process is supposed to involve adding podman to sudoers...

Fixes #7958

Related to #7960 in that it runs podman, no matter what driver is used.

### CODE REVIEW

File: pkg/drivers/kic/oci/cli_runner.go [hunk 1]
```diff
@@ -67,7 +67,7 @@ func (rr RunResult) Output() string {
 // PrefixCmd adds any needed prefix (such as sudo) to the command
 func PrefixCmd(cmd *exec.Cmd) *exec.Cmd {
 	if cmd.Args[0] == Podman && runtime.GOOS == "linux" { // want sudo when not running podman-remote
-		cmdWithSudo := exec.Command("sudo", cmd.Args...)
+		cmdWithSudo := exec.Command("sudo", append([]string{"-n"}, cmd.Args...)...)
```
Comment (tstromberg) [inline pkg/drivers/kic/oci/cli_runner.go:70]: What is this trying to solve? Won't this break a lot of folks who require interactive use?

I suspect this should only happen if --interactive=false.

Comment (afbjorklund) [reply pkg/drivers/kic/oci/cli_runner.go:70]: Currently we are verifying the sudo setup when we validate the podman driver.

But since we also call it for _all_ drivers (#7963), might as well use it always ?

Comment (tstromberg) [reply pkg/drivers/kic/oci/cli_runner.go:70]: As a sysadmin, I would be annoyed about a command executing things as root unnecessarily, but it's not completely clear to me how to solve #7958 elegantly without it. 

This whole business of running commands for container runtimes that have never been used is not so hot.

**Comment by afbjorklund** [comment]
@medyagh : why do we need to run an extra cleanup like this, outside all machines etc ?

isn't enough to delete the volume when the container is removed, since they are all "named"

File: pkg/drivers/kic/oci/cli_runner.go (hunk 1 above)
Comment (afbjorklund) [reply pkg/drivers/kic/oci/cli_runner.go:70]: Agree, it is more of a workaround...

File: cmd/minikube/cmd/delete.go [hunk 2]
```diff
@@ -90,26 +90,31 @@ func init() {
...
-	errs = oci.DeleteAllVolumesByLabel(oci.Docker, delLabel)
+	errs = oci.DeleteAllVolumesByLabel(ociBin, delLabel)
 	if len(errs) > 0 { // it will not error if there is nothing to delete
 		glog.Warningf("error delete volumes by label %q (might be okay): %+v", delLabel, errs)
 	}
 
-	errs = oci.PruneAllVolumesByLabel(oci.Docker, delLabel)
+	if ociBin == oci.Podman {
+		// podman prune does not support --filter
+		return
```
Comment (medyagh) [inline cmd/minikube/cmd/delete.go:114]: in this line it seems to return and wont go to the deleteall process?

Comment (afbjorklund) [reply cmd/minikube/cmd/delete.go:114]: The operation is not supported (volume prune) on podman, so we can only list-and-delete

File: cmd/minikube/cmd/delete.go [hunk 3]
```diff
@@ -137,7 +142,8 @@ func runDelete(cmd *cobra.Command, args []string) {
 	}
 
 	if deleteAll {
-		deleteContainersAndVolumes()
+		deleteContainersAndVolumes(oci.Docker)
```
Comment (medyagh) [inline cmd/minikube/cmd/delete.go:145]: maybe do them in parallel ?

Comment (afbjorklund) [reply cmd/minikube/cmd/delete.go:145]: possibly, the theory is that one of them will be "empty"
