### PR TITLE
Unify Kubernetes client creation around kapi.Client

### LINKED ISSUE #7745: Enabling 'default-storageclass' returned an error: no Auth Provider found for name "gcp"
-- Reported by @etanshaul 

I see the often in the Minikube startup logs (things still start up successfully):

`! Enabling 'default-storageclass' returned an error: running callbacks: [Error getting storagev1 interface Error creating new client from kubeConfig.ClientConfig(): no Auth Provider found for name "gcp" : Error creating new client from kubeConfig.ClientConfig(): no Auth Provider found for name "gcp"]`

### PR DESCRIPTION
**Pull request by tstromberg**
Fixes race condition where minikube may try to apply the default storage-class to the current Kubernetes context rather than to the minikube context. 

Fixes #7745

### CODE REVIEW

File: pkg/minikube/service/service.go [hunk 1]
```diff
@@ -156,7 +127,8 @@ func GetServiceURLs(api libmachine.API, namespace string, t *template.Template)
 
 // GetServiceURLsForService returns a SvcUrl object for a service in a namespace. Supports optional formatting.
 func GetServiceURLsForService(api libmachine.API, namespace, service string, t *template.Template) (SvcURL, error) {
```
Comment (medyagh) [inline pkg/minikube/service/service.go:129]: would it be out of scope to pass the profile name instead of viper ?

Comment (tstromberg) [reply pkg/minikube/service/service.go]: Done.
